cwlVersion: v1.2
class: CommandLineTool
baseCommand: psmc
label: psmc
doc: "Pairwise SMC Model for estimating population size history\n\nTool homepage:
  https://github.com/lh3/psmc"
inputs:
  - id: input_file
    type: File
    doc: Input psmcfa file
    inputBinding:
      position: 1
  - id: bootstrap
    type:
      - 'null'
      - boolean
    doc: bootstrap (input be preprocessed with split_psmcfa)
    inputBinding:
      position: 102
      prefix: -b
  - id: cpg_counts
    type:
      - 'null'
      - File
    doc: CpG counts generated by cntcpg
    inputBinding:
      position: 102
      prefix: -c
  - id: initial_divergence_time
    type:
      - 'null'
      - float
    doc: initial divergence time; -1 to disable
    default: -1.0
    inputBinding:
      position: 102
      prefix: -T
  - id: initial_theta_rho_ratio
    type:
      - 'null'
      - float
    doc: initial theta/rho ratio
    default: 4.0
    inputBinding:
      position: 102
      prefix: -r
  - id: input_parameter_file
    type:
      - 'null'
      - File
    doc: input parameter file
    inputBinding:
      position: 102
      prefix: -i
  - id: max_coalescent_time
    type:
      - 'null'
      - float
    doc: maximum 2N0 coalescent time
    default: 15.0
    inputBinding:
      position: 102
      prefix: -t
  - id: max_iterations
    type:
      - 'null'
      - int
    doc: maximum number of iterations
    default: 30
    inputBinding:
      position: 102
      prefix: -N
  - id: pattern
    type:
      - 'null'
      - string
    doc: pattern of parameters
    default: 4+5*3+4
    inputBinding:
      position: 102
      prefix: -p
  - id: perform_decoding
    type:
      - 'null'
      - boolean
    doc: perform decoding
    inputBinding:
      position: 102
      prefix: -d
  - id: print_posterior_probabilities
    type:
      - 'null'
      - boolean
    doc: print full posterior probabilities
    inputBinding:
      position: 102
      prefix: -D
  - id: simulate_sequence
    type:
      - 'null'
      - boolean
    doc: simulate sequence
    inputBinding:
      position: 102
      prefix: -S
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: output file
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/psmc:0.6.5--h5ca1c30_4
