cwlVersion: v1.2
class: CommandLineTool
baseCommand: linkedsv.py
label: linkedsv_linkedsv.py
doc: "Detection of SVs from linked-read sequencing data\n\nTool homepage: https://github.com/WGLab/LinkedSV"
inputs:
  - id: bedtools
    type:
      - 'null'
      - string
    doc: 'path to bedtools (default: find in environmental path)'
    inputBinding:
      position: 101
      prefix: --bedtools
  - id: black_region_bed
    type:
      - 'null'
      - File
    doc: black region in bed format, required if --ref_version is not specified
    inputBinding:
      position: 101
      prefix: --black_region_bed
  - id: gap_distance_cut_off
    type:
      - 'null'
      - int
    doc: 'max distance between two reads in a HMW DNA molecule (default: automatically
      determined)'
    inputBinding:
      position: 101
      prefix: --gap_distance_cut_off
  - id: gap_region_bed
    type:
      - 'null'
      - File
    doc: reference gap region in bed format, required if --ref_version is not 
      specified
    inputBinding:
      position: 101
      prefix: --gap_region_bed
  - id: germline_mode
    type:
      - 'null'
      - boolean
    doc: detect germline SVs
    inputBinding:
      position: 101
      prefix: --germline_mode
  - id: input_bam
    type: File
    doc: input bam file (should be the phased_possorted_bam.bam generated by 
      Longranger
    inputBinding:
      position: 101
      prefix: --bam
  - id: min_fragment_length
    type:
      - 'null'
      - int
    doc: minimal fragment length considered for SV calling
    inputBinding:
      position: 101
      prefix: --min_fragment_length
  - id: min_reads_in_fragment
    type:
      - 'null'
      - int
    doc: minimal number of confidently mapped reads in one fragment
    inputBinding:
      position: 101
      prefix: --min_reads_in_fragment
  - id: min_supp_barcodes
    type:
      - 'null'
      - int
    doc: minimal number of shared barcodes between two SV breakpoints
    inputBinding:
      position: 101
      prefix: --min_supp_barcodes
  - id: num_thread
    type:
      - 'null'
      - int
    doc: number of threads
    inputBinding:
      position: 101
      prefix: --n_thread
  - id: output_directory
    type: Directory
    doc: output directory
    inputBinding:
      position: 101
      prefix: --out_dir
  - id: ref_fasta
    type: File
    doc: reference FASTA file
    inputBinding:
      position: 101
      prefix: --ref
  - id: ref_version
    type:
      - 'null'
      - string
    doc: 'version of reference fasta file. Current supported versions are: hg19, b37,
      hg38'
    inputBinding:
      position: 101
      prefix: --ref_version
  - id: samtools
    type:
      - 'null'
      - string
    doc: 'path to samtools (default: find in environmental path)'
    inputBinding:
      position: 101
      prefix: --samtools
  - id: save_temp_files
    type:
      - 'null'
      - boolean
    doc: 'Do not remove intermediate files after the run. Use in debug mode. Default:
      False'
    inputBinding:
      position: 101
      prefix: --save_temp_files
  - id: somatic_mode
    type:
      - 'null'
      - boolean
    doc: detect somatic SVs (with low variant allele frequency)
    inputBinding:
      position: 101
      prefix: --somatic_mode
  - id: target_region
    type:
      - 'null'
      - File
    doc: bed file of target regions (required if --targeted is specified)
    inputBinding:
      position: 101
      prefix: --target_region
  - id: targeted
    type:
      - 'null'
      - boolean
    doc: the input is targeted region sequencing data (such as WES)
    inputBinding:
      position: 101
      prefix: --targeted
  - id: wgs
    type:
      - 'null'
      - boolean
    doc: the input is whole-genome sequencing data
    inputBinding:
      position: 101
      prefix: --wgs
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/linkedsv:0.1.0--h077b44d_0
stdout: linkedsv_linkedsv.py.out
