cwlVersion: v1.2
class: CommandLineTool
baseCommand: chooseK.py
label: faststructure_chooseK.py
doc: "A script to help choose the number of populations (K) that best explains the
  data after running fastStructure. It reads the .log and .meanQ files of all runs
  with the given prefix.\n\nTool homepage: https://github.com/rajanil/fastStructure"
requirements:
  - class: InitialWorkDirRequirement
    listing: $(inputs.structure_outputs)
inputs:
  - id: structure_outputs
    type: 'File[]'
    doc: Output files (.log and .meanQ) of structure.py runs for different K, named
      <prefix>.<K>.log and <prefix>.<K>.meanQ; they are staged in the working directory
  - id: input_prefix
    type: string
    doc: Prefix of the output files generated by structure.py (for output files
      'test.3.log' and 'test.3.meanQ' the prefix is 'test')
    inputBinding:
      position: 101
      prefix: --input
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/faststructure:1.0--py311h1f01909_6
stdout: faststructure_chooseK.py.out
