cwlVersion: v1.2
class: CommandLineTool
baseCommand: fmlrc
label: fmlrc
doc: "FMLRC (FM-index Long Read Corrector) is a tool for correcting long reads (like
  Oxford Nanopore or Pacific Biosciences) using a BWT of short read sequencing data.\n\
  \nTool homepage: https://github.com/holtjma/fmlrc"
inputs:
  - id: comp_msbwt
    type: File
    doc: The BWT of the short reads (generated by msbwt, typically a .npy file)
    inputBinding:
      position: 1
  - id: long_reads
    type: File
    doc: The long reads to be corrected (FASTA/FASTQ format)
    inputBinding:
      position: 2
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: K-mer size for correction
    default: 21
    inputBinding:
      position: 103
      prefix: --kmer-size
  - id: min_count
    type:
      - 'null'
      - int
    doc: Minimum count for a k-mer to be considered
    default: 5
    inputBinding:
      position: 103
      prefix: --min-count
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use
    default: 1
    inputBinding:
      position: 103
      prefix: --threads
outputs:
  - id: corrected_reads
    type: File
    doc: The name of the output file for corrected reads (FASTA format)
    outputBinding:
      glob: '*.out'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fmlrc:1.0.0--h9948957_6
