cwlVersion: v1.2
class: CommandLineTool
baseCommand: bakta
label: bakta
doc: "Rapid & standardized annotation of bacterial genomes, MAGs & plasmids\n\nTool
  homepage: https://github.com/oschwengers/bakta"
inputs:
  - id: genome
    type: File
    doc: Genome sequences in (zipped) fasta format
    inputBinding:
      position: 1
  - id: complete
    type:
      - 'null'
      - boolean
    doc: All sequences are complete replicons (chromosome/plasmid[s])
    inputBinding:
      position: 102
      prefix: --complete
  - id: compliant
    type:
      - 'null'
      - boolean
    doc: Force Genbank/ENA/DDJB compliance
    inputBinding:
      position: 102
      prefix: --compliant
  - id: db
    type:
      - 'null'
      - Directory
    doc: Database path (default = <bakta_path>/db). Can also be provided as 
      BAKTA_DB environment variable.
    default: <bakta_path>/db
    inputBinding:
      position: 102
      prefix: --db
  - id: debug
    type:
      - 'null'
      - boolean
    doc: Run Bakta in debug mode. Temp data will not be removed.
    inputBinding:
      position: 102
      prefix: --debug
  - id: force
    type:
      - 'null'
      - boolean
    doc: Force overwriting existing output folder (except for current working 
      directory)
    inputBinding:
      position: 102
      prefix: --force
  - id: genus
    type:
      - 'null'
      - string
    doc: Genus name
    inputBinding:
      position: 102
      prefix: --genus
  - id: gram
    type:
      - 'null'
      - string
    doc: 'Gram type for signal peptide predictions: +/-/? (default = ?)'
    default: '?'
    inputBinding:
      position: 102
      prefix: --gram
  - id: hmms
    type:
      - 'null'
      - File
    doc: HMM file of trusted hidden markov models in HMMER format for CDS 
      annotation
    inputBinding:
      position: 102
      prefix: --hmms
  - id: keep_contig_headers
    type:
      - 'null'
      - boolean
    doc: Keep original contig/sequence headers
    inputBinding:
      position: 102
      prefix: --keep-contig-headers
  - id: locus
    type:
      - 'null'
      - string
    doc: Locus prefix (default = 'contig')
    default: "'contig'"
    inputBinding:
      position: 102
      prefix: --locus
  - id: locus_tag
    type:
      - 'null'
      - string
    doc: Locus tag prefix (default = autogenerated)
    default: autogenerated
    inputBinding:
      position: 102
      prefix: --locus-tag
  - id: locus_tag_increment
    type:
      - 'null'
      - string
    doc: 'Locus tag increment: 1/5/10 (default = 1)'
    default: '1'
    inputBinding:
      position: 102
      prefix: --locus-tag-increment
  - id: meta
    type:
      - 'null'
      - boolean
    doc: Run in metagenome mode. This only affects CDS prediction.
    inputBinding:
      position: 102
      prefix: --meta
  - id: min_contig_length
    type:
      - 'null'
      - int
    doc: Minimum contig/sequence size (default = 1; 200 in compliant mode)
    default: 1
    inputBinding:
      position: 102
      prefix: --min-contig-length
  - id: output
    type:
      - 'null'
      - Directory
    doc: Output directory (default = current working directory)
    default: current working directory
    inputBinding:
      position: 102
      prefix: --output
  - id: partial
    type:
      - 'null'
      - boolean
    doc: Predict partial (truncated) genes spanning linear sequence ends
    inputBinding:
      position: 102
      prefix: --partial
  - id: plasmid
    type:
      - 'null'
      - string
    doc: Plasmid name
    inputBinding:
      position: 102
      prefix: --plasmid
  - id: prefix
    type:
      - 'null'
      - string
    doc: Prefix for output files
    inputBinding:
      position: 102
      prefix: --prefix
  - id: prodigal_tf
    type:
      - 'null'
      - File
    doc: Path to existing Prodigal training file to use for CDS prediction
    inputBinding:
      position: 102
      prefix: --prodigal-tf
  - id: proteins
    type:
      - 'null'
      - File
    doc: Fasta file of trusted protein sequences for CDS annotation
    inputBinding:
      position: 102
      prefix: --proteins
  - id: regions
    type:
      - 'null'
      - File
    doc: Path to pre-annotated regions in GFF3 or Genbank format (regions only, 
      no functional annotations).
    inputBinding:
      position: 102
      prefix: --regions
  - id: replicons
    type:
      - 'null'
      - File
    doc: Replicon information table (tsv/csv)
    inputBinding:
      position: 102
      prefix: --replicons
  - id: skip_cds
    type:
      - 'null'
      - boolean
    doc: Skip CDS detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-cds
  - id: skip_crispr
    type:
      - 'null'
      - boolean
    doc: Skip CRISPR array detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-crispr
  - id: skip_filter
    type:
      - 'null'
      - boolean
    doc: Skip feature overlap filters
    inputBinding:
      position: 102
      prefix: --skip-filter
  - id: skip_gap
    type:
      - 'null'
      - boolean
    doc: Skip gap detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-gap
  - id: skip_ncrna
    type:
      - 'null'
      - boolean
    doc: Skip ncRNA detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-ncrna
  - id: skip_ncrna_region
    type:
      - 'null'
      - boolean
    doc: Skip ncRNA region detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-ncrna-region
  - id: skip_ori
    type:
      - 'null'
      - boolean
    doc: Skip oriC/oriT detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-ori
  - id: skip_plot
    type:
      - 'null'
      - boolean
    doc: Skip generation of circular genome plots
    inputBinding:
      position: 102
      prefix: --skip-plot
  - id: skip_pseudo
    type:
      - 'null'
      - boolean
    doc: Skip pseudogene detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-pseudo
  - id: skip_rrna
    type:
      - 'null'
      - boolean
    doc: Skip rRNA detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-rrna
  - id: skip_sorf
    type:
      - 'null'
      - boolean
    doc: Skip sORF detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-sorf
  - id: skip_tmrna
    type:
      - 'null'
      - boolean
    doc: Skip tmRNA detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-tmrna
  - id: skip_trna
    type:
      - 'null'
      - boolean
    doc: Skip tRNA detection & annotation
    inputBinding:
      position: 102
      prefix: --skip-trna
  - id: species
    type:
      - 'null'
      - string
    doc: Species name
    inputBinding:
      position: 102
      prefix: --species
  - id: strain
    type:
      - 'null'
      - string
    doc: Strain name
    inputBinding:
      position: 102
      prefix: --strain
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use (default = number of available CPUs)
    default: number of available CPUs
    inputBinding:
      position: 102
      prefix: --threads
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: Location for temporary files (default = system dependent auto 
      detection)
    default: system dependent auto detection
    inputBinding:
      position: 102
      prefix: --tmp-dir
  - id: translation_table
    type:
      - 'null'
      - string
    doc: 'Translation table: 11/4/25 (default = 11)'
    default: '11'
    inputBinding:
      position: 102
      prefix: --translation-table
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print verbose information
    inputBinding:
      position: 102
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bakta:1.12.0--pyhdfd78af_0
stdout: bakta.out
