cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - clair.py
  - CreateTensor
label: clair_CreateTensor
doc: "Generate tensors summarizing local alignments from a BAM file and a list of candidate locations\n\nTool homepage: https://github.com/HKU-BAL/Clair"
inputs:
  - id: bam_fn
    type: File
    doc: "Sorted BAM file input"
    secondaryFiles:
      - pattern: ".bai"
        required: true
    inputBinding:
      position: 101
      prefix: --bam_fn
  - id: ref_fn
    type: File
    doc: "Reference fasta file input"
    secondaryFiles:
      - pattern: ".fai"
        required: false
    inputBinding:
      position: 101
      prefix: --ref_fn
  - id: can_fn
    type: File
    doc: "Variant candidate list generated by ExtractVariantCandidates.py or true variant list generated by GetTruth.py"
    inputBinding:
      position: 101
      prefix: --can_fn
  - id: tensor_fn
    type: string
    doc: "Tensor output file name (gzip-compressed text)"
    inputBinding:
      position: 101
      prefix: --tensor_fn
  - id: minMQ
    type:
      - 'null'
      - int
    doc: "Minimum Mapping Quality. Mapping quality lower than the setting will be filtered, default: 0"
    inputBinding:
      position: 101
      prefix: --minMQ
  - id: ctgName
    type:
      - 'null'
      - string
    doc: "The name of sequence to be processed"
    inputBinding:
      position: 101
      prefix: --ctgName
  - id: ctgStart
    type:
      - 'null'
      - int
    doc: "The 1-based starting position of the sequence to be processed"
    inputBinding:
      position: 101
      prefix: --ctgStart
  - id: ctgEnd
    type:
      - 'null'
      - int
    doc: "The 1-based inclusive ending position of the sequence to be processed"
    inputBinding:
      position: 101
      prefix: --ctgEnd
  - id: samtools
    type:
      - 'null'
      - string
    doc: "Path to the 'samtools', default: samtools"
    inputBinding:
      position: 101
      prefix: --samtools
  - id: stop_consider_left_edge
    type:
      - 'null'
      - boolean
    doc: "If not set, would consider left edge only. That is, count the left-most base-pairs of a read for coverage even if the starting position of a read is after the starting position of a tensor"
    inputBinding:
      position: 101
      prefix: --stop_consider_left_edge
  - id: dcov
    type:
      - 'null'
      - int
    doc: "Cap depth per position at 250"
    inputBinding:
      position: 101
      prefix: --dcov
  - id: minCoverage
    type:
      - 'null'
      - int
    doc: "Minimum coverage required to generate a tensor, default: 0"
    inputBinding:
      position: 101
      prefix: --minCoverage
outputs:
  - id: tensors
    type: File
    doc: "Tensors (gzip-compressed text)"
    outputBinding:
      glob: "$(inputs.tensor_fn)"
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/clair:2.1.1--hdfd78af_1
