cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - clair.py
  - PairWithNonVariants
label: clair_PairWithNonVariants
doc: "Pair truth-variant tensors with non-variant tensors for training\n\nTool homepage: https://github.com/HKU-BAL/Clair"
inputs:
  - id: tensor_can_fn
    type: File
    doc: "Tensors generated at randome genome positions by ExtractVariantCandidates.py+CreateTensor.py"
    inputBinding:
      position: 101
      prefix: --tensor_can_fn
  - id: tensor_var_fn
    type: File
    doc: "Variant tensors generated by GetTruth.py+CreateTensor.py"
    inputBinding:
      position: 101
      prefix: --tensor_var_fn
  - id: bed_fn
    type:
      - 'null'
      - File
    doc: "Usable genome regions input in BED format"
    inputBinding:
      position: 101
      prefix: --bed_fn
  - id: output_fn
    type: string
    doc: "Tensors output filename (gzip-compressed text)"
    inputBinding:
      position: 101
      prefix: --output_fn
  - id: amp
    type:
      - 'null'
      - float
    doc: "Pick ((# of the Truth Variants)*amp) non-variants to pair with the Truth Variants, default: 2"
    inputBinding:
      position: 101
      prefix: --amp
outputs:
  - id: paired_tensors
    type: File
    doc: "Paired tensors (gzip-compressed text)"
    outputBinding:
      glob: "$(inputs.output_fn)"
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/clair:2.1.1--hdfd78af_1
