cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - clair.py
  - train_clr
label: clair_train_clr
doc: "Train model with a cyclical learning rate\n\nTool homepage: https://github.com/HKU-BAL/Clair"
inputs:
  - id: clr_mode
    type:
      - 'null'
      - string
    doc: "clr modes: tri, tri2, exp"
    inputBinding:
      position: 101
      prefix: --clr_mode
  - id: SGDM
    type:
      - 'null'
      - boolean
    doc: "Use Stochastic Gradient Descent with momentum as optimizer"
    inputBinding:
      position: 101
      prefix: --SGDM
  - id: Adam
    type:
      - 'null'
      - boolean
    doc: "Use Adam as optimizer"
    inputBinding:
      position: 101
      prefix: --Adam
  - id: cross_entropy
    type:
      - 'null'
      - boolean
    doc: "Use Cross Entropy as loss function"
    inputBinding:
      position: 101
      prefix: --cross_entropy
  - id: focal_loss
    type:
      - 'null'
      - boolean
    doc: "Use Focal Loss as loss function"
    inputBinding:
      position: 101
      prefix: --focal_loss
  - id: bin_fn
    type:
      - 'null'
      - File
    doc: "Binary tensor input generated by tensor2Bin.py, tensor_fn, var_fn and bed_fn will be ignored"
    inputBinding:
      position: 101
      prefix: --bin_fn
  - id: train_bin_fn
    type:
      - 'null'
      - File
    doc: "Train Binary, used together with --validation_bin_fn (would ignore: bin_fn, tensor_fn, var_fn, bed_fn)"
    inputBinding:
      position: 101
      prefix: --train_bin_fn
  - id: validation_bin_fn
    type:
      - 'null'
      - File
    doc: "Validation Binary, used together with --train_bin_fn (would ignore: bin_fn, tensor_fn, var_fn, bed_fn)"
    inputBinding:
      position: 101
      prefix: --validation_bin_fn
  - id: tensor_fn
    type:
      - 'null'
      - File
    doc: "Tensor input"
    inputBinding:
      position: 101
      prefix: --tensor_fn
  - id: var_fn
    type:
      - 'null'
      - File
    doc: "Truth variants list input"
    inputBinding:
      position: 101
      prefix: --var_fn
  - id: bed_fn
    type:
      - 'null'
      - File
    doc: "High confident genome regions input in the BED format"
    inputBinding:
      position: 101
      prefix: --bed_fn
  - id: chkpnt_fn
    type:
      - 'null'
      - File
    doc: "Input a checkpoint for testing or continue training: Trained model checkpoint: give the .index file of the model; the checkpoint prefix (path without .index) is passed, with the .meta and .data-00000-of-00001 files beside it"
    secondaryFiles:
      - pattern: "^.meta"
        required: true
      - pattern: "^.data-00000-of-00001"
        required: true
    inputBinding:
      position: 101
      prefix: --chkpnt_fn
      valueFrom: "$(self.path.replace(/\\.index$/, ''))"
  - id: learning_rate
    type:
      - 'null'
      - float
    doc: "Set the initial learning rate, default: 0.0001"
    inputBinding:
      position: 101
      prefix: --learning_rate
  - id: lambd
    type:
      - 'null'
      - float
    doc: "Set the l2 regularization lambda, default: 0.005"
    inputBinding:
      position: 101
      prefix: --lambd
  - id: ochk_prefix
    type: string
    doc: "Prefix for checkpoint outputs at each learning rate change, REQUIRED"
    inputBinding:
      position: 101
      prefix: --ochk_prefix
  - id: olog_dir
    type:
      - 'null'
      - string
    doc: "Directory for tensorboard log outputs"
    inputBinding:
      position: 101
      prefix: --olog_dir
outputs:
  - id: checkpoints
    type:
      type: array
      items: File
    doc: "Model checkpoint files"
    outputBinding:
      glob: "$(inputs.ochk_prefix)*"
  - id: log_dir
    type:
      - 'null'
      - Directory
    doc: "Tensorboard logs"
    outputBinding:
      glob: "$(inputs.olog_dir ? inputs.olog_dir : [])"
  - id: stdout
    type: stdout
    doc: Standard output
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/clair:2.1.1--hdfd78af_1
stdout: clair_train_clr.out
