cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - imfusion-insertions
  - tophat
label: imfusion_insertions_tophat
doc: "Identify transposon insertions from gene-transposon fusions in RNA-seq reads aligned with Tophat2 to an IM-Fusion augmented reference.\n\nTool homepage: https://github.com/NKI-CCB/imfusion"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.reference)
        writable: true
inputs:
  - id: fastq
    type: File
    doc: Path to the sample fastq file.
    inputBinding:
      position: 1
      prefix: --fastq
  - id: fastq2
    type:
      - 'null'
      - File
    doc: Path to the second pair fastq file (for paired-end sequencing data).
    inputBinding:
      position: 1
      prefix: --fastq2
  - id: reference
    type: Directory
    doc: Path to the index of the augmented reference generated by imfusion-build.
    inputBinding:
      position: 1
      prefix: --reference
  - id: output_dir
    type: string
    doc: The samples output directory.
    inputBinding:
      position: 1
      prefix: --output_dir
  - id: tophat_threads
    type:
      - 'null'
      - int
    doc: Number of threads to use when running Tophat2.
    inputBinding:
      position: 1
      prefix: --tophat_threads
  - id: tophat_min_flank
    type:
      - 'null'
      - int
    doc: Minimum mapped length of the two segments on each side of the fusion.
    inputBinding:
      position: 1
      prefix: --tophat_min_flank
  - id: tophat_args
    type:
      - 'null'
      - string
    doc: Additional args to pass to Tophat2.
    inputBinding:
      position: 1
      prefix: --tophat_args
  - id: assemble
    type:
      - 'null'
      - boolean
    doc: Perform de-novo transcript assembly using StringTie.
    inputBinding:
      position: 1
      prefix: --assemble
  - id: no_filter_orientation
    type:
      - 'null'
      - boolean
    doc: Don't filter fusions with transposon features and genes in opposite (incompatible) orientations.
    inputBinding:
      position: 1
      prefix: --no_filter_orientation
  - id: no_filter_feature
    type:
      - 'null'
      - boolean
    doc: Don't filter fusions with non-SA/SD features.
    inputBinding:
      position: 1
      prefix: --no_filter_feature
  - id: blacklisted_genes
    type:
      - 'null'
      - type: array
        items: string
    doc: Blacklisted genes to filter.
    inputBinding:
      position: 1
      prefix: --blacklisted_genes
outputs:
  - id: sample_dir
    type: Directory
    doc: Sample output directory with alignment and insertions.txt.
    outputBinding:
      glob: $(inputs.output_dir)
  - id: insertions
    type: File
    doc: Identified insertions (insertions.txt).
    outputBinding:
      glob: $(inputs.output_dir)/insertions.txt
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imfusion:0.3.2--pyhdfd78af_1
