cwlVersion: v1.2
class: CommandLineTool
baseCommand: imfusion-ctg
label: imfusion_ctg
doc: "Identify commonly targeted genes (CTGs) from merged IM-Fusion insertions, 
  optionally testing them for differential expression.\n\nTool homepage: https://github.com/NKI-CCB/imfusion"
inputs:
  - id: chromosomes
    type:
      - 'null'
      - type: array
        items: string
    doc: Chromosomes to consider. Used to omit specific chromosomes from the 
      CTG analysis.
    inputBinding:
      position: 101
      prefix: --chromosomes
  - id: de_threshold
    type:
      - 'null'
      - float
    doc: Minimum p-value for a CTG to be considered as differentially 
      expressed.
    inputBinding:
      position: 101
      prefix: --de_threshold
  - id: expression
    type:
      - 'null'
      - File
    doc: Path to the merged expression file from imfusion-merge.
    inputBinding:
      position: 101
      prefix: --expression
  - id: gene_ids
    type:
      - 'null'
      - type: array
        items: string
    doc: IDs of genes to test.
    inputBinding:
      position: 101
      prefix: --gene_ids
  - id: insertions
    type: File
    doc: Path to the merged insertions file from imfusion-merge.
    inputBinding:
      position: 101
      prefix: --insertions
  - id: min_depth
    type:
      - 'null'
      - int
    doc: Minimum supporting number of reads for insertions to be included in
      the CTG analysis.
    inputBinding:
      position: 101
      prefix: --min_depth
  - id: pattern
    type:
      - 'null'
      - string
    doc: Regular expression of the nucleotide sequence at which the 
      transposon typically integrates, e.g. (AT|TA) for T2onc2.
    inputBinding:
      position: 101
      prefix: --pattern
  - id: reference
    type: Directory
    doc: Path to the reference generated by imfusion-build (augmented 
      reference directory with reference.fa and reference.gtf.gz).
    inputBinding:
      position: 101
      prefix: --reference
  - id: threshold
    type:
      - 'null'
      - float
    doc: Minimum corrected p-value for CTGs. (Default = 0.01).
    inputBinding:
      position: 101
      prefix: --threshold
  - id: window
    type:
      - 'null'
      - type: array
        items: int
    doc: Window around the gene (two values, upstream and downstream) within
      which a gene is tested for enrichment in insertions.
    inputBinding:
      position: 101
      prefix: --window
  - id: output_path
    type: string
    doc: Path for the output CTG file.
    inputBinding:
      position: 102
      prefix: --output
outputs:
  - id: output
    type: File
    doc: CTG result table (tab-separated).
    outputBinding:
      glob: $(inputs.output_path)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.reference)
        writable: true
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imfusion:0.3.2--pyhdfd78af_1
