cwlVersion: v1.2
class: CommandLineTool
baseCommand: imfusion-expression
label: imfusion_expression
doc: "Generate exon expression counts (featureCounts) for an IM-Fusion sample 
  directory.\n\nTool homepage: https://github.com/NKI-CCB/imfusion"
inputs:
  - id: paired
    type:
      - 'null'
      - boolean
    doc: Paired-end sequencing
    inputBinding:
      position: 101
      prefix: --paired
  - id: reference
    type: Directory
    doc: Path to the index of the augmented reference generated by imfusion-build.
    inputBinding:
      position: 101
      prefix: --reference
  - id: sample_dir
    type: Directory
    doc: Path to sample directory (typically the output of imfusion-insertions).
    inputBinding:
      position: 101
      prefix: --sample_dir
  - id: stranded
    type:
      - 'null'
      - string
    doc: 'Strandedness of the RNA-seq data: stranded, unstranded or reverse.'
    inputBinding:
      position: 101
      prefix: --stranded
  - id: output_path
    type: string
    doc: Output path for the exon counts file.
    default: expression.txt
    inputBinding:
      position: 102
      prefix: --output
outputs:
  - id: output
    type: File
    doc: Exon expression counts (tab-separated).
    outputBinding:
      glob: $(inputs.output_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imfusion:0.3.2--pyhdfd78af_1
