cwlVersion: v1.2
class: CommandLineTool
baseCommand: nanosv
label: nanosv
doc: "NanoSV is a software tool for the detection of structural variations (SVs) in
  long-read sequencing data, such as those generated by Oxford Nanopore Technologies
  (ONT).\n\nTool homepage: https://github.com/mroosmalen/nanosv"
inputs:
  - id: input_bam
    type: File
    doc: Input BAM file
    inputBinding:
      position: 1
  - id: bed_file
    type:
      - 'null'
      - File
    doc: BED file with regions to analyze
    inputBinding:
      position: 102
      prefix: --bed
  - id: bwa
    type:
      - 'null'
      - File
    doc: Path to BWA executable
    inputBinding:
      position: 102
      prefix: --bwa
  - id: gff_file
    type:
      - 'null'
      - File
    doc: GFF file with genomic features
    inputBinding:
      position: 102
      prefix: --gff
  - id: reference
    type:
      - 'null'
      - File
    doc: Reference genome FASTA file
    inputBinding:
      position: 102
      prefix: --reference
  - id: samtools
    type:
      - 'null'
      - File
    doc: Path to samtools executable
    inputBinding:
      position: 102
      prefix: --samtools
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use
    default: 4
    inputBinding:
      position: 102
      prefix: --threads
outputs:
  - id: output_vcf
    type:
      - 'null'
      - File
    doc: Output VCF file
    outputBinding:
      glob: $(inputs.output_vcf)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/nanosv:1.2.4--py_0
