cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - picard
  - IlluminaBasecallsToFastq
label: picard_IlluminaBasecallsToFastq
doc: "Generate FASTQ file(s) from Illumina basecall read data. Separate FASTQ files
  are created for each template, barcode, and index (molecular barcode) read.\n\n\
  Tool homepage: http://broadinstitute.github.io/picard/"
inputs:
  - id: adapters_to_check
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Which adapters to look for in the reads. Possible values: {PAIRED_END, INDEXED,
      SINGLE_END, NEXTERA_V1, NEXTERA_V2, DUAL_INDEXED, FLUIDIGM, TRUSEQ_SMALLRNA,
      ALTERNATIVE_SINGLE_END}'
    default: 'null'
    inputBinding:
      position: 101
      prefix: --ADAPTERS_TO_CHECK
  - id: apply_eamss_filter
    type:
      - 'null'
      - boolean
    doc: Apply EAMSS filtering to identify inappropriately quality scored bases 
      towards the ends of reads and convert their quality scores to Q2.
    default: true
    inputBinding:
      position: 101
      prefix: --APPLY_EAMSS_FILTER
  - id: arguments_file
    type:
      - 'null'
      - type: array
        items: File
    doc: read one or more arguments files and add them to the command line
    inputBinding:
      position: 101
      prefix: --arguments_file
  - id: barcodes_dir
    type:
      - 'null'
      - Directory
    doc: The barcodes directory with _barcode.txt files (generated by 
      ExtractIlluminaBarcodes). If not set, use BASECALLS_DIR.
    inputBinding:
      position: 101
      prefix: --BARCODES_DIR
  - id: basecalls_dir
    type: Directory
    doc: The Illumina basecalls directory.
    inputBinding:
      position: 101
      prefix: --BASECALLS_DIR
  - id: compress_outputs
    type:
      - 'null'
      - boolean
    doc: Compress output FASTQ files using gzip and append a .gz extension to 
      the file names.
    default: false
    inputBinding:
      position: 101
      prefix: --COMPRESS_OUTPUTS
  - id: compression_level
    type:
      - 'null'
      - int
    doc: Compression level for all compressed files created (e.g. BAM and VCF).
    default: 5
    inputBinding:
      position: 101
      prefix: --COMPRESSION_LEVEL
  - id: create_index
    type:
      - 'null'
      - boolean
    doc: Whether to create an index when writing VCF or coordinate sorted BAM 
      output.
    default: false
    inputBinding:
      position: 101
      prefix: --CREATE_INDEX
  - id: create_md5_file
    type:
      - 'null'
      - boolean
    doc: Whether to create an MD5 digest for any BAM or FASTQ files created.
    default: false
    inputBinding:
      position: 101
      prefix: --CREATE_MD5_FILE
  - id: distance_mode
    type:
      - 'null'
      - string
    doc: The distance metric that should be used to compare the barcode-reads 
      and the provided barcodes.
    default: HAMMING
    inputBinding:
      position: 101
      prefix: --DISTANCE_MODE
  - id: first_tile
    type:
      - 'null'
      - int
    doc: If set, this is the first tile to be processed (used for debugging).
    inputBinding:
      position: 101
      prefix: --FIRST_TILE
  - id: five_prime_adapter
    type:
      - 'null'
      - string
    doc: For specifying adapters other than standard Illumina
    inputBinding:
      position: 101
      prefix: --FIVE_PRIME_ADAPTER
  - id: flowcell_barcode
    type:
      - 'null'
      - string
    doc: The barcode of the flowcell that was sequenced; required if emitting 
      Casava1.8-style read name headers
    inputBinding:
      position: 101
      prefix: --FLOWCELL_BARCODE
  - id: force_gc
    type:
      - 'null'
      - boolean
    doc: If true, call System.gc() periodically.
    default: true
    inputBinding:
      position: 101
      prefix: --FORCE_GC
  - id: ignore_unexpected_barcodes
    type:
      - 'null'
      - boolean
    doc: Whether to ignore reads whose barcodes are not found in 
      MULTIPLEX_PARAMS.
    default: false
    inputBinding:
      position: 101
      prefix: --IGNORE_UNEXPECTED_BARCODES
  - id: include_non_pf_reads
    type:
      - 'null'
      - boolean
    doc: Whether to include non-PF reads
    default: true
    inputBinding:
      position: 101
      prefix: --INCLUDE_NON_PF_READS
  - id: input_params_file
    type:
      - 'null'
      - File
    doc: The input file that defines parameters for the program (BARCODE_FILE, 
      MULTIPLEX_PARAMS, or LIBRARY_PARAMS).
    inputBinding:
      position: 101
      prefix: --INPUT_PARAMS_FILE
  - id: lane
    type:
      type: array
      items: int
    doc: Lane number. This can be specified multiple times. Reads with the same 
      index in multiple lanes will be added to the same output file.
    inputBinding:
      position: 101
      prefix: --LANE
  - id: machine_name
    type:
      - 'null'
      - string
    doc: The name of the machine on which the run was sequenced; required if 
      emitting Casava1.8-style read name headers
    inputBinding:
      position: 101
      prefix: --MACHINE_NAME
  - id: match_barcodes_inline
    type:
      - 'null'
      - boolean
    doc: If true, match barcodes on the fly. Otherwise parse the barcodes from 
      the barcodes file.
    default: false
    inputBinding:
      position: 101
      prefix: --MATCH_BARCODES_INLINE
  - id: max_mismatches
    type:
      - 'null'
      - int
    doc: Maximum mismatches for a barcode to be considered a match.
    default: 1
    inputBinding:
      position: 101
      prefix: --MAX_MISMATCHES
  - id: max_no_calls
    type:
      - 'null'
      - int
    doc: Maximum allowable number of no-calls in a barcode read before it is 
      considered unmatchable.
    default: 2
    inputBinding:
      position: 101
      prefix: --MAX_NO_CALLS
  - id: max_records_in_ram
    type:
      - 'null'
      - int
    doc: When writing files that need to be sorted, this will specify the number
      of records stored in RAM before spilling to disk.
    default: 500000
    inputBinding:
      position: 101
      prefix: --MAX_RECORDS_IN_RAM
  - id: min_mismatch_delta
    type:
      - 'null'
      - int
    doc: Minimum difference between number of mismatches in the best and second 
      best barcodes for a barcode to be considered a match.
    default: 1
    inputBinding:
      position: 101
      prefix: --MIN_MISMATCH_DELTA
  - id: min_trimmed_length
    type:
      - 'null'
      - int
    doc: The minimum length for a trimmed read.
    default: 20
    inputBinding:
      position: 101
      prefix: --MIN_TRIMMED_LENGTH
  - id: minimum_base_quality
    type:
      - 'null'
      - int
    doc: Minimum base quality. Any barcode bases falling below this quality will
      be considered a mismatch.
    default: 0
    inputBinding:
      position: 101
      prefix: --MINIMUM_BASE_QUALITY
  - id: minimum_quality
    type:
      - 'null'
      - int
    doc: The minimum quality (after transforming 0s to 1s) expected from reads.
    default: 2
    inputBinding:
      position: 101
      prefix: --MINIMUM_QUALITY
  - id: multiplex_params
    type: File
    doc: Tab-separated file for creating all output FASTQs demultiplexed by 
      barcode for a lane with single IlluminaBasecallsToFastq invocation. Cannot
      be used in conjunction with OUTPUT_PREFIX.
    inputBinding:
      position: 101
      prefix: --MULTIPLEX_PARAMS
  - id: num_processors
    type:
      - 'null'
      - int
    doc: The number of threads to run in parallel. 0 sets to available cores.
    default: 0
    inputBinding:
      position: 101
      prefix: --NUM_PROCESSORS
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Whether to suppress job-summary info on System.err.
    default: false
    inputBinding:
      position: 101
      prefix: --QUIET
  - id: read_name_format
    type:
      - 'null'
      - string
    doc: 'The read name header formatting to emit. Possible values: {CASAVA_1_8, ILLUMINA}'
    default: CASAVA_1_8
    inputBinding:
      position: 101
      prefix: --READ_NAME_FORMAT
  - id: read_structure
    type: string
    doc: A description of the logical structure of clusters in an Illumina Run 
      (e.g. 28T8M8B8S28T).
    inputBinding:
      position: 101
      prefix: --READ_STRUCTURE
  - id: reference_sequence
    type:
      - 'null'
      - File
    doc: Reference sequence file.
    inputBinding:
      position: 101
      prefix: --REFERENCE_SEQUENCE
  - id: run_barcode
    type: string
    doc: The barcode of the run. Prefixed to read names.
    inputBinding:
      position: 101
      prefix: --RUN_BARCODE
  - id: show_hidden
    type:
      - 'null'
      - boolean
    doc: display hidden arguments
    default: false
    inputBinding:
      position: 101
      prefix: --showHidden
  - id: sort
    type:
      - 'null'
      - boolean
    doc: If true, the output records are sorted by read name.
    default: true
    inputBinding:
      position: 101
      prefix: --SORT
  - id: three_prime_adapter
    type:
      - 'null'
      - string
    doc: For specifying adapters other than standard Illumina
    inputBinding:
      position: 101
      prefix: --THREE_PRIME_ADAPTER
  - id: tile_limit
    type:
      - 'null'
      - int
    doc: If set, process no more than this many tiles (used for debugging).
    inputBinding:
      position: 101
      prefix: --TILE_LIMIT
  - id: tmp_dir
    type:
      - 'null'
      - type: array
        items: Directory
    doc: One or more directories with space available to be used by this program
      for temporary storage of working files
    inputBinding:
      position: 101
      prefix: --TMP_DIR
  - id: trimming_quality
    type:
      - 'null'
      - int
    doc: The quality to use as a threshold for trimming.
    inputBinding:
      position: 101
      prefix: --TRIMMING_QUALITY
  - id: use_jdk_deflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Deflater instead of the Intel Deflater for writing 
      compressed output
    default: false
    inputBinding:
      position: 101
      prefix: --USE_JDK_DEFLATER
  - id: use_jdk_inflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Inflater instead of the Intel Inflater for reading 
      compressed input
    default: false
    inputBinding:
      position: 101
      prefix: --USE_JDK_INFLATER
  - id: validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for all SAM files read by this program. Possible values:
      {STRICT, LENIENT, SILENT}'
    default: STRICT
    inputBinding:
      position: 101
      prefix: --VALIDATION_STRINGENCY
  - id: verbosity
    type:
      - 'null'
      - string
    doc: 'Control verbosity of logging. Possible values: {ERROR, WARNING, INFO, DEBUG}'
    default: INFO
    inputBinding:
      position: 101
      prefix: --VERBOSITY
outputs:
  - id: output_prefix
    type: File
    doc: The prefix for output FASTQs. Extensions are appended. Cannot be used 
      in conjunction with MULTIPLEX_PARAMS.
    outputBinding:
      glob: $(inputs.output_prefix)
  - id: metrics_file
    type:
      - 'null'
      - File
    doc: Per-barcode and per-lane metrics written to this file.
    outputBinding:
      glob: $(inputs.metrics_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/picard:3.4.0--hdfd78af_0
