cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - picard
  - GtcToVcf
label: picard_GtcToVcf
doc: GtcToVcf takes an Illumina GTC file and converts it to a VCF file using 
  several supporting files. A GTC file is an Illumina-specific file containing 
  called genotypes in AA/AB/BB format. A VCF, aka Variant Calling Format, is a 
  text file for storing how a sequenced sample differs from the reference 
  genome.
inputs:
  - id: cluster_file
    type: File
    doc: An Illumina cluster file (egt)
    inputBinding:
      position: 101
      prefix: --CLUSTER_FILE
  - id: extended_illumina_manifest
    type:
      - 'null'
      - File
    doc: An Extended Illumina Manifest file (csv). This is an extended version 
      of the Illumina manifest it contains additional reference-specific fields
    inputBinding:
      position: 101
      prefix: --EXTENDED_ILLUMINA_MANIFEST
  - id: illumina_bead_pool_manifest_file
    type:
      - 'null'
      - File
    doc: The Illumina Bead Pool Manifest (.bpm) file
    inputBinding:
      position: 101
      prefix: --ILLUMINA_BEAD_POOL_MANIFEST_FILE
  - id: input
    type:
      - 'null'
      - File
    doc: GTC file to be converted
    inputBinding:
      position: 101
      prefix: --INPUT
  - id: output
    type: string
    doc: The output VCF file to write.
    inputBinding:
      position: 101
      prefix: --OUTPUT
  - id: reference_sequence
    type:
      - 'null'
      - File
    doc: Reference sequence file.
    inputBinding:
      position: 101
      prefix: --REFERENCE_SEQUENCE
  - id: sample_alias
    type: string
    doc: The sample alias
    inputBinding:
      position: 101
      prefix: --SAMPLE_ALIAS
  - id: analysis_version_number
    type:
      - 'null'
      - int
    doc: The analysis version of the data used to generate this VCF
    inputBinding:
      position: 101
      prefix: --ANALYSIS_VERSION_NUMBER
  - id: arguments_file
    type:
      - 'null'
      - type: array
        items: File
    doc: read one or more arguments files and add them to the command line
    inputBinding:
      position: 101
      prefix: --arguments_file
  - id: compression_level
    type:
      - 'null'
      - int
    doc: Compression level for all compressed files created (e.g. BAM and VCF).
    inputBinding:
      position: 101
      prefix: --COMPRESSION_LEVEL
  - id: create_index
    type:
      - 'null'
      - boolean
    doc: Whether to create an index when writing VCF or coordinate sorted BAM 
      output.
    inputBinding:
      position: 101
      prefix: --CREATE_INDEX
  - id: create_md5_file
    type:
      - 'null'
      - boolean
    doc: Whether to create an MD5 digest for any BAM or FASTQ files created.
    inputBinding:
      position: 101
      prefix: --CREATE_MD5_FILE
  - id: do_not_allow_calls_on_zeroed_out_assays
    type:
      - 'null'
      - boolean
    doc: Causes the program to fail if it finds a case where there is a call on 
      an assay that is flagged as 'zeroed-out' in the Illumina cluster file.
    inputBinding:
      position: 101
      prefix: --DO_NOT_ALLOW_CALLS_ON_ZEROED_OUT_ASSAYS
  - id: expected_gender
    type:
      - 'null'
      - string
    doc: The expected gender for this sample.
    inputBinding:
      position: 101
      prefix: --EXPECTED_GENDER
  - id: fingerprint_genotypes_vcf_file
    type:
      - 'null'
      - File
    doc: The fingerprint VCF for this sample
    inputBinding:
      position: 101
      prefix: --FINGERPRINT_GENOTYPES_VCF_FILE
  - id: gender_gtc
    type:
      - 'null'
      - File
    doc: An optional GTC file that was generated by calling the chip using a 
      cluster file designed to optimize gender calling.
    inputBinding:
      position: 101
      prefix: --GENDER_GTC
  - id: max_records_in_ram
    type:
      - 'null'
      - int
    doc: When writing files that need to be sorted, this will specify the number
      of records stored in RAM before spilling to disk.
    inputBinding:
      position: 101
      prefix: --MAX_RECORDS_IN_RAM
  - id: pipeline_version
    type:
      - 'null'
      - string
    doc: The version of the pipeline used to generate this VCF
    inputBinding:
      position: 101
      prefix: --PIPELINE_VERSION
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Whether to suppress job-summary info on System.err.
    inputBinding:
      position: 101
      prefix: --QUIET
  - id: tmp_dir
    type:
      - 'null'
      - type: array
        items: Directory
    doc: One or more directories with space available to be used by this program
      for temporary storage of working files
    inputBinding:
      position: 101
      prefix: --TMP_DIR
  - id: use_jdk_deflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Deflater instead of the Intel Deflater for writing 
      compressed output
    inputBinding:
      position: 101
      prefix: --USE_JDK_DEFLATER
  - id: use_jdk_inflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Inflater instead of the Intel Inflater for reading 
      compressed input
    inputBinding:
      position: 101
      prefix: --USE_JDK_INFLATER
  - id: validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for all SAM files read by this program. Possible values:
      {STRICT, LENIENT, SILENT}'
    inputBinding:
      position: 101
      prefix: --VALIDATION_STRINGENCY
  - id: show_hidden
    type:
      - 'null'
      - boolean
    doc: display hidden arguments
    inputBinding:
      position: 101
      prefix: --showHidden
outputs:
  - id: output_output
    type: File
    doc: The output VCF file to write.
    outputBinding:
      glob: $(inputs.output)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/picard:3.4.0--hdfd78af_0
s:url: http://broadinstitute.github.io/picard/
$namespaces:
  s: https://schema.org/
