cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - picard
  - IlluminaBasecallsToSam
label: picard_IlluminaBasecallsToSam
doc: Transforms raw Illumina sequencing data into an unmapped SAM, BAM or CRAM 
  file. The IlluminaBaseCallsToSam program collects, demultiplexes, and sorts 
  reads across all of the tiles of a lane via barcode to produce an unmapped 
  SAM, BAM or CRAM file.
inputs:
  - id: barcode_params
    type: File
    doc: Deprecated (use LIBRARY_PARAMS). Tab-separated file for creating all 
      output SAM, BAM or CRAM files for barcoded run with single 
      IlluminaBasecallsToSam invocation.
    inputBinding:
      position: 101
      prefix: --BARCODE_PARAMS
  - id: basecalls_dir
    type:
      - 'null'
      - Directory
    doc: The Illumina basecalls directory.
    inputBinding:
      position: 101
      prefix: --BASECALLS_DIR
  - id: lane
    type:
      type: array
      items: int
    doc: Lane number. This can be specified multiple times.
    inputBinding:
      position: 101
      prefix: --LANE
  - id: library_params
    type:
      - 'null'
      - File
    doc: Tab-separated file for creating all output SAM, BAM or CRAM files for a
      lane with single IlluminaBasecallsToSam invocation.
    inputBinding:
      position: 101
      prefix: --LIBRARY_PARAMS
  - id: output
    type: string
    doc: Deprecated (use LIBRARY_PARAMS). The output SAM, BAM or CRAM file.
    inputBinding:
      position: 101
      prefix: --OUTPUT
  - id: read_structure
    type: string
    doc: A description of the logical structure of clusters in an Illumina Run.
    inputBinding:
      position: 101
      prefix: --READ_STRUCTURE
  - id: run_barcode
    type: string
    doc: The barcode of the run. Prefixed to read names.
    inputBinding:
      position: 101
      prefix: --RUN_BARCODE
  - id: sample_alias
    type: string
    doc: Deprecated (use LIBRARY_PARAMS). The name of the sequenced sample.
    inputBinding:
      position: 101
      prefix: --SAMPLE_ALIAS
  - id: sequencing_center
    type: string
    doc: The name of the sequencing center that produced the reads. Used to set 
      the @RG->CN header tag.
    inputBinding:
      position: 101
      prefix: --SEQUENCING_CENTER
  - id: adapters_to_check
    type:
      - 'null'
      - type: array
        items: string
    doc: Which adapters to look for in the read.
    inputBinding:
      position: 101
      prefix: --ADAPTERS_TO_CHECK
  - id: apply_eamss_filter
    type:
      - 'null'
      - boolean
    doc: Apply EAMSS filtering to identify inappropriately quality scored bases 
      towards the ends of reads.
    inputBinding:
      position: 101
      prefix: --APPLY_EAMSS_FILTER
  - id: arguments_file
    type:
      - 'null'
      - type: array
        items: File
    doc: read one or more arguments files and add them to the command line
    inputBinding:
      position: 101
      prefix: --arguments_file
  - id: barcode_population_strategy
    type:
      - 'null'
      - string
    doc: When should the sample barcode (as read by the sequencer) be placed on 
      the reads in the BC tag?
    inputBinding:
      position: 101
      prefix: --BARCODE_POPULATION_STRATEGY
  - id: barcodes_dir
    type:
      - 'null'
      - Directory
    doc: The barcodes directory with _barcode.txt files (generated by 
      ExtractIlluminaBarcodes).
    inputBinding:
      position: 101
      prefix: --BARCODES_DIR
  - id: compress_outputs
    type:
      - 'null'
      - boolean
    doc: Compress output FASTQ files using gzip and append a .gz extension to 
      the file names.
    inputBinding:
      position: 101
      prefix: --COMPRESS_OUTPUTS
  - id: compression_level
    type:
      - 'null'
      - int
    doc: Compression level for all compressed files created (e.g. BAM and VCF).
    inputBinding:
      position: 101
      prefix: --COMPRESSION_LEVEL
  - id: create_index
    type:
      - 'null'
      - boolean
    doc: Whether to create an index when writing VCF or coordinate sorted BAM 
      output.
    inputBinding:
      position: 101
      prefix: --CREATE_INDEX
  - id: create_md5_file
    type:
      - 'null'
      - boolean
    doc: Whether to create an MD5 digest for any BAM or FASTQ files created.
    inputBinding:
      position: 101
      prefix: --CREATE_MD5_FILE
  - id: distance_mode
    type:
      - 'null'
      - string
    doc: The distance metric that should be used to compare the barcode-reads 
      and the provided barcodes.
    inputBinding:
      position: 101
      prefix: --DISTANCE_MODE
  - id: first_tile
    type:
      - 'null'
      - int
    doc: If set, this is the first tile to be processed (used for debugging).
    inputBinding:
      position: 101
      prefix: --FIRST_TILE
  - id: five_prime_adapter
    type:
      - 'null'
      - string
    doc: For specifying adapters other than standard Illumina
    inputBinding:
      position: 101
      prefix: --FIVE_PRIME_ADAPTER
  - id: ignore_unexpected_barcodes
    type:
      - 'null'
      - boolean
    doc: Whether to ignore reads whose barcodes are not found in LIBRARY_PARAMS.
    inputBinding:
      position: 101
      prefix: --IGNORE_UNEXPECTED_BARCODES
  - id: include_barcode_quality
    type:
      - 'null'
      - boolean
    doc: Should the barcode quality be included when the sample barcode is 
      included?
    inputBinding:
      position: 101
      prefix: --INCLUDE_BARCODE_QUALITY
  - id: include_bc_in_rg_tag
    type:
      - 'null'
      - boolean
    doc: Whether to include the barcode information in the @RG->BC header tag.
    inputBinding:
      position: 101
      prefix: --INCLUDE_BC_IN_RG_TAG
  - id: include_non_pf_reads
    type:
      - 'null'
      - boolean
    doc: Whether to include non-PF reads
    inputBinding:
      position: 101
      prefix: --INCLUDE_NON_PF_READS
  - id: input_params_file
    type:
      - 'null'
      - File
    doc: The input file that defines parameters for the program.
    inputBinding:
      position: 101
      prefix: --INPUT_PARAMS_FILE
  - id: library_name
    type:
      - 'null'
      - string
    doc: Deprecated (use LIBRARY_PARAMS). The name of the sequenced library
    inputBinding:
      position: 101
      prefix: --LIBRARY_NAME
  - id: match_barcodes_inline
    type:
      - 'null'
      - boolean
    doc: If true, match barcodes on the fly. Otherwise parse the barcodes from 
      the barcodes file.
    inputBinding:
      position: 101
      prefix: --MATCH_BARCODES_INLINE
  - id: max_mismatches
    type:
      - 'null'
      - int
    doc: Maximum mismatches for a barcode to be considered a match.
    inputBinding:
      position: 101
      prefix: --MAX_MISMATCHES
  - id: max_no_calls
    type:
      - 'null'
      - int
    doc: Maximum allowable number of no-calls in a barcode read before it is 
      considered unmatchable.
    inputBinding:
      position: 101
      prefix: --MAX_NO_CALLS
  - id: max_records_in_ram
    type:
      - 'null'
      - int
    doc: When writing files that need to be sorted, this will specify the number
      of records stored in RAM before spilling to disk.
    inputBinding:
      position: 101
      prefix: --MAX_RECORDS_IN_RAM
  - id: metrics_file
    type: string
    doc: Per-barcode and per-lane metrics written to this file.
    inputBinding:
      position: 101
      prefix: --METRICS_FILE
  - id: min_mismatch_delta
    type:
      - 'null'
      - int
    doc: Minimum difference between number of mismatches in the best and second 
      best barcodes for a barcode to be considered a match.
    inputBinding:
      position: 101
      prefix: --MIN_MISMATCH_DELTA
  - id: minimum_base_quality
    type:
      - 'null'
      - int
    doc: Minimum base quality. Any barcode bases falling below this quality will
      be considered a mismatch even if the bases match.
    inputBinding:
      position: 101
      prefix: --MINIMUM_BASE_QUALITY
  - id: minimum_quality
    type:
      - 'null'
      - int
    doc: The minimum quality (after transforming 0s to 1s) expected from reads.
    inputBinding:
      position: 101
      prefix: --MINIMUM_QUALITY
  - id: molecular_index_base_quality_tag
    type:
      - 'null'
      - string
    doc: The tag to use to store any molecular index base qualities.
    inputBinding:
      position: 101
      prefix: --MOLECULAR_INDEX_BASE_QUALITY_TAG
  - id: molecular_index_tag
    type:
      - 'null'
      - string
    doc: The tag to use to store any molecular indexes.
    inputBinding:
      position: 101
      prefix: --MOLECULAR_INDEX_TAG
  - id: num_processors
    type:
      - 'null'
      - int
    doc: The number of threads to run in parallel.
    inputBinding:
      position: 101
      prefix: --NUM_PROCESSORS
  - id: platform
    type:
      - 'null'
      - string
    doc: The name of the sequencing technology that produced the read.
    inputBinding:
      position: 101
      prefix: --PLATFORM
  - id: process_single_tile
    type:
      - 'null'
      - int
    doc: If set, process only the tile number given and prepend the tile number 
      to the output file name.
    inputBinding:
      position: 101
      prefix: --PROCESS_SINGLE_TILE
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Whether to suppress job-summary info on System.err.
    inputBinding:
      position: 101
      prefix: --QUIET
  - id: read_group_id
    type:
      - 'null'
      - string
    doc: ID used to link RG header record with RG tag in SAM record.
    inputBinding:
      position: 101
      prefix: --READ_GROUP_ID
  - id: reference_sequence
    type:
      - 'null'
      - File
    doc: Reference sequence file.
    inputBinding:
      position: 101
      prefix: --REFERENCE_SEQUENCE
  - id: sort
    type:
      - 'null'
      - boolean
    doc: If true, the output records are sorted by read name. Otherwise they are
      unsorted.
    inputBinding:
      position: 101
      prefix: --SORT
  - id: tag_per_molecular_index
    type:
      - 'null'
      - type: array
        items: string
    doc: The list of tags to store each molecular index.
    inputBinding:
      position: 101
      prefix: --TAG_PER_MOLECULAR_INDEX
  - id: three_prime_adapter
    type:
      - 'null'
      - string
    doc: For specifying adapters other than standard Illumina
    inputBinding:
      position: 101
      prefix: --THREE_PRIME_ADAPTER
  - id: tile_limit
    type:
      - 'null'
      - int
    doc: If set, process no more than this many tiles (used for debugging).
    inputBinding:
      position: 101
      prefix: --TILE_LIMIT
  - id: tmp_dir
    type:
      - 'null'
      - type: array
        items: Directory
    doc: One or more directories with space available to be used by this program
      for temporary storage of working files
    inputBinding:
      position: 101
      prefix: --TMP_DIR
  - id: use_jdk_deflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Deflater instead of the Intel Deflater for writing 
      compressed output
    inputBinding:
      position: 101
      prefix: --USE_JDK_DEFLATER
  - id: use_jdk_inflater
    type:
      - 'null'
      - boolean
    doc: Use the JDK Inflater instead of the Intel Inflater for reading 
      compressed input
    inputBinding:
      position: 101
      prefix: --USE_JDK_INFLATER
  - id: validation_stringency
    type:
      - 'null'
      - string
    doc: Validation stringency for all SAM files read by this program.
    inputBinding:
      position: 101
      prefix: --VALIDATION_STRINGENCY
  - id: show_hidden
    type:
      - 'null'
      - boolean
    doc: display hidden arguments
    inputBinding:
      position: 101
      prefix: --showHidden
outputs:
  - id: output_output
    type: File
    doc: Deprecated (use LIBRARY_PARAMS). The output SAM, BAM or CRAM file.
    outputBinding:
      glob: $(inputs.output)
  - id: output_metrics_file
    type:
      - 'null'
      - File
    doc: Per-barcode and per-lane metrics written to this file.
    outputBinding:
      glob: $(inputs.metrics_file)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/picard:3.4.0--hdfd78af_0
s:url: http://broadinstitute.github.io/picard/
$namespaces:
  s: https://schema.org/
