cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - scssim
  - genreads
label: scssim_genreads
doc: "Generate reads from a sequence file using MALBAC and read simulation models\n
  \nTool homepage: https://github.com/qasimyu/scssim"
inputs:
  - id: coverage
    type:
      - 'null'
      - float
    doc: sequencing coverage
    default: 5
    inputBinding:
      position: 101
      prefix: --coverage
  - id: gamma
    type:
      - 'null'
      - float
    doc: a parameter controlling the number of primers used in each cycle
    default: 1e-09
    inputBinding:
      position: 101
      prefix: --gamma
  - id: input
    type: File
    doc: sequence file (.fasta) generated by simuVars program
    inputBinding:
      position: 101
      prefix: --input
  - id: isize
    type:
      - 'null'
      - int
    doc: mean insert size for paired-end sequencing
    default: 260
    inputBinding:
      position: 101
      prefix: --isize
  - id: layout
    type:
      - 'null'
      - string
    doc: read layout (SE for single end, PE for paired-end)
    default: PE
    inputBinding:
      position: 101
      prefix: --layout
  - id: model
    type:
      - 'null'
      - File
    doc: profile inferred from real sequencing data
    inputBinding:
      position: 101
      prefix: --model
  - id: primers
    type:
      - 'null'
      - int
    doc: the number of primers
    default: 100000
    inputBinding:
      position: 101
      prefix: --primers
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads to use
    default: 1
    inputBinding:
      position: 101
      prefix: --threads
outputs:
  - id: output
    type:
      - 'null'
      - File
    doc: the prefix of output file
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/scssim:1.0--h9948957_5
