#!/usr/bin/env cwltool

cwlVersion: v1.2
class: CommandLineTool

label: Bakta - rapid & standardized annotation of bacterial genomes, MAGs & plasmids

doc: |
  The software and documentation can be found here:
  https://github.com/oschwengers/bakta

  Necessary database files can be found here:
  https://doi.org/10.5281/zenodo.4247252

requirements:
  InlineJavascriptRequirement: {}

hints:
  DockerRequirement:
    dockerPull: docker-registry.wur.nl/m-unlock/docker/bakta:1.9.4-db-light5.1 # this docker container has bakta as entrypoint, so a baseCommand is not needed
  SoftwareRequirement:
    packages:
      bakta:
        version: [ "1.9.4" ]
        specs: ["identifiers.org/RRID:SCR_026400"]
  
arguments:
  - prefix: "--db"
    valueFrom: |
      ${
        // check if custom profile directory is used
        if (inputs.db){
          return inputs.db.path
        }
        // else use default built-in bakta db-light database
        else { 
          return "/bakta-db_v5.1-light";
        }
      }

inputs:
  fasta_file:
    type: File
    label: input genome
    doc: Genome assembly in FASTA format.
    inputBinding:
      position: 100
  database:
    type: Directory?
    label: database path
    doc: Path to the database (default = built-in light database).
  min_contig_length:
    type: int?
    label: minimum contig size
    doc: Minimum contig size (default = 1; 200 in compliant mode).
    inputBinding:
      prefix: --min-contig-length
  prefix:
    type: string?
    label: output prefix
    doc: Prefix for output files.
    inputBinding:
      prefix: --prefix
  output_folder:
    type: string?
    label: output directory
    doc: Output directory (default = current working directory).
    inputBinding:
      prefix: --output
  force_overwrite:
    type: boolean?
    label: force overwrite
    doc: Force overwriting existing output folder (except for current working directory).
    inputBinding:
      prefix: --force
  genus:
    type: string?
    label: genus name
    doc: Genus name.
    inputBinding:
      prefix: --genus
  species:
    type: string?
    label: species name
    doc: Species name.
    inputBinding:
      prefix: --species
  strain:
    type: string?
    label: strain name
    doc: Strain name.
    inputBinding:
      prefix: --strain
  plasmid:
    type: string?
    label: plasmid name
    doc: Plasmid name.
    inputBinding:
      prefix: --plasmid
  complete_replicons:
    type: boolean?
    label: complete replicons
    doc: All sequences are complete replicons (chromosome/plasmid[s]).
    inputBinding:
      prefix: --complete
  prodigal_tf:
    type: File?
    label: prodigal training file
    doc: Prodigal training file for CDS prediction.
    inputBinding:
      prefix: --prodigal-tf
  translation_table:
    type: int?
    label: translation table
    doc: Translation table (default = 11).
    inputBinding:
      prefix: --translation-table
  gram_type:
    type: string?
    label: gram type
    doc: Gram type.
    inputBinding:
      prefix: --gram
  locus_prefix:
    type: string?
    label: locus prefix
    doc: Locus prefix (default = contig).
    inputBinding:
      prefix: --locus
  locus_tag_prefix:
    type: string?
    label: locus tag prefix
    doc: Locus tag prefix (default = autogenerated).
    inputBinding:
      prefix: --locus-tag
  keep_contig_headers:
    type: boolean?
    label: keep contig headers
    doc: Keep original contig headers.
    inputBinding:
      prefix: --keep-contig-headers
  compliant:
    type: boolean?
    label: force compliance
    doc: Force Genbank/ENA/DDJB compliance.
    inputBinding:
      prefix: --compliant
  replicons:
    type: File?
    label: replicon information table
    doc: Replicon information table (tsv/csv).
    inputBinding:
      prefix: --replicons
  regions:
    type: File?
    label: regions file
    doc: Genbank/GFF3 file of trusted regions for pre-detected feature coordinates.
    inputBinding:
      prefix: --regions
  proteins:
    type: File?
    label: protein sequences file
    doc: Fasta file of trusted protein sequences for CDS annotation.
    inputBinding:
      prefix: --proteins
  meta:
    type: boolean?
    label: run in metagenome mode
    doc: Run in metagenome mode.
    inputBinding:
      prefix: --meta
  skip_tRNA:
    type: boolean?
    label: skip tRNA detection
    doc: Skip tRNA detection & annotation.
    inputBinding:
      prefix: --skip-trna
  skip_tmrna:
    type: boolean?
    label: skip tmRNA detection
    doc: Skip tmRNA detection & annotation.
    inputBinding:
      prefix: --skip-tmrna
  skip_rrna:
    type: boolean?
    label: skip rRNA detection
    doc: Skip rRNA detection & annotation.
    inputBinding:
      prefix: --skip-rrna
  skip_ncrna:
    type: boolean?
    label: skip ncRNA detection
    doc: Skip ncRNA detection & annotation.
    inputBinding:
      prefix: --skip-ncrna
  skip_ncrna_region:
    type: boolean?
    label: skip ncRNA region detection
    doc: Skip ncRNA region detection & annotation.
    inputBinding:
      prefix: --skip-ncrna-region
  skip_crispr:
    type: boolean?
    label: skip CRISPR detection
    doc: Skip CRISPR detection & annotation.
    inputBinding:
      prefix: --skip-crispr
  skip_cds:
    type: boolean?
    label: skip CDS detection
    doc: Skip CDS detection & annotation.
    inputBinding:
      prefix: --skip-cds
  skip_pseudo:
    type: boolean?
    label: skip pseudogene detection
    doc: Skip Pseudogene detection & annotation.
    inputBinding:
      prefix: --skip-pseudo
  skip_sorf:
    type: boolean?
    label: skip sORF detection
    doc: Skip sORF detection & annotation.
    inputBinding:
      prefix: --skip-sorf
  skip_gap:
    type: boolean?
    label: skip gap detection
    doc: Skip gap detection & annotation.
    inputBinding:
      prefix: --skip-gap
  skip_ori:
    type: boolean?
    label: skip ori detection
    doc: Skip ori detection & annotation.
    inputBinding:
      prefix: --skip-ori
  skip_plot:
    type: boolean?
    label: skip genome plotting
    doc: Skip genome plotting.
    inputBinding:
      prefix: --skip-plot
  verbose:
    type: boolean?
    label: print verbose information
    doc: Print verbose information.
    inputBinding:
      prefix: --verbose
  debug:
    type: boolean?
    label: run in debug mode
    doc: Run Bakta in debug mode.
    inputBinding:
      prefix: --debug
  threads:
    type: int?
    label: threads
    doc: Number of threads.
    inputBinding:
      prefix: --threads
  tmp_dir:
    type: Directory?
    label: temporary directory
    doc: Directory for temporary files (default = system dependent auto detection).
    inputBinding:
      prefix: --tmp-dir
  
outputs:
  output_dir:
    type: Directory
    label: output directory
    doc: Bakta output directory.
    outputBinding:
      glob: "$(inputs.output_folder)"
  hypo_sequences_cds:
    type: File
    label: hypothetical CDS AA sequences as Fasta
    doc: Hypothetical CDS AA sequences as Fasta.
    format: edam:format_2200
    outputBinding:
      glob: "$(inputs.output_folder)/*.hypotheticals.faa"
  hypo_annotation_tsv:
    type: File
    label: information on hypothetical CDS as TSV
    doc: Information on hypothetical CDS as TSV.
    format: edam:format_3475
    outputBinding:
      glob: "$(inputs.output_folder)/*.hypotheticals.tsv"
  annotation_tsv:
    type: File
    label: annotation as TSV
    doc: Annotation as TSV.
    format: edam:format_3475
    outputBinding:
      glob: "$(inputs.output_folder)/*.tsv"
      outputEval: $(self.filter(function(f) { return !f.basename.match('hypotheticals'); }))
  summary_txt:
    type: File
    label: annotation summary as txt
    doc: Annotation summary as txt.
    format: edam:format_2330
    outputBinding:
      glob: "$(inputs.output_folder)/*.txt"
  annotation_json:
    type: File
    label: annotation as JSON
    doc: Annotation as JSON.
    format: edam:format_3464
    outputBinding:
      glob: "$(inputs.output_folder)/*.json"
  annotation_gff3:
    type: File
    label: annotation as GFF3
    doc: Annotation as GFF3.
    format: edam:format_1939
    outputBinding:
      glob: "$(inputs.output_folder)/*.gff3"
  annotation_gbff:
    type: File
    label: annotation as GenBank
    doc: Annotation as GenBank.
    format: edam:format_1936
    outputBinding:
      glob: "$(inputs.output_folder)/*.gbff"
  annotation_embl:
    type: File
    label: annotation as EMBL
    doc: Annotation as EMBL.
    format: edam:format_1927
    outputBinding:
      glob: "$(inputs.output_folder)/*.embl"
  sequences_fna:
    type: File
    label: genome sequences as Fasta
    doc: Genome sequences as Fasta.
    format: edam:format_2200
    outputBinding:
      glob: "$(inputs.output_folder)/*.fna"
  sequences_ffn:
    type: File
    label: gene DNA sequences as Fasta
    doc: Gene DNA sequences as Fasta.
    format: edam:format_2200
    outputBinding:
      glob: "$(inputs.output_folder)/*.ffn"
  sequences_cds:
    type: File
    label: CDS AA sequences as Fasta
    doc: CDS AA sequences as Fasta.
    format: edam:format_2200
    outputBinding:
      glob: "$(inputs.output_folder)/*.faa"
      outputEval: $(self.filter(function(f) { return !f.basename.match('hypotheticals'); }))
  plot_png:
    type: File?
    label: circular genome plot as PNG
    doc: Circular genome plot as PNG.
    format: edam:format_3603
    outputBinding:
      glob: "$(inputs.output_folder)/*.png"
  plot_svg:
    type: File?
    label: circular genome plot as SVG
    doc: Circular genome plot as SVG.
    format: edam:format_3604
    outputBinding:
      glob: "$(inputs.output_folder)/*.svg"

$namespaces:
  s: https://schema.org/
  edam: http://edamontology.org/
s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-8172-8981
    s:email: mailto:jasper.koehorst@wur.nl
    s:name: Jasper Koehorst
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-9524-5964
    s:email: mailto:bart.nijsse@wur.nl
    s:name: Bart Nijsse
  - class: s:Person
    s:identifier: https://orcid.org/0009-0001-1350-5644
    s:email: mailto:changlin.ke@wur.nl
    s:name: Changlin Ke
  - class: s:Person
    s:identifier: https://orcid.org/0000-0003-4216-2721
    s:email: mailto:oliver.schwengers@computational.bio.uni-giessen.de
    s:name: Oliver Schwengers
  - class: s:Person
    s:identifier: https://orcid.org/0009-0005-0017-0928
    s:email: mailto:martijn.melissen@wur.nl
    s:name: Martijn Melissen
s:citation: https://m-unlock.nl
s:codeRepository: https://gitlab.com/m-unlock/cwl
s:dateCreated: "2020-00-00"
s:dateModified: "2025-03-12"
s:license: https://spdx.org/licenses/Apache-2.0
s:copyrightHolder: "UNLOCK - Unlocking Microbial Potential"