cwlVersion: v1.2
class: CommandLineTool
baseCommand: StrainR
label: strainr2_StrainR
doc: "StrainR normalizes mapping from reads using the output from PreProcessR\n\n\
  Tool homepage: https://github.com/BisanzLab/StrainR2"
inputs:
  - id: background1
    type:
      - 'null'
      - File
    doc: path to forward background reads for exclusion. This is not necessary 
      in a typical use case.
    default: None
    inputBinding:
      position: 101
      prefix: --background1
  - id: background2
    type:
      - 'null'
      - File
    doc: path to reverse background reads for exclusion. This is not necessary 
      in a typical use case.
    default: None
    inputBinding:
      position: 101
      prefix: --background2
  - id: forward_reads
    type: File
    doc: path to forward reads
    inputBinding:
      position: 101
      prefix: --forward
  - id: mem
    type:
      - 'null'
      - int
    doc: gigabytes of memory to use when running bbmap
    default: 8
    inputBinding:
      position: 101
      prefix: --mem
  - id: prefix
    type:
      - 'null'
      - string
    doc: Name of community (used in output files)
    default: sample
    inputBinding:
      position: 101
      prefix: --prefix
  - id: reference_directory
    type: Directory
    doc: path to the output directory generated by PreProcessR
    inputBinding:
      position: 101
      prefix: --reference
  - id: reverse_reads
    type:
      - 'null'
      - File
    doc: path to reverse reads
    inputBinding:
      position: 101
      prefix: --reverse
  - id: subcontigfilter
    type:
      - 'null'
      - float
    doc: Percentage of a strain's subcontigs that should be filtered out based 
      on number of unique k-mers
    default: 0
    inputBinding:
      position: 101
      prefix: --subcontigfilter
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads to use when running fastp, bbmap, and samtools. 
      Maximum is 16
    default: 8
    inputBinding:
      position: 101
      prefix: --threads
  - id: weighted_percentile
    type:
      - 'null'
      - float
    doc: Weighted percentile for a strain's FUKMs to use in abundance estimation
    default: 60
    inputBinding:
      position: 101
      prefix: --weightedpercentile
outputs:
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: path to your output directory to contain normalized abundances
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/strainr2:2.3.0--r44h577a1d6_0
