Code

* Show All Code
* Hide All Code

# Access GSE159526 data using Bioconductor’s ExperimentHub

Victor Yuan1\*

1University of British Columbia, Vancouver, Canada

\*vyuan@bcchr.ca

#### 4 November 2025

#### Package

GSE159526 1.16.0

# 1 How to access GSE159526 with Bioconductor

## 1.1 Citing `GSE159526`

We hope that *[GSE159526](https://bioconductor.org/packages/3.22/GSE159526)* will be useful for your research. Please
use the following information to cite the package and the overall approach.
Thank you!

```
## Citation info
citation("GSE159526")
#> To cite package 'GSE159526' in publications use:
#>
#>   Yuan V, Hui D, Penaherrera M, Beristain A, Robinson W (2021).
#>   "Cell-specific characterization of the placental methylome." _BMC
#>   Genomics_. doi:10.1186/s12864-020-07186-6
#>   <https://doi.org/10.1186/s12864-020-07186-6>,
#>   <https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-07186-6>.
#>
#> A BibTeX entry for LaTeX users is
#>
#>   @Article{,
#>     title = {Cell-specific characterization of the placental methylome},
#>     author = {Victor Yuan and Desmond Hui and Maria S. Penaherrera and Alexander G. Beristain and Wendy P. Robinson},
#>     year = {2021},
#>     journal = {BMC Genomics},
#>     doi = {10.1186/s12864-020-07186-6},
#>     url = {https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-07186-6},
#>   }
```

# 2 Quick start to using to `GSE159526`

There are 3 objects associated with GSE159526:

**EH6130** - Raw DNA methylation data, .idat files read into r with `minfi` and
saved as an `rgset` object.

**EH6131** - Processed filtered DNA methylation data. Described in
(Yuan, Hui, Penaherrera, Beristain, and Robinson, 2021).

**EH6132** - Sample information stored as a `tibble`/`data.frame` object.

```
eh <- ExperimentHub()
query(eh, "GSE159526")

# raw rgset
library(minfi)
GSE159526_rgset <- eh[['EH6130']] # requires minfi

# normalized processed data matrix
GSE159526_data <- eh[['EH6131']]

# sample information
GSE159526_pdat <- eh[['EH6132']]
```

# 3 Reproducibility

The *[GSE159526](https://bioconductor.org/packages/3.22/GSE159526)* package (Yuan, Hui, Penaherrera et al., 2021) was made
possible thanks to:

* R (R Core Team, 2025)
* *[BiocStyle](https://bioconductor.org/packages/3.22/BiocStyle)* (Oleś, 2025)
* *[knitr](https://CRAN.R-project.org/package%3Dknitr)* (Xie, 2025)
* *[RefManageR](https://CRAN.R-project.org/package%3DRefManageR)* (McLean, 2017)
* *[rmarkdown](https://CRAN.R-project.org/package%3Drmarkdown)* (Allaire, Xie, Dervieux, McPherson, Luraschi, Ushey, Atkins, Wickham, Cheng, Chang, and Iannone, 2025)
* *[sessioninfo](https://CRAN.R-project.org/package%3Dsessioninfo)* (Wickham, Chang, Flight, Müller, and Hester, 2025)
* *[testthat](https://CRAN.R-project.org/package%3Dtestthat)* (Wickham, 2011)

This package was developed using *[biocthis](https://bioconductor.org/packages/3.22/biocthis)*.

Code for creating the vignette:

```
## Create the vignette
library("rmarkdown")
system.time(render(here::here("vignettes", "GSE159526.Rmd"),
                   "BiocStyle::html_document"))

## Extract the R code
library("knitr")
knit("GSE159526.Rmd", tangle = TRUE)
```

Date the vignette was generated.

```
#> [1] "2025-11-04 11:21:10 EST"
```

Wallclock time spent generating the vignette.

```
#> Time difference of 0.659 secs
```

`R` session information.

```
#> ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.5.1 Patched (2025-08-23 r88802)
#>  os       Ubuntu 24.04.3 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  C
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2025-11-04
#>  pandoc   2.7.3 @ /usr/bin/ (via rmarkdown)
#>  quarto   1.7.32 @ /usr/local/bin/quarto
#>
#> ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  backports     1.5.0   2024-05-23 [2] CRAN (R 4.5.1)
#>  bibtex        0.5.1   2023-01-26 [2] CRAN (R 4.5.1)
#>  BiocManager   1.30.26 2025-06-05 [2] CRAN (R 4.5.1)
#>  BiocStyle   * 2.38.0  2025-11-03 [2] Bioconductor 3.22 (R 4.5.1)
#>  bookdown      0.45    2025-10-03 [2] CRAN (R 4.5.1)
#>  bslib         0.9.0   2025-01-30 [2] CRAN (R 4.5.1)
#>  cachem        1.1.0   2024-05-16 [2] CRAN (R 4.5.1)
#>  cli           3.6.5   2025-04-23 [2] CRAN (R 4.5.1)
#>  digest        0.6.37  2024-08-19 [2] CRAN (R 4.5.1)
#>  evaluate      1.0.5   2025-08-27 [2] CRAN (R 4.5.1)
#>  fastmap       1.2.0   2024-05-15 [2] CRAN (R 4.5.1)
#>  generics      0.1.4   2025-05-09 [2] CRAN (R 4.5.1)
#>  glue          1.8.0   2024-09-30 [2] CRAN (R 4.5.1)
#>  htmltools     0.5.8.1 2024-04-04 [2] CRAN (R 4.5.1)
#>  httr          1.4.7   2023-08-15 [2] CRAN (R 4.5.1)
#>  jquerylib     0.1.4   2021-04-26 [2] CRAN (R 4.5.1)
#>  jsonlite      2.0.0   2025-03-27 [2] CRAN (R 4.5.1)
#>  knitr         1.50    2025-03-16 [2] CRAN (R 4.5.1)
#>  lifecycle     1.0.4   2023-11-07 [2] CRAN (R 4.5.1)
#>  lubridate     1.9.4   2024-12-08 [2] CRAN (R 4.5.1)
#>  magrittr      2.0.4   2025-09-12 [2] CRAN (R 4.5.1)
#>  plyr          1.8.9   2023-10-02 [2] CRAN (R 4.5.1)
#>  R6            2.6.1   2025-02-15 [2] CRAN (R 4.5.1)
#>  Rcpp          1.1.0   2025-07-02 [2] CRAN (R 4.5.1)
#>  RefManageR  * 1.4.0   2022-09-30 [2] CRAN (R 4.5.1)
#>  rlang         1.1.6   2025-04-11 [2] CRAN (R 4.5.1)
#>  rmarkdown     2.30    2025-09-28 [2] CRAN (R 4.5.1)
#>  sass          0.4.10  2025-04-11 [2] CRAN (R 4.5.1)
#>  sessioninfo * 1.2.3   2025-02-05 [2] CRAN (R 4.5.1)
#>  stringi       1.8.7   2025-03-27 [2] CRAN (R 4.5.1)
#>  stringr       1.5.2   2025-09-08 [2] CRAN (R 4.5.1)
#>  timechange    0.3.0   2024-01-18 [2] CRAN (R 4.5.1)
#>  xfun          0.54    2025-10-30 [2] CRAN (R 4.5.1)
#>  xml2          1.4.1   2025-10-27 [2] CRAN (R 4.5.1)
#>  yaml          2.3.10  2024-07-26 [2] CRAN (R 4.5.1)
#>
#>  [1] /tmp/Rtmps18Nd9/Rinst4c996173e4f5f
#>  [2] /home/biocbuild/bbs-3.22-bioc/R/site-library
#>  [3] /home/biocbuild/bbs-3.22-bioc/R/library
#>  * ── Packages attached to the search path.
#>
#> ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

# 4 Bibliography

This vignette was generated using *[BiocStyle](https://bioconductor.org/packages/3.22/BiocStyle)*
(Oleś, 2025) with *[knitr](https://CRAN.R-project.org/package%3Dknitr)*
(Xie, 2025) and *[rmarkdown](https://CRAN.R-project.org/package%3Drmarkdown)*
(Allaire, Xie, Dervieux et al., 2025) running behind the scenes.

Citations made with *[RefManageR](https://CRAN.R-project.org/package%3DRefManageR)* (McLean, 2017).

[[1]](#cite-allaire2025rmarkdown)
J. Allaire, Y. Xie, C. Dervieux, et al.
*rmarkdown: Dynamic Documents for R*.
R package version 2.30.
2025.
URL: <https://github.com/rstudio/rmarkdown>.

[[2]](#cite-mclean2017refmanager)
M. W. McLean.
“RefManageR: Import and Manage BibTeX and BibLaTeX References in R”.
In: *The Journal of Open Source Software* (2017).
DOI: [10.21105/joss.00338](https://doi.org/10.21105/joss.00338).

[[3]](#cite-ole2025biocstyle)
A. Oleś.
*BiocStyle: Standard styles for vignettes and other Bioconductor documents*.
R package version 2.38.0.
2025.
DOI: [10.18129/B9.bioc.BiocStyle](https://doi.org/10.18129/B9.bioc.BiocStyle).
URL: <https://bioconductor.org/packages/BiocStyle>.

[[4]](#cite-2025language)
R Core Team.
*R: A Language and Environment for Statistical Computing*.
R Foundation for Statistical Computing.
Vienna, Austria, 2025.
URL: <https://www.R-project.org/>.

[[5]](#cite-wickham2011testthat)
H. Wickham.
“testthat: Get Started with Testing”.
In: *The R Journal* 3 (2011), pp. 5–10.
URL: <https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf>.

[[6]](#cite-wickham2025sessioninfo)
H. Wickham, W. Chang, R. Flight, et al.
*sessioninfo: R Session Information*.
R package version 1.2.3.
2025.
DOI: [10.32614/CRAN.package.sessioninfo](https://doi.org/10.32614/CRAN.package.sessioninfo).
URL: [https://CRAN.R-project.org/package=sessioninfo](https://CRAN.R-project.org/package%3Dsessioninfo).

[[7]](#cite-xie2025knitr)
Y. Xie.
*knitr: A General-Purpose Package for Dynamic Report Generation in R*.
R package version 1.50.
2025.
URL: <https://yihui.org/knitr/>.

[[8]](#cite-yuan2021cell)
V. Yuan, D. Hui, M. Penaherrera, et al.
“Cell-specific characterization of the placental methylome”.
In: *BMC Genomics* (2021).
DOI: [10.1186/s12864-020-07186-6](https://doi.org/10.1186/s12864-020-07186-6).
URL: <https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-07186-6>.