cwlVersion: v1.2
class: CommandLineTool
baseCommand: evolve.py
label: phylowgs_evolve.py
doc: "Run PhyloWGS to infer subclonal composition from SSMs and CNVs\n\nTool homepage:
  https://github.com/morrislab/phylowgs"
inputs:
  - id: ssm_file
    type: File
    doc: File listing SSMs (simple somatic mutations, i.e., single nucleotide 
      variants. For proper format, see README.md.
    inputBinding:
      position: 1
  - id: cnv_file
    type: File
    doc: File listing CNVs (copy number variations). For proper format, see 
      README.md.
    inputBinding:
      position: 2
  - id: burnin_samples
    type:
      - 'null'
      - int
    doc: Number of burnin samples
    default: 1000
    inputBinding:
      position: 103
      prefix: --burnin-samples
  - id: mcmc_samples
    type:
      - 'null'
      - int
    doc: Number of MCMC samples
    default: 2500
    inputBinding:
      position: 103
      prefix: --mcmc-samples
  - id: mh_iterations
    type:
      - 'null'
      - int
    doc: Number of Metropolis-Hastings iterations
    default: 5000
    inputBinding:
      position: 103
      prefix: --mh-iterations
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: Path to output directory
    default: None
    inputBinding:
      position: 103
      prefix: --output-dir
  - id: params_file
    type:
      - 'null'
      - File
    doc: JSON file listing run parameters, generated by the parser
    default: None
    inputBinding:
      position: 103
      prefix: --params
  - id: random_seed
    type:
      - 'null'
      - string
    doc: Random seed for initializing MCMC sampler
    default: None
    inputBinding:
      position: 103
      prefix: --random-seed
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: Path to directory for temporary files
    default: None
    inputBinding:
      position: 103
      prefix: --tmp-dir
  - id: write_backups_every
    type:
      - 'null'
      - int
    doc: Number of iterations to go between writing backups of program state
    default: 100
    inputBinding:
      position: 103
      prefix: --write-backups-every
  - id: write_state_every
    type:
      - 'null'
      - int
    doc: Number of iterations between writing program state to disk. Higher 
      values reduce IO burden at the cost of losing progress made if program is 
      interrupted.
    default: 10
    inputBinding:
      position: 103
      prefix: --write-state-every
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/phylowgs:20181105--py27ha7db03b_3
stdout: phylowgs_evolve.py.out
