cwlVersion: v1.2
class: CommandLineTool
baseCommand: searchSVbyGene
label: neoloop_searchSVbyGene
doc: "Search matched SV regions by gene.\n\nTool homepage: https://github.com/XiaoTaoWang/NeoLoopFinder"
inputs:
  - id: ensembl_release
    type:
      - 'null'
      - int
    doc: Release number of the Ensembl database. The reference genome assembly 
      should be consistent with your Hi-C data used in neoloop-caller.
    default: 93
    inputBinding:
      position: 101
      prefix: --ensembl-release
  - id: gene_name
    type:
      - 'null'
      - string
    doc: Gene name.
    default: None
    inputBinding:
      position: 101
      prefix: --gene-name
  - id: loop_file
    type:
      - 'null'
      - File
    doc: Path to the loop file generated by neoloop-caller.
    default: None
    inputBinding:
      position: 101
      prefix: --loop-file
  - id: species
    type:
      - 'null'
      - string
    doc: Species name of your cell line.
    default: human
    inputBinding:
      position: 101
      prefix: --species
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/neoloop:0.4.3.post2--pyhdfd78af_0
stdout: neoloop_searchSVbyGene.out
