cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - circtools
  - enrich
label: circtools_enrich
doc: "circular RNA RBP enrichment tools\n\nTool homepage: https://github.com/dieterich-lab/circtools"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing: |-
      ${
        var l = [];
        if (inputs.output_directory) { l.push({"class": "Directory", "basename": inputs.output_directory.replace(/\/+$/, ""), "listing": [], "writable": true}); }
        if (inputs.temp) { l.push({"class": "Directory", "basename": inputs.temp.replace(/\/+$/, ""), "listing": [], "writable": true}); }
        return l;
      }
inputs:
  - id: circ_file
    type: File
    doc: 'Path to the CircCoordinates file generated by circtools detect'
    inputBinding:
      position: 101
      prefix: -c
  - id: bed_input
    type: File
    doc: 'BED file containing features to overlap'
    inputBinding:
      position: 101
      prefix: -b
  - id: annotation
    type: File
    doc: 'Genome reference annotation file used to not shuffle into intragenic regions'
    inputBinding:
      position: 101
      prefix: -a
  - id: genome_file
    type: File
    doc: 'Genome file for use with bedtools shuffle. See bedtools man page for details.'
    inputBinding:
      position: 101
      prefix: -g
  - id: output_directory
    type:
      - 'null'
      - string
    doc: 'The output folder for files created by circtools [default: .]'
    inputBinding:
      position: 101
      prefix: -o
  - id: iterations
    type:
      - 'null'
      - int
    doc: 'Number of iterations for CLIP shuffling [default: 1000]'
    inputBinding:
      position: 101
      prefix: -i
  - id: processes
    type:
      - 'null'
      - int
    doc: 'Number of threads to distribute the work to'
    inputBinding:
      position: 101
      prefix: -p
  - id: temp
    type:
      - 'null'
      - string
    doc: 'Temporary directory used by pybedtools'
    inputBinding:
      position: 101
      prefix: -t
  - id: threshold
    type:
      - 'null'
      - int
    doc: 'p-value cutoff (-T)'
    inputBinding:
      position: 101
      prefix: -T
  - id: pval
    type:
      - 'null'
      - float
    doc: 'p-value cutoff'
    inputBinding:
      position: 101
      prefix: -P
  - id: white_list
    type:
      - 'null'
      - File
    doc: 'BED file containing coordinates of exons that should be exclusively taken into account when generating the enrichment.'
    inputBinding:
      position: 101
      prefix: -W
  - id: output_filename
    type:
      - 'null'
      - string
    doc: 'Defines the output file prefix [default: output]'
    inputBinding:
      position: 101
      prefix: -F
  - id: include_features
    type:
      - 'null'
      - type: array
        items: string
        inputBinding:
          prefix: -I
    doc: 'Features which should be used for shuffling. May be specified multiple times. [default: gene]'
    inputBinding:
      position: 101
  - id: keep_temp
    type:
      - 'null'
      - string
    doc: 'Keep temporary files created by circtools/bedtools [default: no]'
    inputBinding:
      position: 101
      prefix: -k
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: Files written with the output file prefix
    outputBinding:
      glob: $((inputs.output_directory || '.') + '/' + (inputs.output_filename || 'output') + '*')
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/circtools:2.0.4--pyhdfd78af_0
stdout: circtools_enrich.out
