cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - circtools
  - reconstruct
label: circtools_reconstruct
doc: "circular RNA reconstruction\n\nTool homepage: https://github.com/dieterich-lab/circtools"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing: |-
      ${
        var l = [];
        if (inputs.out_folder) { l.push({"class": "Directory", "basename": inputs.out_folder.replace(/\/+$/, ""), "listing": [], "writable": true}); }
        if (inputs.tmp_folder) { l.push({"class": "Directory", "basename": inputs.tmp_folder.replace(/\/+$/, ""), "listing": [], "writable": true}); }
        return l;
      }
inputs:
  - id: circle_file
    type:
      - 'null'
      - File
    doc: 'Tab-separated file chr:start_end(tab)read1,read2,read3.'
    inputBinding:
      position: 101
      prefix: -C
  - id: circrna_count
    type:
      - 'null'
      - File
    doc: 'List of circle ids (CircRNACount or CircCoordinates from circtools detect); supply either -C or -D'
    inputBinding:
      position: 101
      prefix: -D
  - id: chimeric_junction
    type:
      - 'null'
      - File
    doc: 'Paired end Chimeric.junction.out file from STAR (for step1)'
    inputBinding:
      position: 101
      prefix: -J
  - id: mate1
    type:
      - 'null'
      - File
    doc: 'mate1.Chimeric.junction.out file (optional if ends were mapped separately)'
    inputBinding:
      position: 101
      prefix: -F
  - id: mate2
    type:
      - 'null'
      - File
    doc: 'mate2.Chimeric.junction.out file (optional if ends were mapped separately)'
    inputBinding:
      position: 101
      prefix: -R
  - id: bamfile
    type: File
    secondaryFiles:
      - pattern: .bai
        required: false
    doc: 'BAM file containing chimeric reads, linear reads may be in it but are not required.'
    inputBinding:
      position: 101
      prefix: -B
  - id: annotation
    type: File
    doc: 'bed formatted feature file including exons.'
    inputBinding:
      position: 101
      prefix: -A
  - id: out_folder
    type:
      - 'null'
      - string
    doc: 'Output folder. There will be a sub folder for the sample containing a BAM file for each circle.'
    inputBinding:
      position: 101
      prefix: -O
  - id: sample
    type: string
    doc: 'sample name to title every thing.'
    inputBinding:
      position: 101
      prefix: -N
  - id: reads
    type:
      - 'null'
      - int
    doc: 'Circle has to have at least <r> reads to be analysed.'
    inputBinding:
      position: 101
      prefix: -r
  - id: mapq
    type:
      - 'null'
      - int
    doc: 'MAPQ cutoff, only reads passing this threshold will be written to circle BAM file.'
    inputBinding:
      position: 101
      prefix: -q
  - id: split_character
    type:
      - 'null'
      - string
    doc: 'feature name separator.'
    inputBinding:
      position: 101
      prefix: -c
  - id: exon_index
    type:
      - 'null'
      - int
    doc: 'Field indicating the exon number after splitting feature name by split_character (for the annotation file).'
    inputBinding:
      position: 101
      prefix: -e
  - id: ref_platform
    type:
      - 'null'
      - string
    doc: 'Specifies the annotation platform which was used (refseq or ensembl)'
    inputBinding:
      position: 101
      prefix: -p
  - id: skip_steps
    type:
      - 'null'
      - string
    doc: 'Comma separated list of steps that should be skipped (e.g. step3,step4,step6)'
    inputBinding:
      position: 101
      prefix: -s
  - id: tmp_folder
    type:
      - 'null'
      - string
    doc: 'Folder to store temporary files generated by pybedtools.'
    inputBinding:
      position: 101
      prefix: -T
  - id: cpus
    type:
      - 'null'
      - int
    doc: 'Number of CPUs used.'
    inputBinding:
      position: 101
      prefix: -P
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: out_folder_dir
    type:
      - 'null'
      - Directory
    doc: 'Output folder'
    outputBinding:
      glob: $(inputs.out_folder)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/circtools:2.0.4--pyhdfd78af_0
stdout: circtools_reconstruct.out
