cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - run-bwamem
label: bwakit_run-bwamem
doc: "Map reads with BWA-MEM through the bwa.kit pipeline (optional adapter trimming,
  duplicate marking, sorting, ALT-aware mapping and HLA typing). run-bwamem prints a
  shell script; this tool runs that script with sh.\n\nTool homepage: https://github.com/lh3/bwa/tree/master/bwakit"
inputs:
  - id: output_prefix
    type: string
    doc: prefix for output files
    inputBinding:
      position: 1
      prefix: -o
  - id: read_group
    type:
      - 'null'
      - string
    doc: read group header line such as '@RG\tID:foo\tSM:bar'
    inputBinding:
      position: 1
      prefix: -R
  - id: read_type
    type:
      - 'null'
      - string
    doc: 'read type: pacbio, ont2d or intractg'
    inputBinding:
      position: 1
      prefix: -x
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads
    inputBinding:
      position: 1
      prefix: -t
  - id: hla_typing
    type:
      - 'null'
      - boolean
    doc: apply HLA typing
    inputBinding:
      position: 1
      prefix: -H
  - id: trim_adapters
    type:
      - 'null'
      - boolean
    doc: trim HiSeq2000/2500 PE resequencing adapters (via trimadap)
    inputBinding:
      position: 1
      prefix: -a
  - id: mark_duplicates
    type:
      - 'null'
      - boolean
    doc: mark duplicate (via samblaster)
    inputBinding:
      position: 1
      prefix: -d
  - id: no_shuffle
    type:
      - 'null'
      - boolean
    doc: for BAM input, don't shuffle
    inputBinding:
      position: 1
      prefix: -S
  - id: sort_output
    type:
      - 'null'
      - boolean
    doc: sort the output alignment (via samtools; requring more RAM)
    inputBinding:
      position: 1
      prefix: -s
  - id: keep_hla_temp
    type:
      - 'null'
      - boolean
    doc: keep temporary files generated by typeHLA
    inputBinding:
      position: 1
      prefix: -k
  - id: mark_secondary
    type:
      - 'null'
      - boolean
    doc: mark shorter split hits as secondary
    inputBinding:
      position: 1
      prefix: -M
  - id: skip_postalt
    type:
      - 'null'
      - boolean
    doc: do not run bwa-postalt.js even when <idxbase>.alt exists (option in the script
      source, not in the usage text)
    inputBinding:
      position: 1
      prefix: -P
  - id: idxbase
    type: File
    doc: The bwa index, given as its .bwt file (for example ref.fa.bwt from bwa index) or
      as the file named like the index prefix (for example ref.fa); the .amb, .ann,
      .bwt, .pac and .sa files must sit beside it, and an optional .alt file enables
      ALT-aware mapping and HLA typing
    secondaryFiles:
      - pattern: "${ var b = self.basename.replace(/\\.bwt$/, ''); var s = ['.amb', '.ann', '.pac', '.sa']; if (b === self.basename) { s.push('.bwt'); } return s.map(function (e) { return b + e; }); }"
        required: true
      - pattern: "${ return self.basename.replace(/\\.bwt$/, '') + '.alt'; }"
        required: false
    inputBinding:
      position: 2
      valueFrom: $(self.path.replace(/\.bwt$/, ''))
  - id: file1
    type: File
    doc: reads (FASTQ/FASTA, optionally gzipped) or a BAM/SAM file
    inputBinding:
      position: 3
  - id: file2
    type:
      - 'null'
      - File
    doc: second reads file for paired-end data
    inputBinding:
      position: 4
arguments:
  - position: 5
    valueFrom: '| sh'
    shellQuote: false
outputs:
  - id: aln_bam
    type: File
    doc: final alignment ({-o}.aln.bam)
    outputBinding:
      glob: $(inputs.output_prefix).aln.bam
  - id: hla_top
    type:
      - 'null'
      - File
    doc: best genotypes for the 6 classical HLA genes ({-o}.hla.top, with -H and HLA
      contigs in the .alt file)
    outputBinding:
      glob: $(inputs.output_prefix).hla.top
  - id: hla_all
    type:
      - 'null'
      - File
    doc: additional HLA genotypes consistent with data ({-o}.hla.all)
    outputBinding:
      glob: $(inputs.output_prefix).hla.all
  - id: hla_files
    type: File[]
    doc: per-gene HLA reads and typing files kept with -k ({-o}.hla.HLA-*)
    outputBinding:
      glob: $(inputs.output_prefix).hla.HLA-*
  - id: logs
    type: File[]
    doc: log files ({-o}.log.*)
    outputBinding:
      glob: $(inputs.output_prefix).log.*
requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwakit:0.7.18.dev1--hdfd78af_0
