cwlVersion: v1.2
class: CommandLineTool
baseCommand: /usr/local/bin/dropletutils-read-10x-counts.R
label: dropletutils-scripts_dropletutils-read-10x-counts.R
doc: "Reads data from 10X Genomics single-cell RNA-seq experiments.\n\nTool homepage:
  https://github.com/ebi-gene-expression-group/dropletutils-scripts"
inputs:
  - id: cell_id_column
    type:
      - 'null'
      - string
    doc: Name of the metadata file column that corresponds to the unique 
      identifier of each cell in the dataset (e.g. barcode). Must correspond to 
      column names in the 10X directory.
    inputBinding:
      position: 101
      prefix: --cell-id-column
  - id: col_names
    type:
      - 'null'
      - boolean
    doc: A logical scalar indicating whether the columns of the output object 
      should be named with the cell barcodes.
    inputBinding:
      position: 101
      prefix: --col-names
  - id: metadata_columns
    type:
      - 'null'
      - type: array
        items: string
    doc: A comma-separated list of metadata file field names that should be 
      added to the SCE object. By default, all columns are kept.
    inputBinding:
      position: 101
      prefix: --metadata-columns
  - id: metadata_files
    type:
      - 'null'
      - type: array
        items: string
    doc: A comma-separated list containing one or more paths to metadata files 
      in .txt format, e.g. with cell type annotations. Note that gene ids must 
      be consistent across the files and correspond to the matrix data.
    inputBinding:
      position: 101
      prefix: --metadata-files
  - id: samples
    type:
      - 'null'
      - type: array
        items: string
    doc: A comma-separated list containing one or more directory names, each 
      corresponding to a 10X sample. Each directory should contain the 
      'matrix.mtx', 'genes.tsv' and 'barcodes.tsv' files generated by 
      CellRanger. Alternatively, strings may contain a path to a HDF5 file in 
      the sparse matrix format generated by 10X. These can be mixed with 
      directory names when type='auto'.
    inputBinding:
      position: 101
      prefix: --samples
outputs:
  - id: output_object_file
    type:
      - 'null'
      - File
    doc: File name in which to store serialized SingleCellExperiment object.
    outputBinding:
      glob: $(inputs.output_object_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/dropletutils-scripts:0.0.5--hdfd78af_1
