cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - portcullis
  - bamfilt
label: portcullis_bamfilt
doc: "Removes alignments associated with bad junctions from BAM file\n\nTool homepage:
  https://github.com/maplesond/portcullis"
inputs:
  - id: junction_file
    type: File
    doc: Junction file
    inputBinding:
      position: 1
  - id: bam_file
    type: File
    doc: BAM file
    inputBinding:
      position: 2
  - id: clip_mode
    type:
      - 'null'
      - string
    doc: 'How to clip reads associated with bad junctions: "HARD" (Hard clip reads
      at junction boundary - suitable for cufflinks); "SOFT" (Soft clip reads at junction
      boundaries); "COMPLETE" (Remove reads associated exclusively with bad junctions,
      MSRs covering both good and bad junctions are kept)'
    default: HARD
    inputBinding:
      position: 103
      prefix: --clip_mode
  - id: save_msrs
    type:
      - 'null'
      - boolean
    doc: Whether or not to output modified MSRs to a separate file. If true will
      output to a file with name specified by output with ".msr.bam" extension
    inputBinding:
      position: 103
      prefix: --save_msrs
  - id: use_csi
    type:
      - 'null'
      - boolean
    doc: Whether to use CSI indexing rather than BAI indexing. CSI has the 
      advantage that it supports very long target sequences (probably not an 
      issue unless you are working on huge genomes). BAI has the advantage that 
      it is more widely supported (useful for viewing in genome browsers).
    inputBinding:
      position: 103
      prefix: --use_csi
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print extra information
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: Output BAM file generated by this program.
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/portcullis:1.2.4--py39hc87ae8a_4
