cwlVersion: v1.2
class: CommandLineTool
baseCommand: portcullis_junc
label: portcullis_junc
doc: "Analyses all potential junctions found in the input BAM file.\n\nTool homepage:
  https://github.com/maplesond/portcullis"
inputs:
  - id: prep_data_dir
    type: Directory
    doc: Directory containing data prepared by 'portcullis prep'
    inputBinding:
      position: 1
  - id: exon_gff
    type:
      - 'null'
      - boolean
    doc: Output exon-based junctions in GFF format.
    inputBinding:
      position: 102
      prefix: --exon_gff
  - id: intron_gff
    type:
      - 'null'
      - boolean
    doc: Output intron-based junctions in GFF format.
    inputBinding:
      position: 102
      prefix: --intron_gff
  - id: orientation
    type:
      - 'null'
      - string
    doc: 'The orientation of the reads that produced the BAM alignments: "F" (Single-end
      forward orientation); "R" (single-end reverse orientation); "FR" (paired-end,
      with reads sequenced towards center of fragment -> <-. This is usual setting
      for most Illumina paired end sequencing); "RF" (paired-end, reads sequenced
      away from center of fragment <- ->); "FF" (paired-end, reads both sequenced
      in forward orientation); "RR" (paired-end, reads both sequenced in reverse orientation);
      "UNKNOWN" (default, portcullis will workaround any calculations requiring orientation
      information)'
    inputBinding:
      position: 102
      prefix: --orientation
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Output prefix for files generated by this program.
    inputBinding:
      position: 102
      prefix: --output
  - id: separate
    type:
      - 'null'
      - boolean
    doc: Separate spliced from unspliced reads. Creates two new BAM files.
    inputBinding:
      position: 102
      prefix: --separate
  - id: source
    type:
      - 'null'
      - string
    doc: The value to enter into the "source" field in GFF files.
    inputBinding:
      position: 102
      prefix: --source
  - id: strandedness
    type:
      - 'null'
      - string
    doc: 'Whether BAM alignments were generated using a type of strand specific RNAseq
      library: "unstranded" (Standard Illumina); "firststrand" (dUTP, NSR, NNSR);
      "secondstrand" (Ligation, Standard SOLiD, flux sim reads); "UNKNOWN" (default,
      portcullis will workaround any calculations requiring strandedness information)'
    inputBinding:
      position: 102
      prefix: --strandedness
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use. Note that increasing the number of 
      threads will also increase memory requirements.
    inputBinding:
      position: 102
      prefix: --threads
  - id: use_csi
    type:
      - 'null'
      - boolean
    doc: Whether to use CSI indexing rather than BAI indexing. CSI has the 
      advantage that it supports very long target sequences (probably not an 
      issue unless you are working on huge genomes). BAI has the advantage that 
      it is more widely supported (useful for viewing in genome browsers).
    inputBinding:
      position: 102
      prefix: --use_csi
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print extra information
    inputBinding:
      position: 102
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/portcullis:1.2.4--py39hc87ae8a_4
stdout: portcullis_junc.out
