cwlVersion: v1.2
class: CommandLineTool
baseCommand: popscle_plp-make-dge-matrix
label: popscle_plp-make-dge-matrix
doc: "Make Digital Expression Matrix from Digital Pileups\n\nTool homepage: https://github.com/statgen/popscle"
inputs:
  - id: common_gene_types
    type:
      - 'null'
      - boolean
    doc: Load only common gene types, searching for specific gene types - 
      protein_coding, lincRNA, antisense, IG_ and TR_ genes
    default: false
    inputBinding:
      position: 101
      prefix: --common-gene-types
  - id: create_gene_transcript
    type:
      - 'null'
      - boolean
    doc: Create genes and transcripts if not exist in GTF
    default: false
    inputBinding:
      position: 101
      prefix: --create-gene-transcript
  - id: gene_type
    type:
      - 'null'
      - string
    doc: Gene types to include to produce DGE matrix (e.g. protein-coding)
    inputBinding:
      position: 101
      prefix: --gene-type
  - id: group_list
    type:
      - 'null'
      - string
    doc: List of tag readgroup/cell barcode to consider in this run. All other 
      barcodes will be ignored. This is useful for parallelized run
    inputBinding:
      position: 101
      prefix: --group-list
  - id: gtf_add_chr
    type:
      - 'null'
      - boolean
    doc: Add 'chr' prefix from input GTF file
    default: false
    inputBinding:
      position: 101
      prefix: --gtf-add-chr
  - id: gtf_file
    type:
      - 'null'
      - File
    doc: GTF-formatted file for gene/transcript annotation
    inputBinding:
      position: 101
      prefix: --gtf
  - id: gtf_remove_chr
    type:
      - 'null'
      - boolean
    doc: Remove 'chr' prefix from input GTF file
    default: false
    inputBinding:
      position: 101
      prefix: --gtf-remove-chr
  - id: min_snp
    type:
      - 'null'
      - int
    doc: Minimum number of SNPs with coverage for a droplet/cell to be 
      considered
    default: 0
    inputBinding:
      position: 101
      prefix: --min-snp
  - id: min_total
    type:
      - 'null'
      - int
    doc: Minimum number of total reads for a droplet/cell to be considered
    default: 0
    inputBinding:
      position: 101
      prefix: --min-total
  - id: min_uniq
    type:
      - 'null'
      - int
    doc: Minimum number of unique reads (determined by UMI/SNP pair) for a 
      droplet/cell to be considered
    default: 0
    inputBinding:
      position: 101
      prefix: --min-uniq
  - id: plp_prefix
    type:
      - 'null'
      - string
    doc: Prefix of input files generated by dsc-pileup
    inputBinding:
      position: 101
      prefix: --plp
  - id: uniq_bin
    type:
      - 'null'
      - int
    doc: Bin size to uniquely count a UMI into a single gene
    default: 1000000000
    inputBinding:
      position: 101
      prefix: --uniq-bin
  - id: verbose
    type:
      - 'null'
      - int
    doc: 'Turn on verbose mode with specific verbosity threshold. 0: fully verbose,
      100 : no verbose messages'
    default: 100
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_prefix
    type:
      - 'null'
      - File
    doc: Output file prefix
    outputBinding:
      glob: $(inputs.output_prefix)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/popscle:0.1--ha0d7e29_1
