cwlVersion: v1.2
class: CommandLineTool
baseCommand: popscle_freemuxlet-old
label: popscle_freemuxlet-old
doc: "Genotype-free deconvolution of sc-RNAseq (deprecated)\n\nTool homepage: https://github.com/statgen/popscle"
inputs:
  - id: aux_files
    type:
      - 'null'
      - boolean
    doc: Turn on writing auxilary output files
    inputBinding:
      position: 101
      prefix: --aux-files
  - id: bf_thres
    type:
      - 'null'
      - float
    doc: Bayes Factor Threshold used in the initial clustering
    inputBinding:
      position: 101
      prefix: --bf-thres
  - id: cap_bq
    type:
      - 'null'
      - int
    doc: Maximum base quality (higher BQ will be capped)
    inputBinding:
      position: 101
      prefix: --cap-BQ
  - id: doublet_prior
    type:
      - 'null'
      - float
    doc: Prior of doublet
    inputBinding:
      position: 101
      prefix: --doublet-prior
  - id: frac_init_clust
    type:
      - 'null'
      - float
    doc: Fraction of droplets to be clustered in the very first round of initial
      clustering procedure
    inputBinding:
      position: 101
      prefix: --frac-init-clust
  - id: geno_error
    type:
      - 'null'
      - float
    doc: Genotype error parameter per cluster
    inputBinding:
      position: 101
      prefix: --geno-error
  - id: group_list
    type:
      - 'null'
      - string
    doc: List of tag readgroup/cell barcode to consider in this run. All other 
      barcodes will be ignored. This is useful for parallelized run
    inputBinding:
      position: 101
      prefix: --group-list
  - id: init_cluster
    type:
      - 'null'
      - string
    doc: Input file containing the initial cluster information
    inputBinding:
      position: 101
      prefix: --init-cluster
  - id: iter_init
    type:
      - 'null'
      - int
    doc: Iteration for initial cluster assignment (set to zero to skip the 
      iterations)
    inputBinding:
      position: 101
      prefix: --iter-init
  - id: keep_init_missing
    type:
      - 'null'
      - boolean
    doc: Keep missing cluster assignment as missing in the initial iteration
    inputBinding:
      position: 101
      prefix: --keep-init-missing
  - id: min_bq
    type:
      - 'null'
      - int
    doc: Minimum base quality to consider (lower BQ will be skipped)
    inputBinding:
      position: 101
      prefix: --min-BQ
  - id: min_snp
    type:
      - 'null'
      - int
    doc: Minimum number of SNPs with coverage for a droplet/cell to be 
      considered
    inputBinding:
      position: 101
      prefix: --min-snp
  - id: min_total
    type:
      - 'null'
      - int
    doc: Minimum number of total reads for a droplet/cell to be considered
    inputBinding:
      position: 101
      prefix: --min-total
  - id: min_uniq
    type:
      - 'null'
      - int
    doc: Minimum number of unique reads (determined by UMI/SNP pair) for a 
      droplet/cell to be considered
    inputBinding:
      position: 101
      prefix: --min-uniq
  - id: nsample
    type:
      - 'null'
      - int
    doc: Number of samples multiplexed together
    inputBinding:
      position: 101
      prefix: --nsample
  - id: plp
    type:
      - 'null'
      - string
    doc: Prefix of input files generated by dsc-pileup
    inputBinding:
      position: 101
      prefix: --plp
  - id: verbose
    type:
      - 'null'
      - int
    doc: 'Turn on verbose mode with specific verbosity threshold. 0: fully verbose,
      100 : no verbose messages'
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: out
    type:
      - 'null'
      - File
    doc: Output file prefix
    outputBinding:
      glob: $(inputs.out)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/popscle:0.1--ha0d7e29_1
