cwlVersion: v1.2
class: CommandLineTool
baseCommand: fastspar_pvalues
label: fastspar_pvalues
doc: "Calculate p-values for FastSpar correlations from bootstrap correlation tables\n\nTool
  homepage: https://github.com/scwatts/fastspar"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing: $(inputs.bootstrap_correlations)
inputs:
  - id: otu_table
    type: File
    doc: OTU input table used to generate the correlations
    inputBinding:
      position: 1
      prefix: --otu_table
  - id: correlation
    type: File
    doc: Correlation table generated by FastSpar
    inputBinding:
      position: 2
      prefix: --correlation
  - id: bootstrap_correlations
    type: 'File[]'
    doc: Correlation tables of the bootstrapped count tables, named <prefix>_<n>.tsv with
      n from 0 to permutations-1 (staged in the working directory)
  - id: prefix
    type: string
    doc: Prefix of the bootstrap correlation files
    inputBinding:
      position: 3
      prefix: --prefix
  - id: permutations
    type: int
    doc: Number of permutations (bootstraps)
    inputBinding:
      position: 4
      prefix: --permutations
  - id: outfile
    type: string
    doc: Output p-value matrix file name
    inputBinding:
      position: 5
      prefix: --outfile
  - id: pseudo
    type: ['null', boolean]
    doc: Calculate pseudo p-values rather than exact p-values
    inputBinding:
      position: 6
      prefix: --pseudo
  - id: threads
    type: ['null', int]
    doc: Number of threads (default 1)
    inputBinding:
      position: 7
      prefix: --threads
outputs:
  - id: pvalues
    type: File
    doc: P-value matrix
    outputBinding:
      glob: $(inputs.outfile)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fastspar:1.0.0--h1b620e3_6
