cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - mgikit
  - reformat
label: mgikit_reformat
doc: "Reformat MGI fastq headers to Illumina's and prepare quality report.\n\nTool
  homepage: https://sagc-bioinformatics.github.io/mgikit/"
inputs:
  - id: barcode
    type:
      - 'null'
      - string
    doc: The barcode of the specific sample to calulate the mismatches for the 
      reports. If not provided, no mismtahces will be calculated.
    inputBinding:
      position: 101
      prefix: --barcode
  - id: compression_buffer_size
    type:
      - 'null'
      - int
    doc: The size of the buffer for data compression for each sample.
    default: 131072
    inputBinding:
      position: 101
      prefix: --compression-buffer-size
  - id: compression_level
    type:
      - 'null'
      - int
    doc: The level of compression (between 0 and 12). 0 is fast but no 
      compression, 12 is slow but high compression.
    default: 1
    inputBinding:
      position: 101
      prefix: --compression-level
  - id: disable_illumina
    type:
      - 'null'
      - boolean
    doc: Disable illumina file naming and read header format. Output file names 
      and reads' header using MGI format.
    inputBinding:
      position: 101
      prefix: --disable-illumina
  - id: force
    type:
      - 'null'
      - boolean
    doc: Force running the tool and overwrite existed output/report files.
    inputBinding:
      position: 101
      prefix: --force
  - id: info_file
    type:
      - 'null'
      - File
    doc: The path to the info file that contains the run information (similar to
      `BioInfo.csv` generated by MGI machines under the lane directory).
    inputBinding:
      position: 101
      prefix: --info-file
  - id: instrument
    type:
      - 'null'
      - string
    doc: The Id of the instrument required for Illumina format.
    inputBinding:
      position: 101
      prefix: --instrument
  - id: lane
    type:
      - 'null'
      - string
    doc: The lane number, required for Illumina format.
    inputBinding:
      position: 101
      prefix: --lane
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'log level for output messages. Expected values: [error, warn, info, debug,
      trace]. Default is info.'
    default: info
    inputBinding:
      position: 101
      prefix: --log-level
  - id: memory
    type:
      - 'null'
      - int
    doc: The requested maximum memory to be used (in giga byte). Default is 0 
      then the tool will use the available memory on the machine.
    default: 0
    inputBinding:
      position: 101
      prefix: --memory
  - id: read1
    type:
      - 'null'
      - File
    doc: The path to read1.fastq.gz See the example for the required format.
    inputBinding:
      position: 101
      prefix: --read1
  - id: read2
    type:
      - 'null'
      - File
    doc: The path to read2.fastq.gz See the example for the required format.
    inputBinding:
      position: 101
      prefix: --read2
  - id: report_level
    type:
      - 'null'
      - int
    doc: 'The level of reporting. 0 no reports will be generated!, 1 data quality
      and demultipexing reports. 2: all reports (reports on data quality, demultipexing,
      undetermined and ambigouse barcodes).'
    default: 2
    inputBinding:
      position: 101
      prefix: --report-level
  - id: run
    type:
      - 'null'
      - string
    doc: The run number, required for Illumina format.
    inputBinding:
      position: 101
      prefix: --run
  - id: sample_index
    type:
      - 'null'
      - int
    doc: The index of the sample in the sample sheet, needed for file naming.
    default: 1
    inputBinding:
      position: 101
      prefix: --sample-index
  - id: sample_label
    type:
      - 'null'
      - string
    doc: Sample label to be used for file naming. if not provided, it will be 
      taken from the name of the input file
    inputBinding:
      position: 101
      prefix: --sample-label
  - id: umi_length
    type:
      - 'null'
      - int
    doc: The length of UMI expected at the end of the read (r1 for single-end, 
      or r2 for paired-end).
    default: 0
    inputBinding:
      position: 101
      prefix: --umi-length
  - id: validate
    type:
      - 'null'
      - boolean
    doc: Validate the content of the fastq files.
    inputBinding:
      position: 101
      prefix: --validate
  - id: writing_buffer_size
    type:
      - 'null'
      - int
    doc: The size of the buffer for each sample to be filled with data then 
      written once to the disk.
    default: 67108864
    inputBinding:
      position: 101
      prefix: --writing-buffer-size
outputs:
  - id: output
    type:
      - 'null'
      - Directory
    doc: Path to the output folder. If not provided, the output will be written 
      at mgiKit_ followed by current data and time.
    outputBinding:
      glob: $(inputs.output)
  - id: reports
    type:
      - 'null'
      - Directory
    doc: Prefix of report file. If not provided, the output will be written at 
      output_ followed by current data and time.
    outputBinding:
      glob: $(inputs.reports)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mgikit:2.1.1--h3ab6199_0
