cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - mgikit
  - demultiplex
label: mgikit_demultiplex
doc: "Demultipex fastq files.\n\nTool homepage: https://sagc-bioinformatics.github.io/mgikit/"
inputs:
  - id: all_index_error
    type:
      - 'null'
      - boolean
    doc: By default, the allowed mismatches `-m or --mismatches` are considered 
      to be per index. This flag will make it for the total mismatches across 
      all indices.
    inputBinding:
      position: 101
      prefix: --all-index-error
  - id: ambiguous_label
    type:
      - 'null'
      - string
    doc: The name of the file that contains ambiguous reads.
    default: Ambiguous
    inputBinding:
      position: 101
      prefix: --ambiguous-label
  - id: comprehensive_scan
    type:
      - 'null'
      - boolean
    doc: Check all possible matches, otherwise, search will stop after first 
      match. Only needed for mixed library.
    inputBinding:
      position: 101
      prefix: --comprehensive-scan
  - id: compression_buffer_size
    type:
      - 'null'
      - int
    doc: The size of the buffer for data compression for each sample.
    default: 131072
    inputBinding:
      position: 101
      prefix: --compression-buffer-size
  - id: compression_level
    type:
      - 'null'
      - int
    doc: The level of compression (between 0 and 12). 0 is fast but no 
      compression, 12 is slow but high compression.
    default: 1
    inputBinding:
      position: 101
      prefix: --compression-level
  - id: disable_illumina
    type:
      - 'null'
      - boolean
    doc: Disable illumina file naming and read header format. Output file names 
      and reads' header using MGI format.
    inputBinding:
      position: 101
      prefix: --disable-illumina
  - id: force
    type:
      - 'null'
      - boolean
    doc: Force running the tool and overwrite existed output/report files.
    inputBinding:
      position: 101
      prefix: --force
  - id: i5_rc
    type:
      - 'null'
      - boolean
    doc: Convert i5 to reveres complement. Only valid when using general 
      template.
    inputBinding:
      position: 101
      prefix: --i5-rc
  - id: i7_rc
    type:
      - 'null'
      - boolean
    doc: Convert i7 to reveres complement. Only valid when using general 
      template.
    inputBinding:
      position: 101
      prefix: --i7-rc
  - id: ignore_undetermined
    type:
      - 'null'
      - boolean
    doc: Do not stop if there are many undetermined reads in the dataset.
    inputBinding:
      position: 101
      prefix: --ignore-undetermined
  - id: in_r1_file_suf
    type:
      - 'null'
      - string
    doc: The suffix to read1 file name. When using the --input parameter, the 
      tool looks for the file that ends with this suffix and use it as read1 
      file.
    default: _read_1.fq.gz
    inputBinding:
      position: 101
      prefix: --in-r1-file-suf
  - id: in_r2_file_suf
    type:
      - 'null'
      - string
    doc: The suffix to read2 file name. When using the --input parameter, the 
      tool looks for the file that ends with this suffix and use it as read2 
      file.
    default: _read_2.fq.gz
    inputBinding:
      position: 101
      prefix: --in-r2-file-suf
  - id: info_file
    type:
      - 'null'
      - File
    doc: The path to the info file that contains the run information (similar to
      `BioInfo.csv` generated by MGI machines under the lane directory).
    inputBinding:
      position: 101
      prefix: --info-file
  - id: input_folder
    type:
      - 'null'
      - Directory
    doc: The path to read2.fastq.gz See the example for the required format.
    inputBinding:
      position: 101
      prefix: --input
  - id: instrument
    type:
      - 'null'
      - string
    doc: The Id of the instrument required for Illumina format.
    inputBinding:
      position: 101
      prefix: --instrument
  - id: keep_barcode
    type:
      - 'null'
      - boolean
    doc: Keep the barcode at the tail of read sequence.
    inputBinding:
      position: 101
      prefix: --keep-barcode
  - id: lane
    type:
      - 'null'
      - string
    doc: The lane number, required for Illumina format.
    inputBinding:
      position: 101
      prefix: --lane
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'log level for output messages. Expected values: [error, warn, info, debug,
      trace]. Default is info.'
    default: info
    inputBinding:
      position: 101
      prefix: --log-level
  - id: memory
    type:
      - 'null'
      - int
    doc: The requested maximum memory to be used (in giga byte). Default is 0 
      then the tool will use the available memory on the machine.
    default: 0
    inputBinding:
      position: 101
      prefix: --memory
  - id: mgi_full_header
    type:
      - 'null'
      - boolean
    doc: Add sample barcode and UMI to MGI header when MGI format is enabled.
    inputBinding:
      position: 101
      prefix: --mgi-full-header
  - id: mismatches
    type:
      - 'null'
      - int
    doc: The number of allowed mismatches when detecting indexes from reads.
    default: 1
    inputBinding:
      position: 101
      prefix: --mismatches
  - id: not_mgi
    type:
      - 'null'
      - boolean
    doc: This flag needs to be enabled if the input fastq files don't have MGI 
      format.
    inputBinding:
      position: 101
      prefix: --not-mgi
  - id: read1
    type:
      - 'null'
      - File
    doc: The path to read1.fastq.gz See the example for the required format.
    inputBinding:
      position: 101
      prefix: --read1
  - id: read2
    type:
      - 'null'
      - File
    doc: The path to read2.fastq.gz See the example for the required format.
    inputBinding:
      position: 101
      prefix: --read2
  - id: reader_threads
    type:
      - 'null'
      - int
    doc: The requested threads to be used for input reading. Default is 0 which 
      means auto configuration.
    default: 0
    inputBinding:
      position: 101
      prefix: --reader-threads
  - id: report_level
    type:
      - 'null'
      - int
    doc: 'The level of reporting. 0 no reports will be generated!, 1 data quality
      and demultipexing reports. 2: all reports.'
    default: 2
    inputBinding:
      position: 101
      prefix: --report-level
  - id: report_limit
    type:
      - 'null'
      - int
    doc: The number of barcodes to be reported in the list of undetermined and 
      ambiguous barcodes for short/multiqc report.
    default: 20
    inputBinding:
      position: 101
      prefix: --report-limit
  - id: run
    type:
      - 'null'
      - string
    doc: The run number, required for Illumina format.
    inputBinding:
      position: 101
      prefix: --run
  - id: sample_sheet
    type: File
    doc: The path to the sample/index map.
    inputBinding:
      position: 101
      prefix: --sample-sheet
  - id: template
    type:
      - 'null'
      - string
    doc: The general template of the indexes to be used for demultiplexing.
    inputBinding:
      position: 101
      prefix: --template
  - id: threads
    type:
      - 'null'
      - int
    doc: The requested threads to be used. Default is 0 which means to use all 
      available CPUs.
    default: 0
    inputBinding:
      position: 101
      prefix: --threads
  - id: undetermined_label
    type:
      - 'null'
      - string
    doc: The name of the file that contains undetermined reads.
    default: Undetermined
    inputBinding:
      position: 101
      prefix: --undetermined-label
  - id: validate
    type:
      - 'null'
      - boolean
    doc: Validate the content of the fastq files.
    inputBinding:
      position: 101
      prefix: --validate
  - id: writer_threads
    type:
      - 'null'
      - int
    doc: The requested threads to be used for processing and writing outputs. 
      Default is 0 which means auto configuration.
    default: 0
    inputBinding:
      position: 101
      prefix: --writer-threads
  - id: writing_buffer_size
    type:
      - 'null'
      - int
    doc: The size of the buffer for each sample to be filled with data then 
      written once to the disk.
    default: 67108864
    inputBinding:
      position: 101
      prefix: --writing-buffer-size
outputs:
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: Path to the output folder. If not provided, the output will be written 
      at mgiKit_ followed by current data and time.
    outputBinding:
      glob: $(inputs.output_dir)
  - id: reports_dir
    type:
      - 'null'
      - Directory
    doc: Prefix of report file. If not provided, the output will be written at 
      output_ followed by current data and time.
    outputBinding:
      glob: $(inputs.reports_dir)
  - id: log_path
    type:
      - 'null'
      - File
    doc: Path to the output log, instead of writing to the stdout.
    outputBinding:
      glob: $(inputs.log_path)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mgikit:2.1.1--h3ab6199_0
