cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - mgikit
  - template
label: mgikit_template
doc: "Detect barcode template.\n\nTool homepage: https://sagc-bioinformatics.github.io/mgikit/"
inputs:
  - id: barcode_length
    type:
      - 'null'
      - int
    doc: The barcode length to detect the template. When set to 0, the barcode 
      length will be length's difference between R2 and R1.
    default: 0
    inputBinding:
      position: 101
      prefix: --barcode-length
  - id: in_r1_file_suf
    type:
      - 'null'
      - string
    doc: The suffix to read1 file name. When using the --input parameter, the 
      tool looks for the file that ends with this suffix and use it as read1 
      file.
    default: _read_1.fq.gz
    inputBinding:
      position: 101
      prefix: --in-r1-file-suf
  - id: in_r2_file_suf
    type:
      - 'null'
      - string
    doc: The suffix to read2 file name. When using the --input parameter, the 
      tool looks for the file that ends with this suffix and use it as read2 
      file.
    default: _read_2.fq.gz
    inputBinding:
      position: 101
      prefix: --in-r2-file-suf
  - id: info_file
    type:
      - 'null'
      - File
    doc: The path to the info file that contains the run information (similar to
      `BioInfo.csv` generated by MGI machines under the lane directory).
    default: ''
    inputBinding:
      position: 101
      prefix: --info-file
  - id: input
    type:
      - 'null'
      - Directory
    doc: The path to read2.fastq.gz See the example for the required format.
    default: ''
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'log level for output messages. Expected values: [error, warn, info, debug,
      trace]. Default is info.'
    default: info
    inputBinding:
      position: 101
      prefix: --log-level
  - id: max_umi_len
    type:
      - 'null'
      - int
    doc: The maximum expected UMI length.
    default: 10
    inputBinding:
      position: 101
      prefix: --max-umi-len
  - id: no_umi
    type:
      - 'null'
      - boolean
    doc: Don't extract UMI from the read barcode.
    inputBinding:
      position: 101
      prefix: --no-umi
  - id: popular_template
    type:
      - 'null'
      - boolean
    doc: Use the most frequent template for all samples even if some of them 
      have more matches with other template.
    inputBinding:
      position: 101
      prefix: --popular-template
  - id: read1
    type:
      - 'null'
      - File
    doc: The path to read1.fastq.gz See the example for the required format.
    default: ''
    inputBinding:
      position: 101
      prefix: --read1
  - id: read2
    type:
      - 'null'
      - File
    doc: The path to read2.fastq.gz See the example for the required format.
    default: ''
    inputBinding:
      position: 101
      prefix: --read2
  - id: sample_sheet
    type: File
    doc: The path to the sample/index map.
    inputBinding:
      position: 101
      prefix: --sample-sheet
  - id: testing_reads
    type:
      - 'null'
      - int
    doc: The number of reads used to detect the barcode.
    default: 5000
    inputBinding:
      position: 101
      prefix: --testing-reads
outputs:
  - id: output
    type:
      - 'null'
      - Directory
    doc: Path to the output file prefix. If not provided, the output will be 
      written at mgiKit_ followed by current data and time.
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mgikit:2.1.1--h3ab6199_0
