cwlVersion: v1.2
class: CommandLineTool
baseCommand: hicup
label: hicup
doc: "The HiCUP pipeline receives FASTQ files and generates Hi-C paired read (di-tag)
  files. The hicup script regulates the pipeline, passing output from one script to
  the next.\n\nTool homepage: http://www.bioinformatics.babraham.ac.uk/projects/hicup/"
inputs:
  - id: config_file
    type:
      - 'null'
      - type: array
        items: File
    doc: Configuration file
    inputBinding:
      position: 1
  - id: files
    type:
      - 'null'
      - type: array
        items: File
    doc: FASTQ files
    inputBinding:
      position: 2
  - id: bowtie2_path
    type:
      - 'null'
      - string
    doc: Specify the path to Bowtie 2
    inputBinding:
      position: 103
      prefix: --bowtie2
  - id: bowtie_path
    type:
      - 'null'
      - string
    doc: Specify the path to Bowtie
    inputBinding:
      position: 103
      prefix: --bowtie
  - id: config
    type:
      - 'null'
      - File
    doc: Specify the configuration file
    inputBinding:
      position: 103
      prefix: --config
  - id: digest_file
    type:
      - 'null'
      - File
    doc: Specify the digest file listing restriction fragment co-ordinates
    inputBinding:
      position: 103
      prefix: --digest
  - id: example
    type:
      - 'null'
      - boolean
    doc: Produce an example configuration file
    inputBinding:
      position: 103
      prefix: --example
  - id: fastq_format
    type:
      - 'null'
      - string
    doc: Specify FASTQ format
    inputBinding:
      position: 103
      prefix: --format
  - id: keep_intermediate
    type:
      - 'null'
      - boolean
    doc: Keep intermediate pipeline files
    inputBinding:
      position: 103
      prefix: --keep
  - id: longest_insert_size
    type:
      - 'null'
      - int
    doc: Maximum allowable insert size (bps)
    inputBinding:
      position: 103
      prefix: --longest
  - id: nofill
    type:
      - 'null'
      - boolean
    doc: Hi-C protocol did NOT include a fill-in of sticky ends prior to 
      ligation step and therefore FASTQ reads shall be truncated at the Hi-C 
      restriction enzyme cut site (if present) sequence is encountered
    inputBinding:
      position: 103
      prefix: --nofill
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Suppress progress reports (except warnings)
    inputBinding:
      position: 103
      prefix: --quiet
  - id: reference_index
    type:
      - 'null'
      - Directory
    doc: Path to the relevant reference genome Bowtie/Bowtie2 indices
    inputBinding:
      position: 103
      prefix: --index
  - id: shortest_insert_size
    type:
      - 'null'
      - int
    doc: Minimum allowable insert size (bps)
    inputBinding:
      position: 103
      prefix: --shortest
  - id: temp_directory
    type:
      - 'null'
      - Directory
    doc: Write intermediate files (i.e. all except summary files and files 
      generated by HiCUP Deduplicator) to a specified directory
    inputBinding:
      position: 103
      prefix: --temp
  - id: threads
    type:
      - 'null'
      - int
    doc: Specify the number of threads, allowing simultaneous processing of 
      multiple files
    inputBinding:
      position: 103
      prefix: --threads
  - id: zip_output
    type:
      - 'null'
      - boolean
    doc: Compress output
    inputBinding:
      position: 103
      prefix: --zip
outputs:
  - id: output_directory
    type:
      - 'null'
      - Directory
    doc: Directory to write output files
    outputBinding:
      glob: $(inputs.output_directory)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hicup:0.9.2--hdfd78af_1
