cwlVersion: v1.2
class: CommandLineTool
baseCommand: gottcha.pl
label: gottcha_gottcha.pl
doc: "Genomic Origin Through Taxonomic CHAllenge (GOTTCHA) is an annotation-independent
  and signature-based metagenomic taxonomic profiling tool that has significantly
  smaller FDR than other profiling tools. This Perl script is a wrapper to run the
  GOTTCHA profiling tool with pre-computed signature databases. The procedure includes
  3 major steps: split-trimming the input data, mapping reads to a GOTTCHA database
  using BWA, profiling/filtering the result.\n\nTool homepage: https://github.com/poeli/GOTTCHA"
inputs:
  - id: ascii
    type:
      - 'null'
      - int
    doc: ASCII encoding of quality score (33 or 64)
    default: 33
    inputBinding:
      position: 101
      prefix: --ascii
  - id: bwa_opt
    type:
      - 'null'
      - string
    doc: BWA-MEM in this script is used to map input reads to GOTTCHA database. 
      If you want to run it with your own parameters, use this option to 
      specify.
    default: '"-k 30 -T 0 -B 100 -O 100 -E 100"'
    inputBinding:
      position: 101
      prefix: --bwaOpt
  - id: c_cov
    type:
      - 'null'
      - float
    doc: Critical coverage below which --minMLHL will cause an organism to fail
    default: 0.006
    inputBinding:
      position: 101
      prefix: --cCov
  - id: database
    type: string
    doc: The path of signature database. The database can be in FASTA format or 
      BWA index (5 files).
    inputBinding:
      position: 101
      prefix: --database
  - id: db_level
    type:
      - 'null'
      - string
    doc: Specify the taxonomic level of the input database (e.g. family, 
      species, genus, strain, etc.). The value will be auto-detected if the 
      input database ended with levels (e.g. GOTTCHA_db.species).
    default: none
    inputBinding:
      position: 101
      prefix: --dbLevel
  - id: dump_sam
    type:
      - 'null'
      - boolean
    doc: Dump the mapping result in SAM format.
    inputBinding:
      position: 101
      prefix: --dumpSam
  - id: fix_l
    type:
      - 'null'
      - int
    doc: Fixed length to which each trimmed read will be cut down to
    default: 30
    inputBinding:
      position: 101
      prefix: --fixL
  - id: input
    type: string
    doc: Input one or multiple FASTQ file(s). Use comma (,) to separate multiple
      input files.
    inputBinding:
      position: 101
      prefix: --input
  - id: min_cov
    type:
      - 'null'
      - float
    doc: Minimum linear coverage to be considered valid in abundance calculation
    default: 0.005
    inputBinding:
      position: 101
      prefix: --minCov
  - id: min_hits
    type:
      - 'null'
      - int
    doc: Minimum number of hits to be considered valid in abundance calculation
    default: 10
    inputBinding:
      position: 101
      prefix: --minHits
  - id: min_len
    type:
      - 'null'
      - int
    doc: Minimum unique length to be considered valid in abundance calculation
    default: 100
    inputBinding:
      position: 101
      prefix: --minLen
  - id: min_mlhl
    type:
      - 'null'
      - int
    doc: Minimum Mean-Linear-Hit-Length to be considered valid in abundance 
      calculation
    default: 5
    inputBinding:
      position: 101
      prefix: --minMLHL
  - id: min_q
    type:
      - 'null'
      - int
    doc: Minimum quality for a read to be considered valid (0-41)
    default: 20
    inputBinding:
      position: 101
      prefix: --minQ
  - id: mode
    type:
      - 'null'
      - string
    doc: 'You can specify one of the output mode: "summary" : this mode will report
      a summary of profiling result to *.gottcha.tsv file. "full" : other than a summary,
      this mode will report unfiltered result to *.gottcha_full.tsv with more detail.
      "all" : other than two tables, this mode will keep all output files that were
      generated by each profiling step.'
    default: summary
    inputBinding:
      position: 101
      prefix: --mode
  - id: no_plasmid_hit
    type:
      - 'null'
      - boolean
    doc: Ignore alignments that hit to plasmids
    inputBinding:
      position: 101
      prefix: --noPlasmidHit
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: Output directory
    default: ./
    inputBinding:
      position: 101
      prefix: --outdir
  - id: prefix
    type:
      - 'null'
      - string
    doc: Filename prefix of the output.
    default: <INPUT_FILENAME_PREFIX>
    inputBinding:
      position: 101
      prefix: --prefix
  - id: rel_abu
    type:
      - 'null'
      - string
    doc: 'The field will be used to calculate relative abundance. You can specify
      one of the following fields: "LINEAR_LENGTH", "TOTAL_BP_MAPPED", "HIT_COUNT",
      "LINEAR_DOC".'
    default: LINEAR_DOC
    inputBinding:
      position: 101
      prefix: --relAbu
  - id: st_dir
    type:
      - 'null'
      - Directory
    doc: Specify a directory contains pre-splitrimmed input files. E.g. input 
      file is "test.fastq", the script will looking for "test_splitrim.fastq" 
      and "test_splitrim.stats.txt" in the specified directory.
    inputBinding:
      position: 101
      prefix: --stDir
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads
    default: auto-detect
    inputBinding:
      position: 101
      prefix: --threads
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gottcha:1.0--pl526_2
stdout: gottcha_gottcha.pl.out
