cwlVersion: v1.2
class: CommandLineTool
baseCommand: get_homologues_plot_pancore_matrix.pl
label: get_homologues_plot_pancore_matrix.pl
doc: "Plot pancore matrix\n\nTool homepage: https://github.com/eead-csic-compbio/get_homologues"
inputs:
  - id: animation_dir
    type:
      - 'null'
      - Directory
    doc: 'save snapshots for animations in dir (optional, example: -a animation)'
    inputBinding:
      position: 101
      prefix: -a
  - id: fit_type
    type:
      - 'null'
      - string
    doc: 'type of fit [pan|core_Tettelin|core_Willenbrock|core_both] (default: core_Tettelin,
      PubMed:16172379,18088402)'
    default: core_Tettelin
    inputBinding:
      position: 101
      prefix: -f
  - id: font_scale
    type:
      - 'null'
      - float
    doc: font scale for fitted formulas (optional, default=0.8)
    default: 0.8
    inputBinding:
      position: 101
      prefix: -F
  - id: input_file
    type: File
    doc: input .tab data file (required, generated by get_homologues.pl)
    inputBinding:
      position: 101
      prefix: -i
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/get_homologues:3.8.1--hdfd78af_0
stdout: get_homologues_plot_pancore_matrix.pl.out
