cwlVersion: v1.2
class: CommandLineTool
baseCommand: plot_pancore_matrix.pl
label: get_homologues_plot_pancore_matrix.pl
doc: "Plot pancore matrix\n\nTool homepage: https://github.com/eead-csic-compbio/get_homologues"
inputs:
  - id: animation_dir
    type:
      - 'null'
      - string
    doc: 'save snapshots for animations in dir (optional, example: -a animation)'
    inputBinding:
      position: 101
      prefix: -a
  - id: fit_type
    type:
      - 'null'
      - string
    doc: 'type of fit [pan|core_Tettelin|core_Willenbrock|core_both] (default: core_Tettelin,
      PubMed:16172379,18088402)'
    inputBinding:
      position: 101
      prefix: -f
  - id: font_scale
    type:
      - 'null'
      - float
    doc: font scale for fitted formulas (optional, default=0.8)
    inputBinding:
      position: 101
      prefix: -F
  - id: input_file
    type: File
    doc: input .tab data file (required, generated by get_homologues.pl)
    inputBinding:
      position: 101
      prefix: -i
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.input_file)
        writable: true
outputs:
  - id: animation_snapshots
    type:
      - 'null'
      - Directory
    doc: Directory with the snapshots for animations, when animation_dir is given.
    outputBinding:
      glob: $(inputs.animation_dir)
  - id: plot_files
    type:
      type: array
      items: File
    doc: Plots (png, pdf, svg) and fit results written next to the input file.
    outputBinding:
      glob: $(inputs.input_file.basename)_*
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/get_homologues:3.8.1--hdfd78af_0
stdout: get_homologues_plot_pancore_matrix.pl.out
