cwlVersion: v1.2
class: CommandLineTool
baseCommand: get_homologues_compare_clusters.pl
label: get_homologues_compare_clusters.pl
doc: "Compares cluster directories generated by get_homologues.pl\n\nTool homepage:
  https://github.com/eead-csic-compbio/get_homologues"
inputs:
  - id: cluster_dirs
    type:
      type: array
      items: string
    doc: comma-separated names of cluster directories
    inputBinding:
      position: 101
      prefix: -d
  - id: include_list
    type:
      - 'null'
      - File
    doc: produce clusters with single-copy seqs from ALL taxa in file
    inputBinding:
      position: 101
      prefix: -I
  - id: min_taxa_single_copy
    type:
      - 'null'
      - int
    doc: use only clusters with single-copy orthologues from taxa >= t
    inputBinding:
      position: 101
      prefix: -t
  - id: nucleotide_sequences
    type:
      - 'null'
      - boolean
    doc: use nucleotide sequence .fna clusters
    inputBinding:
      position: 101
      prefix: -n
  - id: orthoxml_report
    type:
      - 'null'
      - boolean
    doc: produce cluster report in OrthoXML format
    inputBinding:
      position: 101
      prefix: -x
  - id: pangenome_matrices
    type:
      - 'null'
      - boolean
    doc: produce intersection pangenome matrices
    inputBinding:
      position: 101
      prefix: -m
  - id: pangenomic_tree
    type:
      - 'null'
      - boolean
    doc: produce parsimony-based pangenomic tree
    inputBinding:
      position: 101
      prefix: -T
  - id: reference_set
    type:
      - 'null'
      - boolean
    doc: take first cluster dir as reference set, which might contain a single 
      representative sequence per cluster
    inputBinding:
      position: 101
      prefix: -r
  - id: syntenic_genes
    type:
      - 'null'
      - boolean
    doc: use only clusters with syntenic genes
    inputBinding:
      position: 101
      prefix: -s
outputs:
  - id: output_dir
    type: Directory
    doc: output directory
    outputBinding:
      glob: $(inputs.output_dir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/get_homologues:3.8.1--hdfd78af_0
