cwlVersion: v1.2
class: CommandLineTool
baseCommand: dadaist2
label: dadaist2
doc: "a shell wrapper for DADA2, to detect representative sequences and generate a
  feature table starting from Illumina Paired End reads. This is the main program
  of the *dadaist2 toolkit* that includes several wrappers and utilities to streamline
  the analysis of metabarcoding reads from the Linux shell to R.\n\nTool homepage:
  https://github.com/quadram-institute-bioscience/dadaist2"
inputs:
  - id: crosstalk
    type:
      - 'null'
      - boolean
    doc: Remove crosstalk using the UNCROSS2 algorithm as described here 
      <https://doi.org/10.1101/400762>.
    inputBinding:
      position: 101
      prefix: --crosstalk
  - id: dada_pool
    type:
      - 'null'
      - boolean
    doc: Pool samples in DADA2 analysis (experimental)
    inputBinding:
      position: 101
      prefix: --dada-pool
  - id: database
    type:
      - 'null'
      - File
    doc: 'Reference database in gzipped FASTA format. Optional (default: skip) but
      highly recommended.'
    inputBinding:
      position: 101
      prefix: --database
  - id: debug
    type:
      - 'null'
      - boolean
    doc: Increase reported information
    inputBinding:
      position: 101
      prefix: --debug
  - id: fastp
    type:
      - 'null'
      - boolean
    doc: Perform the legacy "fastp" QC
    inputBinding:
      position: 101
      prefix: --fastp
  - id: for_tag
    type:
      - 'null'
      - string
    doc: Tag to recognize forward reads
    inputBinding:
      position: 101
      prefix: --for-tag
  - id: force
    type:
      - 'null'
      - boolean
    doc: Will overwrite output folder if it already exists, and will attempt to 
      produce MicrobiomeAnalyst and Rhea folders even when DADA2 filters too 
      many reads.
    inputBinding:
      position: 101
      prefix: --force
  - id: id_separator
    type:
      - 'null'
      - string
    doc: Character separating the sample name from the rest of the filename
    inputBinding:
      position: 101
      prefix: --id-separator
  - id: input_directory
    type: Directory
    doc: Directory containing the paired end files in FASTQ format, gzipped or 
      not.
    inputBinding:
      position: 101
      prefix: --input-directory
  - id: just_concat
    type:
      - 'null'
      - boolean
    doc: Do not try merging paired end reads, just concatenate.
    inputBinding:
      position: 101
      prefix: --just-concat
  - id: log_file
    type:
      - 'null'
      - File
    doc: Filename for the program log.
    inputBinding:
      position: 101
      prefix: --log-file
  - id: max_loss
    type:
      - 'null'
      - float
    doc: After DADA2 run, check the amount of reads globally remaining from 
      input to non-chimeric, abort if the ratio is below threshold
    inputBinding:
      position: 101
      prefix: --max-loss
  - id: maxee1
    type:
      - 'null'
      - float
    doc: Maximum Expected Errors in R1
    inputBinding:
      position: 101
      prefix: --maxee1
  - id: maxee2
    type:
      - 'null'
      - float
    doc: Maximum Expected Errors in R2
    inputBinding:
      position: 101
      prefix: --maxee2
  - id: metadata
    type:
      - 'null'
      - File
    doc: Metadata file in TSV format, first column must match sample IDs. If not
      supplied a template will be autogenerated using "dadaist2-metadata".
    inputBinding:
      position: 101
      prefix: --metadata
  - id: min_qual
    type:
      - 'null'
      - float
    doc: Minimum average quality for DADA2 truncation
    inputBinding:
      position: 101
      prefix: --min-qual
  - id: no_trim
    type:
      - 'null'
      - boolean
    doc: Do not trim primers (using fastp). Equivalent to "--trim-primer-for 0 
      --trim-primer-rev 0".
    inputBinding:
      position: 101
      prefix: --no-trim
  - id: no_trunc
    type:
      - 'null'
      - boolean
    doc: Do not truncate reads at the end (required for non-overlapping 
      amplicons, like ITS)
    inputBinding:
      position: 101
      prefix: --no-trunc
  - id: popup
    type:
      - 'null'
      - boolean
    doc: Display popup notifications (tested on MacOS and Ubuntu)
    inputBinding:
      position: 101
      prefix: --popup
  - id: prefix
    type:
      - 'null'
      - string
    doc: Prefix for the output FASTA file, if "MD5" is specified, the sequence 
      MD5 hash will be used instead.
    inputBinding:
      position: 101
      prefix: --prefix
  - id: primers
    type:
      - 'null'
      - string
    doc: Strip primers with *cutadapt*, supply both sequences separated by a 
      colon.
    inputBinding:
      position: 101
      prefix: --primers
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Reduce verbosity
    inputBinding:
      position: 101
      prefix: --quiet
  - id: rev_tag
    type:
      - 'null'
      - string
    doc: Tag to recognize reverse reads
    inputBinding:
      position: 101
      prefix: --rev-tag
  - id: save_rds
    type:
      - 'null'
      - boolean
    doc: Save a copy of the RDS file
    inputBinding:
      position: 101
      prefix: --save-rds
  - id: skip_plots
    type:
      - 'null'
      - boolean
    doc: Do not generate quality plots.
    inputBinding:
      position: 101
      prefix: --skip-plots
  - id: skip_tree
    type:
      - 'null'
      - boolean
    doc: Do not generate tree. *Experimental|Not recommended*.
    inputBinding:
      position: 101
      prefix: --skip-tree
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads
    inputBinding:
      position: 101
      prefix: --threads
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: Where to place the temporary directory (default are system temp dir or 
      $TMPDIR).
    inputBinding:
      position: 101
      prefix: --tmp-dir
  - id: trim_primer_for
    type:
      - 'null'
      - int
    doc: Trim primer from R1 read specifying the number of bases.
    inputBinding:
      position: 101
      prefix: --trim-primer-for
  - id: trim_primer_rev
    type:
      - 'null'
      - int
    doc: Trim primer from R2 read specifying the number of bases.
    inputBinding:
      position: 101
      prefix: --trim-primer-rev
  - id: trunc_len_1
    type:
      - 'null'
      - int
    doc: Position at which truncate reads (forward)
    inputBinding:
      position: 101
      prefix: --trunc-len-1
  - id: trunc_len_2
    type:
      - 'null'
      - int
    doc: Position at which truncate reads (reverse)
    inputBinding:
      position: 101
      prefix: --trunc-len-2
  - id: trunc_qual
    type:
      - 'null'
      - float
    doc: DADA2 truncate quality
    inputBinding:
      position: 101
      prefix: --trunc-qual
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Increase reported information
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_directory
    type: Directory
    doc: Output directory (will be created). It is recommended recomment using a
      new directory for each run.
    outputBinding:
      glob: $(inputs.output_directory)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/dadaist2:1.3.1--hdfd78af_2
