cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - sparse
  - index
label: meta-sparse_sparse_index
doc: "Fill reference genomes into a SPARSE database created by sparse init.\n\nTool homepage: https://github.com/zheminzhou/SPARSE"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.dbname)
        writable: true
  - class: NetworkAccess
    networkAccess: true
inputs:
  - id: dbname
    type: Directory
    doc: "SPARSE database folder (created by sparse init); staged writable in the working directory"
    inputBinding:
      position: 1
      prefix: --dbname
      valueFrom: $(self.basename)
  - id: update
    type: 
      - 'null'
      - boolean
    doc: "Index the current RefSeq database. Overwrite SEQLIST."
    inputBinding:
      position: 2
      prefix: --update
  - id: seqlist
    type: 
      - 'null'
      - File
    doc: "Tab-delimited file generated by sparse query; give the absolute path in column file_path for local genomes, or ftp_path/url_path to download them"
    inputBinding:
      position: 3
      prefix: --seqlist
  - id: n_thread
    type: 
      - 'null'
      - int
    doc: "Number of threads to use. Default: 20"
    inputBinding:
      position: 4
      prefix: --n_thread
outputs:
  - id: database
    type: Directory
    doc: "Updated SPARSE database folder"
    outputBinding:
      glob: $(inputs.dbname.basename)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meta-sparse:0.1.12--py27h24bf2e0_0
