cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - sparse
  - mapDB
label: meta-sparse_sparse_mapDB
doc: "Generate sub-databases for read alignments.\n\nTool homepage: https://github.com/zheminzhou/SPARSE"
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.dbname)
        writable: true
  - class: NetworkAccess
    networkAccess: true
inputs:
  - id: dbname
    type: Directory
    doc: "SPARSE database folder (created by sparse init); staged writable in the working directory"
    inputBinding:
      position: 1
      prefix: --dbname
      valueFrom: $(self.basename)
  - id: mapdb
    type: string
    doc: "Name for the sub-database"
    inputBinding:
      position: 2
      prefix: --mapDB
  - id: seqlist
    type: File
    doc: "Tab-delimited list of references to include; can be generated by sparse query"
    inputBinding:
      position: 3
      prefix: --seqlist
  - id: n_thread
    type: 
      - 'null'
      - int
    doc: "Number of threads to use. Default: 20"
    inputBinding:
      position: 4
      prefix: --n_thread
  - id: malt
    type: 
      - 'null'
      - boolean
    doc: "Use MALT instead of minimap2"
    inputBinding:
      position: 5
      prefix: --malt
  - id: append
    type: 
      - 'null'
      - boolean
    doc: "Append to existing database instead of overwrite"
    inputBinding:
      position: 6
      prefix: --append
outputs:
  - id: database
    type: Directory
    doc: "Updated SPARSE database folder"
    outputBinding:
      glob: $(inputs.dbname.basename)
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meta-sparse:0.1.12--py27h24bf2e0_0
stdout: meta-sparse_sparse_mapDB.out
