cwlVersion: v1.2
class: CommandLineTool
baseCommand: mmult_bbglm
label: mmult_bbglm
doc: "Analyze methylation data using a generalized linear model.\n\nTool homepage:
  https://github.com/lijinbio/MMULT"
inputs:
  - id: batchthreads
    type:
      - 'null'
      - int
    doc: Number of batch threads.
    default: 5
    inputBinding:
      position: 101
      prefix: --batchthreads
  - id: chrom
    type:
      - 'null'
      - type: array
        items: string
    doc: 'A specific chromosome for analysis. Can be specified multiple times for
      multiple chromosomes. The size can be encoded for a chromosome. For example,
      `-c chr1:248956422 -c chr2:242193529`. The size can be used to split a chromosome
      for running in small batches. Default: all chromosomes appear in methylation
      files.'
    inputBinding:
      position: 101
      prefix: --chrom
  - id: length
    type:
      - 'null'
      - int
    doc: Split length of coordinates in a chromomsome. This is necessary for 
      many replicates with a limited memory. To enable small-batch running, size
      info should be specificed by `-c|--chrom`. Because the size of chr1 in 
      hg38 is >200 million, 1/10th (20M) can be good to go.
    default: 20000000
    inputBinding:
      position: 101
      prefix: --length
  - id: maxdistdmcs
    type:
      - 'null'
      - int
    doc: Maximum distance between consecutive DMCs for DMR.
    default: 300
    inputBinding:
      position: 101
  - id: methfile
    type:
      type: array
      items: File
    doc: Methylation BED files. The BED file is generated by `MCALL` in MOABS. 
      Replicates in a group are concatenated by comma `,`. Multiple groups can 
      be specified. For example, `-m g1_r1.bed,g1_r2.bed -m g2_r1.bed -m 
      g3_r1.bed,g3_r2.bed,g3_r3.bed`.
    inputBinding:
      position: 101
      prefix: --methfile
  - id: mindepth
    type:
      - 'null'
      - int
    doc: Minimum depth for a CpG coverage.
    default: 1
    inputBinding:
      position: 101
      prefix: --mindepth
  - id: mindmc
    type:
      - 'null'
      - int
    doc: Minimum number ofDMCs in a DMR.
    default: 3
    inputBinding:
      position: 101
  - id: nominaldiff
    type:
      - 'null'
      - float
    doc: Nominal methylation difference threshold for DMC.
    default: 0.2
    inputBinding:
      position: 101
  - id: qval
    type:
      - 'null'
      - float
    doc: Q-value threshold for DMC.
    default: 0.05
    inputBinding:
      position: 101
  - id: readthreads
    type:
      - 'null'
      - int
    doc: Number of read threads.
    default: 10
    inputBinding:
      position: 101
      prefix: --readthreads
outputs:
  - id: outfile
    type:
      - 'null'
      - File
    doc: Output file.
    outputBinding:
      glob: $(inputs.outfile)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mmult:0.0.0.2--r40h8b68381_0
