cwlVersion: v1.2
class: CommandLineTool
baseCommand: mmult_vmcvmrnme
label: mmult_vmcvmrnme
doc: "Detects VMCs (Variable Methylation Calls) and VMRs (Variable Methylation Regions)
  from methylation BED files.\n\nTool homepage: https://github.com/lijinbio/MMULT"
inputs:
  - id: chrom
    type:
      - 'null'
      - type: array
        items: string
    doc: 'One specific-chromosome for analysis. Can be specified multiple times for
      multiple chromosomes. Default: all chromosomes appear in methylation BED files.'
    inputBinding:
      position: 101
      prefix: --chrom
  - id: maxdistvmcs
    type:
      - 'null'
      - int
    doc: 'Maximum distance between consecutive VMCs for VMR. Default: 300.'
    default: 300
    inputBinding:
      position: 101
      prefix: --maxdistvmcs
  - id: methfile
    type:
      - 'null'
      - type: array
        items: File
    doc: Methylation BED files. The BED file is generated by `MCALL` in MOABS. 
      Replicates are concatenated by comma `,`. For example, `-m 
      r1.bed,r2.bed,r3.bed`.
    inputBinding:
      position: 101
      prefix: --methfile
  - id: mincpg
    type:
      - 'null'
      - int
    doc: 'Minimum CpGs in a window. Default: 3.'
    default: 3
    inputBinding:
      position: 101
      prefix: --mincpg
  - id: mindepth
    type:
      - 'null'
      - int
    doc: 'Minimum depth for a CpG coverage. Default: 3.'
    default: 3
    inputBinding:
      position: 101
      prefix: --mindepth
  - id: minsample
    type:
      - 'null'
      - int
    doc: 'Minimum samples for a CpG. Default: 5.'
    default: 5
    inputBinding:
      position: 101
  - id: nme
    type:
      - 'null'
      - float
    doc: 'NME for VMC. Default: 0.25.'
    default: 0.25
    inputBinding:
      position: 101
      prefix: --nme
  - id: numthreads
    type:
      - 'null'
      - int
    doc: 'Number of threads. Default: 8.'
    default: 8
    inputBinding:
      position: 101
      prefix: --numthreads
  - id: sd
    type:
      - 'null'
      - float
    doc: 'sd for VMC. Default: 0.2.'
    default: 0.2
    inputBinding:
      position: 101
      prefix: --sd
  - id: state
    type:
      - 'null'
      - int
    doc: 'Number of discretization states. Default: 2.'
    default: 2
    inputBinding:
      position: 101
      prefix: --state
  - id: vmcfile
    type:
      - 'null'
      - File
    doc: VMC file.
    inputBinding:
      position: 101
  - id: vmrmethod
    type:
      - 'null'
      - int
    doc: 'VMR detection method. 0: identify VMCs first and detect VMRs from consecutive
      VMCs; 1: Genome scan method by fixed-size windows. Default: 0.'
    default: 0
    inputBinding:
      position: 101
      prefix: --vmrmethod
  - id: window
    type:
      - 'null'
      - int
    doc: 'Window size for genome scan. Default: 150.'
    default: 150
    inputBinding:
      position: 101
      prefix: --window
  - id: windowfile
    type:
      - 'null'
      - File
    doc: VMR file by genome scan.
    inputBinding:
      position: 101
outputs:
  - id: outfile
    type:
      - 'null'
      - File
    doc: Output file.
    outputBinding:
      glob: $(inputs.outfile)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mmult:0.0.0.2--r40h8b68381_0
