cwlVersion: v1.2
class: CommandLineTool
baseCommand: java -jar clinod-1.3.jar
label: clinod
doc: "Nucleolar localization sequence Detector\n\nTool homepage: https://github.com/RogerioAP/Clinodonto-Soft"
inputs:
  - id: batchman_path
    type:
      - 'null'
      - File
    doc: 'optional, an absolute path to the Batchman executable. By default this path
      is searched in the environmental variable called BATCHMAN_PATH. If it is not
      found there, then clinod attempts to locate the batchman executable in the same
      directory as the clinod jar file. In order to be found there the batchman executable
      must be called the "batchman.exe" on Windows systems and the "batchman" on all
      other operating systems. If neither of those paths are valid then the execution
      fails. If several paths are valid then clinod uses them in the following order:
      1) Path from the command line parameter 2) Path from the environmental variable
      3) Local directory path'
    inputBinding:
      position: 101
      prefix: -bm
  - id: clean_sequence
    type:
      - 'null'
      - boolean
    doc: 'optional, if specified causes the predictor to automatically remove all
      non-protein characters from the sequences that contains them. The predictor
      only works with unambiguous protein sequences. Only the following characters
      considered to be valid: ARNDCQEGHILKMFPSTWYV. If any other character is detected
      in the sequence the predictor stops the execution and raises the exception unless
      this flag is specified. In this case, the predictor removes invalid characters
      from the sequence and writes the information about it into the log file.'
    inputBinding:
      position: 101
      prefix: -clean_sequence
  - id: input_file
    type: File
    doc: absolute path to the input file. The input file expected to contain the
      list of FASTA formatted sequences.
    inputBinding:
      position: 101
      prefix: -in
  - id: number_of_threads
    type:
      - 'null'
      - int
    doc: optional, defaults to the number of cores available on the computer. 
      Maximum number of threads cannot be greater than twice the number of 
      available cores. However, we have not observed any significant gains from 
      increasing the number of threads beyond the number of CPU cores actually 
      available on the computer.
    inputBinding:
      position: 101
      prefix: -t
  - id: output_format
    type:
      - 'null'
      - string
    doc: optional, defaults to MEDIUM. Possible values COMPLETE, FULL, MEDIUM, 
      SHORT and MINIMAL (case sensitive)
    inputBinding:
      position: 101
      prefix: -f
  - id: suppress_no_nols
    type:
      - 'null'
      - boolean
    doc: optional, suppresses reporting of the proteins with no NOLS detected if
      specified.
    inputBinding:
      position: 101
      prefix: -nonols
  - id: working_directory
    type:
      - 'null'
      - Directory
    doc: optional, defaults to the system temp directory (defined by the 
      "java.io.tmpdir" environmental variable) If the directory does not exist, 
      it will be created. However the parent directory must exist. For example 
      if working directory is set to /home/tmp and home directory does not exist
      then the execution will be terminated. If the home directory exist but tmp
      directory does not, the tmp directory will be created. If the /home/tmp 
      directory exist then it will be used. If the /home/tmp directory is not 
      empty, then any files with the same name as generated by the program will 
      be overridden.
      environmental variable)
    inputBinding:
      position: 101
      prefix: -d
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: optional, by default the system prints the output to the console. If 
      the file exists it will be overridden. The order of the predictions in the
      output is guaranteed to be the same as the order of the sequences in the 
      input. This means that the prediction for the tenth sequence from the 
      input will be the tenth prediction in the output, unless -nonols parameter
      was used to suppress reporting predictions with no NOLS detected
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/clinod:1.3--py27_0
