cwlVersion: v1.2
class: CommandLineTool
baseCommand: reviewer_REViewer
label: reviewer_REViewer
doc: "Analyze ExpansionHunter results\n\nTool homepage: https://github.com/Illumina/REViewer"
inputs:
  - id: catalog
    type: File
    doc: Variant catalog
    inputBinding:
      position: 101
      prefix: --catalog
  - id: locus
    type: string
    doc: Locus to analyze (or a list of comma-separated loci)
    inputBinding:
      position: 101
      prefix: --locus
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Prefix for the output files
    inputBinding:
      position: 101
      prefix: --output-prefix
  - id: reads
    type: File
    doc: BAMlet generated by ExpansionHunter
    inputBinding:
      position: 101
      prefix: --reads
  - id: reference
    type: File
    doc: FASTA file with reference genome
    inputBinding:
      position: 101
      prefix: --reference
  - id: region_extension_length
    type:
      - 'null'
      - int
    doc: Length of flanking region (must match corresponding ExpansionHunter 
      setting)
    inputBinding:
      position: 101
      prefix: --region-extension-length
  - id: vcf
    type: File
    doc: VCF file generated by ExpansionHunter
    inputBinding:
      position: 101
      prefix: --vcf
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/reviewer:0.2.7--h48da230_0
stdout: reviewer_REViewer.out
