cwlVersion: v1.2
class: CommandLineTool
baseCommand: examl
label: examl_build
doc: "ExaML (Exascale Maximum Likelihood) is a tool for phylogenetic inference on
  huge datasets using Maximum Likelihood.\n\nTool homepage: https://github.com/stamatak/ExaML"
inputs:
  - id: binary_alignment_file
    type: File
    doc: The name of the binary alignment file (generated by parse-examl)
    inputBinding:
      position: 101
      prefix: -s
  - id: checkpoint_interval
    type:
      - 'null'
      - int
    doc: The checkpoint interval in seconds
    inputBinding:
      position: 101
      prefix: -i
  - id: model
    type: string
    doc: The name of the substitution model (e.g., PSR or GAMMA)
    inputBinding:
      position: 101
      prefix: -m
  - id: output_name
    type: string
    doc: The suffix for the output files
    inputBinding:
      position: 101
      prefix: -n
  - id: search_convergence
    type:
      - 'null'
      - string
    doc: Enable ML search convergence criterion
    inputBinding:
      position: 101
      prefix: -D
  - id: seed
    type:
      - 'null'
      - int
    doc: Random number seed for parsimony starting tree
    inputBinding:
      position: 101
      prefix: -p
  - id: starting_tree
    type: File
    doc: The name of the starting tree file in Newick format
    inputBinding:
      position: 101
      prefix: -t
  - id: work_directory
    type:
      - 'null'
      - Directory
    doc: The name of the working directory where ExaML will write its output 
      files
    inputBinding:
      position: 101
      prefix: -w
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: biocontainers/examl:v3.0.21-2-deb_cv1
stdout: examl_build.out
