cwlVersion: v1.2
class: CommandLineTool
baseCommand: moss
label: moss
doc: "Multiple Sample Somatic variant caller\n\nTool homepage: https://github.com/elkebir-group/Moss"
inputs:
  - id: bam_files
    type:
      type: array
      items: File
    doc: original BAM files for one sample, can be addressed multiple times
    inputBinding:
      position: 101
      prefix: --bam
  - id: candidate_loci_vcf
    type:
      - 'null'
      - File
    doc: candidate loci VCF files generated by python script
    inputBinding:
      position: 101
      prefix: --loci
  - id: dry_run
    type:
      - 'null'
      - boolean
    doc: set to dry run
    inputBinding:
      position: 101
      prefix: --dry
  - id: filter_total_depth
    type:
      - 'null'
      - boolean
    doc: set to filter variants with total tumor depth < 150
    inputBinding:
      position: 101
      prefix: --filter-total
  - id: filter_vaf
    type:
      - 'null'
      - boolean
    doc: set to filter variants with VAF in any samples < 0.1
    inputBinding:
      position: 101
      prefix: --filter-vaf
  - id: grid_size
    type:
      - 'null'
      - int
    doc: number of grid points in [0, 1] for approximate integration, must be 
      non-negative
    inputBinding:
      position: 101
      prefix: --grid-size
  - id: ignore_zero_allele
    type:
      - 'null'
      - boolean
    doc: ignore samples with all reads same as the normal allele
    inputBinding:
      position: 101
      prefix: --ignore0
  - id: max_depth
    type:
      - 'null'
      - int
    doc: max depth of the dataset
    inputBinding:
      position: 101
      prefix: --max_dep
  - id: min_base_quality
    type:
      - 'null'
      - int
    doc: minimum threshold for base quality
    inputBinding:
      position: 101
      prefix: --min-base-qual
  - id: min_mapping_quality
    type:
      - 'null'
      - int
    doc: minimum threshold for mapping quality
    inputBinding:
      position: 101
      prefix: --min-mapping-qual
  - id: normal_germline_vcf
    type: File
    doc: normal sample's germline VCF result
    inputBinding:
      position: 101
      prefix: --normal
  - id: output_pileup
    type:
      - 'null'
      - boolean
    doc: output pileup, only effective in dry-run mode
    inputBinding:
      position: 101
      prefix: --pileup
  - id: realigned_bam_files
    type:
      - 'null'
      - type: array
        items: File
    doc: realigned BAM files for one sample, can be addressed multiple times
    inputBinding:
      position: 101
      prefix: --realigned
  - id: reference
    type: File
    doc: reference FASTA file
    inputBinding:
      position: 101
      prefix: --ref
  - id: somatic_mutation_prior_m
    type:
      - 'null'
      - float
    doc: set somatic mutation prior, 1-5x10^(-m)
    inputBinding:
      position: 101
      prefix: --mu
  - id: tau_threshold
    type:
      - 'null'
      - float
    doc: optional threshold for somatic score
    inputBinding:
      position: 101
      prefix: --tau
  - id: tumor_somatic_vcf
    type: File
    doc: tumor samples' somatic VCF result
    inputBinding:
      position: 101
      prefix: --vcf
outputs:
  - id: output_vcf
    type: File
    doc: output VCF file
    outputBinding:
      glob: $(inputs.output_vcf)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/moss:0.1.1--h06e5f0a_2
