cwlVersion: v1.2
class: CommandLineTool
baseCommand: kat cold
label: kat_cold
doc: "COntig Length and Duplication analysis tool\n\nCalculates median read k-mer
  coverage, assembly k-mer coverage and GC% across each sequence in the provided assembly.
  Then, assuming plotting is enabled, the results are converted into a scatter plot,
  where each point is colored according to a similar scheme used in spectra-cn plots,
  and sized according to its length.  The y-axis representsmedian read K-mer coverage,
  and x-axis represents GC%.\n\n The <assembly> should be a fasta file that is NOT
  gzipped compressed.  The <reads> can be any number of <fasta/q> files, which CAN
  be gzipped compressed, or a pre-counted hash.\n\nTool homepage: https://github.com/TGAC/KAT"
inputs:
  - id: assembly
    type: File
    doc: The assembly fasta file (not gzipped compressed)
    inputBinding:
      position: 1
  - id: reads
    type:
      type: array
      items: File
    doc: Any number of fasta/q files (can be gzipped compressed), or a 
      pre-counted hash
    inputBinding:
      position: 2
  - id: cvg_bins
    type:
      - 'null'
      - int
    doc: Number of bins for the cvg data when creating the contamination matrix.
    default: 1001
    inputBinding:
      position: 103
      prefix: --cvg_bins
  - id: disable_hash_grow
    type:
      - 'null'
      - boolean
    doc: By default jellyfish will double the size of the hash if it gets 
      filled, and then attempt to recount. Setting this option to true, disables
      automatic hash growing. If the hash gets filled an error is thrown. This 
      option is useful if you are working with large genomes, or have strict 
      memory limits on your system.
    inputBinding:
      position: 103
      prefix: --disable_hash_grow
  - id: dump_hashes
    type:
      - 'null'
      - boolean
    doc: Dumps any jellyfish hashes to disk that were produced during this run. 
      Normally, this is not recommended, as hashes are slow to load and will 
      likely consume a significant amount of disk space.
    inputBinding:
      position: 103
      prefix: --dump_hashes
  - id: gc_bins
    type:
      - 'null'
      - int
    doc: Number of bins for the gc data when creating the contamination matrix.
    default: 1001
    inputBinding:
      position: 103
      prefix: --gc_bins
  - id: hash_size
    type:
      - 'null'
      - int
    doc: If kmer counting is required, then use this value as the hash size for 
      the reads. We assume the assembly should use half this value. If this hash
      size is not large enough for your dataset then the default behaviour is to
      double the size of the hash and recount, which will increase runtime and 
      memory usage.
    default: 100000000
    inputBinding:
      position: 103
      prefix: --hash_size
  - id: mer_len
    type:
      - 'null'
      - int
    doc: The kmer length to use in the kmer hashes. Larger values will provide 
      more discriminating power between kmers but at the expense of additional 
      memory and lower coverage.
    default: 27
    inputBinding:
      position: 103
      prefix: --mer_len
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Path prefix for files generated by this program.
    default: kat-cold
    inputBinding:
      position: 103
      prefix: --output_prefix
  - id: output_type
    type:
      - 'null'
      - string
    doc: 'The plot file type to create: png, ps, pdf.'
    default: png
    inputBinding:
      position: 103
      prefix: --output_type
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use
    default: 1
    inputBinding:
      position: 103
      prefix: --threads
  - id: trim_5p
    type:
      - 'null'
      - string
    doc: Ignore the first X bases from reads. If more that one file is provided 
      you can specify different values for each file by seperating with commas.
    default: '0'
    inputBinding:
      position: 103
      prefix: --5ptrim
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print extra information.
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/kat:2.4.2--py39he0b6574_5
stdout: kat_cold.out
