cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - kat
  - sect
label: kat_sect
doc: "Estimates coverage levels across sequences in the provided input sequence file.\n\
  \nTool homepage: https://github.com/TGAC/KAT"
inputs:
  - id: sequence_file
    type: File
    doc: Input sequence file
    inputBinding:
      position: 1
  - id: input
    type:
      type: array
      items: string
    doc: One or more input files (jellyfish hash, FastA, or FastQ)
    inputBinding:
      position: 2
  - id: cvg_bins
    type:
      - 'null'
      - int
    doc: Number of bins for the cvg data when creating the contamination matrix.
    inputBinding:
      position: 103
      prefix: --cvg_bins
  - id: cvg_logscale
    type:
      - 'null'
      - boolean
    doc: Compresses cvg scores into logscale for determining the cvg bins within
      the contamination matrix. Otherwise compresses cvg scores by a factor of 
      0.1 into the available bins.
    inputBinding:
      position: 103
      prefix: --cvg_logscale
  - id: dump_hash
    type:
      - 'null'
      - boolean
    doc: Dumps any jellyfish hashes to disk that were produced during this run. 
      Normally, this is not recommended, as hashes are slow to load and will 
      likely consume a significant amount of disk space.
    inputBinding:
      position: 103
      prefix: --dump_hash
  - id: extract_nr
    type:
      - 'null'
      - boolean
    doc: Tells SECT extract non-repetitive regions into a separate FastA file.
    inputBinding:
      position: 103
      prefix: --extract_nr
  - id: extract_r
    type:
      - 'null'
      - boolean
    doc: Tells SECT extract repetitive regions into a separate FastA file.
    inputBinding:
      position: 103
      prefix: --extract_r
  - id: gc_bins
    type:
      - 'null'
      - int
    doc: Number of bins for the gc data when creating the contamination matrix.
    inputBinding:
      position: 103
      prefix: --gc_bins
  - id: hash_size
    type:
      - 'null'
      - int
    doc: If kmer counting is required for the input, then use this value as the 
      hash size. If this hash size is not large enough for your dataset then the
      default behaviour is to double the size of the hash and recount, which 
      will increase runtime and memory usage.
    inputBinding:
      position: 103
      prefix: --hash_size
  - id: max_repeat
    type:
      - 'null'
      - int
    doc: If user requests repeat region extraction (--extract_r), this value 
      allows the user to override the default maximum limit on the amount of 
      repetition allowed. This allows users to avoid regions that are likely to 
      be due to low complexity sequences. A value of 0 means no limit on max 
      repeats.
    inputBinding:
      position: 103
      prefix: --max_repeat
  - id: mer_len
    type:
      - 'null'
      - int
    doc: The kmer length to use in the kmer hashes. Larger values will provide 
      more discriminating power between kmers but at the expense of additional 
      memory and lower coverage.
    inputBinding:
      position: 103
      prefix: --mer_len
  - id: min_repeat
    type:
      - 'null'
      - int
    doc: If user requests repeat region extraction (--extract_r), this value 
      allows the user to override the default minimum limit on the amount of 
      repetition required.
    inputBinding:
      position: 103
      prefix: --min_repeat
  - id: no_count_stats
    type:
      - 'null'
      - boolean
    doc: Tells SECT not to output count stats. Sometimes when using SECT on read
      files the output can get very large. When flagged this just outputs 
      summary stats for each sequence.
    inputBinding:
      position: 103
      prefix: --no_count_stats
  - id: non_canonical
    type:
      - 'null'
      - boolean
    doc: If counting fast(a/q), store explicit kmer as found. By default, we 
      store 'canonical' kmers, which means we count both strands.
    inputBinding:
      position: 103
      prefix: --non_canonical
  - id: output_gc_stats
    type:
      - 'null'
      - boolean
    doc: Tells SECT to output GC counts for each k-mer. Output is a FastA like 
      counts file similar to that produce for the k-mer counts. This can be 
      slow.
    inputBinding:
      position: 103
      prefix: --output_gc_stats
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Path prefix for files generated by this program.
    inputBinding:
      position: 103
      prefix: --output_prefix
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use
    inputBinding:
      position: 103
      prefix: --threads
  - id: trim_5ptrim
    type:
      - 'null'
      - string
    doc: Ignore the first X bases from reads. If more that one file is provided 
      you can specify different values for each file by seperating with commas.
    inputBinding:
      position: 103
      prefix: --5ptrim
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print extra information.
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/kat:2.4.2--py39he0b6574_5
stdout: kat_sect.out
