cwlVersion: v1.2
class: CommandLineTool
baseCommand: kat_hist
label: kat_hist
doc: "Create an histogram of k-mer occurrences from the input.\n\nTool homepage: https://github.com/TGAC/KAT"
inputs:
  - id: inputs
    type:
      type: array
      items: File
    doc: Input jellyfish hash, or one or more FastA or FastQ files.
    inputBinding:
      position: 1
  - id: dump_hash
    type:
      - 'null'
      - boolean
    doc: Dumps any jellyfish hashes to disk that were produced during this run. 
      Normally, this is not recommended, as hashes are slow to load and will 
      likely consume a significant amount of disk space.
    inputBinding:
      position: 102
      prefix: --dump_hash
  - id: hash_size
    type:
      - 'null'
      - int
    doc: If kmer counting is required for the input, then use this value as the 
      hash size. If this hash size is not large enough for your dataset then the
      default behaviour is to double the size of the hash and recount, which 
      will increase runtime and memory usage.
    default: 100000000
    inputBinding:
      position: 102
      prefix: --hash_size
  - id: high
    type:
      - 'null'
      - int
    doc: High count value of histogram
    default: 10000
    inputBinding:
      position: 102
      prefix: --high
  - id: inc
    type:
      - 'null'
      - int
    doc: Increment for each bin
    default: 1
    inputBinding:
      position: 102
      prefix: --inc
  - id: low
    type:
      - 'null'
      - int
    doc: Low count value of histogram
    default: 1
    inputBinding:
      position: 102
      prefix: --low
  - id: mer_len
    type:
      - 'null'
      - int
    doc: The kmer length to use in the kmer hashes. Larger values will provide 
      more discriminating power between kmers but at the expense of additional 
      memory and lower coverage.
    default: 27
    inputBinding:
      position: 102
      prefix: --mer_len
  - id: non_canonical
    type:
      - 'null'
      - boolean
    doc: If counting fast(a/q), store explicit kmer as found. By default, we 
      store 'canonical' k-mers, which means we count both strands.
    inputBinding:
      position: 102
      prefix: --non_canonical
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Path prefix for files generated by this program.
    default: kat.hist
    inputBinding:
      position: 102
      prefix: --output_prefix
  - id: output_type
    type:
      - 'null'
      - string
    doc: 'The plot file type to create: png, ps, pdf.'
    default: png
    inputBinding:
      position: 102
      prefix: --output_type
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use
    default: 1
    inputBinding:
      position: 102
      prefix: --threads
  - id: trim_5ptrim
    type:
      - 'null'
      - int
    doc: Ignore the first X bases from reads. If more that one file is provided 
      you can specify different values for each file by seperating with commas.
    default: 0
    inputBinding:
      position: 102
      prefix: --5ptrim
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print extra information.
    inputBinding:
      position: 102
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/kat:2.4.2--py39he0b6574_5
stdout: kat_hist.out
