cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - kat
  - filter
  - seq
label: kat_filter_seq
doc: "Filter sequences based on whether those sequences contain specific k-mers.\n\nThe user loads a k-mer hash and then filters sequences (either in or out) depending on whether those sequences contain the k-mer or not.\n\nTool homepage: https://github.com/TGAC/KAT"
inputs:
  - id: input
    type:
      type: array
      items: File
    doc: "Input FastA/FastQ file(s) or a jellyfish hash used to load the k-mers"
    inputBinding:
      position: 20
  - id: seq
    type: File
    doc: "The sequence file to filter"
    inputBinding:
      position: 1
      prefix: --seq
  - id: seq2
    type:
      - 'null'
      - File
    doc: "The second sequence file to filter (use this if you want to filter paired end reads)"
    inputBinding:
      position: 2
      prefix: --seq2
  - id: output_prefix
    type: string
    default: kat.filter.seq
    doc: "Path prefix for files generated by this program."
    inputBinding:
      position: 3
      prefix: --output_prefix
  - id: threads
    type:
      - 'null'
      - int
    doc: "The number of threads to use"
    inputBinding:
      position: 4
      prefix: --threads
  - id: threshold
    type:
      - 'null'
      - float
    doc: "What percentage of the sequence needs to be covered with target k-mers to keep the sequence"
    inputBinding:
      position: 5
      prefix: --threshold
  - id: invert
    type:
      - 'null'
      - boolean
    doc: "Whether to output sequences not found in the kmer hash, rather than those inside."
    inputBinding:
      position: 6
      prefix: --invert
  - id: separate
    type:
      - 'null'
      - boolean
    doc: "Whether to partition the sequences into two sets, those with k-mers detected and those without.  Works in combination with invert."
    inputBinding:
      position: 7
      prefix: --separate
  - id: frequency
    type:
      - 'null'
      - float
    doc: "If a value is set here then only keep the sequence if matching the kmer dataset and a random number is generated between 0 and 1 that exceeds this threshold."
    inputBinding:
      position: 8
      prefix: --frequency
  - id: stats
    type:
      - 'null'
      - boolean
    doc: "Whether to emit statistics about quantity of found k-mers in each sequence."
    inputBinding:
      position: 9
      prefix: --stats
  - id: non_canonical
    type:
      - 'null'
      - boolean
    doc: "If counting fast(a/q), store explicit kmer as found.  By default, we store canonical k-mers, which means we count both strands."
    inputBinding:
      position: 10
      prefix: --non_canonical
  - id: mer_len
    type:
      - 'null'
      - int
    doc: "The kmer length to use in the kmer hashes."
    inputBinding:
      position: 11
      prefix: --mer_len
  - id: hash_size
    type:
      - 'null'
      - int
    doc: "If kmer counting is required for the input, then use this value as the hash size."
    inputBinding:
      position: 12
      prefix: --hash_size
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Print extra information."
    inputBinding:
      position: 13
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: "Files written with the output prefix (filtered sequences and statistics)"
    outputBinding:
      glob: $(inputs.output_prefix)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/kat:2.4.2--py39he0b6574_5
stdout: kat_filter_seq.out
