cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - kat
  - filter
  - kmer
label: kat_filter_kmer
doc: "Filter kmers to those within defined bounds and those outside.\n\nThe user can produce K-mer hashes, within and outside user defined GC and k-mer coverage bounds.\n\nTool homepage: https://github.com/TGAC/KAT"
inputs:
  - id: input
    type: File
    doc: "Input FastA/FastQ file(s) or a jellyfish hash"
    inputBinding:
      position: 1
  - id: output_prefix
    type: string
    default: kat.filter.kmer
    doc: "Path prefix for files generated by this program."
    inputBinding:
      position: 2
      prefix: --output_prefix
  - id: threads
    type:
      - 'null'
      - int
    doc: "The number of threads to use"
    inputBinding:
      position: 3
      prefix: --threads
  - id: low_count
    type:
      - 'null'
      - int
    doc: "Low count threshold"
    inputBinding:
      position: 4
      prefix: --low_count
  - id: high_count
    type:
      - 'null'
      - int
    doc: "High count threshold"
    inputBinding:
      position: 5
      prefix: --high_count
  - id: low_gc
    type:
      - 'null'
      - int
    doc: "Low GC count threshold"
    inputBinding:
      position: 6
      prefix: --low_gc
  - id: high_gc
    type:
      - 'null'
      - int
    doc: "High GC count threshold"
    inputBinding:
      position: 7
      prefix: --high_gc
  - id: invert
    type:
      - 'null'
      - boolean
    doc: "Whether to take k-mers outside region as selected content, rather than those inside."
    inputBinding:
      position: 8
      prefix: --invert
  - id: separate
    type:
      - 'null'
      - boolean
    doc: "Whether to partition the k-mers into two sets, those inside region and those outside.  Works in combination with invert."
    inputBinding:
      position: 9
      prefix: --separate
  - id: non_canonical
    type:
      - 'null'
      - boolean
    doc: "If counting fast(a/q), store explicit kmer as found.  By default, we store canonical k-mers, which means we count both strands."
    inputBinding:
      position: 10
      prefix: --non_canonical
  - id: mer_len
    type:
      - 'null'
      - int
    doc: "The kmer length to use in the kmer hashes."
    inputBinding:
      position: 11
      prefix: --mer_len
  - id: hash_size
    type:
      - 'null'
      - int
    doc: "If kmer counting is required for the input, then use this value as the hash size."
    inputBinding:
      position: 12
      prefix: --hash_size
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Print extra information."
    inputBinding:
      position: 13
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: "Files written with the output prefix (filtered jellyfish hashes)"
    outputBinding:
      glob: $(inputs.output_prefix)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/kat:2.4.2--py39he0b6574_5
stdout: kat_filter_kmer.out
