cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - gapseq
  - pan
label: gapseq_pan
doc: "Reconstruct a pan-Draft from a list of models.

Tool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: models_path
    type:
      type: array
      items: File
    doc: "Gapseq draft models (RDS format) to reconstruct the pan-model"
    inputBinding:
      position: 101
      prefix: --models_path
      itemSeparator: ","
  - id: rxn_weights_files_path
    type:
      - 'null'
      - type: array
        items: File
    doc: "Reaction weight tables generated by gapseq draft (RDS format)"
    inputBinding:
      position: 101
      prefix: --rxn.weights.files_path
      itemSeparator: ","
  - id: rxnxgene_tables_path
    type:
      - 'null'
      - type: array
        items: File
    doc: "Tables with gene-X-reaction associations as generated by gapseq draft (RDS format)"
    inputBinding:
      position: 101
      prefix: --rxnXgene.tables_path
      itemSeparator: ","
  - id: pathways_table_path
    type:
      - 'null'
      - type: array
        items: File
    doc: "All-Pathways tables as generated by gapseq find (tbl format)"
    inputBinding:
      position: 101
      prefix: --pathways.table.path
      itemSeparator: ","
  - id: min_rxn_freq_in_mods
    type:
      - 'null'
      - float
    doc: "Minimum reaction frequency to include the reactions in the pan-Draft (default: 0.06)"
    inputBinding:
      position: 101
      prefix: --min.rxn.freq.in.mods
  - id: only_binary_rxn_tbl
    type:
      - 'null'
      - boolean
    doc: "Perform only models comparison to get a binary table summarizing reaction presence/absence (default: false)"
    inputBinding:
      position: 101
      prefix: --only.binary.rxn.tbl
  - id: output_dir
    type:
      - 'null'
      - string
    doc: "Path to directory, where output files will be saved (default: current directory)"
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: "Do not save model as sbml file (default: save as SBML)"
    inputBinding:
      position: 101
      prefix: --sbml.no.output
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: pan_model_files
    type:
      type: array
      items: File
    doc: "Pan-draft model files and reaction tables"
    outputBinding:
      glob:
        - "*.RDS"
        - "*.xml"
        - "*.tsv"
        - "*.tbl"
  - id: output_dir_dir
    type:
      - 'null'
      - Directory
    doc: "Output directory when output_dir is given"
    outputBinding:
      glob: $(inputs.output_dir)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - '${ if (inputs.output_dir) { return [{class: "Directory", basename: inputs.output_dir, listing: [], writable: true}]; } else { return []; } }'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_pan.out
