cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - gapseq
  - medium
label: gapseq_medium
doc: "(gapfill-)Medium prediction based on results from find and draft

Tool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: model
    type: File
    doc: "GapSeq(-Draft)-Model (RDS or SBML)"
    inputBinding:
      position: 101
      prefix: --model
  - id: pathway_pred
    type: File
    doc: "Pathway-results table generated by gapseq find"
    inputBinding:
      position: 101
      prefix: --pathway.pred
  - id: manual_flux
    type:
      - 'null'
      - string
    doc: "Specify fixed maxFlux values in medium for specific compounds. Format: [Compound 1]:[Compound 1 maxFlux];[Compound 2]:[Compound 2 maxFlux]"
    inputBinding:
      position: 101
      prefix: --manual.flux
  - id: output_file
    type:
      - 'null'
      - string
    doc: "File name for medium table in csv format (default: model file name with -medium.csv)"
    inputBinding:
      position: 101
      prefix: --output.file
  - id: output_dir
    type:
      - 'null'
      - string
    doc: "Path to directory, where output files will be saved (default: current directory)"
    inputBinding:
      position: 101
      prefix: --output.dir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: medium_table
    type:
      type: array
      items: File
    doc: "Predicted medium table in csv format"
    outputBinding:
      glob: "*.csv"
  - id: output_dir_dir
    type:
      - 'null'
      - Directory
    doc: "Output directory when output_dir is given"
    outputBinding:
      glob: $(inputs.output_dir)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - '${ if (inputs.output_dir) { return [{class: "Directory", basename: inputs.output_dir, listing: [], writable: true}]; } else { return []; } }'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_medium.out
