cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - gapseq
  - fill
label: gapseq_fill
doc: "Gap filling of a model.

Tool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: model
    type: File
    doc: "gapseq-Draft-Model to be gapfilled (RDS or SBML)"
    inputBinding:
      position: 101
      prefix: --model
  - id: media
    type: File
    doc: "Tab- or comma separated table for media components. Requires three named columns: compounds (metabolite IDs), name (metabolite name), maxFlux (maximum inflow flux)"
    inputBinding:
      position: 101
      prefix: --media
  - id: target_metabolite
    type:
      - 'null'
      - string
    doc: "ID (without compartment suffix) of metabolite that shall be produced (default: cpd11416, biomass)"
    inputBinding:
      position: 101
      prefix: --target.metabolite
  - id: rxn_weights_file
    type: File
    doc: "Reaction weights table generated by gapseq draft (RDS format)"
    inputBinding:
      position: 101
      prefix: --rxn.weights.file
  - id: rxnxgene_table
    type: File
    doc: "Table with gene-X-reaction associations as generated by gapseq draft (RDS format)"
    inputBinding:
      position: 101
      prefix: --rxnXgene.table
  - id: bcore
    type:
      - 'null'
      - float
    doc: "Minimum bitscore for reaction associated blast hits to consider reactions as core/candidate reactions (default: 50)"
    inputBinding:
      position: 101
      prefix: --bcore
  - id: output_dir
    type:
      - 'null'
      - string
    doc: "Path to directory, where output files will be saved (default: current directory)"
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: depr_output_dir
    type:
      - 'null'
      - string
    doc: "Deprecated, use output_dir"
    inputBinding:
      position: 101
      prefix: --depr.output.dir
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: "Do not save gapfilled model as sbml file (default: save as SBML)"
    inputBinding:
      position: 101
      prefix: --sbml.no.output
  - id: quick_gf
    type:
      - 'null'
      - boolean
    doc: "Perform only step 1 and 2 (default: false)"
    inputBinding:
      position: 101
      prefix: --quick.gf
  - id: limit
    type:
      - 'null'
      - string
    doc: "Test metabolite to which search is limited"
    inputBinding:
      position: 101
      prefix: --limit
  - id: no_core
    type:
      - 'null'
      - boolean
    doc: "Use always all reactions instead of core reactions, which have sequence evidence (default: false)"
    inputBinding:
      position: 101
      prefix: --no.core
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Verbose output and printing of debug messages (default: false)"
    inputBinding:
      position: 101
      prefix: --verbose
  - id: relaxed_constraints
    type:
      - 'null'
      - boolean
    doc: "Save final model as unconstrained network, i.e. all exchange reactions are open (default: false)"
    inputBinding:
      position: 101
      prefix: --relaxed.constraints
  - id: environment
    type:
      - 'null'
      - string
    doc: "Adjusting reaction directions according to specific environmental conditions (experimental option)"
    inputBinding:
      position: 101
      prefix: --environment
  - id: write_cs_ferm
    type:
      - 'null'
      - boolean
    doc: "Write a list with found carbon sources and fermentation products"
    inputBinding:
      position: 101
      prefix: --write.cs.ferm
  - id: min_obj_val
    type:
      - 'null'
      - float
    doc: "Minimum growth rate that should be achieved by gap-filling (default: 0.01)"
    inputBinding:
      position: 101
      prefix: --min.obj.val
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: filled_model_files
    type:
      type: array
      items: File
    doc: "Gapfilled model (RDS and SBML) and optional carbon source tables"
    outputBinding:
      glob:
        - "*.RDS"
        - "*.xml"
        - "*.csv"
  - id: output_dir_dir
    type:
      - 'null'
      - Directory
    doc: "Output directory when output_dir is given"
    outputBinding:
      glob: $(inputs.output_dir)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - '${ if (inputs.output_dir) { return [{class: "Directory", basename: inputs.output_dir, listing: [], writable: true}]; } else { return []; } }'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_fill.out
