cwlVersion: v1.2
class: CommandLineTool
baseCommand: adapt.R
label: gapseq_adapt
doc: "Extends a gapseq model by adding or removing reactions/pathways, or by enforcing
  growth/non-growth conditions.\n\nTool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: add
    type:
      - 'null'
      - string
    doc: reactions or pathways that should be added to the model 
      (comma-separated)
    inputBinding:
      position: 101
      prefix: --add
  - id: growth
    type:
      - 'null'
      - string
    doc: compounds for which growth or non-growth should be ensured 
      (cpd00027:TRUE,cpd00017:FALSE)
    inputBinding:
      position: 101
      prefix: --growth
  - id: id
    type:
      - 'null'
      - string
    doc: Model identifier when provides model rds file is a list of many models
    inputBinding:
      position: 101
      prefix: --id
  - id: min_growth
    type:
      - 'null'
      - float
    doc: Set minimum growth rate that should be achieved by gap-filling.
    inputBinding:
      position: 101
      prefix: --min.growth
  - id: model
    type: File
    doc: gapseq model to be extended (RDS or SBML)
    inputBinding:
      position: 101
      prefix: --model
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: 'Path to directory, where output files will be saved (default: current directory)'
    default: current directory
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: remove
    type:
      - 'null'
      - string
    doc: reactions or pathways that should be removed from the model 
      (comma-separated)
    inputBinding:
      position: 101
      prefix: --remove
  - id: rxn_blast_file
    type: File
    doc: Blast-results table generated by gapseq find.
    inputBinding:
      position: 101
      prefix: --rxn.blast.file
  - id: rxn_weights_file
    type:
      - 'null'
      - File
    doc: Reaction weights table generated by gapseq function 
      "generate_GSdraft.R" (RDS format; needed for 'growth' option).
    inputBinding:
      position: 101
      prefix: --rxn.weights.file
  - id: rxnxgene_table
    type:
      - 'null'
      - File
    doc: Table with gene-X-reaction associations as generated by the 
      "generate_GSdraft.R" (RDS format; needed for 'growth; option)
    inputBinding:
      position: 101
      prefix: --rxnXgene.table
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: 'Do not save gapfilled model as sbml file. Default: Save as SBML'
    inputBinding:
      position: 101
      prefix: --sbml.no.output
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: 'Verbose output and printing of debug messages. Default: FALSE'
    default: false
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_adapt.out
