cwlVersion: v1.2
class: CommandLineTool
baseCommand: gf.suite.R
label: gapseq_fill
doc: "Gapfilling suite for metabolic models.\n\nTool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: bcore
    type:
      - 'null'
      - float
    doc: 'Minimum bitscore for reaction associated blast hits to consider reactions
      as core/candidate reactions. Default: 50'
    default: 50.0
    inputBinding:
      position: 101
      prefix: --bcore
  - id: depr_output_dir
    type:
      - 'null'
      - Directory
    doc: deprecated. Use flag"-f" instead
    inputBinding:
      position: 101
      prefix: --depr.output.dir
  - id: environment
    type:
      - 'null'
      - string
    doc: 'Adjusting reaction directions according to specific environmental conditions.
      See documentation for details. CAUTION: experimental option!'
    inputBinding:
      position: 101
      prefix: --environment
  - id: limit
    type:
      - 'null'
      - string
    doc: Test metabolite to which search is limitted
    inputBinding:
      position: 101
      prefix: --limit
  - id: media
    type:
      - 'null'
      - string
    doc: 'tab- or komma separated table for media components. Requires three named
      columns: 1 - "compounds" (for metab. IDs), 2 - "name" (metab. name), 3 - "maxFlux"
      (maximum inflow flux)'
    inputBinding:
      position: 101
      prefix: --media
  - id: min_obj_val
    type:
      - 'null'
      - float
    doc: 'Minimum growth rate that should be achieved by gap-filling. Default: 0.01'
    default: 0.01
    inputBinding:
      position: 101
      prefix: --min.obj.val
  - id: model
    type: File
    doc: gapseq-Draft-Model to be gapfilled (RDS or SBML)
    inputBinding:
      position: 101
      prefix: --model
  - id: no_core
    type:
      - 'null'
      - boolean
    doc: 'Use always all reactions instead of core reactions, which have sequence
      evidence. Default: FALSE'
    default: false
    inputBinding:
      position: 101
      prefix: --no.core
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: 'Path to directory, where output files will be saved (default: current directory)'
    default: current directory
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: quick_gf
    type:
      - 'null'
      - boolean
    doc: 'perform only step 1 and 2. Default: FALSE'
    default: false
    inputBinding:
      position: 101
      prefix: --quick.gf
  - id: relaxed_constraints
    type:
      - 'null'
      - boolean
    doc: 'Save final model as unconstraint network (i.e. all exchange reactions are
      open). Default: FALSE'
    default: false
    inputBinding:
      position: 101
      prefix: --relaxed.constraints
  - id: rxn_weights_file
    type:
      - 'null'
      - File
    doc: Reaction weights table generated by gapseq function 
      "generate_GSdraft.R" (RDS format).
    inputBinding:
      position: 101
      prefix: --rxn.weights.file
  - id: rxnxgene_table
    type:
      - 'null'
      - File
    doc: Table with gene-X-reaction associations as generated by the 
      "generate_GSdraft.R" (RDS format)
    inputBinding:
      position: 101
      prefix: --rxnXgene.table
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: 'Do not save gapfilled model as sbml file. Default: Save as SBML'
    inputBinding:
      position: 101
      prefix: --sbml.no.output
  - id: target_metabolite
    type:
      - 'null'
      - string
    doc: 'ID (without compartment suffix) of metabolite that shall be produced. Default:
      cpd11416 (Biomass)'
    default: cpd11416
    inputBinding:
      position: 101
      prefix: --target.metabolite
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: 'Verbose output and printing of debug messages. Default: FALSE'
    default: false
    inputBinding:
      position: 101
      prefix: --verbose
  - id: write_cs_ferm
    type:
      - 'null'
      - boolean
    doc: Write a list with found carbon sources and fermentation products
    inputBinding:
      position: 101
      prefix: --write.cs.ferm
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_fill.out
