cwlVersion: v1.2
class: CommandLineTool
baseCommand: /usr/local/share/gapseq/src/pan-draft.R
label: gapseq_pan
doc: "Reconstructs a pan-Model from a list of gapseq-Draft-Models.\n\nTool homepage:
  https://github.com/jotech/gapseq"
inputs:
  - id: min_rxn_freq_in_mods
    type:
      - 'null'
      - float
    doc: minimum reaction frequency (mrf) to include the reactions in the 
      pan-Draft.
    default: 0.06
    inputBinding:
      position: 101
      prefix: --min.rxn.freq.in.mods
  - id: models_path
    type:
      - 'null'
      - type: array
        items: File
    doc: list of filepaths (comma separated) to gapseq-Draft-Models (RDS format)
      to reconstruct the pan-Model; Input can also be provided using wildcards 
      or path to a directory
    inputBinding:
      position: 101
      prefix: --models_path
  - id: only_binary_rxn_tbl
    type:
      - 'null'
      - boolean
    doc: perform only models comparison to get a binary table summarizing rxn 
      presence/absence.
    default: false
    inputBinding:
      position: 101
      prefix: --only.binary.rxn.tbl
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: path to directory, where output files will be saved
    default: current directory
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: pathways_table_path
    type:
      - 'null'
      - type: array
        items: File
    doc: list of paths to all-Pathways tables as generated by the 
      "gapseq_find.sh" (tbl format)
    inputBinding:
      position: 101
      prefix: --pathways.table.path
  - id: rxn_weights_files_path
    type:
      - 'null'
      - type: array
        items: File
    doc: list of filepaths (comma separated) to reaction weight tables generated
      by gapseq function "generate_GSdraft.R" (RDS format); Input can also be 
      provided using wildcards or path to a directory
    inputBinding:
      position: 101
      prefix: --rxn.weights.files_path
  - id: rxnxgene_tables_path
    type:
      - 'null'
      - type: array
        items: File
    doc: list of paths to tables with gene-X-reaction associations as generated 
      by the "generate_GSdraft.R" (RDS format); Input can also be provided using
      wildcards or path to a directory
    inputBinding:
      position: 101
      prefix: --rxnXgene.tables_path
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: Do not save model as sbml file.
    default: Save as SBML
    inputBinding:
      position: 101
      prefix: --sbml.no.output
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_pan.out
