cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - gapseq
  - adapt
label: gapseq_adapt
doc: "Add or remove reactions or pathways.

Tool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: model
    type: File
    doc: "gapseq model to be extended (RDS or SBML)"
    inputBinding:
      position: 101
      prefix: --model
  - id: id
    type:
      - 'null'
      - string
    doc: "Model identifier when the provided model rds file is a list of many models"
    inputBinding:
      position: 101
      prefix: --id
  - id: add
    type:
      - 'null'
      - string
    doc: "Reactions or pathways that should be added to the model (comma-separated)"
    inputBinding:
      position: 101
      prefix: --add
  - id: remove
    type:
      - 'null'
      - string
    doc: "Reactions or pathways that should be removed from the model (comma-separated)"
    inputBinding:
      position: 101
      prefix: --remove
  - id: growth
    type:
      - 'null'
      - string
    doc: "Compounds for which growth or non-growth should be ensured (cpd00027:TRUE,cpd00017:FALSE)"
    inputBinding:
      position: 101
      prefix: --growth
  - id: rxn_weights_file
    type:
      - 'null'
      - File
    doc: "Reaction weights table generated by gapseq draft (RDS format; needed for the growth option)"
    inputBinding:
      position: 101
      prefix: --rxn.weights.file
  - id: rxnxgene_table
    type:
      - 'null'
      - File
    doc: "Table with gene-X-reaction associations as generated by gapseq draft (RDS format; needed for the growth option)"
    inputBinding:
      position: 101
      prefix: --rxnXgene.table
  - id: rxn_blast_file
    type:
      - 'null'
      - File
    doc: "Blast-results table generated by gapseq find"
    inputBinding:
      position: 101
      prefix: --rxn.blast.file
  - id: output_dir
    type:
      - 'null'
      - string
    doc: "Path to directory, where output files will be saved (default: current directory)"
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: min_growth
    type:
      - 'null'
      - float
    doc: "Minimum growth rate that should be achieved by gap-filling"
    inputBinding:
      position: 101
      prefix: --min.growth
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: "Do not save gapfilled model as sbml file (default: save as SBML)"
    inputBinding:
      position: 101
      prefix: --sbml.no.output
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Verbose output and printing of debug messages (default: false)"
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: adapted_model_files
    type:
      type: array
      items: File
    doc: "Adapted model (RDS and SBML)"
    outputBinding:
      glob:
        - "*.RDS"
        - "*.xml"
  - id: output_dir_dir
    type:
      - 'null'
      - Directory
    doc: "Output directory when output_dir is given"
    outputBinding:
      glob: $(inputs.output_dir)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - '${ if (inputs.output_dir) { return [{class: "Directory", basename: inputs.output_dir, listing: [], writable: true}]; } else { return []; } }'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_adapt.out
