cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - gapseq
  - draft
label: gapseq_draft
doc: "Draft model construction based on results from find and find-transport.

Tool homepage: https://github.com/jotech/gapseq"
inputs:
  - id: blast_res
    type: File
    doc: "Blast-results table generated by gapseq find"
    inputBinding:
      position: 101
      prefix: --blast.res
  - id: transporter_res
    type:
      - 'null'
      - File
    doc: "Blast-results table generated by gapseq find-transport"
    inputBinding:
      position: 101
      prefix: --transporter.res
  - id: biomass
    type:
      - 'null'
      - string
    doc: "Biomass reaction for network model. Options: Gram pos OR neg OR archaea OR auto OR path to user-defined biomass reaction (default: auto)"
    inputBinding:
      position: 101
      prefix: --biomass
  - id: model_name
    type:
      - 'null'
      - string
    doc: "Name of draft model network (default: the basename of blast_res)"
    inputBinding:
      position: 101
      prefix: --model.name
  - id: genome_seq
    type:
      - 'null'
      - File
    doc: "If biomass is auto, the genome sequence is required to predict the prokaryotic biomass reaction"
    inputBinding:
      position: 101
      prefix: --genome.seq
  - id: high_evi_rxn_bs
    type:
      - 'null'
      - int
    doc: "Reactions with an associated blast-hit with a bitscore above this value are added as core reactions (default: 200)"
    inputBinding:
      position: 101
      prefix: --high.evi.rxn.BS
  - id: min_bs_for_core
    type:
      - 'null'
      - int
    doc: "Reactions with an associated blast-hit with a bitscore below this value are considered as reactions that have no blast hit (default: 50)"
    inputBinding:
      position: 101
      prefix: --min.bs.for.core
  - id: output_dir
    type:
      - 'null'
      - string
    doc: "Path to directory, where output files will be saved (default: current directory)"
    inputBinding:
      position: 101
      prefix: --output.dir
  - id: depr_output_dir
    type:
      - 'null'
      - string
    doc: "Deprecated, use output_dir"
    inputBinding:
      position: 101
      prefix: --depr.output.dir
  - id: sbml_no_output
    type:
      - 'null'
      - boolean
    doc: "Do not save draft model as sbml file (default: save as SBML)"
    inputBinding:
      position: 101
      prefix: --sbml.no.output
  - id: pathway_pred
    type:
      - 'null'
      - File
    doc: "Pathway-results table generated by gapseq find"
    inputBinding:
      position: 101
      prefix: --pathway.pred
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: draft_files
    type:
      type: array
      items: File
    doc: "Draft model (RDS and SBML), reaction weights and reaction-gene tables"
    outputBinding:
      glob:
        - "*-draft.RDS"
        - "*-draft.xml"
        - "*-rxnWeights.RDS"
        - "*-rxnXgenes.RDS"
  - id: output_dir_dir
    type:
      - 'null'
      - Directory
    doc: "Output directory when output_dir is given"
    outputBinding:
      glob: $(inputs.output_dir)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - '${ if (inputs.output_dir) { return [{class: "Directory", basename: inputs.output_dir, listing: [], writable: true}]; } else { return []; } }'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gapseq:1.4.0--h9ee0642_1
stdout: gapseq_draft.out
