cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - allhic
  - alleles
label: allhic_alleles
doc: "Identify and classify allelic contigs from a PAF file to be used for 'allhic
  prune'. Generates 'alleles.table'.\n\nTool homepage: https://github.com/tanghaibao/allhic"
inputs:
  - id: paf_file
    type: File
    doc: PAF file containing self-alignments (e.g., generated by minimap2)
    inputBinding:
      position: 1
  - id: counts_re_file
    type: File
    doc: Restriction enzyme counts file (e.g., genome.counts_RE.txt)
    inputBinding:
      position: 2
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/allhic:0.9.14--he881be0_0
stdout: allhic_alleles.out
