cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit merge
label: tadbit_merge
doc: "load two working directories with different Hi-C data samples and merges them
  into a new working directory generating some statistics\n\nTool homepage: http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: bam1
    type:
      - 'null'
      - File
    doc: path to the first TADbit-generated BAM file with all reads (other wise 
      the tool will guess from the working directory database)
    inputBinding:
      position: 101
      prefix: --bam1
  - id: bam2
    type:
      - 'null'
      - File
    doc: path to the second TADbit-generated BAM file with all reads (other wise
      the tool will guess from the working directory database)
    inputBinding:
      position: 101
      prefix: --bam2
  - id: biases1
    type:
      - 'null'
      - File
    doc: path to file with precalculated biases by columns
    inputBinding:
      position: 101
      prefix: --biases1
  - id: biases2
    type:
      - 'null'
      - File
    doc: path to file with precalculated biases by columns
    inputBinding:
      position: 101
      prefix: --biases2
  - id: cpus
    type:
      - 'null'
      - int
    doc: Maximum number of CPU cores available in the execution host. If higher 
      than 1, tasks with multi-threading capabilities will enabled (if 0 all 
      available) cores will be used
    inputBinding:
      position: 101
      prefix: --cpus
  - id: filter
    type:
      - 'null'
      - type: array
        items: int
    doc: "[[1, 2, 3, 4, 6, 7, 9, 10]] Use filters to define a set os valid pair of
      reads e.g.: '--apply 1 2 3 4 8 9 10'. Where these numbers correspond to: 1:
      self-circle, 2: dangling-end, 3: error, 4: extra dangling-end, 5: too close
      from RES, 6: too short, 7: too large, 8: over-represented, 9: duplicated, 10:
      random breaks, 11: trans-chromosomic"
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    inputBinding:
      position: 101
      prefix: --filter
  - id: force
    type:
      - 'null'
      - boolean
    doc: overwrite previously run job
    inputBinding:
      position: 101
      prefix: --force
  - id: jobid1
    type:
      - 'null'
      - int
    doc: Use as input data generated by a job with a given jobid. Use tadbit 
      describe to find out which.
    inputBinding:
      position: 101
      prefix: --jobid1
  - id: jobid2
    type:
      - 'null'
      - int
    doc: Use as input data generated by a job with a given jobid. Use tadbit 
      describe to find out which.
    inputBinding:
      position: 101
      prefix: --jobid2
  - id: no_x_display
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: norm
    type:
      - 'null'
      - boolean
    doc: compare normalized matrices
    inputBinding:
      position: 101
      prefix: --norm
  - id: output_folder
    type: Directory
    doc: path to a new output folder
    inputBinding:
      position: 101
      prefix: --workdir
  - id: resolution
    type:
      - 'null'
      - int
    doc: resolution at which to do the comparison, and generate the matrices.
    inputBinding:
      position: 101
      prefix: --resolution
  - id: samtools_path
    type:
      - 'null'
      - File
    doc: path samtools binary
    inputBinding:
      position: 101
      prefix: --samtools
  - id: save
    type:
      - 'null'
      - type: array
        items: string
    doc: save genomic or chromosomic matrix.
    inputBinding:
      position: 101
      prefix: --save
  - id: skip_comparison
    type:
      - 'null'
      - boolean
    doc: skip the comparison between replicates (faster). Comparisons are 
      performed at 3 levels 1- comparing first diagonals of each experiment (and
      generating SCC score and standard deviation see 
      https://doi.org/10.1101/gr.220640.117) 2- Comparing the first eigenvectors
      of input experiments 3- Generates reproducibility score using function 
      from https://doi.org/10.1093/bioinformatics/btx152
    inputBinding:
      position: 101
      prefix: --skip_comparison
  - id: skip_merge
    type:
      - 'null'
      - boolean
    doc: skip the merge of replicates (faster).
    inputBinding:
      position: 101
      prefix: --skip_merge
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: workdir1
    type: Directory
    doc: path to working directory of the first HiC data sample to merge
    inputBinding:
      position: 101
      prefix: --workdir1
  - id: workdir2
    type: Directory
    doc: path to working directory of the second HiC data sample to merge
    inputBinding:
      position: 101
      prefix: --workdir2
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_merge.out
