cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit parse
label: tadbit_parse
doc: "Parse mapped Hi-C reads and get the intersection\n\nTool homepage: http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: compress_input
    type:
      - 'null'
      - boolean
    doc: Compress input mapped files when parsing is done. This is done in 
      background, while next MAP file is processed, or while reads are sorted.
    inputBinding:
      position: 101
      prefix: --compress_input
  - id: filter_chrom
    type:
      - 'null'
      - string
    doc: regexp to consider only chromosome names passing
    default: '"^(chr)?[A-Za-z]?[0-9]{0,3}[XVI]{0,3}(?:ito)?[A-Z-a-z]?(_dna)?$"'
    inputBinding:
      position: 101
      prefix: --filter_chrom
  - id: genome
    type:
      - 'null'
      - type: array
        items: File
    doc: 'paths to file(s) with FASTA files of the reference genome. If many, files
      will be concatenated. I.e.: --genome chr_1.fa chr_2.fa In this last case, order
      is important or the rest of the analysis. Note: it can also be the path to a
      previously parsed genome in pickle format.'
    inputBinding:
      position: 101
      prefix: --genome
  - id: jobids
    type:
      - 'null'
      - type: array
        items: int
    doc: Use as input data generated by a job with a given jobid(s). Use tadbit 
      describe to find out which. In this case one jobid can be passed per read.
    inputBinding:
      position: 101
      prefix: --jobids
  - id: mapped1
    type:
      - 'null'
      - type: array
        items: File
    doc: paths to mapped bam files (first read-end)
    inputBinding:
      position: 101
      prefix: --mapped1
  - id: mapped2
    type:
      - 'null'
      - type: array
        items: File
    doc: paths to mapped bam files (second read-end)
    inputBinding:
      position: 101
      prefix: --mapped2
  - id: noX
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: read
    type:
      - 'null'
      - int
    doc: In case only one of the reads needs to be parsed
    inputBinding:
      position: 101
      prefix: --read
  - id: restriction_enzyme
    type:
      - 'null'
      - string
    doc: restriction enzyme name
    inputBinding:
      position: 101
      prefix: --renz
  - id: skip
    type:
      - 'null'
      - boolean
    doc: '[DEBUG] in case already mapped.'
    inputBinding:
      position: 101
      prefix: --skip
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: type
    type:
      - 'null'
      - string
    doc: '[map]file type to be parser, MAP (GEM-mapper), SAM or BAM'
    inputBinding:
      position: 101
      prefix: --type
  - id: working_directory
    type:
      - 'null'
      - Directory
    doc: path to working directory (generated with the tool tadbit mapper)
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_parse.out
