cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit filter
label: tadbit_filter
doc: "Filter parsed Hi-C reads and get valid pair of reads to work with\n\nTool homepage:
  http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: apply
    type:
      - 'null'
      - type: array
        items: int
    doc: "[[1, 2, 3, 4, 6, 7, 9, 10]] Use filters to define a set os valid pair of
      reads e.g.: '--apply 1 2 3 4 6 7 8 9'. Where these numbers correspond to: 1:
      self-circle, 2: dangling-end, 3: error, 4: extra dangling-end, 5: too close
      from RES, 6: too short, 7: too large, 8: over-represented, 9: duplicated, 10:
      random breaks"
    default:
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    inputBinding:
      position: 101
      prefix: --apply
  - id: clean
    type:
      - 'null'
      - boolean
    doc: 'remove intermediate files. WARNING: together with format "short" or valid
      options, this may results in losing data'
    inputBinding:
      position: 101
      prefix: --clean
  - id: compress_input
    type:
      - 'null'
      - boolean
    doc: Compress input mapped files when parsing is done. This is done in 
      background, while next MAP file is processed, or while reads are sorted.
    inputBinding:
      position: 101
      prefix: --compress_input
  - id: cpus
    type:
      - 'null'
      - int
    doc: Maximum number of CPU cores available in the execution host. If higher 
      than 1, tasks with multi-threading capabilities will enabled (if 0 all 
      available) cores will be used
    default: 20
    inputBinding:
      position: 101
      prefix: --cpus
  - id: force
    type:
      - 'null'
      - boolean
    doc: overwrite previously run job
    inputBinding:
      position: 101
      prefix: --force
  - id: format
    type:
      - 'null'
      - string
    doc: for compression into pseudo-BAM format. Short contains only positions 
      of reads mapped, mid everything but restriction sites.
    default: mid
    inputBinding:
      position: 101
      prefix: --format
  - id: max_frag_size
    type:
      - 'null'
      - int
    doc: to exclude large genomic RE fragments (probably resulting from gaps in 
      the reference genome)
    default: 100000
    inputBinding:
      position: 101
      prefix: --max_frag_size
  - id: min_frag_size
    type:
      - 'null'
      - int
    doc: to exclude small genomic RE fragments (smaller than sequenced reads)
    default: 50
    inputBinding:
      position: 101
      prefix: --min_frag_size
  - id: no_x
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: over_represented
    type:
      - 'null'
      - float
    doc: percentage of restriction-enzyme (RE) genomic fragments with more 
      coverage to exclude (possible PCR artifact).
    default: 0.001%
    inputBinding:
      position: 101
      prefix: --over_represented
  - id: pathids
    type:
      - 'null'
      - type: array
        items: int
    doc: Use as input data generated by a job under a given pathids. Use tadbit 
      describe to find out which. To filter an intersected file produced with 
      tadbit map --fast_fragment only one PATHid is needed otherwise one per 
      read is needed, first for read 1, second for read 2.
    inputBinding:
      position: 101
      prefix: --pathids
  - id: re_proximity
    type:
      - 'null'
      - int
    doc: to exclude read-ends falling too close from RE site 
      (pseudo-dangling-ends)
    default: 5
    inputBinding:
      position: 101
      prefix: --re_proximity
  - id: resume
    type:
      - 'null'
      - boolean
    doc: use filters of previously run job
    inputBinding:
      position: 101
      prefix: --resume
  - id: samtools
    type:
      - 'null'
      - File
    doc: path samtools binary
    inputBinding:
      position: 101
      prefix: --samtools
  - id: strict_duplicates
    type:
      - 'null'
      - boolean
    doc: 'by default reads are considered duplicates if they coincide in genomic coordinates
      and strand; with strict_duplicates enabled, we also ask to consider read length
      (WARNING: this option is called strict, but it is more permissive)'
    inputBinding:
      position: 101
      prefix: --strict_duplicates
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: valid
    type:
      - 'null'
      - boolean
    doc: stores only valid-pairs discards filtered out reads.
    inputBinding:
      position: 101
      prefix: --valid
  - id: workdir
    type:
      - 'null'
      - Directory
    doc: path to working directory (generated with the tool tadbit mapper)
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_filter.out
