cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit bin
label: tadbit_bin
doc: "bin Hi-C data into matrices\n\nTool homepage: http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: bad_color
    type:
      - 'null'
      - string
    doc: Matplotlib color to use on bins filtered out (only used with normalized
      matrices, not raw).
    default: white
    inputBinding:
      position: 101
      prefix: --bad_color
  - id: bam_file
    type:
      - 'null'
      - File
    doc: path to a TADbit-generated BAM file with all reads (other wise the tool
      will guess from the working directory database)
    inputBinding:
      position: 101
      prefix: --bam
  - id: biases
    type:
      - 'null'
      - File
    doc: path to file with pre-calculated biases by columns
    inputBinding:
      position: 101
      prefix: --biases
  - id: chr_name
    type:
      - 'null'
      - type: array
        items: string
    doc: chromosome name(s). Order of chromosomes in the output matrices.
    inputBinding:
      position: 101
      prefix: --chr_name
  - id: cmap
    type:
      - 'null'
      - string
    doc: Matplotlib color map to use.
    default: viridis
    inputBinding:
      position: 101
      prefix: --cmap
  - id: coord
    type:
      - 'null'
      - string
    doc: 'Coordinate of the region to retrieve. By default all genome, arguments can
      be either one chromosome name, or the coordinate in the form: "-c chr3:110000000-120000000"'
    inputBinding:
      position: 101
      prefix: -c
  - id: coord2
    type:
      - 'null'
      - string
    doc: Coordinate of a second region to retrieve the matrix in the 
      intersection with the first region.
    inputBinding:
      position: 101
      prefix: -c2
  - id: cpus
    type:
      - 'null'
      - int
    doc: Maximum number of CPU cores available in the execution host. If higher 
      than 1, tasks with multi-threading capabilities will enabled (if 0 all 
      available) cores will be used
    default: 20
    inputBinding:
      position: 101
      prefix: --cpus
  - id: figsize
    type:
      - 'null'
      - string
    doc: 'Range, in log2 scale of the color scale. default for triangular matrices:
      --figsize=16,10 and for square matrices: --figsize=16,14'
    inputBinding:
      position: 101
      prefix: --figsize
  - id: filter
    type:
      - 'null'
      - type: array
        items: int
    doc: "[[1, 2, 3, 4, 6, 7, 9, 10]] Use filters to define a set os valid pair of
      reads e.g.: '--apply 1 2 3 4 8 9 10'. Where these numbers correspond to: 0:
      nothing, 1: self-circle, 2: dangling-end, 3: error, 4: extra dangling-end, 5:
      too close from RES, 6: too short, 7: too large, 8: over-represented, 9: duplicated,
      10: random breaks, 11: trans-chromosomic"
    default:
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    inputBinding:
      position: 101
      prefix: --filter
  - id: force
    type:
      - 'null'
      - boolean
    doc: overwrite previously run job
    inputBinding:
      position: 101
      prefix: --force
  - id: force_plot
    type:
      - 'null'
      - boolean
    doc: Force plotting even with demoniacally big matrices (more than 
      5000x5000, or 1500x1500with interactive option).
    inputBinding:
      position: 101
      prefix: --force_plot
  - id: format
    type:
      - 'null'
      - string
    doc: plot file format.
    default: png
    inputBinding:
      position: 101
      prefix: --format
  - id: interactive
    type:
      - 'null'
      - boolean
    doc: Open matplotlib interactive plot (nothing will be saved).
    default: false
    inputBinding:
      position: 101
      prefix: --interactive
  - id: jobid
    type:
      - 'null'
      - int
    doc: Use as input data generated by a job with a given jobid. Use tadbit 
      describe to find out which.
    inputBinding:
      position: 101
      prefix: --jobid
  - id: nchunks
    type:
      - 'null'
      - int
    doc: maximum number of chunks into which to cut the BAM
    inputBinding:
      position: 101
      prefix: --nchunks
  - id: no_display_server
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: norm
    type:
      - 'null'
      - type: array
        items: string
    doc: "[['raw']] normalization(s) to apply. Choices are: [norm, decay, raw, raw&decay]"
    default:
      - raw
    inputBinding:
      position: 101
      prefix: --norm
  - id: only_plot_matrix
    type:
      - 'null'
      - boolean
    doc: Skip writing matrix in text format.
    default: false
    inputBinding:
      position: 101
      prefix: --only_plot
  - id: only_txt
    type:
      - 'null'
      - boolean
    doc: Save only text file for matrices, not images
    inputBinding:
      position: 101
      prefix: --only_txt
  - id: plot
    type:
      - 'null'
      - boolean
    doc: Plot matrix in desired format.
    inputBinding:
      position: 101
      prefix: --plot
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: remove all messages
    inputBinding:
      position: 101
      prefix: --quiet
  - id: resolution
    type: int
    doc: resolution at which to output matrices
    inputBinding:
      position: 101
      prefix: --resolution
  - id: rownames
    type:
      - 'null'
      - boolean
    doc: 'To store row names in the output text matrix. WARNING: when non- matrix,
      results in two extra columns'
    inputBinding:
      position: 101
      prefix: --rownames
  - id: tad_def
    type:
      - 'null'
      - File
    doc: 'tsv file with tad definition, columns: # start end score density'
    inputBinding:
      position: 101
      prefix: --tad_def
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: transform
    type:
      - 'null'
      - string
    doc: can be any of [log2, log, none]
    default: log2
    inputBinding:
      position: 101
      prefix: --transform
  - id: triangular
    type:
      - 'null'
      - boolean
    doc: represents only half matrix. Note that this also results in truly 
      vectorial images of matrix.
    default: false
    inputBinding:
      position: 101
      prefix: --triangular
  - id: working_dir
    type: Directory
    doc: path to working directory (generated with the tool tadbit mapper)
    inputBinding:
      position: 101
      prefix: --workdir
  - id: write_cooler
    type:
      - 'null'
      - boolean
    doc: Write i,j,v matrix in cooler format instead of text.
    inputBinding:
      position: 101
      prefix: --cooler
  - id: write_matrix
    type:
      - 'null'
      - boolean
    doc: Write text matrix in multiple columns (square). By defaults matrices 
      are written in BED-like format (also only way to get a raw matrix with all
      values including the ones in masked columns).
    inputBinding:
      position: 101
      prefix: --matrix
  - id: xtick_rotation
    type:
      - 'null'
      - float
    doc: x-tick rotation
    default: -25
    inputBinding:
      position: 101
      prefix: --xtick_rotation
  - id: zrange
    type:
      - 'null'
      - string
    doc: 'Range, in log2 scale of the color scale. i.e.: --zrange=-2,2'
    inputBinding:
      position: 101
      prefix: --zrange
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_bin.out
