cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit segment
label: tadbit_segment
doc: "Finds TAD or compartment segmentation in Hi-C data.\n\nTool homepage: http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: all_bins
    type:
      - 'null'
      - boolean
    doc: skip the filtering of bins for detection of TADs
    inputBinding:
      position: 101
      prefix: --all_bins
  - id: biases
    type:
      - 'null'
      - File
    doc: path to file with precalculated biases by columns
    inputBinding:
      position: 101
      prefix: --biases
  - id: chromosomes
    type:
      - 'null'
      - type: array
        items: string
    doc: Name of the chromosomes on which to search for TADs or compartments.
    inputBinding:
      position: 101
      prefix: --chromosomes
  - id: cpu
    type:
      - 'null'
      - int
    doc: '[20] Maximum number of CPU cores available in the execution host. If higher
      than 1, tasks with multi-threading capabilities will enabled (if 0 all available)
      cores will be used'
    default: 20
    inputBinding:
      position: 101
      prefix: --cpu
  - id: ev_index
    type:
      - 'null'
      - type: array
        items: int
    doc: "list of indexes of eigenvectors capturing compartments signal (one index
      per chromosome, in the same order as chromosomes in fasta file). Example picking
      the first eigenvector for all chromosomes but for chromosome 3: '--ev_index
      1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'"
    inputBinding:
      position: 101
      prefix: --ev_index
  - id: fasta
    type:
      - 'null'
      - File
    doc: Path to fasta file with genome sequence, to compute GC content and use 
      it to label compartments
    inputBinding:
      position: 101
      prefix: --fasta
  - id: filter
    type:
      - 'null'
      - type: array
        items: int
    doc: "[[1, 2, 3, 4, 6, 7, 9, 10]] Use filters to define a set os valid pair of
      reads e.g.: '--apply 1 2 3 4 8 9 10'. Where these numberscorrespond to: 1: self-circle,
      2: dangling-end, 3: error, 4: extra dangling-end, 5: too close from RES, 6:
      too short, 7: too large, 8: over-represented, 9: duplicated, 10: random breaks,
      11: trans-chromosomic"
    default:
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    inputBinding:
      position: 101
      prefix: --filter
  - id: fix_corr_scale
    type:
      - 'null'
      - boolean
    doc: Correlation matrix plot scaled between correlation 1 and -1 instead of 
      maximum observed values.
    inputBinding:
      position: 101
      prefix: --fix_corr_scale
  - id: force
    type:
      - 'null'
      - boolean
    doc: overwrite previously run job
    inputBinding:
      position: 101
      prefix: --force
  - id: format
    type:
      - 'null'
      - string
    doc: file format for figures
    default: png
    inputBinding:
      position: 101
      prefix: --format
  - id: jobid
    type:
      - 'null'
      - int
    doc: Use as input data generated by a job with a given jobid. Use tadbit 
      describe to find out which.
    inputBinding:
      position: 101
      prefix: --jobid
  - id: max_tad_size
    type:
      - 'null'
      - int
    doc: an integer defining the maximum size of TAD. Default defines it as the 
      number of rows/columns
    inputBinding:
      position: 101
      prefix: --max_tad_size
  - id: mreads
    type:
      - 'null'
      - File
    doc: path valid-pairs file (TADbit BAM format)
    inputBinding:
      position: 101
      prefix: --mreads
  - id: n_evs
    type:
      - 'null'
      - int
    doc: Number of eigenvectors to store. if "-1" all eigenvectors will be 
      calculated
    default: 3
    inputBinding:
      position: 101
      prefix: --n_evs
  - id: noX
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: norm_matrix
    type:
      - 'null'
      - File
    doc: path to a matrix file with normalized read counts
    inputBinding:
      position: 101
      prefix: --norm_matrix
  - id: nosql
    type:
      - 'null'
      - boolean
    doc: do not load/store data from/in sqlite database
    inputBinding:
      position: 101
      prefix: --nosql
  - id: only_compartments
    type:
      - 'null'
      - boolean
    doc: search A/B compartments using first eigen vector of the correlation 
      matrix
    inputBinding:
      position: 101
      prefix: --only_compartments
  - id: only_tads
    type:
      - 'null'
      - boolean
    doc: search TAD boundaries break-point detection algorithm
    inputBinding:
      position: 101
      prefix: --only_tads
  - id: raw_matrix
    type:
      - 'null'
      - File
    doc: path to a matrix file with raw read counts
    inputBinding:
      position: 101
      prefix: --raw_matrix
  - id: resolution
    type: int
    doc: resolution at which to output matrices
    inputBinding:
      position: 101
      prefix: --resolution
  - id: rich_in_a
    type:
      - 'null'
      - File
    doc: path to a BED or bedGraph file with list of protein coding gene or 
      other active epigenetic mark, to be used to label compartments instead of 
      using the relative interaction count.
    inputBinding:
      position: 101
      prefix: --rich_in_A
  - id: savecorr
    type:
      - 'null'
      - boolean
    doc: Save correlation matrix used to predict compartments.
    inputBinding:
      position: 101
      prefix: --savecorr
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: print more messages
    inputBinding:
      position: 101
      prefix: --verbose
  - id: workdir
    type: Directory
    doc: path to working directory (generated with the tool tadbit mapper)
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_segment.out
