cwlVersion: v1.2
class: CommandLineTool
baseCommand: tadbit normalize
label: tadbit_normalize
doc: "normalize Hi-C data and generates array of biases\n\nTool homepage: http://sgt.cnag.cat/3dg/tadbit/"
inputs:
  - id: badcols
    type:
      - 'null'
      - type: array
        items: string
    doc: 'extra regions to be added to bad-columns (ingenomic position). e.g.: --badcols
      1:150000000-160000000 2:1200000-1300000'
    inputBinding:
      position: 101
      prefix: --badcols
  - id: bam_file
    type:
      - 'null'
      - File
    doc: path to a TADbit-generated BAM file with all reads (other wise the tool
      will guess from the working directory database)
    inputBinding:
      position: 101
      prefix: --bam
  - id: biases_path
    type:
      - 'null'
      - File
    doc: 'biases file to compute decay. REQUIRED with "custom" normalization. Format:
      single column with header'
    inputBinding:
      position: 101
      prefix: --biases_path
  - id: cpus
    type:
      - 'null'
      - int
    doc: Maximum number of CPU cores available in the execution host. If higher 
      than 1, tasks with multi-threading capabilities will enabled (if 0 all 
      available) cores will be used
    inputBinding:
      position: 101
      prefix: --cpus
  - id: factor
    type:
      - 'null'
      - float
    doc: target mean value of a cell after normalization (can be used to weight 
      experiments before merging)
    inputBinding:
      position: 101
      prefix: --factor
  - id: fast_filter
    type:
      - 'null'
      - boolean
    doc: only filter according to the percentage of zero count or minimum count 
      of reads
    inputBinding:
      position: 101
      prefix: --fast_filter
  - id: fasta
    type:
      - 'null'
      - File
    doc: Path to FASTA file with genome sequence, to compute GC content and 
      number of restriction sites per bin. Required for oneD normalization
    inputBinding:
      position: 101
      prefix: --fasta
  - id: filter
    type:
      - 'null'
      - type: array
        items: int
    doc: "[[1, 2, 3, 4, 6, 7, 9, 10]] Use filters to define a set os valid pair of
      reads e.g.: '--apply 1 2 3 4 8 9 10'. Where these numbers correspond to: 1:
      self-circle, 2: dangling-end, 3: error, 4: extra dangling-end, 5: too close
      from RES, 6: too short, 7: too large, 8: over-represented, 9: duplicated, 10:
      random breaks, 11: trans-chromosomic"
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    inputBinding:
      position: 101
      prefix: --filter
  - id: filter_only
    type:
      - 'null'
      - boolean
    doc: skip normalization
    inputBinding:
      position: 101
      prefix: --filter_only
  - id: force
    type:
      - 'null'
      - boolean
    doc: overwrite previously run job
    inputBinding:
      position: 101
      prefix: --force
  - id: jobid
    type:
      - 'null'
      - int
    doc: Use as input data generated by a job with a given jobid. Use tadbit 
      describe to find out which.
    inputBinding:
      position: 101
      prefix: --jobid
  - id: mappability
    type:
      - 'null'
      - File
    doc: 'Path to mappability bedGraph file, required for oneD normalization. Mappability
      file can be generated with GEM (example from the genomic FASTA file hg38.fa):
      gem-indexer -i hg38.fa -o hg38 gem-mappability -I hg38.gem -l 50 -o hg38.50mer
      -T 8 gem-2-wig -I hg38.gem -i hg38.50mer.mappability -o hg38.50mer wigToBigWig
      hg38.50mer.wig hg38.50mer.sizes hg38.50mer.bw bigWigToBedGraph hg38.50mer.bw
      hg38.50mer.bedGraph'
    inputBinding:
      position: 101
      prefix: --mappability
  - id: max_njobs
    type:
      - 'null'
      - int
    doc: Define maximum number of jobs for reading BAM file (set to higher 
      numbers for large files and low RAM memory).
    inputBinding:
      position: 101
      prefix: --max_njobs
  - id: max_perc
    type:
      - 'null'
      - int
    doc: upper percentile until which consider bins as good.
    inputBinding:
      position: 101
      prefix: --max_perc
  - id: min_count
    type:
      - 'null'
      - int
    doc: minimum number of reads mapped to a bin (recommended value could be 
      2500). If set this option overrides the perc_zero filtering... This option
      is slightly slower.
    inputBinding:
      position: 101
      prefix: --min_count
  - id: min_perc
    type:
      - 'null'
      - int
    doc: lower percentile from which consider bins as good.
    inputBinding:
      position: 101
      prefix: --min_perc
  - id: noX
    type:
      - 'null'
      - boolean
    doc: no display server (X screen)
    inputBinding:
      position: 101
      prefix: --noX
  - id: normalization
    type:
      - 'null'
      - string
    doc: 'normalization(s) to apply. Order matters. Choices: Vanilla, ICE, SQRT, oneD,
      custom'
    inputBinding:
      position: 101
      prefix: --normalization
  - id: normalize_only
    type:
      - 'null'
      - boolean
    doc: skip calculation of Cis-percentage and decay
    inputBinding:
      position: 101
      prefix: --normalize_only
  - id: perc_zeros
    type:
      - 'null'
      - float
    doc: maximum percentage of zeroes allowed per column.
    inputBinding:
      position: 101
      prefix: --perc_zeros
  - id: prop_data
    type:
      - 'null'
      - float
    doc: 'Only for oneD normalization: proportion of data to be used in fitting (for
      very large datasets). Number between 0 and 1.'
    inputBinding:
      position: 101
      prefix: --prop_data
  - id: renz
    type:
      - 'null'
      - string
    doc: restriction enzyme name(s). Required for oneD normalization
    inputBinding:
      position: 101
      prefix: --renz
  - id: resolution
    type: int
    doc: resolution at which to output matrices
    inputBinding:
      position: 101
      prefix: --resolution
  - id: seed
    type:
      - 'null'
      - int
    doc: 'Only for oneD normalization: seed number for the random picking of data
      when using the "prop_data" parameter'
    inputBinding:
      position: 101
      prefix: --seed
  - id: tmpdb
    type:
      - 'null'
      - Directory
    doc: if provided uses this directory to manipulate the database
    inputBinding:
      position: 101
      prefix: --tmpdb
  - id: valid
    type:
      - 'null'
      - boolean
    doc: input BAM file contains only valid pairs (already filtered).
    inputBinding:
      position: 101
      prefix: --valid
  - id: workdir
    type: Directory
    doc: path to working directory (generated with the tool tadbit mapper)
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/tadbit:1.0.1--py310h2a84d7f_1
stdout: tadbit_normalize.out
