cwlVersion: v1.2
class: CommandLineTool
baseCommand: ting
label: bio-ting_ting
doc: "TCR analysis tool\n\nTool homepage: https://github.com/FelixMoelder/ting"
inputs:
  - id: gliph_minp
    type:
      - 'null'
      - float
    doc: probability threshold for identifying significant k-mers by gliph test
    inputBinding:
      position: 101
      prefix: --gliph_minp
  - id: kmer_file
    type:
      - 'null'
      - File
    doc: Existing tab separated file holding kmers in first row. When not given,
      ting generates the k-mer file named by kmer_file_name.
  - id: kmer_file_name
    type:
      - 'null'
      - string
    doc: Name of the k-mer file that ting generates when kmer_file is not given
    default: kmers.tsv
  - id: kmers_gliph
    type:
      - 'null'
      - boolean
    doc: If set kmers are identified by the non-deterministic approach as 
      implemented by gliph
    inputBinding:
      position: 101
      prefix: --kmers_gliph
  - id: max_p_value
    type:
      - 'null'
      - float
    doc: p-value threshold for identifying significant k-mers by fisher exact 
      test
    inputBinding:
      position: 101
      prefix: --max_p_value
  - id: no_global
    type:
      - 'null'
      - boolean
    doc: If set global clustering is excluded
    inputBinding:
      position: 101
      prefix: --no_global
  - id: no_local
    type:
      - 'null'
      - boolean
    doc: If set local clustering is excluded
    inputBinding:
      position: 101
      prefix: --no_local
  - id: reference
    type: File
    doc: Reference fasta file of naive CDR3 amino acid sequences used for 
      estimation of significant k-mers.
    inputBinding:
      position: 101
      prefix: --reference
  - id: stringent_filtering
    type:
      - 'null'
      - boolean
    doc: If used only TCRs starting with a cystein and ending with phenylalanine
      will be used
    inputBinding:
      position: 101
      prefix: --stringent_filtering
  - id: tcr_sequences
    type: File
    doc: File holding TCRs
    inputBinding:
      position: 101
      prefix: --tcr_sequences
  - id: use_structural_boundaries
    type:
      - 'null'
      - boolean
    doc: First and last three amino acids are included in processing
    inputBinding:
      position: 101
      prefix: --use_structural_boundaries
  - id: output_path
    type: string
    doc: path of output-file
    inputBinding:
      position: 102
      prefix: --output
arguments:
  - position: 101
    prefix: --kmer_file
    valueFrom: '$(inputs.kmer_file ? inputs.kmer_file.path : inputs.kmer_file_name)'
outputs:
  - id: kmer_table
    type:
      - 'null'
      - File
    doc: K-mer file generated by ting (when kmer_file is not given)
    outputBinding:
      glob: '$(inputs.kmer_file ? [] : inputs.kmer_file_name)'
  - id: output
    type: File
    doc: path of output-file
    outputBinding:
      glob: $(inputs.output_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bio-ting:1.1.0--py_0
