cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - fgbio
  - FilterConsensusReads
label: fgbio_FilterConsensusReads
doc: "Filters consensus reads generated by fgbio.\n\nTool homepage: https://github.com/fulcrumgenomics/fgbio"
inputs: []
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgbio:3.1.1--hdfd78af_0
stdout: fgbio_FilterConsensusReads.out
