cwlVersion: v1.2
class: CommandLineTool
baseCommand: fgbio
label: fgbio_CollectDuplexSeqMetrics
doc: "Collects a suite of metrics to QC duplex sequencing data.\n\nInputs ------\n\
  \nThe input to this tool must be a BAM file that is either:\n\n  1. The exact BAM\
  \ output by the 'GroupReadsByUmi' tool (in the sort-order it was produced in)\n\
  \  2. A BAM file that has MI tags present on all reads (usually set by 'GroupReadsByUmi'\
  \ and has been sorted with\n     'SortBam' into 'TemplateCoordinate' order.\n\n\
  Calculation of metrics may be restricted to a set of regions using the '--intervals'\
  \ parameter. This can significantly affect results as off-target reads in duplex\
  \ sequencing experiments often have very different properties than on-target reads\
  \ due to the lack of enrichment.\n\nSeveral metrics are calculated related to the\
  \ fraction of tag families that have duplex coverage. The definition of \"duplex\"\
  \ is controlled by the '--min-ab-reads' and '--min-ba-reads' parameters. The default\
  \ is to treat any tag family with at least one observation of each strand as a duplex,\
  \ but this could be made more stringent, e.g. by setting '--min-ab-reads=3 --min-ba-reads=3'.\
  \ If different thresholds are used then '--min-ab-reads' must be the higher value.\n\
  \nOutputs -------\n\nThe following output files are produced:\n\n  1. <output>.family_sizes.txt:\
  \ metrics on the frequency of different types of families of different sizes\n \
  \ 2. <output>.duplex_family_sizes.txt: metrics on the frequency of duplex tag families\
  \ by the number of observations\n     from each strand\n  3. <output>.duplex_yield_metrics.txt:\
  \ summary QC metrics produced using 5%, 10%, 15%...100% of the data\n  4. <output>.umi_counts.txt:\
  \ metrics on the frequency of observations of UMIs within reads and tag families\n\
  \  5. <output>.duplex_qc.pdf: a series of plots generated from the preceding metrics\
  \ files for visualization\n  6. <output>.duplex_umi_counts.txt: (optional) metrics\
  \ on the frequency of observations of duplex UMIs within reads\n     and tag families.\
  \ This file is only produced if the '--duplex-umi-counts' option is used as it requires\
  \ significantly\n     more memory to track all pairs of UMIs seen when a large number\
  \ of UMI sequences are present.\n\nWithin the metrics files the prefixes 'CS', 'SS'\
  \ and 'DS' are used to mean:\n\n  * CS: tag families where membership is defined\
  \ solely on matching genome coordinates and strand\n  * SS: single-stranded tag\
  \ families where membership is defined by genome coordinates, strand and UMI; ie.\
  \ 50/A and\n    50/B are considered different tag families.\n  * DS: double-stranded\
  \ tag families where membership is collapsed across single-stranded tag families\
  \ from the same\n    double-stranded source molecule; i.e. 50/A and 50/B become\
  \ one family\n\nRequirements ------------\n\nFor plots to be generated R must be\
  \ installed and the ggplot2 package installed with suggested dependencies. Successfully\
  \ executing the following in R will ensure a working installation:\n\n  install.packages(\"\
  ggplot2\", repos=\"http://cran.us.r-project.org\", dependencies=TRUE)\n\nTool homepage:\
  \ https://github.com/fulcrumgenomics/fgbio"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    inputBinding:
      position: 1
      prefix: --async-io
  - id: cell_tag
    type:
      - 'null'
      - string
    doc: The tag containing the cell barcode.
    inputBinding:
      position: 101
      prefix: --cell-tag
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    inputBinding:
      position: 1
      prefix: --compression
  - id: cram_ref_fasta
    type:
      - 'null'
      - File
    doc: Reference FASTA for CRAM encoding/decoding.
    inputBinding:
      position: 1
      prefix: --cram-ref-fasta
  - id: description
    type:
      - 'null'
      - string
    doc: Description of data set used to label plots. Defaults to sample/library.
    inputBinding:
      position: 101
      prefix: --description
  - id: duplex_umi_counts
    type:
      - 'null'
      - boolean
    doc: If true, produce the .duplex_umi_counts.txt file with counts of duplex UMI
      observations.
    inputBinding:
      position: 101
      prefix: --duplex-umi-counts
  - id: input_bam
    secondaryFiles:
      - pattern: .bai
        required: false
      - pattern: ^.bai
        required: false
    type: File
    doc: Input BAM file generated by 'GroupReadsByUmi'.
    inputBinding:
      position: 101
      prefix: --input
  - id: intervals
    type:
      - 'null'
      - File
    doc: Optional set of intervals over which to restrict analysis.
    inputBinding:
      position: 101
      prefix: --intervals
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    inputBinding:
      position: 1
      prefix: --log-level
  - id: mi_tag
    type:
      - 'null'
      - string
    doc: The output tag for UMI grouping.
    inputBinding:
      position: 101
      prefix: --mi-tag
  - id: min_ab_reads
    type:
      - 'null'
      - int
    doc: Minimum AB reads to call a tag family a 'duplex'.
    inputBinding:
      position: 101
      prefix: --min-ab-reads
  - id: min_ba_reads
    type:
      - 'null'
      - int
    doc: Minimum BA reads to call a tag family a 'duplex'.
    inputBinding:
      position: 101
      prefix: --min-ba-reads
  - id: output_prefix
    type: string
    doc: Prefix of output files to write.
    inputBinding:
      position: 101
      prefix: --output
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for SAM/BAM reading. Options: STRICT, LENIENT, SILENT.'
    inputBinding:
      position: 1
      prefix: --sam-validation-stringency
  - id: tmp_dir
    type:
      - 'null'
      - string
    doc: Directory to use for temporary files.
    inputBinding:
      position: 1
      prefix: --tmp-dir
  - id: umi_tag
    type:
      - 'null'
      - string
    doc: The tag containing the raw UMI.
    inputBinding:
      position: 101
      prefix: --umi-tag
arguments:
  - position: 50
    valueFrom: CollectDuplexSeqMetrics
outputs:
  - id: output_prefix_files
    type:
      type: array
      items: File
    doc: Metrics and plot files written with the given output prefix.
    outputBinding:
      glob: $(inputs.output_prefix)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgbio:3.1.1--hdfd78af_0
