cwlVersion: v1.2
class: CommandLineTool
baseCommand: fgbio
label: fgbio_FilterConsensusReads
doc: "Filters consensus reads generated by CallMolecularConsensusReads or CallDuplexConsensusReads.\
  \ Two kinds of filtering are performed:\n\n  1. Masking/filtering of individual\
  \ bases in reads\n  2. Filtering out of reads (i.e. not writing them to the output\
  \ file)\n\nBase-level filtering/masking is only applied if per-base tags are present\
  \ (see CallDuplexConsensusReads and CallMolecularConsensusReads for descriptions\
  \ of these tags). Read-level filtering is always applied. When filtering reads,\
  \ secondary alignments and supplementary records may be removed independently if\
  \ they fail one or more filters; if either R1 or R2 primary alignments fail a filter\
  \ then all records for the template will be filtered out.\n\nThe filters applied\
  \ are as follows:\n\n  1. Reads with fewer than min-reads contributing reads are\
  \ filtered out\n  2. Reads with an average consensus error rate higher than max-read-error-rate\
  \ are filtered out\n  3. Reads with mean base quality of the consensus read, prior\
  \ to any masking, less than min-mean-base-quality are\n     filtered out (if specified)\n\
  \  4. Bases with quality scores below min-base-quality are masked to Ns\n  5. Bases\
  \ with fewer than min-reads contributing raw reads are masked to Ns\n  6. Bases\
  \ with a consensus error rate (defined as the fraction of contributing reads that\
  \ voted for a different base\n     than the consensus call) higher than max-base-error-rate\
  \ are masked to Ns\n  7. For duplex reads, if require-single-strand-agreement is\
  \ provided, masks to Ns any bases where the base was\n     observed in both single-strand\
  \ consensus reads and the two reads did not agree\n  8. Reads with a fraction or\
  \ count of Ns higher than max-no-calls after per-base filtering are filtered out.\n\
  \     'max-no-calls' is interpreted as a fraction if less than 1.0, and a count\
  \ if >= 1.0.\n\nWhen filtering single-umi consensus reads generated by CallMolecularConsensusReads\
  \ a single value each should be supplied for '--min-reads', '--max-read-error-rate',\
  \ and '--max-base-error-rate'.\n\nWhen filtering duplex consensus reads generated\
  \ by CallDuplexConsensusReads each of the three parameters may independently take\
  \ 1-3 values. For example:\n\n  FilterConsensusReads ... --min-reads 10 5 3 --max-base-error-rate\
  \ 0.1\n\nIn each case if fewer than three values are supplied, the last value is\
  \ repeated (i.e. '80 40' -> '80 40 40' and '0.1' -> '0.1 0.1 0.1'. The first value\
  \ applies to the final consensus read, the second value to one single-strand consensus,\
  \ and the last value to the other single-strand consensus. It is required that if\
  \ values two and three differ, the more stringent value comes earlier.\n\nIn order\
  \ to correctly filter reads in or out by template, the input BAM must be either\
  \ 'queryname' sorted or 'query' grouped. If your BAM is not already in an appropriate\
  \ order, this can be done in streaming fashion with:\n\n  samtools sort -n -u in.bam\
  \ | fgbio FilterConsensusReads -i /dev/stdin ...\n\nThe output sort order may be\
  \ specified with '--sort-order'. If not given, then the output will be in the same\
  \ order as input.\n\nThe '--reverse-tags-per-base' option controls whether per-base\
  \ tags should be reversed before being used on reads marked as being mapped to the\
  \ negative strand. This is necessary if the reads have been mapped and the bases/quals\
  \ reversed but the consensus tags have not. If true, the tags written to the output\
  \ BAM will be reversed where necessary in order to line up with the bases and quals.\n\
  \nTool homepage: https://github.com/fulcrumgenomics/fgbio"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    inputBinding:
      position: 1
      prefix: --async-io
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    inputBinding:
      position: 1
      prefix: --compression
  - id: cram_ref_fasta
    type:
      - 'null'
      - File
    doc: Reference FASTA for CRAM encoding/decoding.
    inputBinding:
      position: 1
      prefix: --cram-ref-fasta
  - id: input_bam
    type: File
    doc: The input SAM or BAM file of consensus reads.
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    inputBinding:
      position: 1
      prefix: --log-level
  - id: max_base_error_rate
    type:
      - 'null'
      - type: array
        items: float
    doc: The maximum error rate for a single consensus base.
    inputBinding:
      position: 101
      prefix: --max-base-error-rate
  - id: max_no_calls
    type:
      - 'null'
      - float
    doc: Maximum fraction (if < 1.0) or number (if >= 1.0) of no-calls in the read
      after filtering.
    inputBinding:
      position: 101
      prefix: --max-no-calls
  - id: max_read_error_rate
    type:
      - 'null'
      - type: array
        items: float
    doc: The maximum raw-read error rate across the entire consensus read.
    inputBinding:
      position: 101
      prefix: --max-read-error-rate
  - id: min_base_quality
    type: int
    doc: Mask (make 'N') consensus bases with quality less than this threshold.
    inputBinding:
      position: 101
      prefix: --min-base-quality
  - id: min_mean_base_quality
    type:
      - 'null'
      - int
    doc: The minimum mean base quality across the consensus read.
    inputBinding:
      position: 101
      prefix: --min-mean-base-quality
  - id: min_reads
    type:
      type: array
      items: int
    doc: The minimum number of reads supporting a consensus base/read.
    inputBinding:
      position: 101
      prefix: --min-reads
  - id: output_bam
    type: string
    doc: Output SAM or BAM file.
    inputBinding:
      position: 101
      prefix: --output
  - id: ref_fasta
    secondaryFiles:
      - pattern: .fai
        required: false
      - pattern: ^.dict
        required: false
    type: File
    doc: Reference fasta file.
    inputBinding:
      position: 101
      prefix: --ref
  - id: require_single_strand_agreement
    type:
      - 'null'
      - boolean
    doc: Mask (make 'N') consensus bases where the AB and BA consensus reads disagree
      (for duplex-sequencing only).
    inputBinding:
      position: 101
      prefix: --require-single-strand-agreement
  - id: reverse_per_base_tags
    type:
      - 'null'
      - boolean
    doc: Reverse complement per base tags on reverse strand reads.
    inputBinding:
      position: 101
      prefix: --reverse-per-base-tags
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for SAM/BAM reading. Options: STRICT, LENIENT, SILENT.'
    inputBinding:
      position: 1
      prefix: --sam-validation-stringency
  - id: sort_order
    type:
      - 'null'
      - string
    doc: 'The sort order of the output. If not given, output will be in the same order
      as input if the input is query name sorted or query grouped, otherwise queryname
      order. Options: Coordinate, Queryname, Random, RandomQuery, TemplateCoordinate,
      Unsorted, Unknown.'
    inputBinding:
      position: 101
      prefix: --sort-order
  - id: tmp_dir
    type:
      - 'null'
      - string
    doc: Directory to use for temporary files.
    inputBinding:
      position: 1
      prefix: --tmp-dir
arguments:
  - position: 50
    valueFrom: FilterConsensusReads
outputs:
  - id: output_bam_out
    type: File
    doc: Output SAM or BAM file.
    outputBinding:
      glob: $(inputs.output_bam)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgbio:3.1.1--hdfd78af_0
