cwlVersion: v1.2
class: CommandLineTool
baseCommand: fgbio
label: fgbio_CallDuplexConsensusReads
doc: "Calls duplex consensus sequences from reads generated from the same double-stranded\
  \ source molecule. Prior to running this tool, read must have been grouped with\
  \ 'GroupReadsByUmi' using the 'paired' strategy. Doing so will apply (by default)\
  \ MI tags to all reads of the form '*/A' and '*/B' where the /A and /B suffixes\
  \ with the same identifier denote reads that are derived from opposite strands of\
  \ the same source duplex molecule.\n\nReads from the same unique molecule are first\
  \ partitioned by source strand and assembled into single strand consensus molecules\
  \ as described by CallMolecularConsensusReads. Subsequently, for molecules that\
  \ have at least one observation of each strand, duplex consensus reads are assembled\
  \ by combining the evidence from the two single strand consensus reads.\n\nBecause\
  \ of the nature of duplex sequencing, this tool does not support fragment reads\
  \ - if found in the input they are ignored. Similarly, read pairs for which consensus\
  \ reads cannot be generated for one or other read (R1 or R2) are omitted from the\
  \ output.\n\nThe consensus reads produced are unaligned, due to the difficulty and\
  \ error-prone nature of inferring the conesensus alignment. Consensus reads should\
  \ therefore be aligned after, which should not be too expensive as likely there\
  \ are far fewer consensus reads than input raw raws. Please see how best to use\
  \ this tool within the best-practice pipeline: https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md\n\
  \nConsensus reads have a number of additional optional tags set in the resulting\
  \ BAM file. The tag names follow a pattern where the first letter (a, b or c) denotes\
  \ that the tag applies to the first single strand consensus (a), second single-strand\
  \ consensus (b) or the final duplex consensus (c). The second letter is intended\
  \ to capture the meaning of the tag (e.g. d=depth, m=min depth, e=errors/error-rate)\
  \ and is upper case for values that are one per read and lower case for values that\
  \ are one per base.\n\nThe tags break down into those that are single-valued per\
  \ read:\n\n  consensus depth      [aD,bD,cD] (int)  : the maximum depth of raw reads\
  \ at any point in the consensus reads\n  consensus min depth  [aM,bM,cM] (int) \
  \ : the minimum depth of raw reads at any point in the consensus reads\n  consensus\
  \ error rate [aE,bE,cE] (float): the fraction of bases in raw reads disagreeing\
  \ with the final consensus calls\n\nAnd those that have a value per base (duplex\
  \ values are not generated, but can be generated by summing):\n\n  consensus depth\
  \  [ad,bd] (short[]): the count of bases contributing to each single-strand consensus\
  \ read at each position\n  consensus errors [ae,be] (short[]): the count of bases\
  \ from raw reads disagreeing with the final single-strand consensus base\n  consensus\
  \ errors [ac,bc] (string): the single-strand consensus bases\n  consensus errors\
  \ [aq,bq] (string): the single-strand consensus qualities\n\nThe per base depths\
  \ and errors are both capped at 32,767. In all cases no-calls (Ns) and bases below\
  \ the min-input-base-quality are not counted in tag value calculations.\n\nThe --min-reads\
  \ option can take 1-3 values similar to 'FilterConsensusReads'. For example:\n\n\
  \  CallDuplexConsensusReads ... --min-reads 10 5 3\n\nIf fewer than three values\
  \ are supplied, the last value is repeated (i.e. '5 4' -> '5 4 4' and '1' -> '1\
  \ 1 1'. The first value applies to the final consensus read, the second value to\
  \ one single-strand consensus, and the last value to the other single-strand consensus.\
  \ It is required that if values two and three differ, the more stringent value comes\
  \ earlier.\n\nTool homepage: https://github.com/fulcrumgenomics/fgbio"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    inputBinding:
      position: 1
      prefix: --async-io
  - id: cell_tag
    type:
      - 'null'
      - string
    doc: Tag containing the cellular barcodes.
    inputBinding:
      position: 101
      prefix: --cell-tag
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    inputBinding:
      position: 1
      prefix: --compression
  - id: consensus_call_overlapping_bases
    type:
      - 'null'
      - boolean
    doc: Consensus call overlapping bases in mapped paired end reads
    inputBinding:
      position: 101
      prefix: --consensus-call-overlapping-bases
      separate: false
      valueFrom: $("=" + self)
  - id: cram_ref_fasta
    type:
      - 'null'
      - File
    doc: Reference FASTA for CRAM encoding/decoding.
    inputBinding:
      position: 1
      prefix: --cram-ref-fasta
  - id: error_rate_post_umi
    type:
      - 'null'
      - int
    doc: The Phred-scaled error rate for an error post the UMIs have been integrated.
    inputBinding:
      position: 101
      prefix: --error-rate-post-umi
  - id: error_rate_pre_umi
    type:
      - 'null'
      - int
    doc: The Phred-scaled error rate for an error prior to the UMIs being integrated.
    inputBinding:
      position: 101
      prefix: --error-rate-pre-umi
  - id: input_bam
    type: File
    doc: The input SAM or BAM file.
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    inputBinding:
      position: 1
      prefix: --log-level
  - id: max_reads_per_strand
    type:
      - 'null'
      - int
    doc: The maximum number of reads to use when building a single-strand consensus.
      If more than this many reads are present in a tag family, the family is randomly
      downsampled to exactly max-reads reads.
    inputBinding:
      position: 101
      prefix: --max-reads-per-strand
  - id: min_input_base_quality
    type:
      - 'null'
      - int
    doc: Ignore bases in raw reads that have Q below this value.
    inputBinding:
      position: 101
      prefix: --min-input-base-quality
  - id: min_reads
    type:
      - 'null'
      - type: array
        items: int
    doc: The minimum number of input reads to a consensus read.
    inputBinding:
      position: 101
      prefix: --min-reads
  - id: output_bam
    type: string
    doc: Output SAM or BAM file to write consensus reads.
    inputBinding:
      position: 101
      prefix: --output
  - id: read_group_id
    type:
      - 'null'
      - string
    doc: The new read group ID for all the consensus reads.
    inputBinding:
      position: 101
      prefix: --read-group-id
  - id: read_name_prefix
    type:
      - 'null'
      - string
    doc: The prefix all consensus read names
    inputBinding:
      position: 101
      prefix: --read-name-prefix
  - id: rejects_bam
    type:
      - 'null'
      - string
    doc: Optional output SAM or BAM file to write reads not used.
    inputBinding:
      position: 101
      prefix: --rejects
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for SAM/BAM reading. Options: STRICT, LENIENT, SILENT.'
    inputBinding:
      position: 1
      prefix: --sam-validation-stringency
  - id: sort_order
    type:
      - 'null'
      - string
    doc: 'The sort order of the output, the same as the input if not given. Options:
      Coordinate, Queryname, Random, RandomQuery, TemplateCoordinate, Unsorted, Unknown.'
    inputBinding:
      position: 101
      prefix: --sort-order
  - id: stats
    type:
      - 'null'
      - string
    doc: Optional output text file of key consensus calling statistics.
    inputBinding:
      position: 101
      prefix: --stats
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use while consensus calling.
    inputBinding:
      position: 101
      prefix: --threads
  - id: tmp_dir
    type:
      - 'null'
      - string
    doc: Directory to use for temporary files.
    inputBinding:
      position: 1
      prefix: --tmp-dir
  - id: trim
    type:
      - 'null'
      - boolean
    doc: If true, quality trim input reads in addition to masking low Q bases.
    inputBinding:
      position: 101
      prefix: --trim
arguments:
  - position: 50
    valueFrom: CallDuplexConsensusReads
outputs:
  - id: output_bam_out
    type: File
    doc: Output SAM or BAM file to write consensus reads.
    outputBinding:
      glob: $(inputs.output_bam)
  - id: rejects_bam_out
    type:
      - 'null'
      - File
    doc: Optional output SAM or BAM file to write reads not used.
    outputBinding:
      glob: $(inputs.rejects_bam)
  - id: stats_out
    type:
      - 'null'
      - File
    doc: Optional output text file of key consensus calling statistics.
    outputBinding:
      glob: $(inputs.stats)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgbio:3.1.1--hdfd78af_0
