cwlVersion: v1.2
class: CommandLineTool
baseCommand: fgbio
label: fgbio_CallCodecConsensusReads
doc: "Calls consensus sequences from reads generated from the the CODEC protocol.\
  \ For more information on the CODEC sequencing protocol and the resulting data please\
  \ refer to Bae et al 20231.\n\nPrior to running this tool, reads must have been\
  \ grouped with 'GroupReadsByUmi' using the 'adjacency' or 'identity' strategy (NOT\
  \ 'paired').\n\nReads from the same original duplex are collected, and the R1s and\
  \ R2s assembled into single strand consensus reads as described by 'CallMolecularConsensusReads'.\
  \ Subsequently, a single consensus read is generated including both any single-strand\
  \ regions as well as the double-stranded region of the template.\n\nThe consensus\
  \ reads produced are unaligned, due to the difficulty and error-prone nature of\
  \ inferring the consensus alignment. Consensus reads should therefore be aligned\
  \ after, which should not be too expensive as likely there are significantly fewer\
  \ consensus reads than input raw reads. Please see how best to use this tool within\
  \ the best-practice pipeline: https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md\n\
  \nConsensus reads have a number of additional optional tags set in the resulting\
  \ BAM file. The tag names follow a pattern where the first letter (a, b or c) denotes\
  \ that the tag applies to the first single strand consensus (a), second single-strand\
  \ consensus (b) or the final duplex consensus (c). The second letter is intended\
  \ to capture the meaning of the tag (e.g. d=depth, m=min depth, e=errors/error-rate)\
  \ and is upper case for values that are one per read and lower case for values that\
  \ are one per base.\n\nThe tags break down into those that are single-valued per\
  \ read:\n\n  consensus depth      [aD,bD,cD] (int)  : the maximum depth of raw reads\
  \ at any point in the consensus reads\n  consensus min depth  [aM,bM,cM] (int) \
  \ : the minimum depth of raw reads at any point in the consensus reads\n  consensus\
  \ error rate [aE,bE,cE] (float): the fraction of bases in raw reads disagreeing\
  \ with the final consensus calls\n\nAnd those that have a value per base (duplex\
  \ values are not generated, but can be generated by summing):\n\n  consensus depth\
  \  [ad,bd] (short[]): the count of bases contributing to each single-strand consensus\
  \ read at each position\n  consensus errors [ae,be] (short[]): the count of bases\
  \ from raw reads disagreeing with the final single-strand consensus base\n  consensus\
  \ errors [ac,bc] (string): the single-strand consensus bases\n  consensus errors\
  \ [aq,bq] (string): the single-strand consensus qualities\n\nThe per base depths\
  \ and error counts are both capped at 32,767. In all cases no-calls (Ns) and bases\
  \ below the min-input-base-quality are not counted in tag value calculations.\n\n\
  1 https://doi.org/10.1038/s41588-023-01376-0\n\nTool homepage: https://github.com/fulcrumgenomics/fgbio"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    inputBinding:
      position: 1
      prefix: --async-io
  - id: cell_tag
    type:
      - 'null'
      - string
    doc: Tag containing the cellular barcodes.
    inputBinding:
      position: 101
      prefix: --cell-tag
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    inputBinding:
      position: 1
      prefix: --compression
  - id: cram_ref_fasta
    type:
      - 'null'
      - File
    doc: Reference FASTA for CRAM encoding/decoding.
    inputBinding:
      position: 1
      prefix: --cram-ref-fasta
  - id: error_rate_post_umi
    type:
      - 'null'
      - int
    doc: The Phred-scaled error rate for an error post the UMIs have been integrated.
    inputBinding:
      position: 101
      prefix: --error-rate-post-umi
  - id: error_rate_pre_umi
    type:
      - 'null'
      - int
    doc: The Phred-scaled error rate for an error prior to the UMIs being integrated.
    inputBinding:
      position: 101
      prefix: --error-rate-pre-umi
  - id: input_bam
    type: File
    doc: The input SAM or BAM file.
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    inputBinding:
      position: 1
      prefix: --log-level
  - id: max_duplex_disagreement_rate
    type:
      - 'null'
      - float
    doc: Discard consensus reads where greater than this fraction of duplex bases
      disagree.
    inputBinding:
      position: 101
      prefix: --max-duplex-disagreement-rate
  - id: max_duplex_disagreements
    type:
      - 'null'
      - int
    doc: Discard consensus reads where greater than this number of duplex bases disagree.
    inputBinding:
      position: 101
      prefix: --max-duplex-disagreements
  - id: max_read_pairs
    type:
      - 'null'
      - int
    doc: The maximum number of reads to use when building a single-strand consensus.
      If more than this many reads are present in a tag family, the family is randomly
      downsampled to exactly max-reads-pairs reads.
    inputBinding:
      position: 101
      prefix: --max-read-pairs
  - id: min_duplex_length
    type:
      - 'null'
      - int
    doc: Minimum length of the duplex region (where R1 and R2 overlap).
    inputBinding:
      position: 101
      prefix: --min-duplex-length
  - id: min_input_base_quality
    type:
      - 'null'
      - int
    doc: Ignore bases in raw reads that have Q below this value.
    inputBinding:
      position: 101
      prefix: --min-input-base-quality
  - id: min_read_pairs
    type:
      - 'null'
      - int
    doc: The minimum number of codec read pairs to form a consensus read.
    inputBinding:
      position: 101
      prefix: --min-read-pairs
  - id: outer_bases_length
    type:
      - 'null'
      - int
    doc: The number of bases at the start and end of the read to reduce quality over
      if 'outer-bases-qual' is specified.
    inputBinding:
      position: 101
      prefix: --outer-bases-length
  - id: outer_bases_qual
    type:
      - 'null'
      - int
    doc: Reduce the first and last 'outer-bases-length' bases to the given quality.
    inputBinding:
      position: 101
      prefix: --outer-bases-qual
  - id: output_bam
    type: string
    doc: Output SAM or BAM file to write consensus reads.
    inputBinding:
      position: 101
      prefix: --output
  - id: read_group_id
    type:
      - 'null'
      - string
    doc: The new read group ID for all the consensus reads.
    inputBinding:
      position: 101
      prefix: --read-group-id
  - id: read_name_prefix
    type:
      - 'null'
      - string
    doc: The prefix all consensus read names
    inputBinding:
      position: 101
      prefix: --read-name-prefix
  - id: rejects_bam
    type:
      - 'null'
      - string
    doc: Optional output SAM or BAM file to write reads not used.
    inputBinding:
      position: 101
      prefix: --rejects
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for SAM/BAM reading. Options: STRICT, LENIENT, SILENT.'
    inputBinding:
      position: 1
      prefix: --sam-validation-stringency
  - id: single_strand_qual
    type:
      - 'null'
      - int
    doc: Reduce quality scores in single stranded regions of the consensus read to
      the given quality.
    inputBinding:
      position: 101
      prefix: --single-strand-qual
  - id: sort_order
    type:
      - 'null'
      - string
    doc: 'The sort order of the output, the same as the input if not given. Options:
      Coordinate, Queryname, Random, RandomQuery, TemplateCoordinate, Unsorted, Unknown.'
    inputBinding:
      position: 101
      prefix: --sort-order
  - id: stats
    type:
      - 'null'
      - string
    doc: Optional output text file of key consensus calling statistics.
    inputBinding:
      position: 101
      prefix: --stats
  - id: threads
    type:
      - 'null'
      - int
    doc: The number of threads to use while consensus calling.
    inputBinding:
      position: 101
      prefix: --threads
  - id: tmp_dir
    type:
      - 'null'
      - string
    doc: Directory to use for temporary files.
    inputBinding:
      position: 1
      prefix: --tmp-dir
arguments:
  - position: 50
    valueFrom: CallCodecConsensusReads
outputs:
  - id: output_bam_out
    type: File
    doc: Output SAM or BAM file to write consensus reads.
    outputBinding:
      glob: $(inputs.output_bam)
  - id: rejects_bam_out
    type:
      - 'null'
      - File
    doc: Optional output SAM or BAM file to write reads not used.
    outputBinding:
      glob: $(inputs.rejects_bam)
  - id: stats_out
    type:
      - 'null'
      - File
    doc: Optional output text file of key consensus calling statistics.
    outputBinding:
      glob: $(inputs.stats)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgbio:3.1.1--hdfd78af_0
