#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: Workflow
requirements:
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {}
  MultipleInputFeatureRequirement: {}
  ScatterFeatureRequirement: {}
  SubworkflowFeatureRequirement: {}

label: Long Read Quality Control and Filtering
doc: |
  **Workflow for long read quality control and contamination filtering.**
  - NanoPlot before and after filtering (read quality control)
  - Filtlong filter on quality and length
  - minimap2 read filtering based on given references

  Other UNLOCK workflows on WorkflowHub: https://workflowhub.eu/projects/16/workflows?view=default<br><br>

  **All tool CWL files and other workflows can be found here:**<br>
    Tools: https://gitlab.com/m-unlock/cwl/-/tree/master/cwl <br>
    Workflows: https://gitlab.com/m-unlock/cwl/-/tree/master/cwl/workflows<br>

  **How to setup and use an UNLOCK workflow:**<br>
  https://docs.m-unlock.nl/docs/workflows/setup.html<br>

outputs:
  reports_folder:
    type: Directory?
    label: Reports folder
    doc: Folder with quality plots and filter reports
    outputSource: reports_files_to_folder/results

  filtered_reads:
    type: File
    label: Filtered long reads
    doc: Filtered long reads
    outputSource: output_filtered_reads/reads_out

inputs:
  identifier:
    type: string
    doc: Identifier for this dataset used in this workflow
    label: identifier used
  longreads:
    type: File[]
    doc: Long read sequence file locally fastq format
    label: Long reads
  readtype:
    type:
      - type: enum
        symbols:
          - nanopore
          - pacbio
    doc: Type of read PacBio or Nanopore.
    label: Read type
  fastq_rich:
    type: boolean
    doc: | 
          Input fastq is generated by albacore, MinKNOW or guppy  with additional information concerning channel and time. 
          Used to creating more informative quality plots (Default false)
    label: Fastq rich (ONT)

  skip_qc_unfiltered:
    type: boolean
    doc: Skip quality plot of unfiltered input data (Default false)
    label: Skip NanoPlot before
  skip_qc_filtered:
    type: boolean
    doc: Skip quality plot of filter input data (Default false)
    label: Skip NanoPlot after

  minimum_length:
    type: int?
    label: Minimum length required
    doc: "Reads shorter will be discarded. (Default 100)"
  length_limit:
    type: int?
    label: Maximum length limit
    doc: "Reads longer than length_limit will be discarded. (Default no limit)"
  qualified_quality_phred:
    type: int?
    label: Qualified_quality_phred
    doc: "the quality value that a base is qualified. Default 9 means phred quality >=Q9 is qualified."
  mean_qual:
    type: int?
    label: Mean quality
    doc: "if one read's mean_qual quality score < mean_qual, then this read is discarded. (Default 10)"
  trim_front:
    type: int?
    label: Trim_front
    doc: "Trimming how many bases in front for read. (Default 0)"
  trim_tail:
    type: int?
    label: trim_tail
    doc: "Trimming how many bases in tail for read, Default 0)"

  cut_front:
    type: boolean?
    label: Cut front
    doc: "Move a sliding window from front (5') to tail, drop the bases in the window if its mean quality < threshold, stop otherwise. Default false"
  cut_tail:
    type: boolean?
    label: Cut tail
    doc: "Move a sliding window from tail (3') to front, drop the bases in the window if its mean quality < threshold, stop otherwise Default false."
  cut_window_size:
    type: int?
    label: Cut window size
    doc: "The window size option shared by cut_front, cut_tail or cut_sliding. Range: 1~1000. Default 4"
  cut_mean_quality:
    type: int?
    label: Cut mean quality
    doc: "The mean quality requirement option shared by cut_front, cut_tail or cut_sliding. Range: 1~36. Default 20"

  trim_poly_x:
    type: boolean?
    label: Trim_poly_x
    doc: "Enable polyX trimming in 3' ends. (Default false)"
  poly_x_min_len:
    type: int?
    label: Poly_x_min_len
    doc: "The minimum length to detect polyX in the read tail. (Default 10 when trim_poly_x is true)"
  start_adapter:
    type: string?
    label: start_adapter
    doc: "The adapter sequence at read start (5'). (Default auto-detect)"
  end_adapter:
    type: string?
    label: End adapter
    doc: "The adapter sequence at read end (3'). (Default auto-detect)"
  adapter_fasta:
    type: File?
    label: Adapter fasta
    doc: "Specify a FASTA file to trim both read ends by all the sequences in this FASTA file. (Default None)"
  disable_adapter_trimming:
    type: boolean?
    label: Disable adapter trimming
    doc: "Adapter trimming is enabled by default. If this option is specified, adapter trimming is disabled. Default false"
  disable_quality_filtering:
    type: boolean?
    label: Disable_quality_filtering
    doc: |
      "Quality filtering is enabled by default. If this option is specified, quality filtering is disabled. 
      Does not apply to human and reference filtering. (Default false)"

  humandb:
    type: File?
    doc: A fasta file or minimap2 indexed filed (.mmi) index needs to be provided. Preindexed is much faster. (Default None)
    label: Filter human reads
    loadListing: no_listing
  reference_filter_db:
    type: File?
    doc: A fasta file or minimap2 indexed filed (.mmi) index needs to be provided. Preindexed is much faster. (Default none)
    label: Filter reference file(s)
    loadListing: no_listing
  keep_reference_mapped_reads:
    type: boolean
    doc: Discard unmapped and keep reads mapped to the given reference. Default false (discard mapped)
    label: Keep mapped reads

  do_not_output_filtered_reads:
    type: boolean
    label: Don't output reads.
    doc: Do not output filtered reads. (default false)

  threads:
    type: int
    doc: Number of threads to use for computational processes
    label: Number of threads

  # Input provenance (used in cwl-prov)
  destination:
    type: string?
    label: Output Destination
    doc: Optional output destination only used for cwl-prov reporting.
  source:
    label: Input URLs used for this run
    doc: A provenance element to capture the original source of the input data
    type: string[]?

steps:
#############################################
#### Merge reads
  workflow_merge_reads:
    label: Merge paired reads
    doc: Creates a single file object. Also merges reads if multiple files are given.
    run: workflow_merge_se_reads.cwl
    in:
      filename: 
        source: identifier
        valueFrom: $(self)_merged
      reads: longreads
    out: [merged_reads]
#############################################
#### NanoPlot Before
  nanoplot_longreads_unfiltered:
    label: NanoPlot unfiltered
    doc: NanoPlot Quality assessment and report of reads before filtering
    run: ../tools/nanoplot/nanoplot.cwl
    when: $(inputs.skip_qc_unfiltered == false)
    in:
      skip_qc_unfiltered: skip_qc_unfiltered
      identifier: identifier
      readtype: readtype
      fastq_rich: fastq_rich

      plot_title:
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_unfiltered
      file_prefix:
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_unfiltered_

      longreads: workflow_merge_reads/merged_reads
      fastq_files:
        valueFrom: |
          ${ return !inputs.fastq_rich ? [inputs.longreads] : null; }
      rich_fastq_files:
        valueFrom: | 
          ${ return inputs.fastq_rich ? [inputs.longreads] : null }

      store_pickle:
      store_raw:
      threads: threads
    out: [log, WeightedHistogramReadlength, WeightedLogTransformed_HistogramReadlength, Non_weightedHistogramReadlength, Non_weightedLogTransformed_HistogramReadlength, LengthvsQualityScatterPlot, Yield_By_Length, report, logfile, nanostats, pickle, raw_data, CumulativeYieldPlot_Gigabases, CumulativeYieldPlot_NumberOfReads, NumberOfReads_Over_Time, ActivePores_Over_Time, TimeLengthViolinPlot, TimeQualityViolinPlot]
#############################################
#### Longread quality filter
  longread_quality_filter:
    label: Fastplong
    doc: Filter longreads on quality and length
    run: ../tools/fastplong/fastplong.cwl
    in:
      disable_quality_filtering: disable_quality_filtering

      identifier: identifier
      readtype: readtype
      output_filename_prefix:
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_filtered
      report_title:
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_fastplong_report

      input_file: workflow_merge_reads/merged_reads

      length_required: minimum_length
      length_limit: length_limit

      qualified_quality_phred: qualified_quality_phred
      mean_qual: mean_qual

      trim_front: trim_front
      trim_tail: trim_tail

      cut_front: cut_front
      cut_tail: cut_tail
      cut_window_size: cut_window_size
      cut_mean_quality: cut_mean_quality

      trim_poly_x: trim_poly_x
      poly_x_min_len: poly_x_min_len

      start_adapter: start_adapter
      end_adapter: end_adapter

      adapter_fasta: adapter_fasta
      disable_adapter_trimming: disable_adapter_trimming

      threads: threads
    out: [out_reads, html_report, json_report]

#############################################
#### Filter Human reads
  human_filter_longreads:
    label: Human filter
    doc: Filter human reads from the dataset using Hostile
    when: $(inputs.index !== null)
    run: ../tools/hostile/hostile_clean_longreads.cwl
    in:
      readtype: readtype
      output_filename_prefix:
        source: identifier
        valueFrom: $(self+"_"+inputs.readtype+"_human_filter")

      index: humandb
      reads:
        source:
        - longread_quality_filter/out_reads
        - workflow_merge_reads/merged_reads
        pickValue: first_non_null

      threads: threads
    out: [out_reads, summary]

#############################################
#### Custom reference filter
  reference_filter_longreads:
    label: Custom reference filter
    doc: Filter reads using custom references with Hostile
    when: $(inputs.index !== null)
    run: ../tools/hostile/hostile_clean_longreads.cwl
    in:
      readtype: readtype
      output_filename_prefix:
        source: identifier
        valueFrom: $(self+"_"+inputs.readtype+"_ref-filter")

      index: reference_filter_db
      reads:
        source:
         - human_filter_longreads/out_reads
         - longread_quality_filter/out_reads
         - workflow_merge_reads/merged_reads
        pickValue: first_non_null

      threads: threads
      invert: keep_reference_mapped_reads
    out: [out_reads, summary]

#############################################
#### NanoPlot After
  nanoplot_longreads_filtered:
    label: NanoPlot before
    doc: NanoPlot Quality assessment and report of reads after filtering
    run: ../tools/nanoplot/nanoplot.cwl
    when: $(inputs.skip_qc_filtered == false && inputs.fastq_files !== null && inputs.fastq_files.length !== 0)
    in:
      skip_qc_filtered: skip_qc_filtered
      identifier: identifier
      readtype: readtype

      plot_title: 
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_filtered
      file_prefix:
        valueFrom: $(inputs.identifier)_$(inputs.readtype)_filtered_

      filt_reads: longread_quality_filter/out_reads
      humanfilt_reads: human_filter_longreads/out_reads
      reffilt_reads: reference_filter_longreads/out_reads

      #
      fastq_files:
        valueFrom: |
          ${
            const sources = [
              inputs.reffilt_reads,
              inputs.humanfilt_reads,
              inputs.filt_reads
            ];
            const first = sources.find(x => x !== null);
            if (!first || first.size < 100) {
              return null;
            }
            return [first];
          }

      store_pickle:
      store_raw:
      threads: threads
    out: [log, WeightedHistogramReadlength, WeightedLogTransformed_HistogramReadlength, Non_weightedHistogramReadlength, Non_weightedLogTransformed_HistogramReadlength, LengthvsQualityScatterPlot, Yield_By_Length, report, logfile, nanostats, pickle, raw_data, CumulativeYieldPlot_Gigabases, CumulativeYieldPlot_NumberOfReads, NumberOfReads_Over_Time, ActivePores_Over_Time, TimeLengthViolinPlot, TimeQualityViolinPlot]

#############################################
#### Move files to a specific folder
  nanoplot_unfiltered_files_to_folder:
    label: Nanoplot unfiltered folder
    doc: Nanoplot plots and files to single folder
    when: $(inputs.skip_qc_unfiltered == false)
    in:
      skip_qc_unfiltered: skip_qc_unfiltered

      files:
        source: [nanoplot_longreads_unfiltered/log, nanoplot_longreads_unfiltered/WeightedHistogramReadlength, nanoplot_longreads_unfiltered/WeightedLogTransformed_HistogramReadlength, nanoplot_longreads_unfiltered/Non_weightedHistogramReadlength, nanoplot_longreads_unfiltered/Non_weightedLogTransformed_HistogramReadlength, nanoplot_longreads_unfiltered/LengthvsQualityScatterPlot, nanoplot_longreads_unfiltered/Yield_By_Length, nanoplot_longreads_unfiltered/report, nanoplot_longreads_unfiltered/logfile, nanoplot_longreads_unfiltered/nanostats, nanoplot_longreads_unfiltered/pickle, nanoplot_longreads_unfiltered/raw_data, nanoplot_longreads_unfiltered/CumulativeYieldPlot_Gigabases, nanoplot_longreads_unfiltered/CumulativeYieldPlot_NumberOfReads, nanoplot_longreads_unfiltered/NumberOfReads_Over_Time, nanoplot_longreads_unfiltered/ActivePores_Over_Time, nanoplot_longreads_unfiltered/TimeLengthViolinPlot, nanoplot_longreads_unfiltered/TimeQualityViolinPlot]
        linkMerge: merge_flattened
        pickValue: all_non_null
      destination: 
        source: readtype
        valueFrom: $(self+"_nanoplot_unfiltered")
    run: ../tools/expressions/files_to_folder.cwl
    out:
      [results]

  nanoplot_filtered_files_to_folder:
    label: Nanoplot filtered folder
    doc: Nanoplot plots and files to single folder
    when: $(inputs.skip !== null)
    run: ../tools/expressions/files_to_folder.cwl
    in:
      # Set a value if the step is run or not for the when condition
      skip:
        source: nanoplot_longreads_filtered/log
        valueFrom: |
          valueFrom: ${ return inputs.self ? [inputs.self] : null }

      files:
        source: [nanoplot_longreads_filtered/log, nanoplot_longreads_filtered/WeightedHistogramReadlength, nanoplot_longreads_filtered/WeightedLogTransformed_HistogramReadlength, nanoplot_longreads_filtered/Non_weightedHistogramReadlength, nanoplot_longreads_filtered/Non_weightedLogTransformed_HistogramReadlength, nanoplot_longreads_filtered/LengthvsQualityScatterPlot, nanoplot_longreads_filtered/Yield_By_Length, nanoplot_longreads_filtered/report, nanoplot_longreads_filtered/logfile, nanoplot_longreads_filtered/nanostats, nanoplot_longreads_filtered/pickle, nanoplot_longreads_filtered/raw_data, nanoplot_longreads_filtered/CumulativeYieldPlot_Gigabases, nanoplot_longreads_filtered/CumulativeYieldPlot_NumberOfReads, nanoplot_longreads_filtered/NumberOfReads_Over_Time, nanoplot_longreads_filtered/ActivePores_Over_Time, nanoplot_longreads_filtered/TimeLengthViolinPlot, nanoplot_longreads_filtered/TimeQualityViolinPlot]
        linkMerge: merge_flattened
        pickValue: all_non_null
      destination:
        source: readtype
        valueFrom: $(self+"_nanoplot_filtered")
    out:
      [results]

  reports_files_to_folder:
    label: Reports to folder
    doc: Preparation of QC output files to a specific output folder
    run: ../tools/expressions/files_to_folder.cwl
    in:
      readtype: readtype
      files:
        source: [longread_quality_filter/html_report, longread_quality_filter/json_report, human_filter_longreads/summary, reference_filter_longreads/summary]
        linkMerge: merge_flattened
        pickValue: all_non_null
      folders:
        source: [nanoplot_unfiltered_files_to_folder/results, nanoplot_filtered_files_to_folder/results]
        linkMerge: merge_flattened
        pickValue: all_non_null
      destination:
        source: readtype
        valueFrom: $(self+"_quality_filter_reports")
    out:
      [results]

#############################################
#### Output reads 
  output_filtered_reads:
    label: Output reads
    doc: Step needed to output filtered reads because there is an option to not to.
    when: $(!inputs.do_not_output_filtered_reads && inputs.reads_in !== null)
    run:
      class: ExpressionTool
      requirements:
        InlineJavascriptRequirement: {}
      inputs:
        reads_in: File?
      outputs:
        reads_out: File
      expression: |
        ${ return {'reads_out': inputs.reads_in}; }
    in:
      do_not_output_filtered_reads: do_not_output_filtered_reads

      identifier: identifier
      readtype: readtype

      filt_reads: longread_quality_filter/out_reads
      humanfilt_reads: human_filter_longreads/out_reads
      reffilt_reads: reference_filter_longreads/out_reads

      reads_in:
        valueFrom: |
          ${
            const sources = [
              inputs.reffilt_reads,
              inputs.humanfilt_reads,
              inputs.filt_reads
            ];
            const firstAvailable = sources.find(x => x !== null);
            // If the first available read is not null, change output filename.
            if (firstAvailable) {
              firstAvailable.basename = inputs.identifier+"_"+inputs.readtype+"_filtered.fastq.gz";
            }
            return firstAvailable || null;
          }
    out:
      [reads_out]

s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-9524-5964
    s:email: mailto:bart.nijsse@wur.nl
    s:name: Bart Nijsse
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-8172-8981
    s:email: mailto:jasper.koehorst@wur.nl
    s:name: Jasper Koehorst

s:citation: https://m-unlock.nl
s:codeRepository: https://gitlab.com/m-unlock/cwl
s:dateModified: "2025-08-22"
s:dateCreated: "2025-04-30"
s:license: https://spdx.org/licenses/Apache-2.0
s:copyrightHolder: "UNLOCK - Unlocking Microbial Potential"


$namespaces:
  s: https://schema.org/