cwlVersion: v1.2
class: CommandLineTool
baseCommand: rnaQUAST.py
label: rnaquast_rnaQUAST.py
doc: "QUALITY ASSESSMENT FOR TRANSCRIPTOME ASSEMBLIES\n\nTool homepage: http://cab.spbu.ru/software/rnaquast/"
inputs:
  - id: alignment
    type:
      - 'null'
      - type: array
        items: File
    doc: File(s) with transcript alignments to the reference genome [PSL]
    inputBinding:
      position: 101
      prefix: --alignment
  - id: blat
    type:
      - 'null'
      - boolean
    doc: Run with BLAT alignment tool (http://hgwdev.cse.ucsc.edu/~kent/exe/) 
      instead of GMAP
    inputBinding:
      position: 101
      prefix: --blat
  - id: busco
    type:
      - 'null'
      - string
    doc: Run with BUSCO tool (http://busco.ezlab.org/). Automated lineage 
      selection [auto-lineage], BUSCO dataset name or a path to the lineage data
      to be used
    inputBinding:
      position: 101
      prefix: --busco
  - id: debug
    type:
      - 'null'
      - boolean
    doc: Report detailed information, typically used only for detecting 
      problems.
    inputBinding:
      position: 101
      prefix: --debug
  - id: disable_infer_genes
    type:
      - 'null'
      - boolean
    doc: Use this option if your GTF file already contains genes records
    inputBinding:
      position: 101
      prefix: --disable_infer_genes
  - id: disable_infer_transcripts
    type:
      - 'null'
      - boolean
    doc: Use this option if your GTF already contains transcripts records
    inputBinding:
      position: 101
      prefix: --disable_infer_transcripts
  - id: gene_db
    type:
      - 'null'
      - string
    doc: Path to the gene database generated by gffutils to be used
    inputBinding:
      position: 101
      prefix: --gene_db
  - id: gene_mark
    type:
      - 'null'
      - boolean
    doc: Run with GeneMarkS-T tool (http://topaz.gatech.edu/GeneMark/)
    inputBinding:
      position: 101
      prefix: --gene_mark
  - id: gmap_index
    type:
      - 'null'
      - Directory
    doc: Folder containing GMAP index for the reference genome
    inputBinding:
      position: 101
      prefix: --gmap_index
  - id: gtf
    type:
      type: array
      items: File
    doc: File with gene coordinates (or several files or *.txt file with 
      one-per-line list of GTF / GFF files for meta RNA). We recommend to use 
      files downloaded from GENCODE or Ensembl [GTF/GFF]
    inputBinding:
      position: 101
      prefix: --gtf
  - id: labels
    type:
      - 'null'
      - type: array
        items: string
    doc: Name(s) of assemblies that will be used in the reports
    inputBinding:
      position: 101
      prefix: --labels
  - id: left_reads
    type:
      - 'null'
      - File
    doc: File with forward paired-end reads [FASTQ or gzip-compressed]
    inputBinding:
      position: 101
      prefix: --left_reads
  - id: lower_threshold
    type:
      - 'null'
      - float
    doc: 'Lower threshold for x-assembled/covered/matched metrics, default: 0.5'
    default: 0.5
    inputBinding:
      position: 101
      prefix: --lower_threshold
  - id: meta
    type:
      - 'null'
      - boolean
    doc: Run QUALITY ASSESSMENT FOR METATRANSCRIPTOME ASSEMBLIES
    inputBinding:
      position: 101
      prefix: --meta
  - id: min_alignment
    type:
      - 'null'
      - int
    doc: 'Minimal alignment length, default: 50'
    default: 50
    inputBinding:
      position: 101
      prefix: --min_alignment
  - id: no_plots
    type:
      - 'null'
      - boolean
    doc: Do not draw plots (to speed up computation)
    inputBinding:
      position: 101
      prefix: --no_plots
  - id: prokaryote
    type:
      - 'null'
      - boolean
    doc: Use this option if the genome is prokaryotic
    inputBinding:
      position: 101
      prefix: --prokaryote
  - id: reads_alignment
    type:
      - 'null'
      - File
    doc: File with read alignments to the reference genome [SAM]
    inputBinding:
      position: 101
      prefix: --reads_alignment
  - id: reference
    type:
      type: array
      items: File
    doc: Single file (or several files for meta RNA) with reference genome in 
      FASTA format or *.txt file with one-per-line list of FASTA files with 
      reference sequences
    inputBinding:
      position: 101
      prefix: --reference
  - id: right_reads
    type:
      - 'null'
      - File
    doc: File with reverse paired-end reads [FASTQ or gzip-compressed]
    inputBinding:
      position: 101
      prefix: --right_reads
  - id: single_reads
    type:
      - 'null'
      - File
    doc: File with unpaired reads [FASTQ or gzip-compressed]
    inputBinding:
      position: 101
      prefix: --single_reads
  - id: strand_specific
    type:
      - 'null'
      - boolean
    doc: Set if transcripts were assembled using strand-specific RNA-Seq data
    inputBinding:
      position: 101
      prefix: --strand_specific
  - id: test
    type:
      - 'null'
      - boolean
    doc: Run rnaQUAST on the test data from the test_data folder, output 
      directory is rnaOUAST_test_output
    inputBinding:
      position: 101
      prefix: --test
  - id: threads
    type:
      - 'null'
      - int
    doc: 'Maximum number of threads, default: min(number of CPUs / 2, 16)'
    inputBinding:
      position: 101
      prefix: --threads
  - id: transcripts
    type:
      type: array
      items: File
    doc: File(s) with transcripts [FASTA]
    inputBinding:
      position: 101
      prefix: --transcripts
  - id: upper_threshold
    type:
      - 'null'
      - float
    doc: 'Upper threshold for x-assembled/covered/matched metrics, default: 0.95'
    default: 0.95
    inputBinding:
      position: 101
      prefix: --upper_threshold
outputs:
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: 'Directory to store all results [default: rnaQUAST_results/results_<datetime>]'
    outputBinding:
      glob: $(inputs.output_dir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/rnaquast:2.3.0--h9ee0642_0
