cwlVersion: v1.2
class: CommandLineTool
baseCommand: make
label: qax_make
doc: "Create a Qiime Visualization Artifact from a directory with files. By default,
  will create a \"Visualization\", thus requiring an \"index.html\" file in the root
  of the input directory.\n\nTool homepage: https://github.com/telatin/qax"
inputs:
  - id: input_directory
    type: Directory
    doc: Input directory
    inputBinding:
      position: 1
  - id: artifact_archive_version
    type:
      - 'null'
      - string
    doc: Artifact archive version
    inputBinding:
      position: 102
      prefix: --archive
  - id: artifact_format
    type:
      - 'null'
      - string
    doc: Artifact format
    inputBinding:
      position: 102
      prefix: --format
  - id: artifact_type
    type:
      - 'null'
      - string
    doc: Artifact type
    inputBinding:
      position: 102
      prefix: --type
  - id: attributes
    type:
      - 'null'
      - type: array
        items: string
    doc: Artifact metadata attribute (key=value)
    inputBinding:
      position: 102
      prefix: --attr
  - id: force
    type:
      - 'null'
      - boolean
    doc: Overwrite output artifact
    inputBinding:
      position: 102
      prefix: --force
  - id: tempdir
    type:
      - 'null'
      - Directory
    doc: Temporary directory
    inputBinding:
      position: 102
      prefix: --tempdir
  - id: uuid
    type:
      - 'null'
      - string
    doc: Specify a UUID (otherwise autogenerated)
    inputBinding:
      position: 102
      prefix: --uuid
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Verbose output
    inputBinding:
      position: 102
      prefix: --verbose
outputs:
  - id: output_artifact
    type: File
    doc: Output artifact (required)
    outputBinding:
      glob: $(inputs.output_artifact)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/qax:0.9.8--h515fd9b_0
