cwlVersion: v1.2
class: CommandLineTool
baseCommand: localhgt event
label: localhgt_event
doc: "Infer complete HGT events based on detected HGT breakpoints.\n\nTool homepage:
  https://github.com/samtools/samtools"
inputs:
  - id: breakpoint_results_folder
    type: Directory
    doc: the folder stores all the breakpoint results from all samples, i.e., a 
      folder stores all the *acc.csv files generated by 'localhgt bkp'
    inputBinding:
      position: 101
      prefix: -b
  - id: min_supporting_split_read
    type:
      - 'null'
      - int
    doc: minimum supporting split read number
    default: 2
    inputBinding:
      position: 101
      prefix: -n
  - id: min_transfer_sequence_length
    type:
      - 'null'
      - int
    doc: minimum transfer sequence length
    default: 500
    inputBinding:
      position: 101
      prefix: -m
  - id: output_file
    type: File
    doc: Output file to save all inferred HGT events.
    default: complete_HGT_event.csv
    inputBinding:
      position: 101
      prefix: -f
  - id: reference_file
    type: string
    doc: Uncompressed reference file, which contains all the representative 
      references of concerned bacteria. It should be the same as the reference 
      file used in localhgt bkp -r.
    inputBinding:
      position: 101
      prefix: -r
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/localhgt:1.0.1--h9948957_3
stdout: localhgt_event.out
