cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - fgsv
  - AggregateSvPileup
label: fgsv_AggregateSvPileup
doc: "Aggregates and merges pileups that are likely to support the same breakpoint.\n\
  \nTakes as input the file of pileups produced by 'SvPileup'. That file contains
  a list of breakpoints, each consisting of\na chromosome, position and strand for
  each side of the breakpoint, as well as quantified read support for the\nbreakpoint.\n\
  \nThis tool merges sets of breakpoints that have their left sides on the same chromosome,
  their right sides on the same\nchromosome, the same left and right strands, and
  their left and right positions both within a length threshold. The\nmerging behavior
  is transitive. For example, two breakpoints that are farther apart than the length
  threshold can be\nmerged if there is a third breakpoint that is close to both.\n\
  \n'SvPileup' distinguishes between two types of evidence for breakpoint events:
  split-read evidence, where a breakpoint\noccurs within a mapped read, and read-pair
  evidence, where a breakpoint occurs in the unsequenced insert between two\npaired
  reads. Currently this tool treats both forms of evidence equally, despite the inaccuracy
  of positions reported\nby 'SvPileup' for read-pair evidence.\n\nIf a BAM file is
  provided, each aggregated pileup is annotated with the allele frequency at its left
  and right\nbreakends. Allele frequency is defined as the total number of templates
  supporting constituent breakpoints divided by\nthe count of the union of templates
  that cross any constituent breakends. In particular, paired templates that straddle\n\
  a breakend are considered to cross the breakend.\n\nIf a BED file of target regions
  is provided, each aggregated pileup is annotated with whether its left and right
  sides\noverlap a target region. Additionally, the names of the overlapping target
  regions will be annotated, overwriting any\nvalues from the 'SvPileup' input. If
  no target regions are provided, then the names of the overlapping target regions\n\
  are copied from the 'SvPiluep' input (if present).\n\nThe output file is a tab-delimited
  table with one record per aggregated cluster of pileups. Aggregated pileups are\n\
  reported with the minimum and maximum (inclusive) coordinates of all pileups in
  the cluster, a possible putative\nstructural variant event type supported by the
  pileups, and the sum of read support from all pileups in the cluster.\nPositions
  in this file are 1-based inclusive positions.\n\nTool homepage: https://github.com/fulcrumgenomics/fgsv"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    default: false
    inputBinding:
      position: 101
      prefix: --async-io
  - id: bam_file
    type:
      - 'null'
      - File
    doc: "Bam file for allele frequency analysis. Must be coordinate sorted version
      of the file\nthat was input to SvPileup."
    inputBinding:
      position: 101
      prefix: --bam
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    default: 5
    inputBinding:
      position: 101
      prefix: --compression
  - id: flank
    type:
      - 'null'
      - int
    doc: "If BAM file is provided: distance upstream and downstream of aggregated
      breakpoint\nregions to search for mapped templates that overlap breakends. These
      are the templates\nthat will be partitioned into those supporting the breakpoint
      vs. reading through it for\nthe allele frequency calculation. Recommended to
      use at least the max read pair inner\ndistance used by SvPileup."
    default: 1000
    inputBinding:
      position: 101
      prefix: --flank
  - id: input_file
    type: File
    doc: Input text file of pileups generated by SvPileup
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    default: Info
    inputBinding:
      position: 101
      prefix: --log-level
  - id: max_dist
    type:
      - 'null'
      - int
    doc: Distance threshold below which to cluster breakpoints
    default: 10
    inputBinding:
      position: 101
      prefix: --max-dist
  - id: min_breakpoint_support
    type:
      - 'null'
      - int
    doc: "If BAM file is provided: minimum total number of templates supporting an
      aggregated\nbreakpoint to report allele frequency. Supports speed improvement
      by avoiding querying\nand iterating over huge read pileups that contain insufficient
      support for a breakpoint\nto be considered interesting."
    default: 10
    inputBinding:
      position: 101
      prefix: --min-breakpoint-support
  - id: min_frequency
    type:
      - 'null'
      - float
    doc: "If BAM file is provided: minimum allele frequency to report. Supports speed
      improvement\nby avoiding iterating over huge read pileups that contain insufficient
      support for a\nbreakpoint to be considered interesting."
    default: 0.001
    inputBinding:
      position: 101
      prefix: --min-frequency
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: "Validation stringency for SAM/BAM reading. Options:\nSTRICT, LENIENT, SILENT."
    default: SILENT
    inputBinding:
      position: 101
      prefix: --sam-validation-stringency
  - id: targets_bed
    type:
      - 'null'
      - File
    doc: Optional BED file of target regions
    inputBinding:
      position: 101
      prefix: --targets-bed
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: Directory to use for temporary files.
    default: /tmp
    inputBinding:
      position: 101
      prefix: --tmp-dir
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: Output file
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgsv:0.2.1--hdfd78af_1
