cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - fgsv
  - AggregateSvPileupToBedPE
label: fgsv_AggregateSvPileupToBedPE
doc: "Convert the output of AggregateSvPileup to BEDPE.\n\nTool homepage: https://github.com/fulcrumgenomics/fgsv"
inputs:
  - id: async_io
    type:
      - 'null'
      - boolean
    doc: Use asynchronous I/O where possible, e.g. for SAM and BAM files.
    inputBinding:
      position: 101
      prefix: --async-io
  - id: compression
    type:
      - 'null'
      - int
    doc: Default GZIP compression level, BAM compression level.
    inputBinding:
      position: 101
      prefix: --compression
  - id: input
    type: File
    doc: Input text file of aggregate pileups generated by AggregateSvPileup
    inputBinding:
      position: 101
      prefix: --input
  - id: log_level
    type:
      - 'null'
      - string
    doc: 'Minimum severity log-level to emit. Options: Debug, Info, Warning, Error,
      Fatal.'
    inputBinding:
      position: 101
      prefix: --log-level
  - id: sam_validation_stringency
    type:
      - 'null'
      - string
    doc: 'Validation stringency for SAM/BAM reading. Options: STRICT, LENIENT, SILENT.'
    inputBinding:
      position: 101
      prefix: --sam-validation-stringency
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: Directory to use for temporary files.
    inputBinding:
      position: 101
      prefix: --tmp-dir
outputs:
  - id: output
    type:
      - 'null'
      - File
    doc: Output text file of the aggregate pileups in BEDPE format.
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fgsv:0.2.1--hdfd78af_1
