cwlVersion: v1.2
class: CommandLineTool
baseCommand: danbing-tk
label: danbing-tk
doc: "A tool for processing sequencing reads, likely involving kmer analysis and alignment.\n\
  \nTool homepage: https://github.com/ChaissonLab/danbing-tk"
inputs:
  - id: fasta_file
    type: File
    doc: Fasta file e.g. generated by samtools fasta -n; Reads are paired on the
      fly.
    inputBinding:
      position: 101
      prefix: -fa
  - id: fastq_file
    type: File
    doc: Fastq file e.g. generated by samtools fastq -n; Reads are paired on the
      fly.
    inputBinding:
      position: 101
      prefix: -fq
  - id: graph_index_bait_prefix
    type: string
    doc: Prefix for graph/index/bait files
    inputBinding:
      position: 101
      prefix: -qs
  - id: graph_threading_no_error_correction
    type:
      - 'null'
      - int
    doc: Use graph threading algorithm w/o error correction
    inputBinding:
      position: 101
      prefix: -g
  - id: graph_threading_with_error_correction
    type:
      - 'null'
      - type: array
        items: int
    doc: 'Use graph threading algorithm w/ error correction, the default algorithm.
      Discard pe reads if # of matching kmers < INT1 [100] Maxmimal # of edits allowed
      = INT2 [3]'
      - 100
      - 3
    inputBinding:
      position: 101
      prefix: -gc
  - id: graph_threading_with_error_correction_and_sanity_check
    type:
      - 'null'
      - type: array
        items: int
    doc: Same as above, except also running sanity check
      - 100
      - 3
    inputBinding:
      position: 101
      prefix: -gcc
  - id: kmer_counting_mode
    type:
      - 'null'
      - string
    doc: "Alternative kmer counting mode for .tr.kmers output: \"aln\" or \"asgn\"\
      \ Default counts exact kmer matches aln: counts aligned kmers after applying
      CIGAR operations asgn: counts (exact kmer matches) + (mismatches that should
      be assigned to TR region) Additional arguments allowed in the form '-c STR INT'
      Requires at least INT TR kmer matches for TR-spanning read. Default: not allowed."
    inputBinding:
      position: 101
      prefix: -c
  - id: kmer_filtering_params
    type:
      - 'null'
      - type: array
        items: int
    doc: 'Parameters for kmer-based pre-filtering, optimized for 150bp paired-end
      reads. INT1 = # of sub-sampled kmers. [4] INT2 = minimal # of matches. [1]'
      - 4
      - 1
    inputBinding:
      position: 101
      prefix: -kf
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: Kmer size [21]
    inputBinding:
      position: 101
      prefix: -k
  - id: maxhit_threshold
    type:
      - 'null'
      - int
    doc: Discard both pe reads if maxhit of one pe read is below this threshold.
      [45] Will skip read filtering and run threading directly if not specified.
    inputBinding:
      position: 101
      prefix: -cth
  - id: min_qual_score_threshold
    type:
      - 'null'
      - int
    doc: At baiting step, only consider kmers of which overlapping bases have 
      qual score >= INT. [20]
    inputBinding:
      position: 101
      prefix: -qth
  - id: output_alignments_all_reads
    type:
      - 'null'
      - boolean
    doc: Output alignments for all reads entering threading. Only work with -g 
      or -gc.
    inputBinding:
      position: 101
      prefix: -a
  - id: output_alignments_excluding_unaligned
    type:
      - 'null'
      - boolean
    doc: Same as the -a option, but excluding unaligned reads in threading.
    inputBinding:
      position: 101
      prefix: -ae
  - id: output_prefix
    type: string
    doc: Output prefix
    inputBinding:
      position: 101
      prefix: -o
  - id: output_prefix_with_locus_kmer
    type: string
    doc: Same as the -o option, but write locus and kmer name as well
    inputBinding:
      position: 101
      prefix: -on
  - id: read_fp_kmers_file
    type:
      - 'null'
      - string
    doc: read FP-specific kmers from file STR to remove FP reads. Specify file 
      name STR if having a different prefix than the one for graph/index.
    inputBinding:
      position: 101
      prefix: -b
  - id: reads_per_batch_scaling_factor
    type:
      - 'null'
      - float
    doc: scaling factor for readsPerBatch. Can affect multiprocess efficiency. 
      [1]
    inputBinding:
      position: 101
      prefix: -r
  - id: record_invariant_kmer_counts
    type:
      - 'null'
      - boolean
    doc: Use .inv.kmers to record invariant kmer counts
    inputBinding:
      position: 101
      prefix: -ik
  - id: simulation_mode
    type:
      - 'null'
      - int
    doc: simulation mode
    inputBinding:
      position: 101
      prefix: -s
  - id: threads
    type:
      - 'null'
      - int
    doc: Use n threads. [1]
    inputBinding:
      position: 101
      prefix: -p
  - id: use_kmer_matches_only
    type:
      - 'null'
      - boolean
    doc: Use only kmer matches to assign read to locus, skip threading.
    inputBinding:
      position: 101
      prefix: -xg
  - id: verbosity
    type:
      - 'null'
      - int
    doc: 'Verbosity: 0-3.'
    inputBinding:
      position: 101
      prefix: -v
  - id: write_divergent_kmers
    type:
      - 'null'
      - boolean
    doc: Write read (k+1)-mers divergent from graph to .bub
    inputBinding:
      position: 101
      prefix: -bu
  - id: write_mapped_reads_fasta
    type:
      - 'null'
      - int
    doc: Write mapped reads to STDOUT in fasta format. Specify 1 for keeping 
      original read names. Will not write .kmers output. Specify 2 for appending
      assigned locus to each read name. Used to skip step1 for later queries.
    inputBinding:
      position: 101
      prefix: -e
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/danbing-tk:1.3.2.5--h9948957_0
stdout: danbing-tk.out
