cwlVersion: v1.2
class: CommandLineTool
baseCommand: para
label: ucsc-para_para
doc: "Manage a batch of jobs in parallel on a compute cluster.\n\nTool homepage: http://hgdownload.cse.ucsc.edu/admin/exe/"
inputs:
  - id: command
    type: string
    doc: The command to execute (e.g., create, push, check)
    inputBinding:
      position: 1
  - id: command_specific_arguments
    type:
      - 'null'
      - type: array
        items: string
    doc: Arguments specific to the chosen command
    inputBinding:
      position: 2
  - id: job_list
    type:
      - 'null'
      - File
    doc: A text file with the command line for each job on a separate line.
    inputBinding:
      position: 3
  - id: time
    type:
      - 'null'
      - string
    doc: Time in minutes for filtering running jobs.
    inputBinding:
      position: 4
  - id: new_job_list
    type:
      - 'null'
      - File
    doc: A new job list generated by selecting jobs from an existing list where 
      the 'check out' tests fail.
    inputBinding:
      position: 5
  - id: batch
    type:
      - 'null'
      - Directory
    doc: Specify the directory path that is used to store the batch control 
      files. The directory is created if it doesn't exist. If used, this option 
      must be specified on all para commands for the batch.
    inputBinding:
      position: 106
      prefix: -batch
  - id: cpu
    type:
      - 'null'
      - int
    doc: Number of CPUs used by the jobs.
    default: 1
    inputBinding:
      position: 106
      prefix: -cpu
  - id: delay_time
    type:
      - 'null'
      - int
    doc: Number of seconds to delay before submitting next job to minimize i/o 
      load at startup.
    default: 0
    inputBinding:
      position: 106
      prefix: -delayTime
  - id: job_cwd
    type:
      - 'null'
      - Directory
    doc: Specify the directory path to use as the current working directory for 
      each job. It defaults to the directory where para is run.
    inputBinding:
      position: 106
      prefix: -jobCwd
  - id: kill_time
    type:
      - 'null'
      - int
    doc: Number of minutes hung job runs before push kills it.
    inputBinding:
      position: 106
      prefix: -killTime
  - id: max_job
    type:
      - 'null'
      - string
    doc: Limit the number of jobs the batch can run. Specify number of jobs, for
      example 10 or 'unlimited'. Default unlimited displays as -1.
    default: unlimited
    inputBinding:
      position: 106
      prefix: -maxJob
  - id: max_push
    type:
      - 'null'
      - int
    doc: Maximum number of jobs to queue.
    default: 100000
    inputBinding:
      position: 106
      prefix: -maxPush
  - id: max_queue
    type:
      - 'null'
      - int
    doc: Number of jobs to allow on parasol queue.
    default: 2000000
    inputBinding:
      position: 106
      prefix: -maxQueue
  - id: min_push
    type:
      - 'null'
      - int
    doc: Minimum number of jobs to queue. Overrides maxQueue.
    default: 1
    inputBinding:
      position: 106
      prefix: -minPush
  - id: priority
    type:
      - 'null'
      - string
    doc: Set batch priority to high, medium, or low. Default medium. Or, set 
      batch priority to a specific numeric value - default 10.
    default: medium
    inputBinding:
      position: 106
      prefix: -priority
  - id: ram
    type:
      - 'null'
      - string
    doc: Number of bytes of RAM used by the jobs. Shorthand expressions allow 
      t,g,m,k for tera, giga, mega, kilo. e.g. 4g = 4 Gigabytes.
    inputBinding:
      position: 106
      prefix: -ram
  - id: retries
    type:
      - 'null'
      - int
    doc: Number of retries per job.
    default: 4
    inputBinding:
      position: 106
      prefix: -retries
  - id: verbose
    type:
      - 'null'
      - int
    doc: Set verbosity level.
    inputBinding:
      position: 106
      prefix: -verbose
  - id: warn_time
    type:
      - 'null'
      - int
    doc: Number of minutes job runs before hang warning.
    default: 4320
    inputBinding:
      position: 106
      prefix: -warnTime
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ucsc-para:469--h664eb37_1
stdout: ucsc-para_para.out
