cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cnvetti
  - cmd
  - normalize
label: cnvetti_cmd_normalize
doc: "Normalize coverage on a per-sample level. This command takes the coverage BCF file generated by `cmd coverage` and performs normalization on the whole-sample level.\n\nTool homepage: https://github.com/bihealth/cnvetti"
inputs:
  - id: input
    type: File
    secondaryFiles:
      - .csi
    doc: "Path to indexed input BCF or VCF file from `cnvetti cmd coverage` output."
    inputBinding:
      position: 101
      prefix: --input
  - id: output
    type: string
    doc: "Path to output BCF file (will also write .csi file)"
    inputBinding:
      position: 101
      prefix: --output
  - id: normalization
    type: string
    doc: "The method to use for read count/coverage normalization. Possible values: TotalCoverageSum, CoverageMedian, MedianGcBinned, ExcavatorStyle"
    inputBinding:
      position: 101
      prefix: --normalization
  - id: min_gc_window_count
    type:
      - 'null'
      - int
    doc: "Flag windows of GC content with an occurence of less than `COUNT` as `INFO/FEW_GCWINDOWS`. (default 100)"
    inputBinding:
      position: 101
      prefix: --min-gc-window-count
  - id: contig_regex
    type:
      - 'null'
      - string
    doc: "Regular expression for contigs taking part in statistics. (default ^(chr)?\\d\\d?$)"
    inputBinding:
      position: 101
      prefix: --contig-regex
  - id: io_threads
    type:
      - 'null'
      - int
    doc: "Number of additional threads to use for (de)compression in I/O."
    inputBinding:
      position: 101
      prefix: --io-threads
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: "Decrease verbosity"
    inputBinding:
      position: 101
      prefix: --quiet
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Increase verbosity"
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: "Path to output BCF file (will also write .csi file)"
    outputBinding:
      glob: $(inputs.output)
    secondaryFiles:
      - .csi
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/cnvetti:0.2.0--he4cf2ce_0
