cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cnvetti
  - cmd
  - mod-coverage
label: cnvetti_cmd_mod-coverage
doc: "Compute coverage with information from a model. This command takes a coverage BCF file as created by `cmd coverage` and a model BCF file generated by one of the `cmd build-model-*` commands.\n\nTool homepage: https://github.com/bihealth/cnvetti"
inputs:
  - id: input
    type: File
    secondaryFiles:
      - .csi
    doc: "Path to indexed BCF file containing normalized counts."
    inputBinding:
      position: 1
  - id: output
    type: string
    doc: "Path to output normalized counts BCF file."
    inputBinding:
      position: 101
      prefix: --output
  - id: input_wis_model
    type:
      - 'null'
      - File
    secondaryFiles:
      - .csi
    doc: "Path to BCF file with the within-sample model (give this or input_pool_model)."
    inputBinding:
      position: 101
      prefix: --input-wis-model
  - id: input_pool_model
    type:
      - 'null'
      - File
    secondaryFiles:
      - .csi
    doc: "Path to BCF file with the pool-of-reference model (give this or input_wis_model)."
    inputBinding:
      position: 101
      prefix: --input-pool-model
  - id: io_threads
    type:
      - 'null'
      - int
    doc: "Number of additional threads to use for (de)compression in I/O."
    inputBinding:
      position: 101
      prefix: --io-threads
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: "Decrease verbosity"
    inputBinding:
      position: 101
      prefix: --quiet
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Increase verbosity"
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: "Path to output normalized counts BCF file."
    outputBinding:
      glob: $(inputs.output)
    secondaryFiles:
      - .csi
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/cnvetti:0.2.0--he4cf2ce_0
