cwlVersion: v1.2
class: CommandLineTool
baseCommand: percolator
label: percolator
doc: "Semi-supervised learning for peptide identification from shotgun proteomics
  datasets.\n\nTool homepage: https://github.com/percolator/percolator"
inputs:
  - id: input_file
    type: File
    doc: Input file in pin-tab format (tab delimited output file generated by e.g.
      sqt2pin).
    inputBinding:
      position: 1
  - id: cneg
    type:
      - 'null'
      - float
    doc: Cneg, penalty for mistakes made on negative examples. Set by cross validation
      if not specified or if -p is not specified.
    inputBinding:
      position: 102
      prefix: --Cneg
  - id: composition_match
    type:
      - 'null'
      - boolean
    doc: Run an implementation of the Percolator-RESET psmsAndPeptides with target-decoy
      matching based on composition.
    inputBinding:
      position: 102
      prefix: --composition-match
  - id: cpos
    type:
      - 'null'
      - float
    doc: Cpos, penalty for mistakes made on positive examples. Set by cross validation
      if not specified.
    inputBinding:
      position: 102
      prefix: --Cpos
  - id: decoy_xml_output
    type:
      - 'null'
      - boolean
    doc: Include decoys (PSMs, peptides and/or proteins) in the xml-output. Only available
      if -X is set.
    inputBinding:
      position: 102
      prefix: --decoy-xml-output
  - id: default_direction
    type:
      - 'null'
      - string
    doc: Use given feature name as initial search direction, can be negated to indicate
      that a lower value is better.
    inputBinding:
      position: 102
      prefix: --default-direction
  - id: init_weights
    type:
      - 'null'
      - File
    doc: Read the unnormalized initial weights from the third line of the given file.
    inputBinding:
      position: 102
      prefix: --init-weights
  - id: maxiter
    type:
      - 'null'
      - int
    doc: Maximal number of iterations.
    default: 10
    inputBinding:
      position: 102
      prefix: --maxiter
  - id: nested_xval_bins
    type:
      - 'null'
      - int
    doc: Number of nested cross validation bins within each cross validation bin.
    default: 1
    inputBinding:
      position: 102
      prefix: --nested-xval-bins
  - id: no_analytics
    type:
      - 'null'
      - boolean
    doc: Switch off analytics reporting
    inputBinding:
      position: 102
      prefix: --no-analytics
  - id: no_schema_validation
    type:
      - 'null'
      - boolean
    doc: Skip validation of input file against xml schema.
    inputBinding:
      position: 102
      prefix: --no-schema-validation
  - id: no_terminate
    type:
      - 'null'
      - boolean
    doc: Do not stop execution when encountering questionable SVM inputs or results.
    inputBinding:
      position: 102
      prefix: --no-terminate
  - id: num_threads
    type:
      - 'null'
      - int
    doc: Number of total parallel threads for SVM training during cross validation.
    default: 3
    inputBinding:
      position: 102
      prefix: --num-threads
  - id: only_psms
    type:
      - 'null'
      - boolean
    doc: Report results only at the PSM level.
    inputBinding:
      position: 102
      prefix: --only-psms
  - id: output_retention_time
    type:
      - 'null'
      - boolean
    doc: Adds retention time column to the output file
    inputBinding:
      position: 102
      prefix: --output-retention-time
  - id: override
    type:
      - 'null'
      - boolean
    doc: Override error check and do not fall back on default score vector in case
      of suspect score vector from SVM.
    inputBinding:
      position: 102
      prefix: --override
  - id: parameter_file
    type:
      - 'null'
      - File
    doc: Read flags from a parameter file.
    inputBinding:
      position: 102
      prefix: --parameter-file
  - id: picked_protein
    type:
      - 'null'
      - string
    doc: Use the picked protein-level FDR to infer protein probabilities. Provide
      the fasta file or "auto".
    inputBinding:
      position: 102
      prefix: --picked-protein
  - id: post_processing_mix_max
    type:
      - 'null'
      - boolean
    doc: Use the mix-max method to assign q-values and PEPs. This is the default setting.
    inputBinding:
      position: 102
      prefix: --post-processing-mix-max
  - id: post_processing_tdc
    type:
      - 'null'
      - boolean
    doc: Replace the mix-max method by target-decoy competition for assigning q-values
      and PEPs.
    inputBinding:
      position: 102
      prefix: --post-processing-tdc
  - id: protein_decoy_pattern
    type:
      - 'null'
      - string
    doc: Define the prefix to identify decoy proteins in the database for the picked-protein
      algorithm.
    default: auto
    inputBinding:
      position: 102
      prefix: --protein-decoy-pattern
  - id: protein_enzyme
    type:
      - 'null'
      - string
    doc: Type of enzyme used for in silico protein digestion for picked protein-level
      FDR estimation.
    default: trypsin
    inputBinding:
      position: 102
      prefix: --protein-enzyme
  - id: protein_name_separator
    type:
      - 'null'
      - string
    doc: The separator used in tab delimited input and output for separating protein
      names. Default = tab-char.
    inputBinding:
      position: 102
      prefix: --protein-name-separator
  - id: protein_report_duplicates
    type:
      - 'null'
      - boolean
    doc: Report IDs of duplicated proteins as a comma-separated list.
    inputBinding:
      position: 102
      prefix: --protein-report-duplicates
  - id: protein_report_fragments
    type:
      - 'null'
      - boolean
    doc: Report a comma-separated list of protein IDs for fragment proteins.
    inputBinding:
      position: 102
      prefix: --protein-report-fragments
  - id: quick_validation
    type:
      - 'null'
      - boolean
    doc: Quicker execution by reduced internal cross-validation.
    inputBinding:
      position: 102
      prefix: --quick-validation
  - id: reset_algorithm
    type:
      - 'null'
      - boolean
    doc: Run an implementation of the Percolator-RESET Algorithm.
    inputBinding:
      position: 102
      prefix: --reset-algorithm
  - id: search_input
    type:
      - 'null'
      - string
    doc: 'Specify the type of target-decoy search: "auto", "concatenated" or "separate".'
    default: auto
    inputBinding:
      position: 102
      prefix: --search-input
  - id: seed
    type:
      - 'null'
      - int
    doc: Set seed of the random number generator.
    default: 1
    inputBinding:
      position: 102
      prefix: --seed
  - id: spectral_counting_fdr
    type:
      - 'null'
      - float
    doc: Activates spectral counting on protein level at the specified PSM q-value
      threshold.
    inputBinding:
      position: 102
      prefix: --spectral-counting-fdr
  - id: static
    type:
      - 'null'
      - boolean
    doc: Use the provided initial weights as a static model. If used, the --init-weights
      option must be specified.
    inputBinding:
      position: 102
      prefix: --static
  - id: stdinput_tab
    type:
      - 'null'
      - boolean
    doc: Read percolator tab-input format (pin-tab) from standard input
    inputBinding:
      position: 102
      prefix: --stdinput-tab
  - id: stdinput_xml
    type:
      - 'null'
      - boolean
    doc: Read percolator xml-input format (pin-xml) from standard input
    inputBinding:
      position: 102
      prefix: --stdinput-xml
  - id: subset_max_train
    type:
      - 'null'
      - int
    doc: Only train an SVM on a subset of <x> PSMs, and use the resulting score vector
      to evaluate the other PSMs.
    default: 0
    inputBinding:
      position: 102
      prefix: --subset-max-train
  - id: tab_in
    type:
      - 'null'
      - File
    doc: Input file given in pin-tab format. This is the default setting.
    inputBinding:
      position: 102
      prefix: --tab-in
  - id: test_each_iteration
    type:
      - 'null'
      - boolean
    doc: Measure performance on test set each iteration
    inputBinding:
      position: 102
      prefix: --test-each-iteration
  - id: test_fdr
    type:
      - 'null'
      - float
    doc: False discovery rate threshold for evaluating best cross validation result
      and reported end result.
    default: 0.01
    inputBinding:
      position: 102
      prefix: --testFDR
  - id: train_best_positive
    type:
      - 'null'
      - boolean
    doc: Enforce that, for each spectrum, at most one PSM is included in the positive
      set during each training iteration.
    inputBinding:
      position: 102
      prefix: --train-best-positive
  - id: train_fdr
    type:
      - 'null'
      - float
    doc: False discovery rate threshold to define positive examples in training. Set
      to testFDR if 0.
    default: 0.01
    inputBinding:
      position: 102
      prefix: --trainFDR
  - id: train_fdr_initial
    type:
      - 'null'
      - float
    doc: Set the FDR threshold for the first iteration.
    inputBinding:
      position: 102
      prefix: --train-fdr-initial
  - id: unitnorm
    type:
      - 'null'
      - boolean
    doc: Use unit normalization [0-1] instead of standard deviation normalization
    inputBinding:
      position: 102
      prefix: --unitnorm
  - id: verbose
    type:
      - 'null'
      - int
    doc: 'Set verbosity of output: 0=no processing info, 5=all.'
    default: 2
    inputBinding:
      position: 102
      prefix: --verbose
  - id: xml_in
    type:
      - 'null'
      - File
    doc: Input file given in deprecated pin-xml format.
    inputBinding:
      position: 102
      prefix: --xml-in
outputs:
  - id: xmloutput
    type:
      - 'null'
      - File
    doc: Path to xml-output (pout) file.
    outputBinding:
      glob: $(inputs.xmloutput)
  - id: pepxml_output
    type:
      - 'null'
      - File
    doc: Write a rudimentary pepXML file with psm-level statistics to the specified
      filename.
    outputBinding:
      glob: $(inputs.pepxml_output)
  - id: tab_out
    type:
      - 'null'
      - File
    doc: Output computed features to given file in pin-tab format.
    outputBinding:
      glob: $(inputs.tab_out)
  - id: weights
    type:
      - 'null'
      - File
    doc: Output final weights to the given file
    outputBinding:
      glob: $(inputs.weights)
  - id: results_peptides
    type:
      - 'null'
      - File
    doc: Output tab delimited results of peptides to a file instead of stdout
    outputBinding:
      glob: $(inputs.results_peptides)
  - id: decoy_results_peptides
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy peptides into a file
    outputBinding:
      glob: $(inputs.decoy_results_peptides)
  - id: results_psms
    type:
      - 'null'
      - File
    doc: Output tab delimited results of PSMs to a file instead of stdout
    outputBinding:
      glob: $(inputs.results_psms)
  - id: decoy_results_psms
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy PSMs into a file
    outputBinding:
      glob: $(inputs.decoy_results_psms)
  - id: results_proteins
    type:
      - 'null'
      - File
    doc: Output tab delimited results of proteins to a file instead of stdout
    outputBinding:
      glob: $(inputs.results_proteins)
  - id: decoy_results_proteins
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy proteins into a file
    outputBinding:
      glob: $(inputs.decoy_results_proteins)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/percolator:3.7.1--h3b5f4bd_2
