cwlVersion: v1.2
class: CommandLineTool
baseCommand: ccsmeth_call_mods
label: ccsmeth_call_mods
doc: "call modifications\n\nTool homepage: https://github.com/PengNi/ccsmeth"
inputs:
  - id: batch_size
    type:
      - 'null'
      - int
    doc: batch size, default 512
    inputBinding:
      position: 101
      prefix: --batch_size
  - id: class_num
    type:
      - 'null'
      - int
    inputBinding:
      position: 101
      prefix: --class_num
  - id: d_model
    type:
      - 'null'
      - int
    doc: TransformerEncoder input feature numbers, default 256
    inputBinding:
      position: 101
      prefix: --d_model
  - id: dim_ff
    type:
      - 'null'
      - int
    doc: TransformerEncoder dim_feedforward, default 512
    inputBinding:
      position: 101
      prefix: --dim_ff
  - id: dropout_rate
    type:
      - 'null'
      - float
    inputBinding:
      position: 101
      prefix: --dropout_rate
  - id: gzip
    type:
      - 'null'
      - boolean
    doc: if compressing .per_readsite.tsv when --input is not in bam/sam format.
    inputBinding:
      position: 101
      prefix: --gzip
  - id: hid_rnn
    type:
      - 'null'
      - int
    doc: BiRNN hidden_size, default 256
    inputBinding:
      position: 101
      prefix: --hid_rnn
  - id: holeids_e
    type:
      - 'null'
      - File
    doc: file contains holeids to be extracted, default None
    inputBinding:
      position: 101
      prefix: --holeids_e
  - id: holeids_ne
    type:
      - 'null'
      - File
    doc: file contains holeids not to be extracted, default None
    inputBinding:
      position: 101
      prefix: --holeids_ne
  - id: holes_batch
    type:
      - 'null'
      - int
    doc: number of holes/hifi-reads in an batch to get/put in queues, default 
      50. only used when --input is bam/sam
    inputBinding:
      position: 101
      prefix: --holes_batch
  - id: identity
    type:
      - 'null'
      - float
    doc: identity cutoff for selecting alignment items, [0.0, 1.0], default 0.0
    inputBinding:
      position: 101
      prefix: --identity
  - id: input
    type: File
    doc: input file, can be bam/sam, or features.tsv generated by 
      extract_features.py.
    inputBinding:
      position: 101
      prefix: --input
  - id: is_map
    type:
      - 'null'
      - boolean
    doc: if using mapping features, yes or no, default no. Effects both MODEL 
      input and feature EXTRACTION, only works in EXTRACTION-ALIGN-MODE
    inputBinding:
      position: 101
      prefix: --is_map
  - id: is_npass
    type:
      - 'null'
      - boolean
    doc: if using num_pass features, yes or no, default yes
    inputBinding:
      position: 101
      prefix: --is_npass
  - id: is_sn
    type:
      - 'null'
      - boolean
    doc: if using signal-to-noise-ratio features, yes or no, default no. Effects
      both MODEL input and feature EXTRACTION
    inputBinding:
      position: 101
      prefix: --is_sn
  - id: is_stds
    type:
      - 'null'
      - boolean
    doc: if using std features, yes or no, default no
    inputBinding:
      position: 101
      prefix: --is_stds
  - id: keep_pulse
    type:
      - 'null'
      - boolean
    doc: if keeping ipd/pw tags in .modbam.bam when --input is in bam/sam 
      format.
    inputBinding:
      position: 101
      prefix: --keep_pulse
  - id: layer_rnn
    type:
      - 'null'
      - int
    doc: BiRNN layer num, default 3
    inputBinding:
      position: 101
      prefix: --layer_rnn
  - id: layer_trans
    type:
      - 'null'
      - int
    doc: TransformerEncoder nlayers, default 6
    inputBinding:
      position: 101
      prefix: --layer_trans
  - id: mapq
    type:
      - 'null'
      - int
    doc: MAPping Quality cutoff for selecting alignment items, default 1
    inputBinding:
      position: 101
      prefix: --mapq
  - id: methy_label
    type:
      - 'null'
      - string
    doc: the label of the interested modified bases, this is for training. 0 or 
      1, default 1
    inputBinding:
      position: 101
      prefix: --methy_label
  - id: mod_loc
    type:
      - 'null'
      - int
    doc: 0-based location of the targeted base in the motif, default 0
    inputBinding:
      position: 101
      prefix: --mod_loc
  - id: mode
    type:
      - 'null'
      - string
    doc: 'denovo mode: extract features from unaligned/aligned hifi.bam without reference
      position info; align mode: extract features from aligned hifi.bam with reference
      position info. default: denovo'
    inputBinding:
      position: 101
      prefix: --mode
  - id: model_file
    type: File
    doc: file path of the trained model (.ckpt)
    inputBinding:
      position: 101
      prefix: --model_file
  - id: model_type
    type:
      - 'null'
      - string
    doc: "type of model to use, 'attbilstm2s', 'attbigru2s', 'transencoder2s', 'attbilstm2s2',
      'attbigru2s2', default: attbigru2s"
    inputBinding:
      position: 101
      prefix: --model_type
  - id: motifs
    type:
      - 'null'
      - string
    doc: 'motif seq to be extracted, default: CG. can be multi motifs splited by comma
      (no space allowed in the input str), or use IUPAC alphabet, the mod_loc of all
      motifs must be the same'
    inputBinding:
      position: 101
      prefix: --motifs
  - id: nhead
    type:
      - 'null'
      - int
    doc: TransformerEncoder nhead, default 4
    inputBinding:
      position: 101
      prefix: --nhead
  - id: no_decode
    type:
      - 'null'
      - boolean
    doc: not use CodecV1 to decode ipd/pw
    inputBinding:
      position: 101
      prefix: --no_decode
  - id: no_sort
    type:
      - 'null'
      - boolean
    doc: don't sort .modbam.bam when --input is in bam/sam format.
    inputBinding:
      position: 101
      prefix: --no_sort
  - id: no_supplementary
    type:
      - 'null'
      - boolean
    doc: not use supplementary alignment
    inputBinding:
      position: 101
      prefix: --no_supplementary
  - id: norm
    type:
      - 'null'
      - string
    doc: method for normalizing ipd/pw in subread level. zscore, min-mean, 
      min-max, mad, or none. default zscore
    inputBinding:
      position: 101
      prefix: --norm
  - id: ref
    type:
      - 'null'
      - File
    doc: path to genome reference to be aligned, in fasta/fa format.
    inputBinding:
      position: 101
      prefix: --ref
  - id: seq_len
    type:
      - 'null'
      - int
    doc: len of kmer. default 21
    inputBinding:
      position: 101
      prefix: --seq_len
  - id: skip_unmapped
    type:
      - 'null'
      - boolean
    doc: if skipping unmapped sites in reads, yes or no, default yes
    inputBinding:
      position: 101
      prefix: --skip_unmapped
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads to be used, default 10.
    inputBinding:
      position: 101
      prefix: --threads
  - id: threads_call
    type:
      - 'null'
      - int
    doc: number of threads used to call modifications with trained models, no 
      more than threads/3 is suggested. default 3.
    inputBinding:
      position: 101
      prefix: --threads_call
  - id: tseed
    type:
      - 'null'
      - int
    doc: random seed for torch
    inputBinding:
      position: 101
      prefix: --tseed
  - id: use_compile
    type:
      - 'null'
      - string
    doc: if using torch.compile, yes or no, default no ('yes' only works in 
      pytorch>=2.0)
    inputBinding:
      position: 101
      prefix: --use_compile
outputs:
  - id: output
    type: File
    doc: the prefix of output files to save the predicted results. output files 
      will be [--output].per_readsite.tsv/.modbam.bam
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ccsmeth:0.5.0--pyhdfd78af_0
