cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - bwa
  - samse
label: bwa-aln-interactive_samse
doc: "Generate alignments in the SAM format for single-end reads\n\nTool homepage:
  https://github.com/fulcrumgenomics/bwa-aln-interactive"
inputs:
  - id: prefix
    type: string
    doc: Prefix of the BWA index
    inputBinding:
      position: 1
  - id: in_sai
    type: File
    doc: Input SAI file generated by bwa aln
    inputBinding:
      position: 2
  - id: in_fq
    type: File
    doc: Input FASTQ file
    inputBinding:
      position: 3
  - id: max_occ
    type:
      - 'null'
      - int
    doc: Maximum occurrences for one end
    inputBinding:
      position: 104
      prefix: -n
  - id: rg_line
    type:
      - 'null'
      - string
    doc: Read group line
    inputBinding:
      position: 104
      prefix: -r
outputs:
  - id: output_sam
    type:
      - 'null'
      - File
    doc: Output SAM file
    outputBinding:
      glob: $(inputs.output_sam)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwa-aln-interactive:0.7.18--h577a1d6_2
