cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - bwa-aln-interactive
  - samse
label: bwa-aln-interactive_samse
doc: "Generate alignments in the SAM format for single-end reads\n\nTool homepage:
  https://github.com/fulcrumgenomics/bwa-aln-interactive"
inputs:
  - id: prefix
    type: File
    doc: The bwa index, given as its .bwt file (for example ref.fa.bwt from bwa index) or
      as the file named like the index prefix (for example ref.fa); the .amb, .ann,
      .bwt, .pac and .sa files must sit beside it
    secondaryFiles:
      - pattern: "${ var b = self.basename.replace(/\\.bwt$/, ''); var s = ['.amb', '.ann', '.pac', '.sa']; if (b === self.basename) { s.push('.bwt'); } return s.map(function (e) { return b + e; }); }"
        required: true
    inputBinding:
      position: 1
      valueFrom: $(self.path.replace(/\.bwt$/, ''))
  - id: in_sai
    type: File
    doc: Input SAI file generated by bwa aln
    inputBinding:
      position: 2
  - id: in_fq
    type: File
    doc: Input FASTQ file
    inputBinding:
      position: 3
  - id: max_occ
    type:
      - 'null'
      - int
    doc: Maximum occurrences for one end
    inputBinding:
      position: 104
      prefix: -n
  - id: rg_line
    type:
      - 'null'
      - string
    doc: Read group line
    inputBinding:
      position: 104
      prefix: -r
  - id: output_sam_path
    type: string
    doc: Output or path parameter `output_sam_path`
    inputBinding:
      position: 105
      prefix: -f
outputs:
  - id: output_sam
    type:
      - 'null'
      - File
    doc: Output SAM file
    outputBinding:
      glob: $(inputs.output_sam_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwa-aln-interactive:0.7.18--h577a1d6_2
