cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - vpt
  - compile-tile-segmentation
label: vpt_compile-tile-segmentation
doc: "Combines the per-tile segmentation outputs into a single, internally-consistent
  parquet file containing all of the segmentation boundaries found in the experiment.\n\
  \nTool homepage: https://github.com/Vizgen/vizgen-postprocessing"
inputs:
  - id: input_segmentation_parameters
    type: File
    doc: Json file generated by prepare-segmentation that fully specifies the 
      segmentation to run.
    inputBinding:
      position: 101
      prefix: --input-segmentation-parameters
  - id: max_row_group_size
    type:
      - 'null'
      - int
    doc: Maximum number of rows in row groups inside output parquet files. 
      Cannot be less than 1000
    inputBinding:
      position: 101
      prefix: --max-row-group-size
  - id: overwrite
    type:
      - 'null'
      - boolean
    doc: Set flag if you want to use non empty directory and agree that files 
      can be over-written.
    inputBinding:
      position: 101
      prefix: --overwrite
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/vpt:1.3.0--pyhdfd78af_0
stdout: vpt_compile-tile-segmentation.out
