cwlVersion: v1.2
class: CommandLineTool
baseCommand: centreseq_tree
label: centreseq_tree
doc: "Processes centreseq core output files to produce files that can be fed into
  phylogenetic tree building software.\n\nTool homepage: https://github.com/bfssi-forest-dussault/centreseq"
inputs:
  - id: n_cpu
    type:
      - 'null'
      - int
    doc: Number of CPUs to dedicate to parallelizable steps of the pipeline.Will
      take all available CPUs - 1 if not specified.
    inputBinding:
      position: 101
      prefix: --n-cpu
  - id: percentile
    type:
      - 'null'
      - float
    doc: Filter summary report by n_members to the top nth percentile.
    inputBinding:
      position: 101
      prefix: --percentile
  - id: prokka_dir
    type: Directory
    doc: Path to the Prokka output directory generated by the core pipeline
    inputBinding:
      position: 101
      prefix: --prokka-dir
  - id: summary_report
    type: File
    doc: Path to summary_report.csv file produced by the core pipeline
    inputBinding:
      position: 101
      prefix: --summary-report
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Set this flag to enable more verbose logging.
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: outdir
    type: Directory
    doc: Root directory to store all output files
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/centreseq:0.3.8--py_0
