cwlVersion: v1.2
class: CommandLineTool
baseCommand: centreseq_subset
label: centreseq_subset
doc: "Given an input text file of Sample IDs and a summary report, will return a filtered
  version of the summary report for clusters that belong exclusively in the input
  sample ID list\n\nTool homepage: https://github.com/bfssi-forest-dussault/centreseq"
inputs:
  - id: input_samples
    type: File
    doc: Path to a new line separated text file containing each Sample ID to 
      target
    inputBinding:
      position: 101
      prefix: --input-samples
  - id: summary_report
    type: File
    doc: Path to summary report generated by the centreseq core command, i.e. 
      summary_report.tsv
    inputBinding:
      position: 101
      prefix: --summary-report
outputs:
  - id: outpath
    type:
      - 'null'
      - File
    doc: Path to desired output file. If no value is provided, will create a new
      report in the same directory as the input summary report.
    outputBinding:
      glob: $(inputs.outpath)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/centreseq:0.3.8--py_0
