cwlVersion: v1.2
class: CommandLineTool
baseCommand: orfanage
label: orfanage
doc: "Annotating Open Reading Frames based on reference, phylogeny and sequence similarity.\n\
  \nTool homepage: https://github.com/alevar/ORFanage"
inputs:
  - id: templates
    type:
      type: array
      items: File
    doc: One or more GFF/GTF files with coding exons to be used as templates.
    inputBinding:
      position: 1
  - id: cleanq
    type:
      - 'null'
      - boolean
    doc: If enabled - will ensure all transcripts in the output file will have a
      valid start and end codons. This option requires the use of --reference 
      parameter
    inputBinding:
      position: 102
      prefix: --cleanq
  - id: cleant
    type:
      - 'null'
      - boolean
    doc: If enabled - will ensure all ORFs in the reference annotations start 
      with a valid start codon and end with the first available stop codon. This
      option requires the use of --reference parameter
    inputBinding:
      position: 102
      prefix: --cleant
  - id: ilpi
    type:
      - 'null'
      - int
    doc: Percent identity by length of bases in frame of the reference 
      transcript. If -1 (default) is set - the check will not be performed.
    inputBinding:
      position: 102
      prefix: --ilpi
  - id: keep_all_cds
    type:
      - 'null'
      - boolean
    doc: Mutually exclusive with '--keep_cds_if_not_found'. If enabled, any CDS 
      already present in the query will be kept unmodified.
    inputBinding:
      position: 102
      prefix: --keep_all_cds
  - id: keep_cds_if_not_found
    type:
      - 'null'
      - boolean
    doc: Mutually exclusive with '--keep_all_cds'. If enabled, will still search
      for new ORF in each query transcript. If query transcript has CDS 
      annotated, and no ORF can be identified by the method, the original will 
      be kept. Original CDS will be replaced if a valid ORF can be found. Use 
      '--keep_all_cds' to retain all unmodified CDS in query.
    inputBinding:
      position: 102
      prefix: --keep_cds_if_not_found
  - id: lpi
    type:
      - 'null'
      - int
    doc: Percent identity by length between the original and reference 
      transcripts. If -1 (default) is set - the check will not be performed.
    inputBinding:
      position: 102
      prefix: --lpi
  - id: minlen
    type:
      - 'null'
      - int
    doc: Minimum length of an open reading frame to consider for the analysis
    inputBinding:
      position: 102
      prefix: --minlen
  - id: mlpi
    type:
      - 'null'
      - int
    doc: Percent identity by length of bases that are in both query and 
      reference. If -1 (default) is set - the check will not be performed.
    inputBinding:
      position: 102
      prefix: --mlpi
  - id: mode
    type:
      - 'null'
      - string
    doc: 'Which CDS to report: ALL, LONGEST, LONGEST_MATCH, BEST, START_MATCH. Default:
      LONGEST_MATCH'
    inputBinding:
      position: 102
      prefix: --mode
  - id: non_aug
    type:
      - 'null'
      - boolean
    doc: If enabled, non-AUG start codons in reference transcripts will not be 
      discarded and will be considered in overlapping query transcripts on equal
      grounds with the AUG start codon.
    inputBinding:
      position: 102
      prefix: --non_aug
  - id: output
    type:
      - 'null'
      - string
    doc: Basename for all output files generated by this software
    inputBinding:
      position: 102
      prefix: --output
  - id: overhang
    type:
      - 'null'
      - int
    doc: If enabled, will also evaluate nucleotide sequence up and downstream up
      to N bases as set for the argument.
    inputBinding:
      position: 102
      prefix: --overhang
  - id: query
    type:
      - 'null'
      - string
    doc: Path to a GTF query file with transcripts to which CDSs are to be 
      ported
    inputBinding:
      position: 102
      prefix: --query
  - id: reference
    type:
      - 'null'
      - File
    doc: 'Path to the reference genome file in FASTA format. This parameter is required
      when the following parameters are used: 1. cleanq; 2. cleant; 3. pi.'
    inputBinding:
      position: 102
      prefix: --reference
  - id: rescue
    type:
      - 'null'
      - boolean
    doc: If enabled - will attempt rescuing the broken ORFs in the reference 
      annotations. This option requires the use of --reference parameter
    inputBinding:
      position: 102
      prefix: --rescue
  - id: spliced_overhang
    type:
      - 'null'
      - boolean
    doc: Only in effect when combined with the '--overhang' parameter. If 
      enabled, this option will extend the sequence up to the '--overhang' 
      number of bases, but terminate prematurely if either a splice donor (if 
      extending towards 3') or splice acceptor (if extending towards 5') is 
      detected.
    inputBinding:
      position: 102
      prefix: --spliced_overhang
  - id: stats
    type:
      - 'null'
      - string
    doc: Output a separate file with stats for each query/template pair
    inputBinding:
      position: 102
      prefix: --stats
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to run in parallel
    inputBinding:
      position: 102
      prefix: --threads
  - id: use_id
    type:
      - 'null'
      - boolean
    doc: If enabled, only transcripts with the same gene ID from the query file 
      will be used to form a bundle. In this mode the same template transcript 
      may be used in several bundles, if overlaps transcripts with different 
      gene_ids.
    inputBinding:
      position: 102
      prefix: --use_id
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/orfanage:1.2.0--ha666654_1
stdout: orfanage.out
