cwlVersion: v1.2
class: CommandLineTool
baseCommand: RiboCode
label: ribocode_RiboCode
doc: "The main function designed for detecting ORF using ribosome-profiling data.\n\
  \nTool homepage: https://github.com/xryanglab/RiboCode"
inputs:
  - id: alt_start_codons
    type:
      - 'null'
      - string
    doc: 'The alternative start codon, such as CTG,GTG, default: None. Multiple codons
      should be separated by comma.'
    default: None
    inputBinding:
      position: 101
      prefix: --alt_start_codons
  - id: annot_dir
    type: Directory
    doc: transcripts annotation directory, generated by prepare_transcripts.
    inputBinding:
      position: 101
      prefix: --annot_dir
  - id: config_file
    type: File
    doc: list bam file and P-sites information in this file, please refer to the
      example file in data folder.
    inputBinding:
      position: 101
      prefix: --config_file
  - id: dependence_test
    type:
      - 'null'
      - string
    doc: 'the method for measuring the dependence between frame1 and frame2. This
      test could help determine whether the combined p-values should be ajusted to
      account for the dependence between two test (i.e. F0 vs F1 and F0 vs F2). mic:
      Maximal Information Coefficient; pcc: Pearson Correlation Coefficient.'
    default: none
    inputBinding:
      position: 101
      prefix: --dependence_test
  - id: longest_orf
    type:
      - 'null'
      - string
    doc: the region from most distal AUG to stop was defined as an ORF. If set 
      to no , the position of start codon will be automatically determined by 
      program.
    default: yes
    inputBinding:
      position: 101
      prefix: --longest-orf
  - id: min_aa_length
    type:
      - 'null'
      - int
    doc: The minimal length of predicted peptides,default 5
    default: 5
    inputBinding:
      position: 101
      prefix: --min-AA-length
  - id: output_bed
    type:
      - 'null'
      - boolean
    doc: output the bed file of predicted ORFs
    inputBinding:
      position: 101
      prefix: --output-bed
  - id: output_gtf
    type:
      - 'null'
      - boolean
    doc: output the gtf file of predicted ORFs
    inputBinding:
      position: 101
      prefix: --output-gtf
  - id: output_name
    type:
      - 'null'
      - string
    doc: 'output file name, default: final_result'
    default: final_result
    inputBinding:
      position: 101
      prefix: --output-name
  - id: pval_adj
    type:
      - 'null'
      - string
    doc: 'the method used to correct p-values for multiple testing. default: Benjamini/Hochberg
      method. see details at: https://www.statsmodels.org/devel/generated/statsmodels.stats.multitest.multipletests.html#statsmodels.stats.multitest.multipletests'
    inputBinding:
      position: 101
      prefix: --pval_adj
  - id: pval_cutoff
    type:
      - 'null'
      - float
    doc: P-value cutoff for ORF filtering, default 0.05
    default: 0.05
    inputBinding:
      position: 101
      prefix: --pval-cutoff
  - id: start_codon
    type:
      - 'null'
      - string
    doc: The canonical start codon.
    default: ATG
    inputBinding:
      position: 101
      prefix: --start_codon
  - id: stop_codon
    type:
      - 'null'
      - string
    doc: 'Stop codon, default: TAA,TAG,TGA'
    default: TAA,TAG,TGA
    inputBinding:
      position: 101
      prefix: --stop_codon
  - id: stouffer_adj
    type:
      - 'null'
      - string
    doc: 'the method for adjustment the cominbed p-values to account for the dependence
      between two tests (i.e. F0 vs F1 and F0 vs F2). see details at: https://search.r-project.org/CRAN/refmans/poolr/html/stouffer.html'
    default: none
    inputBinding:
      position: 101
      prefix: --stouffer_adj
  - id: transl_table
    type:
      - 'null'
      - int
    doc: 'ORF translation table(Default: 1). Assign the correct genetic code based
      on your organism, [please refer: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi
      ]'
    default: 1
    inputBinding:
      position: 101
      prefix: --transl_table
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ribocode:1.2.15--pyhdc42f0e_1
stdout: ribocode_RiboCode.out
