cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - pupmapper
  - all
label: pupmapper_all
doc: "Directory for all outputs of k-mer and pileup mappability processing.\n\nTool
  homepage: https://github.com/maxgmarin/pupmapper"
inputs:
  - id: errors
    type: int
    doc: Number of allowed mismatches (hamming distance) in k-mer mapping step.
    inputBinding:
      position: 101
      prefix: --errors
  - id: gff
    type:
      - 'null'
      - File
    doc: GFF formatted genome annotations for input genome (.gff) (Optional)
    inputBinding:
      position: 101
      prefix: --gff
  - id: in_genome_fa
    type: File
    doc: Input genome fasta file (.fasta)
    inputBinding:
      position: 101
      prefix: --in_genome_fa
  - id: kmer_len
    type: int
    doc: k-mer length (bp) used to generate the k-mer mappability values
    inputBinding:
      position: 101
      prefix: --kmer_len
  - id: prefix
    type:
      - 'null'
      - string
    doc: File prefix for all output files generated by Pupmapper. By default, 
      the prefix is the basename of the input genome fasta file.
    inputBinding:
      position: 101
      prefix: --prefix
  - id: save_bigwig
    type:
      - 'null'
      - boolean
    doc: If enabled, pileup mappability scores will be output in .bigwig format.
    inputBinding:
      position: 101
      prefix: --save-bigwig
  - id: save_numpy
    type:
      - 'null'
      - boolean
    doc: If enabled, all pileup mappability scores will be output as compressed 
      numpy arrays (.npz).
    inputBinding:
      position: 101
      prefix: --save-numpy
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Output additional messages during processing. Useful for 
      troubleshooting.
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: outdir
    type: Directory
    doc: Directory for all outputs of k-mer and pileup mappability processing.
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/pupmapper:0.2.0--pyhdfd78af_0
