cwlVersion: v1.2
class: CommandLineTool
baseCommand: hicstuff_rebin
label: hicstuff_rebin
doc: "Rebins a Hi-C matrix and modifies its fragment and chrom files accordingly.\n\
  \    Output files are in the same format as the input files (cool, graal or bg2).\n\
  \nTool homepage: https://github.com/koszullab/hicstuff"
inputs:
  - id: contact_map
    type: File
    doc: Sparse contact matrix in graal, cool or bg2 format.
    inputBinding:
      position: 1
  - id: out_prefix
    type: string
    doc: Prefix path (without extension) for the output files.
    inputBinding:
      position: 2
  - id: binning
    type:
      - 'null'
      - int
    doc: "Subsampling factor or fix value in\n                                   \
      \      basepairs to use for binning"
    inputBinding:
      position: 103
      prefix: --binning
  - id: chroms
    type:
      - 'null'
      - File
    doc: "Tab-separated with headers, containing\n                               \
      \          chromosome names, size, number of\n                             \
      \            restriction fragments. This is the file\n                     \
      \                    \"info_contigs.txt\" generated by hicstuff\n          \
      \                               pipeline."
    inputBinding:
      position: 103
      prefix: --chroms
  - id: force
    type:
      - 'null'
      - boolean
    doc: Write even if the output file already exists.
    inputBinding:
      position: 103
      prefix: --force
  - id: frags
    type:
      - 'null'
      - File
    doc: "Tab-separated file with headers,\n                                     \
      \    containing fragments start position in\n                              \
      \           the 3rd column. This is the file\n                             \
      \            \"fragments_list.txt\" generated by\n                         \
      \                hicstuff pipeline. Required for graal\n                   \
      \                      matrices and recommended for bg2."
    inputBinding:
      position: 103
      prefix: --frags
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hicstuff:3.2.4--pyhdfd78af_0
stdout: hicstuff_rebin.out
