cwlVersion: v1.2
class: CommandLineTool
baseCommand: hicstuff_convert
label: hicstuff_convert
doc: "Convert between different Hi-C dataformats. Currently supports tsv (graal),
  bedgraph2D (bg2) and cooler (cool). Input format is automatically inferred.\n\n\
  Tool homepage: https://github.com/koszullab/hicstuff"
inputs:
  - id: contact_map
    type: File
    doc: The file containing the contact frequencies.
    inputBinding:
      position: 1
  - id: prefix
    type: string
    doc: The prefix path for output files. An extension will be added to the 
      files depending on the output format.
    inputBinding:
      position: 2
  - id: chroms
    type:
      - 'null'
      - File
    doc: Tab-separated with headers, containing columns contig, length, n_frags,
      cumul_length. This is the file "info_contigs.txt" generated by hicstuff 
      pipeline.
    inputBinding:
      position: 103
      prefix: --chroms
  - id: force
    type:
      - 'null'
      - boolean
    doc: Write even if the output file already exists.
    inputBinding:
      position: 103
      prefix: --force
  - id: frags
    type:
      - 'null'
      - File
    doc: Tab-separated file with headers, containing columns id, chrom, 
      start_pos, end_pos size. This is the file "fragments_list.txt" generated 
      by hicstuff pipeline. Required for graal matrices and recommended for bg2.
    inputBinding:
      position: 103
      prefix: --frags
  - id: genome
    type:
      - 'null'
      - File
    doc: Optional genome file used to add a GC content column to the fragments 
      table. This is required to generate instagraal-compatible files.
    inputBinding:
      position: 103
      prefix: --genome
  - id: to
    type:
      - 'null'
      - string
    doc: The format to which files should be converted.
    inputBinding:
      position: 103
      prefix: --to
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hicstuff:3.2.4--pyhdfd78af_0
stdout: hicstuff_convert.out
