cwlVersion: v1.2
class: CommandLineTool
baseCommand: hicstuff_view
label: hicstuff_view
doc: "Visualize a Hi-C matrix file as a heatmap of contact frequencies. Allows to
  tune visualisation by binning and normalizing the matrix, and to save the output
  image to disk. If no output is specified, the output is displayed.\n\nTool homepage:
  https://github.com/koszullab/hicstuff"
inputs:
  - id: contact_map
    type: File
    doc: Sparse contact matrix in bg2, cool or graal format
    inputBinding:
      position: 1
  - id: contact_map2
    type:
      - 'null'
      - File
    doc: Sparse contact matrix in bg2, cool or graal format, if given, the log 
      ratio of contact_map/contact_map2 will be shown.
    inputBinding:
      position: 2
  - id: binning
    type:
      - 'null'
      - string
    doc: Rebin the matrix. If no unit is given, bins will be merged by groups of
      INT. If a unit is given, bins of that size will be generated.
    inputBinding:
      position: 103
      prefix: --binning
  - id: circular
    type:
      - 'null'
      - boolean
    doc: Use if the genome is circular.
    inputBinding:
      position: 103
      prefix: --circular
  - id: cmap
    type:
      - 'null'
      - string
    doc: The name of a matplotlib colormap to use for the matrix.
    inputBinding:
      position: 103
      prefix: --cmap
  - id: despeckle
    type:
      - 'null'
      - boolean
    doc: Remove sharp increases in long range contact by averaging surrounding 
      values.
    inputBinding:
      position: 103
      prefix: --despeckle
  - id: dpi
    type:
      - 'null'
      - int
    doc: Map resolution in DPI (dots per inch).
    inputBinding:
      position: 103
      prefix: --dpi
  - id: frags
    type:
      - 'null'
      - File
    doc: Required for bp binning and chromosome lines. Tab-separated file with 
      headers, containing fragments start position in the 3rd column, as 
      generated by hicstuff pipeline.
    inputBinding:
      position: 103
      prefix: --frags
  - id: lines
    type:
      - 'null'
      - boolean
    doc: Add dotted lines marking separation between chromosomes or contigs. 
      Requires --frags.
    inputBinding:
      position: 103
      prefix: --lines
  - id: max
    type:
      - 'null'
      - string
    doc: Saturation threshold. Maximum pixel value is set to this number. Can be
      followed by % to use a percentile of nonzero pixels in the contact map.
    inputBinding:
      position: 103
      prefix: --max
  - id: min
    type:
      - 'null'
      - string
    doc: Minimum of the colorscale, works identically to --max.
    inputBinding:
      position: 103
      prefix: --min
  - id: n_mad
    type:
      - 'null'
      - float
    doc: Number of median absolute deviations (MAD) from the median of log bin 
      sums allowed to keep bins in the normalization procedure
    inputBinding:
      position: 103
      prefix: --n-mad
  - id: normalize
    type:
      - 'null'
      - boolean
    doc: Should ICE normalization be performed before rendering the matrix ?
    inputBinding:
      position: 103
      prefix: --normalize
  - id: region
    type:
      - 'null'
      - string
    doc: Only view a region of the contact map. Regions are specified as UCSC 
      strings. (e.g.:chr1:1000-12000). If only one region is given, it is viewed
      on the diagonal. If two regions are given, The contacts between both are 
      shown.
    inputBinding:
      position: 103
      prefix: --region
  - id: transform
    type:
      - 'null'
      - string
    doc: 'Apply a mathematical transformation to pixel values to improve visibility
      of long range signals. Possible values are: log2, log10, ln, sqrt, exp0.2.'
    inputBinding:
      position: 103
      prefix: --transform
  - id: trim
    type:
      - 'null'
      - int
    doc: Trims outlier rows/columns from the matrix if the sum of their contacts
      deviates from the mean by more than INT standard deviations.
    inputBinding:
      position: 103
      prefix: --trim
outputs:
  - id: output
    type:
      - 'null'
      - File
    doc: Name of the image file where the view is stored.
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hicstuff:3.2.4--pyhdfd78af_0
