cwlVersion: v1.2
class: CommandLineTool
baseCommand: vRhyme
label: vrhyme_vRhyme
doc: "Binning Virus Genomes from Metagenomes\n\nTool homepage: https://github.com/AnantharamanLab/vRhyme"
inputs:
  - id: aligner
    type:
      - 'null'
      - string
    doc: read alignment software to use
    inputBinding:
      position: 101
      prefix: --aligner
  - id: bam_files
    type:
      - 'null'
      - type: array
        items: File
    doc: BAM (.bam) sequence alignment files, sorted or unsorted.
    inputBinding:
      position: 101
      prefix: -b
  - id: binned_prefix
    type:
      - 'null'
      - string
    doc: prefix to append to binned scaffold names, use the '#' symbol where the
      bin number will be noted
    inputBinding:
      position: 101
      prefix: --prefix
  - id: binning_iterations
    type:
      - 'null'
      - int
    doc: number of binning iterations (presets) to run
    inputBinding:
      position: 101
      prefix: --iter
  - id: coverage_table
    type:
      - 'null'
      - File
    doc: coverage table generated from vRhyme or from cov_table_convert.py
    inputBinding:
      position: 101
      prefix: -c
  - id: coverage_threshold
    type:
      - 'null'
      - float
    doc: coverage threshold to consider scaffold as present in sample
    inputBinding:
      position: 101
      prefix: --cov
  - id: derep_method
    type:
      - 'null'
      - string
    doc: method of input scaffold dereplication, 'composite' compatible with 
      reads input or --derep_only
    inputBinding:
      position: 101
      prefix: --method
  - id: derep_only
    type:
      - 'null'
      - boolean
    doc: only use dereplication function, skip binning
    inputBinding:
      position: 101
      prefix: --derep_only
  - id: derep_overlap_frac
    type:
      - 'null'
      - string
    doc: minimum coverage in overlap percent for dereplication
    inputBinding:
      position: 101
      prefix: --frac
  - id: derep_similarity
    type:
      - 'null'
      - string
    doc: minimum percent similarity for dereplication
    inputBinding:
      position: 101
      prefix: --derep_id
  - id: input_genes
    type:
      - 'null'
      - File
    doc: input nucleotide genes in format name_#, skip to run Prodigal
    inputBinding:
      position: 101
      prefix: -g
  - id: input_proteins
    type:
      - 'null'
      - File
    doc: input amino acid proteins in format name_#, skip to run Prodigal
    inputBinding:
      position: 101
      prefix: -p
  - id: input_scaffolds
    type: string
    doc: input nucleotide scaffolds
    inputBinding:
      position: 101
      prefix: -i
  - id: interest_scaffolds
    type:
      - 'null'
      - File
    doc: file containing a list of scaffolds of interest to dereplicate/bin.
    inputBinding:
      position: 101
      prefix: --interest
  - id: interleaved_reads
    type:
      - 'null'
      - type: array
        items: File
    doc: interleaved paired (.fastq) read files, '--aligner bowtie2' only
    inputBinding:
      position: 101
      prefix: -v
  - id: keep_bam
    type:
      - 'null'
      - boolean
    doc: do not remove unsorted/index BAM files generated by vRhyme, always keep
      sorted
    inputBinding:
      position: 101
      prefix: --keep_bam
  - id: keep_circular
    type:
      - 'null'
      - boolean
    doc: do not remove circular sequences before binning
    inputBinding:
      position: 101
      prefix: --keep_circ
  - id: keep_sam
    type:
      - 'null'
      - boolean
    doc: do not remove SAM files generated by vRhyme, reads input only
    inputBinding:
      position: 101
      prefix: --keep_sam
  - id: mash_sketch_k
    type:
      - 'null'
      - int
    doc: equivalent to mash sketch -k
    inputBinding:
      position: 101
      prefix: --mash_k
  - id: mash_sketch_s
    type:
      - 'null'
      - int
    doc: equivalent to mash sketch -s
    inputBinding:
      position: 101
      prefix: --mash_s
  - id: mask_bases
    type:
      - 'null'
      - int
    doc: mask coverage values <int> bases on each end of a scaffold
    inputBinding:
      position: 101
      prefix: --mask
  - id: max_gc_distance
    type:
      - 'null'
      - float
    doc: maximum gc distance for pre-filtering
    inputBinding:
      position: 101
      prefix: --max_gc
  - id: max_network_edges
    type:
      - 'null'
      - string
    doc: maximum number of edges per node in network clustering
    inputBinding:
      position: 101
      prefix: --max_edges
  - id: max_penalty_count
    type:
      - 'null'
      - int
    doc: maximum number of penalties for Cohen's d distance calculations
    inputBinding:
      position: 101
      prefix: --penalty_n
  - id: max_redundant_proteins
    type:
      - 'null'
      - int
    doc: maximum number of redundant proteins per bin
    inputBinding:
      position: 101
      prefix: --red
  - id: min_bin_scaffolds
    type:
      - 'null'
      - int
    doc: minimum number of scaffolds per bin
    inputBinding:
      position: 101
      prefix: --bin_size
  - id: min_kmer_distance
    type:
      - 'null'
      - float
    doc: minimum k-mer distance for pre-filtering
    inputBinding:
      position: 101
      prefix: --min_kmer
  - id: min_members_for_refinement
    type:
      - 'null'
      - int
    doc: refine bins with at least <int> members
    inputBinding:
      position: 101
      prefix: --mems
  - id: min_read_identity
    type:
      - 'null'
      - float
    doc: minimum percent identity per aligned read for calculating coverage
    inputBinding:
      position: 101
      prefix: --read_id
  - id: min_scaffold_length
    type:
      - 'null'
      - int
    doc: minimum scaffold length to consider for binning
    inputBinding:
      position: 101
      prefix: -l
  - id: min_scaffold_length_derep
    type:
      - 'null'
      - int
    doc: minimum scaffold length to consider for dereplication
    inputBinding:
      position: 101
      prefix: -m
  - id: ml_model
    type:
      - 'null'
      - string
    doc: machine learning model(s) to use
    inputBinding:
      position: 101
      prefix: --model
  - id: nucmer_b
    type:
      - 'null'
      - int
    doc: equivalent to nucmer -b
    inputBinding:
      position: 101
      prefix: --nucmer_b
  - id: nucmer_c
    type:
      - 'null'
      - int
    doc: equivalent to nucmer -c
    inputBinding:
      position: 101
      prefix: --nucmer_c
  - id: nucmer_fragmentations
    type:
      - 'null'
      - int
    doc: maximum fragmentations allowed per scaffold in nucmer alignment
    inputBinding:
      position: 101
      prefix: --nuc_split
  - id: nucmer_g
    type:
      - 'null'
      - int
    doc: equivalent to nucmer -g
    inputBinding:
      position: 101
      prefix: --nucmer_g
  - id: outlier_std_dev
    type:
      - 'null'
      - float
    doc: remove outlier coverage values <val> standard deviations above average
    inputBinding:
      position: 101
      prefix: --outliers
  - id: output_folder
    type:
      - 'null'
      - Directory
    doc: output folder
    inputBinding:
      position: 101
      prefix: -o
  - id: paired_reads
    type:
      - 'null'
      - type: array
        items: File
    doc: paired forward (_1.fastq) and reverse (_2.fastq) read files
    inputBinding:
      position: 101
      prefix: -r
  - id: penalty_weight
    type:
      - 'null'
      - float
    doc: penalty weight for Cohen's d distance calculations
    inputBinding:
      position: 101
      prefix: --penalty_w
  - id: sam_files
    type:
      - 'null'
      - type: array
        items: File
    doc: SAM (.sam) sequence alignment files.
    inputBinding:
      position: 101
      prefix: -s
  - id: sens_free_ends
    type:
      - 'null'
      - float
    doc: free ends sensitivity to merging over regions of complexity; requires 
      '--method composite'
    inputBinding:
      position: 101
      prefix: --sens_ends
  - id: sens_overlap_merge
    type:
      - 'null'
      - float
    doc: alignment overlap sensitivity to merging over regions of complexity; 
      requires '--method composite'
    inputBinding:
      position: 101
      prefix: --sens_overlap
  - id: speed
    type:
      - 'null'
      - boolean
    doc: allow extra CPU multithreading per process (may use more CPUs than '-t 
      <int>' per process)
    inputBinding:
      position: 101
      prefix: --speed
  - id: threads
    type:
      - 'null'
      - int
    doc: number of parallel processes to run (equivalent to threads, see 
      --speed)
    inputBinding:
      position: 101
      prefix: -t
  - id: unpaired_reads
    type:
      - 'null'
      - type: array
        items: File
    doc: unpaired (.fastq) read files
    inputBinding:
      position: 101
      prefix: -u
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: write log file information to standard out while running
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/vrhyme:1.1.0--pyhdfd78af_1
stdout: vrhyme_vRhyme.out
