cwlVersion: v1.2
class: CommandLineTool
baseCommand: mirdeep2_mapper.pl
label: mirdeep2_mapper.pl
doc: "Processes reads and/or maps them to the genome index.\n\nTool homepage: https://www.mdc-berlin.de/8551903/en/research/research_teams/systems_biology_of_gene_regulatory_elements/projects/miRDeep"
inputs:
  - id: reads
    type: File
    doc: Input file (fasta, fastq, or config file)
    inputBinding:
      position: 1
  - id: clip_adapter
    type:
      - 'null'
      - string
    doc: Clip adapter sequence
    inputBinding:
      position: 102
      prefix: -k
  - id: collapse_reads
    type:
      - 'null'
      - boolean
    doc: Collapse reads
    inputBinding:
      position: 102
      prefix: -m
  - id: convert_rna_to_dna
    type:
      - 'null'
      - boolean
    doc: Convert RNA to DNA alphabet (U to T)
    inputBinding:
      position: 102
      prefix: -i
  - id: discard_short_reads
    type:
      - 'null'
      - int
    doc: Discard reads shorter than <int> nts
    inputBinding:
      position: 102
      prefix: -l
  - id: genome_index
    type:
      - 'null'
      - string
    doc: Genome index name (as generated by bowtie-build)
    inputBinding:
      position: 102
      prefix: -p
  - id: input_is_config
    type:
      - 'null'
      - boolean
    doc: Input file is a config file
    inputBinding:
      position: 102
      prefix: -d
  - id: input_is_fasta
    type:
      - 'null'
      - boolean
    doc: Input file is fasta format
    inputBinding:
      position: 102
      prefix: -c
  - id: input_is_fastq
    type:
      - 'null'
      - boolean
    doc: Input file is fastq format
    inputBinding:
      position: 102
      prefix: -e
  - id: max_mappings
    type:
      - 'null'
      - int
    doc: A read is allowed to map up to this number of positions in the genome
    inputBinding:
      position: 102
      prefix: -r
  - id: num_threads
    type:
      - 'null'
      - int
    doc: Number of threads to use for bowtie
    inputBinding:
      position: 102
      prefix: -o
  - id: remove_non_abc
    type:
      - 'null'
      - boolean
    doc: Remove all entries that have a sequence that contains characters other than
      a,c,g,t,u,n,A,C,G,T,U,N
    inputBinding:
      position: 102
      prefix: -j
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print progress report to standard error
    inputBinding:
      position: 102
      prefix: -v
outputs:
  - id: output_processed_reads
    type:
      - 'null'
      - File
    doc: Print processed reads to this file
    outputBinding:
      glob: $(inputs.output_processed_reads)
  - id: output_arf
    type:
      - 'null'
      - File
    doc: Print mappings to this file (arf format)
    outputBinding:
      glob: $(inputs.output_arf)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mirdeep2:2.0.1.3--hdfd78af_2
