cwlVersion: v1.2
class: CommandLineTool
baseCommand: multivcfanalyzer
label: multivcfanalyzer
doc: "MultiVCFAnalyzer performs SNP effect analysis on VCF files.\n\nTool homepage:
  https://github.com/alexherbig/MultiVCFAnalyzer"
inputs:
  - id: snp_effect_file
    type:
      - 'null'
      - File
    doc: SNP effect analysis result file (from SnpEff; txt format). Optional.
    inputBinding:
      position: 1
  - id: reference_genome_fasta
    type: File
    doc: Reference genome fasta file
    inputBinding:
      position: 2
  - id: reference_genome_gff
    type:
      - 'null'
      - File
    doc: Reference genome gene annotation (gff). Optional.
    inputBinding:
      position: 3
  - id: output_directory
    type: Directory
    doc: Output directory
    inputBinding:
      position: 4
  - id: write_allele_frequencies
    type: string
    doc: Write allele frequencies ('T' or 'F')
    inputBinding:
      position: 5
  - id: min_genotyping_quality
    type: int
    doc: Minimal genotyping quality (GATK)
    inputBinding:
      position: 6
  - id: min_coverage_base_call
    type: int
    doc: Minimal coverage for base call
    inputBinding:
      position: 7
  - id: min_allele_freq_homozygous
    type: float
    doc: Minimal allele frequency for homozygous call
    inputBinding:
      position: 8
  - id: min_allele_freq_heterozygous
    type: float
    doc: Minimal allele frequency for heterozygous call
    inputBinding:
      position: 9
  - id: exclude_positions_gff
    type:
      - 'null'
      - File
    doc: List of positions to exclude (gff). Optional.
    inputBinding:
      position: 10
  - id: input_vcf_files
    type:
      type: array
      items: File
    doc: Input vcf files as generated by the GATK UnifiedGenotyper
    inputBinding:
      position: 11
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/multivcfanalyzer:0.88.1--hdfd78af_0
stdout: multivcfanalyzer.out
