cwlVersion: v1.2
class: CommandLineTool
baseCommand: ant
label: ant
doc: "Apache Ant build tool\n\nTool homepage: https://github.com/ant-design/ant-design"
inputs:
  - id: targets
    type:
      - 'null'
      - type: array
        items: string
    doc: Target(s) to build
    inputBinding:
      position: 1
  - id: auto_proxy
    type:
      - 'null'
      - boolean
    doc: 'Java1.5+: use the OS proxy settings'
    inputBinding:
      position: 102
      prefix: -autoproxy
  - id: buildfile
    type:
      - 'null'
      - File
    doc: use given buildfile
    inputBinding:
      position: 102
      prefix: -buildfile
  - id: buildfile_alias
    type:
      - 'null'
      - File
    doc: use given buildfile
    inputBinding:
      position: 102
      prefix: -file
  - id: buildfile_alias_2
    type:
      - 'null'
      - File
    doc: use given buildfile
    inputBinding:
      position: 102
      prefix: -f
  - id: debug
    type:
      - 'null'
      - boolean
    doc: print debugging information
    inputBinding:
      position: 102
      prefix: -debug
  - id: emacs
    type:
      - 'null'
      - boolean
    doc: produce logging information without adornments
    inputBinding:
      position: 102
      prefix: -emacs
  - id: exec_debug
    type:
      - 'null'
      - boolean
    doc: print ant exec line generated by this launch script
    inputBinding:
      position: 102
      prefix: --execdebug
  - id: find_buildfile
    type:
      - 'null'
      - File
    doc: search for buildfile towards the root of the filesystem and use it
    inputBinding:
      position: 102
      prefix: -find
  - id: find_buildfile_alias
    type:
      - 'null'
      - File
    doc: search for buildfile towards the root of the filesystem and use it
    inputBinding:
      position: 102
      prefix: -s
  - id: input_handler_class
    type:
      - 'null'
      - string
    doc: the class which will handle input requests
    inputBinding:
      position: 102
      prefix: -inputhandler
  - id: keep_going
    type:
      - 'null'
      - boolean
    doc: execute all targets that do not depend on failed target(s)
    inputBinding:
      position: 102
      prefix: -keep-going
  - id: lib_path
    type:
      - 'null'
      - string
    doc: specifies a path to search for jars and classes
    inputBinding:
      position: 102
      prefix: -lib
  - id: listener_class
    type:
      - 'null'
      - string
    doc: add an instance of class as a project listener
    inputBinding:
      position: 102
      prefix: -listener
  - id: logfile
    type:
      - 'null'
      - File
    doc: use given file for log
    inputBinding:
      position: 102
      prefix: -logfile
  - id: logfile_alias
    type:
      - 'null'
      - File
    doc: use given file for log
    inputBinding:
      position: 102
      prefix: -l
  - id: logger_class
    type:
      - 'null'
      - string
    doc: the class which is to perform logging
    inputBinding:
      position: 102
      prefix: -logger
  - id: main_class
    type:
      - 'null'
      - string
    doc: override Ant's normal entry point
    inputBinding:
      position: 102
      prefix: -main
  - id: niceness
    type:
      - 'null'
      - int
    doc: 'A niceness value for the main thread: 1 (lowest) to 10 (highest); 5 is the
      default'
    inputBinding:
      position: 102
      prefix: -nice
  - id: no_classpath
    type:
      - 'null'
      - boolean
    doc: Run ant without using CLASSPATH
    inputBinding:
      position: 102
      prefix: -noclasspath
  - id: no_config
    type:
      - 'null'
      - boolean
    doc: suppress sourcing of /etc/ant.conf, $HOME/.ant/ant.conf, and 
      $HOME/.antrc configuration files
    inputBinding:
      position: 102
      prefix: --noconfig
  - id: no_input
    type:
      - 'null'
      - boolean
    doc: do not allow interactive input
    inputBinding:
      position: 102
      prefix: -noinput
  - id: no_user_lib
    type:
      - 'null'
      - boolean
    doc: Run ant without using the jar files from ${user.home}/.ant/lib
    inputBinding:
      position: 102
      prefix: -nouserlib
  - id: project_help
    type:
      - 'null'
      - boolean
    doc: print project help information and exit
    inputBinding:
      position: 102
      prefix: -projecthelp
  - id: property
    type:
      - 'null'
      - type: array
        items: string
    doc: use value for given property
    inputBinding:
      position: 102
  - id: property_file
    type:
      - 'null'
      - string
    doc: load all properties from file with -D properties taking precedence
    inputBinding:
      position: 102
      prefix: -propertyfile
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: be extra quiet
    inputBinding:
      position: 102
      prefix: -quiet
  - id: script_options_h
    type:
      - 'null'
      - boolean
    doc: print this message and ant help
    inputBinding:
      position: 102
      prefix: --h
  - id: silent
    type:
      - 'null'
      - boolean
    doc: print nothing but task outputs and build failures
    inputBinding:
      position: 102
      prefix: -silent
  - id: use_jikes
    type:
      - 'null'
      - boolean
    doc: enable use of jikes by default, unless set explicitly in configuration 
      files
    inputBinding:
      position: 102
      prefix: --usejikes
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: be extra verbose
    inputBinding:
      position: 102
      prefix: -verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ant:1.10.0--0
stdout: ant.out
