cwlVersion: v1.2
class: CommandLineTool
baseCommand: ericscript.pl
label: ericscript_ericscript.pl
doc: "EricScript.pl automatically runs a pipeline to detect chimeric transcripts in
  paired-end RNA-seq samples. It is also able to generate datasets with synthetic
  gene fusions.\n\nTool homepage: https://github.com/databio/ericscript"
inputs:
  - id: reads_1
    type: File
    doc: First paired-end read file (e.g., reads_1.fq(.gz))
    inputBinding:
      position: 1
  - id: reads_2
    type: File
    doc: Second paired-end read file (e.g., reads_2.fq(.gz))
    inputBinding:
      position: 2
  - id: calcstats_algorithm_name
    type:
      - 'null'
      - string
    doc: name of the algorithm that generated results.
    inputBinding:
      position: 103
      prefix: --algoname
  - id: calcstats_data_folder
    type:
      - 'null'
      - Directory
    doc: path to folder containing synthetic data generated by ericscript 
      simulator.
    inputBinding:
      position: 103
      prefix: --datafolder
  - id: calcstats_dataset_type
    type:
      - 'null'
      - string
    doc: type of synthetic data to considered for calculating statistics. IE or 
      BE?
    inputBinding:
      position: 103
      prefix: --dataset
  - id: calcstats_norm_roc
    type:
      - 'null'
      - int
    doc: factor to normalize the score given by the algorithm.
    inputBinding:
      position: 103
      prefix: --normroc
  - id: calcstats_output_folder
    type:
      - 'null'
      - Directory
    doc: where statistics file will be stored
    default: HOME/ericscript_calcstats
    inputBinding:
      position: 103
      prefix: --outputfolder
  - id: calcstats_results_folder
    type:
      - 'null'
      - Directory
    doc: path to folder containing algorithm results.
    inputBinding:
      position: 103
      prefix: --resultsfolder
  - id: calculate_statistics
    type:
      - 'null'
      - boolean
    doc: Calculate the statistics that we used in our paper to evaluate the 
      performance of the algorithms.
    inputBinding:
      position: 103
      prefix: --calcstats
  - id: check_database
    type:
      - 'null'
      - boolean
    doc: Check if your database is up-to-date, based on the latest Ensembl 
      release.
    inputBinding:
      position: 103
      prefix: --checkdb
  - id: db_folder
    type:
      - 'null'
      - Directory
    doc: where database is stored.
    default: ERICSCRIPT_FOLDER/lib/
    inputBinding:
      position: 103
      prefix: --dbfolder
  - id: download_database
    type:
      - 'null'
      - boolean
    doc: Download, build database. refid parameter need to be specified.
    inputBinding:
      position: 103
      prefix: --downdb
  - id: ensembl_version
    type:
      - 'null'
      - string
    doc: Download data of a specific Ensembl version (>= 70). Default is the 
      latest one.
    inputBinding:
      position: 103
      prefix: --ensversion
  - id: min_mapq
    type:
      - 'null'
      - int
    doc: minimum value of mapping quality to consider discordant reads. For MAPQ
      0 use a negative value
    default: 20
    inputBinding:
      position: 103
      prefix: --MAPQ
  - id: min_reads
    type:
      - 'null'
      - int
    doc: minimum reads to consider discordant alignments
    default: 3
    inputBinding:
      position: 103
      prefix: --minreads
  - id: nthreads
    type:
      - 'null'
      - int
    doc: number of threads for the bwa aln process
    default: 4
    inputBinding:
      position: 103
      prefix: --nthreads
  - id: output_folder
    type:
      - 'null'
      - Directory
    doc: where the results will be stored
    inputBinding:
      position: 103
      prefix: --outputfolder
  - id: print_database_list
    type:
      - 'null'
      - boolean
    doc: Print a list of available genomes and exit.
    inputBinding:
      position: 103
      prefix: --printdb
  - id: refid
    type:
      - 'null'
      - string
    doc: Genome reference identification. Run ericscript.pl --printdb to see 
      available refid.
    default: homo_sapiens
    inputBinding:
      position: 103
      prefix: --refid
  - id: remove_temporary_files
    type:
      - 'null'
      - boolean
    doc: remove all temporary files.
    inputBinding:
      position: 103
      prefix: --remove
  - id: run_demo
    type:
      - 'null'
      - boolean
    doc: Run a demonstration of EricScript on simulated reads.
    inputBinding:
      position: 103
      prefix: --demo
  - id: run_simulator
    type:
      - 'null'
      - boolean
    doc: Generate synthetic gene fusions with the same recipe of the 
      ericscript's paper
    inputBinding:
      position: 103
      prefix: --simulator
  - id: sample_name
    type:
      - 'null'
      - string
    doc: what's the name of your sample?
    default: MyEric
    inputBinding:
      position: 103
      prefix: --samplename
  - id: simulator_background_reads_1
    type:
      - 'null'
      - File
    doc: Fastq file (forward) for generating background reads.
    inputBinding:
      position: 103
      prefix: --background_1
  - id: simulator_background_reads_2
    type:
      - 'null'
      - File
    doc: Fastq file (reverse) for generating background reads.
    inputBinding:
      position: 103
      prefix: --background_2
  - id: simulator_insert_size
    type:
      - 'null'
      - int
    doc: parameter of wgsym. Outer distance between the two ends
    default: 200
    inputBinding:
      position: 103
      prefix: --insize
  - id: simulator_max_coverage
    type:
      - 'null'
      - int
    doc: Maximum coverage to simulate
    default: 50
    inputBinding:
      position: 103
      prefix: --max_cov
  - id: simulator_min_coverage
    type:
      - 'null'
      - int
    doc: Minimum coverage to simulate
    default: 1
    inputBinding:
      position: 103
      prefix: --min_cov
  - id: simulator_num_background_reads
    type:
      - 'null'
      - int
    doc: The number of reads to extract from background data
    default: 200000
    inputBinding:
      position: 103
      prefix: --nreads_background
  - id: simulator_num_gene_fusions
    type:
      - 'null'
      - int
    doc: The number of synthetic gene fusions per dataset?
    default: 50
    inputBinding:
      position: 103
      prefix: --ngenefusion
  - id: simulator_num_simulations
    type:
      - 'null'
      - int
    doc: The number of synthetic datasets to simulate
    default: 10
    inputBinding:
      position: 103
      prefix: --nsims
  - id: simulator_read_length
    type:
      - 'null'
      - int
    doc: length of synthetic reads
    default: 75
    inputBinding:
      position: 103
      prefix: --readlength
  - id: simulator_sd_insert_size
    type:
      - 'null'
      - int
    doc: parameter of wgsym. Standard deviation
    default: 50
    inputBinding:
      position: 103
      prefix: --sd_insize
  - id: simulator_use_broken_exons
    type:
      - 'null'
      - boolean
    doc: Use --be to generate Broken Exons (BE) data
    default: false
    inputBinding:
      position: 103
      prefix: --be
  - id: simulator_use_intact_exons
    type:
      - 'null'
      - boolean
    doc: Use --ie to generate Intact Exons (IE) data
    default: true
    inputBinding:
      position: 103
      prefix: --ie
  - id: trim_reads
    type:
      - 'null'
      - int
    doc: trim PE reads from 1st base to $ntrim. Default is no trimming. Set 
      ntrim=0 to don't trim reads.
    inputBinding:
      position: 103
      prefix: --ntrim
  - id: use_bwa_aln
    type:
      - 'null'
      - boolean
    doc: Use BWA ALN instead of BWA MEM to search for discordant reads.
    inputBinding:
      position: 103
      prefix: --bwa_aln
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: use verbose output
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ericscript:0.5.5--pl5.22.0r3.3.2_1
stdout: ericscript_ericscript.pl.out
