cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cojac
  - cooc-tabmut
label: cojac_cooc-tabmut
doc: "Make a table suitable for further processing: RStudio, etc\n\nTool homepage:
  https://github.com/cbg-ethz/cojac"
inputs:
  - id: json
    type:
      - 'null'
      - File
    doc: results generated by mutbamscan (JSON)
    inputBinding:
      position: 101
      prefix: --json
  - id: yaml
    type:
      - 'null'
      - File
    doc: results generated by mutbamscan (YAML)
    inputBinding:
      position: 101
      prefix: --yaml
  - id: batchname
    type:
      - 'null'
      - string
    doc: separator used to split samplename/batchname in separate column
    inputBinding:
      position: 101
      prefix: --batchname
  - id: lines
    type:
      - 'null'
      - boolean
    doc: Line-oriented table alternative
    inputBinding:
      position: 101
      prefix: --lines
  - id: excel
    type:
      - 'null'
      - boolean
    doc: use a semi-colon ';' instead of a comma ',' in the comma-separated-files
      as required by Microsoft Excel
    inputBinding:
      position: 101
      prefix: --excel
  - id: multiindex
    type:
      - 'null'
      - boolean
    doc: Use multi-level indexing (amplicons and counts categories)
    inputBinding:
      position: 101
      prefix: --multiindex
  - id: add_mutations
    type:
      - 'null'
      - File
    doc: add mutations descriptions using list of query amplicons, from mutbamscan
    inputBinding:
      position: 101
      prefix: --add-mutations
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: 'Run quietly: do not print the table'
    inputBinding:
      position: 101
      prefix: --quiet
  - id: output_name
    type:
      - 'null'
      - string
    doc: name of (raw) csv file to save the table into
    inputBinding:
      position: 102
      prefix: --output
outputs:
  - id: stdout
    type: stdout
    doc: Table printed on the terminal
  - id: output_table
    type:
      - 'null'
      - File
    doc: The (raw) csv table
    outputBinding:
      glob: $(inputs.output_name)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/cojac:0.9.3--pyh7e72e81_0
stdout: cojac_cooc-tabmut.out
