cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cojac
  - cooc-curate
label: cojac_cooc-curate
doc: "Helps determining specific mutations and cooccurrences by querying covSPECTRUM\n\
  \nTool homepage: https://github.com/cbg-ethz/cojac"
inputs:
  - id: vocs
    type:
      - 'null'
      - type: array
        items: string
    doc: VOCs to query
    inputBinding:
      position: 1
  - id: always_mutations
    type:
      - 'null'
      - boolean
    doc: always do mutations (even if amplicons YAML provided)
    inputBinding:
      position: 102
      prefix: --mutations
  - id: amplicons_yaml
    type:
      - 'null'
      - File
    doc: use the YAML file generated by mutbamscan to query amplicons instead of
      mutations
    inputBinding:
      position: 102
      prefix: --amplicons
  - id: collapse
    type:
      - 'null'
      - boolean
    doc: 'combine counts of all sublineages together and consider a single value that
      corresponds to a lineages family (e.g.: count all B.1.612.2* together). This
      is especially useful for assessing signatures of old variants that have branched
      out by now.'
    inputBinding:
      position: 102
      prefix: --collapse
  - id: colour
    type:
      - 'null'
      - boolean
    doc: use coloured output
    inputBinding:
      position: 102
      prefix: --colour
  - id: debug
    type:
      - 'null'
      - boolean
    doc: show API calls details (urls and arguments)
    inputBinding:
      position: 102
      prefix: --debug
  - id: high_fraction
    type:
      - 'null'
      - float
    doc: Fraction above which a mutation must be found among seeked lineages
    inputBinding:
      position: 102
      prefix: --high
  - id: lintype
    type:
      - 'null'
      - string
    doc: 'switch the lineage field queried on covspectrum (e.g. nextcladePangoLineage:
      as determined with nextclade, pangoLineage: as provided by upstream sequence
      repository)'
    inputBinding:
      position: 102
      prefix: --lintype
  - id: low_fraction
    type:
      - 'null'
      - float
    doc: Fraction under which a mutation must be found among other lineages
    inputBinding:
      position: 102
      prefix: --low
  - id: no_collapse
    type:
      - 'null'
      - boolean
    doc: 'combine counts of all sublineages together and consider a single value that
      corresponds to a lineages family (e.g.: count all B.1.612.2* together). This
      is especially useful for assessing signatures of old variants that have branched
      out by now.'
    inputBinding:
      position: 102
      prefix: --no-collapse
  - id: no_colour
    type:
      - 'null'
      - boolean
    doc: use coloured output
    inputBinding:
      position: 102
      prefix: --no-colour
  - id: no_debug
    type:
      - 'null'
      - boolean
    doc: show API calls details (urls and arguments)
    inputBinding:
      position: 102
      prefix: --no-debug
  - id: quirk_no_star
    type:
      - 'null'
      - boolean
    doc: special work-around options
    inputBinding:
      position: 102
      prefix: --quirk [noStar]
  - id: url
    type:
      - 'null'
      - string
    doc: url to use when querying covspectrum (e.g. 
      https://lapis.cov-spectrum.org/open/v2, 
      https://lapis.cov-spectrum.org/gisaid/v2, etc.)
    inputBinding:
      position: 102
      prefix: --url
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/cojac:0.9.3--pyh7e72e81_0
stdout: cojac_cooc-curate.out
