cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cojac
  - cooc-pubmut
label: cojac_cooc-pubmut
doc: "Make a pretty table of the mutation cooccurrence results from mutbamscan (CSV
  that can be imported into an article).\n\nTool homepage: https://github.com/cbg-ethz/cojac"
inputs:
  - id: vocdir
    type:
      - 'null'
      - Directory
    doc: directory containing the yamls defining the variant of concerns
    inputBinding:
      position: 101
      prefix: --vocdir
  - id: amplicons
    type:
      - 'null'
      - File
    doc: list of query amplicons, from mutbamscan
    inputBinding:
      position: 101
      prefix: --amplicons
  - id: json
    type:
      - 'null'
      - File
    doc: results generated by mutbamscan (JSON)
    inputBinding:
      position: 101
      prefix: --json
  - id: yaml
    type:
      - 'null'
      - File
    doc: results generated by mutbamscan (YAML)
    inputBinding:
      position: 101
      prefix: --yaml
  - id: escape
    type:
      - 'null'
      - boolean
    doc: use escape characters for newlines
    inputBinding:
      position: 101
      prefix: --escape
  - id: no_escape
    type:
      - 'null'
      - boolean
    doc: do not use escape characters for newlines
    inputBinding:
      position: 101
      prefix: --no-escape
  - id: excel
    type:
      - 'null'
      - boolean
    doc: use a semi-colon ';' instead of a comma ',' in the comma-separated-files
      as required by Microsoft Excel
    inputBinding:
      position: 101
      prefix: --excel
  - id: batchname
    type:
      - 'null'
      - string
    doc: separator used to split samplename/batchname in separate column
    inputBinding:
      position: 101
      prefix: --batchname
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: 'Run quietly: do not print the table'
    inputBinding:
      position: 101
      prefix: --quiet
  - id: output_name
    type:
      - 'null'
      - string
    doc: name of (pretty) csv file to save the table into
    inputBinding:
      position: 102
      prefix: --output
outputs:
  - id: stdout
    type: stdout
    doc: Table printed on the terminal
  - id: output_table
    type:
      - 'null'
      - File
    doc: The (pretty) csv table
    outputBinding:
      glob: $(inputs.output_name)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/cojac:0.9.3--pyh7e72e81_0
stdout: cojac_cooc-pubmut.out
