cwlVersion: v1.2
class: CommandLineTool
baseCommand: arborator
label: arborator
doc: "Arborator, an aggregate tool for producing summary reports of genetic distances
  within groups v. 1.2.2\n\nTool homepage: https://pypi.org/project/arborator/"
inputs:
  - id: config
    type:
      - 'null'
      - File
    doc: Configuration json
    inputBinding:
      position: 101
      prefix: --config
  - id: count_missing
    type:
      - 'null'
      - boolean
    doc: 'UNUSED: Count missing as differences'
    inputBinding:
      position: 101
      prefix: --count_missing
  - id: delimiter
    type:
      - 'null'
      - string
    doc: 'UNUSED: delimiter desired for nomenclature code'
    inputBinding:
      position: 101
      prefix: --delimiter
  - id: distm
    type:
      - 'null'
      - string
    doc: 'UNUSED: Distance method raw hamming or scaled difference [hamming, scaled]'
    inputBinding:
      position: 101
      prefix: --distm
  - id: force
    type:
      - 'null'
      - boolean
    doc: Overwrite existing directory
    inputBinding:
      position: 101
      prefix: --force
  - id: id_col
    type:
      - 'null'
      - string
    doc: Sample identifier column
    inputBinding:
      position: 101
      prefix: --id_col
  - id: metadata
    type: File
    doc: Matched metadata for samples in the allele profile
    inputBinding:
      position: 101
      prefix: --metadata
  - id: method
    type:
      - 'null'
      - string
    doc: cluster method [single, complete, average]
    default: average
    inputBinding:
      position: 101
      prefix: --method
  - id: min_members
    type:
      - 'null'
      - int
    doc: Minimum number of members to perform clustering
    default: 2
    inputBinding:
      position: 101
      prefix: --min_members
  - id: missing_thresh
    type:
      - 'null'
      - float
    doc: 'UNUSED: Maximum percentage of missing data allowed per locus (0 - 1)'
    inputBinding:
      position: 101
      prefix: --missing_thresh
  - id: n_threads
    type:
      - 'null'
      - int
    doc: CPU Threads to use
    default: 1
    inputBinding:
      position: 101
      prefix: --n_threads
  - id: only_report_labeled_columns
    type:
      - 'null'
      - boolean
    doc: Only report labeled columns
    inputBinding:
      position: 101
      prefix: --only_report_labeled_columns
  - id: outlier_thresh
    type:
      - 'null'
      - float
    doc: Threshold to flag outlier comparisons within a group
    default: 100
    inputBinding:
      position: 101
      prefix: --outlier_thresh
  - id: partition_col
    type:
      - 'null'
      - string
    doc: Metadata column name for aggregating samples
    inputBinding:
      position: 101
      prefix: --partition_col
  - id: profile
    type: File
    doc: Allelic profiles
    inputBinding:
      position: 101
      prefix: --profile
  - id: skip_qc
    type:
      - 'null'
      - boolean
    doc: 'UNUSED: Skip QA/QC steps'
    inputBinding:
      position: 101
      prefix: --skip_qc
  - id: sort_matrix
    type:
      - 'null'
      - boolean
    doc: Sorts the samples in the distance matrix generated by GAS. The order of
      sample rarely has an effect on the assigned cluster labels and sorting 
      them ensures the same inputs always generate the same outputs.
    inputBinding:
      position: 101
      prefix: --sort_matrix
  - id: thresholds
    type:
      - 'null'
      - string
    doc: thresholds delimited by ,
    default: '100'
    inputBinding:
      position: 101
      prefix: --thresholds
  - id: tree_distances
    type:
      - 'null'
      - string
    doc: Defines how distances in distance matrices are interpretted by GAS and 
      represented in the output tree (Newick file). Use "patristic" to interpret
      distances in the matrix as sum of branch lengths between clusters or 
      leaves, and "cophenetic" to interpret distances in the matrix as the 
      minimum distance two clusters or leaves need to be in order to be grouped 
      into the same cluster.
    default: patristic
    inputBinding:
      position: 101
      prefix: --tree_distances
outputs:
  - id: outdir
    type: Directory
    doc: Result output files
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/arborator:1.2.2--pyhdfd78af_0
