cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - mitoz
  - visualize
label: mitoz_visualize
doc: "Visualize input GenBank file.\n\nTool homepage: https://github.com/linzhi2013/MitoZ"
inputs:
  - id: base
    type:
      - 'null'
      - string
    doc: whether draw base track
    inputBinding:
      position: 101
      prefix: --base
  - id: bgc
    type:
      - 'null'
      - string
    doc: background color or the path to a user-defined image file (as the 
      background of the resulting file!)
    inputBinding:
      position: 101
      prefix: --bgc
  - id: bwa
    type:
      - 'null'
      - string
    doc: absolute path of bwa executable, otherwise, `bwa` must be in your 
      `PATH` variable
    inputBinding:
      position: 101
      prefix: --bwa
  - id: cds_color
    type:
      - 'null'
      - string
    doc: PCG color
    inputBinding:
      position: 101
      prefix: --cds_color
  - id: circos
    type:
      - 'null'
      - string
    doc: absolute path of circos executable. otherwise, `circos` must be in your
      `PATH` variable
    inputBinding:
      position: 101
      prefix: --circos
  - id: depth_file
    type:
      - 'null'
      - File
    doc: "A file of tab-separated table with three columns: reference name, position,
      and coverage depth, which is generated by 'samtools depth' command. Or you can
      set '--run_map yes' and '--fq1' and '--fq2' to get this information"
    inputBinding:
      position: 101
      prefix: --depth_file
  - id: depth_fill
    type:
      - 'null'
      - string
    doc: color for filling the abundance track
    inputBinding:
      position: 101
      prefix: --depth_fill
  - id: fq1
    type:
      - 'null'
      - File
    doc: fastq 1 file. Do NOT forget to set '--run_map yes'
    inputBinding:
      position: 101
      prefix: --fq1
  - id: fq2
    type:
      - 'null'
      - File
    doc: fastq 2 file. Do NOT forget to set '--run_map yes'
    inputBinding:
      position: 101
      prefix: --fq2
  - id: gb
    type: File
    doc: Your input Genbank file
    inputBinding:
      position: 101
      prefix: --gb
  - id: gc
    type:
      - 'null'
      - string
    doc: whether draw GC content track.
    inputBinding:
      position: 101
      prefix: --gc
  - id: gc_fill
    type:
      - 'null'
      - string
    doc: color for filling the GC track
    inputBinding:
      position: 101
      prefix: --gc_fill
  - id: label_color
    type:
      - 'null'
      - string
    doc: gene name label color
    inputBinding:
      position: 101
      prefix: --label_color
  - id: locus_color
    type:
      - 'null'
      - string
    doc: locus name's clolor showed on center of circle
    inputBinding:
      position: 101
      prefix: --locus_color
  - id: opts_samtools
    type:
      - 'null'
      - string
    doc: optional arguments for samtools [-a -a]
    inputBinding:
      position: 101
      prefix: --opts_samtools
  - id: outdir
    type:
      - 'null'
      - string
    doc: output directory
    inputBinding:
      position: 101
      prefix: --outdir
  - id: rrna_color
    type:
      - 'null'
      - string
    doc: rRNA color
    inputBinding:
      position: 101
      prefix: --rrna_color
  - id: run_map
    type:
      - 'null'
      - string
    doc: If you do NOT have the '--depth_file', setting '--run_map yes' as well 
      as '--fq1' and '--fq2' to map reads to references to get the 
      '--depth_file'
    inputBinding:
      position: 101
      prefix: --run_map
  - id: samtools
    type:
      - 'null'
      - string
    doc: absolute path of samtools executable, otherwise, `samtools` must be in 
      your `PATH` variable
    inputBinding:
      position: 101
      prefix: --samtools
  - id: thread
    type:
      - 'null'
      - int
    doc: BWA thread number
    inputBinding:
      position: 101
      prefix: --thread
  - id: trna_color
    type:
      - 'null'
      - string
    doc: tRNA color
    inputBinding:
      position: 101
      prefix: --trna_color
  - id: win
    type:
      - 'null'
      - string
    doc: windows size for calculating GC content
    inputBinding:
      position: 101
      prefix: --win
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mitoz:3.6--pyhdfd78af_1
stdout: mitoz_visualize.out
