cwlVersion: v1.2
class: CommandLineTool
baseCommand: pslReps
label: ucsc-pslreps_pslReps
doc: "Analyze repeats and generate genome-wide best alignments from a sorted set of
  local alignments\n\nTool homepage: https://hgdownload.cse.ucsc.edu/admin/exe"
inputs:
  - id: input_psl
    type: File
    doc: an alignment file generated by psLayout and sorted by pslSort
    inputBinding:
      position: 1
  - id: cover_q_sizes
    type:
      - 'null'
      - File
    doc: Tab-separate file with effective query sizes. When used with -minCover,
      this allows polyAs to be excluded from the coverage calculation.
    inputBinding:
      position: 102
      prefix: -coverQSizes
  - id: ignore_ns
    type:
      - 'null'
      - boolean
    doc: Ignore Ns when calculating minCover.
    inputBinding:
      position: 102
      prefix: -ignoreNs
  - id: ignore_size
    type:
      - 'null'
      - boolean
    doc: Will not weigh as much in favor of larger alignments.
    inputBinding:
      position: 102
      prefix: -ignoreSize
  - id: min_ali
    type:
      - 'null'
      - float
    doc: Minimum alignment ratio.
    inputBinding:
      position: 102
      prefix: -minAli
  - id: min_cover
    type:
      - 'null'
      - float
    doc: Minimum coverage to output.
    inputBinding:
      position: 102
      prefix: -minCover
  - id: min_near_top_size
    type:
      - 'null'
      - int
    doc: Minimum size of alignment that is near top for alignment to be kept.
    inputBinding:
      position: 102
      prefix: -minNearTopSize
  - id: near_top
    type:
      - 'null'
      - float
    doc: How much can deviate from top and be taken.
    inputBinding:
      position: 102
      prefix: -nearTop
  - id: no_introns
    type:
      - 'null'
      - boolean
    doc: Will not penalize for not having introns when calculating size factor.
    inputBinding:
      position: 102
      prefix: -noIntrons
  - id: nohead
    type:
      - 'null'
      - boolean
    doc: Don't add PSL header.
    inputBinding:
      position: 102
      prefix: -nohead
  - id: single_hit
    type:
      - 'null'
      - boolean
    doc: Takes single best hit, not splitting into parts.
    inputBinding:
      position: 102
      prefix: -singleHit
outputs:
  - id: output_psl
    type: File
    doc: the best alignment output
    outputBinding:
      glob: '*.out'
  - id: output_psr
    type: File
    doc: repeat info
    outputBinding:
      glob: '*.out'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ucsc-pslreps:482--h0b57e2e_0
