cwlVersion: v1.2
class: CommandLineTool
baseCommand: fargene
label: fargene
doc: "Searches and retrieves new and previously known genes from fragmented metagenomic
  data and genomes. Copyright (c) Fanny Berglund 2018.\n\nTool homepage: https://github.com/fannyhb/fargene"
inputs:
  - id: amino_dir
    type:
      - 'null'
      - Directory
    doc: Where the amino acid sequences generated by the method are located. 
      Only to be used in combination with --rerun
    inputBinding:
      position: 101
      prefix: --amino-dir
  - id: fasta_dir
    type:
      - 'null'
      - Directory
    doc: Where the nucleotide sequences in FASTA generated by previous runs of 
      the method are located. Only to be used in combination with --rerun
    inputBinding:
      position: 101
      prefix: --fasta-dir
  - id: force
    type:
      - 'null'
      - boolean
    doc: 'Overwrite output directory if it exists (default: False).'
    inputBinding:
      position: 101
      prefix: --force
  - id: hmm_model
    type: string
    doc: The Hidden Markov Model that should be used to analyse the data. Could 
      either be one of the pre-defined models or the path to a custom HMM.
    inputBinding:
      position: 101
      prefix: --hmm-model
  - id: infiles
    type:
      type: array
      items: File
    doc: Input file(s) to be searched. Could either be in FASTA or FASTQ format.
    inputBinding:
      position: 101
      prefix: --infiles
  - id: loglevel
    type:
      - 'null'
      - string
    doc: 'Set logging level (default: INFO).'
    inputBinding:
      position: 101
      prefix: --loglevel
  - id: meta
    type:
      - 'null'
      - boolean
    doc: 'If the input data is paired end metagenomic data (default: False).'
    inputBinding:
      position: 101
      prefix: --meta
  - id: meta_score
    type:
      - 'null'
      - float
    doc: 'The threshold score for a fragment to be classified as a positive. Expressed
      as score per amino acid (default: None).'
    inputBinding:
      position: 101
      prefix: --meta-score
  - id: min_orf_length
    type:
      - 'null'
      - int
    doc: 'The minimal length for a retrieved predicted ORF (nt). (default: 90% of
      the length of the chosen hmm.)'
    inputBinding:
      position: 101
      prefix: --min-orf-length
  - id: no_assembly
    type:
      - 'null'
      - boolean
    doc: 'Use if you want to skip the assembly and retrieval of contigs for metagenomic
      data (default: False).'
    inputBinding:
      position: 101
      prefix: --no-assembly
  - id: no_orf_predict
    type:
      - 'null'
      - boolean
    doc: Do not perform ORF prediction.
    inputBinding:
      position: 101
      prefix: --no-orf-predict
  - id: no_quality_filtering
    type:
      - 'null'
      - boolean
    doc: 'Use if no quality control should be performed on the metagenomic data (default:
      False).'
    inputBinding:
      position: 101
      prefix: --no-quality-filtering
  - id: orf_finder
    type:
      - 'null'
      - boolean
    doc: 'Use NCBI ORFfinder instead of prodigal for ORF prediction of genomes/contigs
      (default: False).'
    inputBinding:
      position: 101
      prefix: --orf-finder
  - id: processes
    type:
      - 'null'
      - int
    doc: 'Number of processes to be used when processing metagenomic data (default:
      1).'
    inputBinding:
      position: 101
      prefix: --processes
  - id: protein
    type:
      - 'null'
      - boolean
    doc: 'If the input sequence(s) is amino acids (default: False).'
    inputBinding:
      position: 101
      prefix: --protein
  - id: rerun
    type:
      - 'null'
      - boolean
    doc: 'Use of you want to redo the analysis or do the analysis using a different
      model and have kept either the nucletide or amino acid sequences. Please note
      that this only works if the input data is the same for both runs (default: False).'
    inputBinding:
      position: 101
      prefix: --rerun
  - id: retrieve_whole
    type:
      - 'null'
      - boolean
    doc: 'Use this flag if the whole sequence where a hit is detected should be retrieved
      (default: False).'
    inputBinding:
      position: 101
      prefix: --retrieve-whole
  - id: score
    type:
      - 'null'
      - float
    doc: 'The threshold score for a sequence to be classified as a (almost) complete
      gene (default: None).'
    inputBinding:
      position: 101
      prefix: --score
  - id: store_peptides
    type:
      - 'null'
      - boolean
    doc: 'Store the translated sequences. Useful if you plan to redo the analysis
      using a different model and want to skip the preprocessing steps (default: False).'
    inputBinding:
      position: 101
      prefix: --store-peptides
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: 'Directory for (sometimes large) intermediate files. (default: OUT_DIR/tmpdir)'
    inputBinding:
      position: 101
      prefix: --tmp-dir
  - id: translation_format
    type:
      - 'null'
      - string
    doc: 'The translation format that transeq should use. (default: pearson)'
    inputBinding:
      position: 101
      prefix: --translation-format
outputs:
  - id: output
    type:
      - 'null'
      - Directory
    doc: 'The output directory for the whole run (default: ./fargene_output).'
    outputBinding:
      glob: $(inputs.output)
  - id: logfile
    type:
      - 'null'
      - File
    doc: 'Logfile (default: fargene_analysis.log).'
    outputBinding:
      glob: $(inputs.logfile)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/fargene:0.1--py27h5ca1d4c_2
