cwlVersion: v1.2
class: CommandLineTool
baseCommand: ribo sketch
label: riboseed_ribo sketch
doc: "Pretty up the plots generated by mauve contig mover\n\nTool homepage: https://github.com/nickp60/riboSeed"
inputs:
  - id: indir
    type: Directory
    doc: dir containing a genbank file, assembly filesas fastas. Usually the 
      'mauve' dir in the riboSeed results
    inputBinding:
      position: 1
  - id: assembly_ext
    type:
      - 'null'
      - string
    doc: extension of assemblies, usually fasta
    default: fasta
    inputBinding:
      position: 102
      prefix: --assembly_ext
  - id: mauve_jar
    type:
      - 'null'
      - File
    doc: path to Mauve.jar
    default: ~/mauve_snapshot_2015-02-13/Mauve.jar
    inputBinding:
      position: 102
      prefix: --mauve_jar
  - id: names
    type:
      - 'null'
      - string
    doc: name the resulting plot and output dirs; comma-separate
    inputBinding:
      position: 102
      prefix: --names
  - id: outdir
    type: Directory
    doc: output directory
    inputBinding:
      position: 102
      prefix: --outdir
  - id: ref_ext
    type:
      - 'null'
      - string
    doc: extension of reference, usually gb
    default: gb
    inputBinding:
      position: 102
      prefix: --ref_ext
  - id: replot
    type:
      - 'null'
      - boolean
    doc: replot, using a previous run of analyses
    inputBinding:
      position: 102
      prefix: --replot
  - id: verbosity
    type:
      - 'null'
      - int
    doc: Logger writes debug to file in output dir; this sets verbosity level 
      sent to stderr. 1 = debug(), 2 = info(), 3 = warning(), 4 = error() and 5 
      = critical()
    default: 2
    inputBinding:
      position: 102
      prefix: --verbosity
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/riboseed:0.4.90--py_0
stdout: riboseed_ribo sketch.out
