cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ribo
  - run
label: riboseed_ribo run
doc: "Run the riboSeed pipeline of scan, select, and seed, plus any additional stages.
  Uses a config file to wrangle all the args not available via these commandline args.
  This can either be run by providing (as minimum) a reference, some reads, and an
  output directory; or, if you have a completed config file, you can run it with just
  that.\n\nTool homepage: https://github.com/nickp60/riboSeed"
inputs:
  - id: additional_libs
    type:
      - 'null'
      - string
    doc: 'include these libraries in final assembly in addition to the reads supplied
      as -F and -R. They must be supplied according to SPAdes arg naming scheme. Use
      at own risk.default: None'
    inputBinding:
      position: 101
      prefix: --additional_libs
  - id: clean_temps
    type:
      - 'null'
      - boolean
    doc: if --clean_temps, mapping files will be removed once they are no no 
      longer needed during the mapping iterations to save space
    inputBinding:
      position: 101
      prefix: --clean_temps
  - id: cluster_file
    type:
      - 'null'
      - File
    doc: "clustered_loci file output from riboSelect;this is created by default from
      run_riboSeed, but if you don't agree with the operon structure predicted by
      riboSelect, you can use your alternate clustered_loci file. default: None"
    inputBinding:
      position: 101
      prefix: --cluster_file
  - id: clusters
    type:
      - 'null'
      - string
    doc: number of rDNA clusters;if submitting multiple records, must be a 
      colon:separated list whose length matches number of genbank records. 
      Default is inferred from specific feature with fewest hits
    inputBinding:
      position: 101
      prefix: --clusters
  - id: config_file
    type: File
    doc: 'config file; if none given, create one; default: /'
    inputBinding:
      position: 101
      prefix: --config
  - id: cores
    type:
      - 'null'
      - int
    doc: cores used
    inputBinding:
      position: 101
      prefix: --cores
  - id: damn_the_torpedos
    type:
      - 'null'
      - boolean
    doc: Ignore certain errors, full speed ahead!
    inputBinding:
      position: 101
      prefix: --damn_the_torpedos
  - id: experiment_name
    type:
      - 'null'
      - string
    doc: 'prefix for results files; default: inferred'
    inputBinding:
      position: 101
      prefix: --experiment_name
  - id: fastq1
    type:
      - 'null'
      - File
    doc: path to forward fastq file, can be compressed
    inputBinding:
      position: 101
      prefix: --fastq1
  - id: fastq2
    type:
      - 'null'
      - File
    doc: path to reverse fastq file, can be compressed
    inputBinding:
      position: 101
      prefix: --fastq2
  - id: fastq_single1
    type:
      - 'null'
      - File
    doc: path to single fastq file
    inputBinding:
      position: 101
      prefix: --fastq_single1
  - id: flanking_length
    type:
      - 'null'
      - int
    doc: length of flanking regions, in bp
    inputBinding:
      position: 101
      prefix: --flanking_length
  - id: force_kmers
    type:
      - 'null'
      - boolean
    doc: skip checking to see if kmerchoice is appropriate to read length. 
      Sometimes kmers longer than reads can help in the final assembly, as the 
      long reads generated by riboSeed contain kmers longer than the read length
    inputBinding:
      position: 101
      prefix: --force_kmers
  - id: iterations
    type:
      - 'null'
      - int
    doc: if iterations>1, multiple seedings will occur after subassembly of seed
      regions; if setting --target_len, seedings will continue until 
      --iterations are completed or --target_len is matched or exceeded
    inputBinding:
      position: 101
      prefix: --iterations
  - id: just_seed
    type:
      - 'null'
      - boolean
    doc: Don't do an assembly, just generate the long read 'seeds'
    inputBinding:
      position: 101
      prefix: --just_seed
  - id: kingdom
    type:
      - 'null'
      - string
    doc: whether to look for eukaryotic, archaeal, or bacterial rDNA
    inputBinding:
      position: 101
      prefix: --Kingdom
  - id: kmers
    type:
      - 'null'
      - string
    doc: kmers used for final assembly, separated by commas such 
      as21,33,55,77,99,127. Can be set to 'auto', where SPAdes chooses. We 
      ensure kmers are not too big or too close to read length
    inputBinding:
      position: 101
      prefix: --kmers
  - id: linear
    type:
      - 'null'
      - boolean
    doc: 'if genome is known to not be circular and a region of interest (including
      flanking bits) extends past chromosome end, this extends the seqence past chromosome
      origin forward by --padding; default: False'
    inputBinding:
      position: 101
      prefix: --linear
  - id: memory
    type:
      - 'null'
      - int
    doc: cores for multiprocessing
    inputBinding:
      position: 101
      prefix: --memory
  - id: min_flank_depth
    type:
      - 'null'
      - int
    doc: a subassembly won't be performed if this minimum depth is not achieved 
      on both the 3' and5' end of the pseudocontig
    inputBinding:
      position: 101
      prefix: --min_flank_depth
  - id: pre_kmers
    type:
      - 'null'
      - string
    doc: kmers used during seeding assemblies, separated bt commas
    inputBinding:
      position: 101
      prefix: --pre_kmers
  - id: ref_as_contig
    type:
      - 'null'
      - string
    doc: "ignore: reference will not be used in subassembly. trusted: SPAdes will
      use the seed sequences as a --trusted-contig; untrusted: SPAdes will treat as
      --untrusted-contig. infer: if mapping percentage over 80%, 'trusted'; else 'untrusted'.
      See SPAdes docs for details."
    inputBinding:
      position: 101
      prefix: --ref_as_contig
  - id: reference_fasta
    type:
      - 'null'
      - File
    doc: path to a (multi)fasta or a directory containing one or more 
      chromosomal sequences in fasta format. Required, unless using a config 
      file
    inputBinding:
      position: 101
      prefix: --reference_fasta
  - id: score_min
    type:
      - 'null'
      - int
    doc: If using smalt, this sets the '-m' param; default with smalt is 
      inferred from read length. If using BWA, reads mapping with ASscore lower 
      than this will be rejected; default with BWA is half of read length
    inputBinding:
      position: 101
      prefix: --score_min
  - id: serialize
    type:
      - 'null'
      - boolean
    doc: if --serialize, runs seeding and assembly without multiprocessing. We 
      recommend this for machines with less than 8GB RAM
    inputBinding:
      position: 101
      prefix: --serialize
  - id: skip_control
    type:
      - 'null'
      - boolean
    doc: if --skip_control, no de novo assembly will be done
    inputBinding:
      position: 101
      prefix: --skip_control
  - id: specific_features
    type:
      - 'null'
      - string
    doc: colon:separated -- specific features
    inputBinding:
      position: 101
      prefix: --specific_features
  - id: stages
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Which assessment stages you wish to run: sketch, spec, snag, score, stack.
      Any combination thereof'
    inputBinding:
      position: 101
      prefix: --stages
  - id: subassembler
    type:
      - 'null'
      - string
    doc: assembler to use for subassembly scheme. SPAdes is used by default, but
      Skesa is a new addition that seems to work for subassembly and is faster
    inputBinding:
      position: 101
      prefix: --subassembler
  - id: threads
    type:
      - 'null'
      - int
    doc: if your cores are hyperthreaded, set number threads to the number of 
      threads per processer.If unsure, see 'cat /proc/cpuinfo' under 'cpu 
      cores', or 'lscpu' under 'Thread(s) per core'.
    inputBinding:
      position: 101
      prefix: --threads
  - id: verbosity
    type:
      - 'null'
      - int
    doc: Logger writes debug to file in output dir; this sets verbosity level 
      sent to stderr. 1 = debug(), 2 = info(), 3 = warning(), 4 = error() and 5 
      = critical()
    inputBinding:
      position: 101
      prefix: --verbosity
outputs:
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: output directory
    outputBinding:
      glob: $(inputs.output_dir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/riboseed:0.4.90--py_0
