cwlVersion: v1.2
class: CommandLineTool
baseCommand: predict_metagenomes.py
label: picrust_predict_metagenomes.py
doc: "Predict KO abundances for a given OTU table picked against the newest version
  of GreenGenes.\n\nTool homepage: http://picrust.github.com"
inputs:
  - id: accuracy_metrics
    type:
      - 'null'
      - string
    doc: 'If provided, calculate accuracy metrics for the predicted metagenome. NOTE:
      requires that per-genome accuracy metrics were calculated using predict_traits.py
      during genome prediction (e.g. there are "NSTI" values in the genome .biom file
      metadata)'
    inputBinding:
      position: 101
      prefix: --accuracy_metrics
  - id: format_tab_delimited
    type:
      - 'null'
      - boolean
    doc: output the predicted metagenome table in tab-delimited format
    inputBinding:
      position: 101
      prefix: --format_tab_delimited
  - id: gg_version
    type:
      - 'null'
      - string
    doc: 'Version of GreenGenes that was used for OTU picking. Valid choices are:
      13_5, 18may2012'
    inputBinding:
      position: 101
      prefix: --gg_version
  - id: input_count_table
    type:
      - 'null'
      - File
    doc: 'Precalculated function predictions on per otu basis in biom format (can
      be gzipped). Note: using this option overrides --type_of_prediction and --gg_version.'
    inputBinding:
      position: 101
      prefix: --input_count_table
  - id: input_otu_table
    type: File
    doc: the input otu table in biom format
    inputBinding:
      position: 101
      prefix: --input_otu_table
  - id: input_variance_table
    type:
      - 'null'
      - File
    doc: 'Precalculated table of variances corresponding to the precalculated table
      of function predictions. As with the count table, these are on a per otu basis
      and in BIOM format (can be gzipped). Note: using this option overrides --type_of_prediction
      and --gg_version.'
    inputBinding:
      position: 101
      prefix: --input_variance_table
  - id: load_precalc_file_in_biom
    type:
      - 'null'
      - boolean
    doc: Instead of loading the precalculated file in tab- delimited format 
      (with otu ids as row ids and traits as columns) load the data in biom 
      format (with otu as SampleIds and traits as ObservationIds)
    inputBinding:
      position: 101
      prefix: --load_precalc_file_in_biom
  - id: no_round
    type:
      - 'null'
      - boolean
    doc: Disable rounding number of predicted functions to the the nearest whole
      number. This option is important if you are inputting abundances as 
      proportions
    inputBinding:
      position: 101
      prefix: --no_round
  - id: normalize_by_function
    type:
      - 'null'
      - boolean
    doc: Normalizes the predicted functional abundances by dividing each 
      abundance by the sum of functional abundances in the sample. Total sum of 
      abundances for each sample will equal 1.
    inputBinding:
      position: 101
      prefix: --normalize_by_function
  - id: normalize_by_otu
    type:
      - 'null'
      - boolean
    doc: 'Normalizes the predicted functional abundances by dividing each abundance
      by the sum of OTUs in the sample. Note: total sum of abundances for each sample
      will NOT equal 1.'
    inputBinding:
      position: 101
      prefix: --normalize_by_otu
  - id: suppress_subset_loading
    type:
      - 'null'
      - boolean
    doc: Normally, only counts for OTUs present in the sample are loaded. If 
      this flag is passed, the full biom table is loaded. This makes no 
      difference for the analysis, but may result in faster load times (at the 
      cost of more memory usage)
    inputBinding:
      position: 101
      prefix: --suppress_subset_loading
  - id: type_of_prediction
    type:
      - 'null'
      - string
    doc: 'Type of functional predictions. Valid choices are: ko, cog, rfam'
    inputBinding:
      position: 101
      prefix: --type_of_prediction
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print information during execution -- useful for debugging
    inputBinding:
      position: 101
      prefix: --verbose
  - id: with_confidence
    type:
      - 'null'
      - boolean
    doc: Calculate 95% confidence intervals for metagenome predictions. By 
      default, this uses the confidence intervals for the precalculated table of
      genes for greengenes OTUs. If you pass a custom count table with -c and 
      select this option, you must also specify a corresponding table of 
      confidence intervals for the gene content prediction using 
      --input_variance_table. (these are generated by running predict_traits.py 
      with the --with_confidence option). If this flag is set, three addtional 
      output files will be generated, named the same as the metagenome 
      prediction output, but with .variance .upper_CI or .lower_CI appended 
      immediately before the file extension
    inputBinding:
      position: 101
      prefix: --with_confidence
outputs:
  - id: output_metagenome_table
    type: File
    doc: the output file for the predicted metagenome
    outputBinding:
      glob: $(inputs.output_metagenome_table)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/picrust:1.1.4--pyh24bf2e0_0
