cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - augur
  - subsample
label: augur_subsample
doc: "Subsample sequences from an input dataset. The input dataset can consist of
  a metadata file, a sequences file, or both. See documentation page for details on
  configuration.\n\nTool homepage: https://github.com/nextstrain/augur"
inputs:
  - id: config
    type: File
    doc: augur subsample config file. The expected config options must be 
      defined at the top level, or within a specific section using 
      --config-section.
    inputBinding:
      position: 101
      prefix: --config
  - id: config_section
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Use a section of the file given to --config by listing the keys leading
      to the section. Provide one or more keys. (default: use the entire file)'
    inputBinding:
      position: 101
      prefix: --config-section
  - id: metadata
    type:
      - 'null'
      - File
    doc: sequence metadata
    inputBinding:
      position: 101
      prefix: --metadata
  - id: metadata_chunk_size
    type:
      - 'null'
      - int
    doc: maximum number of metadata records to read into memory at a time. 
      Increasing this number can reduce run times at the cost of more memory 
      used.
    inputBinding:
      position: 101
      prefix: --metadata-chunk-size
  - id: metadata_delimiters
    type:
      - 'null'
      - type: array
        items: string
    doc: delimiters to accept when reading a metadata file. Only one delimiter 
      will be inferred.
      - ','
      - "\t"
    inputBinding:
      position: 101
      prefix: --metadata-delimiters
  - id: metadata_id_columns
    type:
      - 'null'
      - type: array
        items: string
    doc: names of possible metadata columns containing identifier information, 
      ordered by priority. Only one ID column will be inferred.
      - strain
      - name
    inputBinding:
      position: 101
      prefix: --metadata-id-columns
  - id: nthreads
    type:
      - 'null'
      - int
    doc: Number of CPUs/cores/threads/jobs to utilize at once. For augur 
      subsample, this means the number of samples to run simultaneously. 
      Individual samples are limited to a single thread. The final augur filter 
      call can take advantage of multiple threads.
    inputBinding:
      position: 101
      prefix: --nthreads
  - id: search_paths
    type:
      - 'null'
      - type: array
        items: Directory
    doc: "One or more directories to search for relative filepath's specified in the
      config file. If a file exists in multiple directories, only the file from the
      first directory will be used. This can also be set via the environment variable
      'AUGUR_SEARCH_PATHS'. Specified directories will be considered before the defaults,
      which are: (1) directory containing the config file (2) current working directory"
    inputBinding:
      position: 101
      prefix: --search-paths
  - id: seed
    type:
      - 'null'
      - int
    doc: random number generator seed for reproducible outputs (with same input 
      data).
    inputBinding:
      position: 101
      prefix: --seed
  - id: sequence_index
    type:
      - 'null'
      - File
    doc: sequence composition report generated by augur index. If not provided, 
      an index will be created on the fly. This should be generated from the 
      same file as --sequences.
    inputBinding:
      position: 101
      prefix: --sequence-index
  - id: sequences
    type:
      - 'null'
      - File
    doc: sequences in FASTA or VCF format. For large inputs, consider using 
      --sequence-index in addition to this option.
    inputBinding:
      position: 101
      prefix: --sequences
  - id: skip_checks
    type:
      - 'null'
      - boolean
    doc: use this option to skip checking for duplicates in sequences and 
      whether ids in metadata have a sequence entry. Can improve performance on 
      large files. Note that this should only be used if you are sure there are 
      no duplicate sequences or mismatched ids since they can lead to errors in 
      downstream Augur commands.
    inputBinding:
      position: 101
      prefix: --skip-checks
outputs:
  - id: output_metadata
    type:
      - 'null'
      - File
    doc: output metadata file
    outputBinding:
      glob: $(inputs.output_metadata)
  - id: output_sequences
    type:
      - 'null'
      - File
    doc: output sequences file
    outputBinding:
      glob: $(inputs.output_sequences)
  - id: output_log
    type:
      - 'null'
      - File
    doc: Tab-delimited file to debug sequence inclusion in samples. All 
      sequences have a row with filter=filter_by_exclude_all. The sequences 
      included in the output each have an additional row per sample that 
      included it (there may be multiple). These rows have 
      filter=force_include_strains with kwargs pointing to a temporary file that
      hints at the intermediate sample it came from.
    outputBinding:
      glob: $(inputs.output_log)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/augur:33.0.0--pyhdfd78af_0
