cwlVersion: v1.2
class: CommandLineTool
baseCommand: LiBis
label: libis_LiBis
doc: "LiBis is a tool for processing and analyzing bisulfite sequencing data.\n\n\
  Tool homepage: https://github.com/Dangertrip/LiBis"
inputs:
  - id: bin_size
    type:
      - 'null'
      - string
    doc: "Plot setting. Set the bin size for averaging\nmethylation ratio among samples,
      default=1000k"
    default: 1000k
    inputBinding:
      position: 101
      prefix: --binsize
  - id: clip_mode
    type:
      - 'null'
      - string
    doc: 'Clip mode. 0 means close. 1 means open. default: 0'
    default: '0'
    inputBinding:
      position: 101
      prefix: --clip
  - id: fastq_files
    type:
      type: array
      items: string
    doc: Required. Fastq file name.
    inputBinding:
      position: 101
      prefix: --name
  - id: file_setup_mode
    type:
      - 'null'
      - string
    doc: Enter a number, 0 means using parameter to set up, 1 means using text 
      file to set up
    inputBinding:
      position: 101
      prefix: --file
  - id: filter_length
    type:
      - 'null'
      - int
    doc: Minimal length for recombined reads
    inputBinding:
      position: 101
      prefix: --filter
  - id: generate_report
    type:
      - 'null'
      - boolean
    doc: Generate the final report or not
    inputBinding:
      position: 101
      prefix: --plot
  - id: genome
    type:
      - 'null'
      - string
    doc: "Genome the reference belong to.(Use for plotting)\nhg18/hg19/mm10/mm9 and
      so on. Plotting script will not\navailable if leave it blank. default=hg38."
    default: hg38
    inputBinding:
      position: 101
      prefix: --genome
  - id: gzip_temp_files
    type:
      - 'null'
      - boolean
    doc: Temporary files are in gz format.
    inputBinding:
      position: 101
      prefix: --gzip
  - id: keep_temp_files
    type:
      - 'null'
      - boolean
    doc: Keep all temp files.
    inputBinding:
      position: 101
      prefix: --fullmode
  - id: multiple_mapping
    type:
      - 'null'
      - boolean
    doc: Apply multiple mapping after first around bsmap
    inputBinding:
      position: 101
      prefix: --multiplemapping
  - id: pair_end_filter
    type:
      - 'null'
      - boolean
    doc: "Apply pairend filter for all LiBis rescued reads. Only\nkeep reads have
      uniquely mapped pair by BSMAP or\nLiBis."
    inputBinding:
      position: 101
      prefix: --pairendfilter
  - id: process
    type:
      - 'null'
      - string
    doc: "Process using for one pipeline. Normally bsmap will\ncost 8 cpu number.
      So total will be 8p."
    inputBinding:
      position: 101
      prefix: --process
  - id: processed_bam_files
    type:
      - 'null'
      - type: array
        items: File
    doc: "Processed bam file for the first step. If bam files\nare offered here, the
      first step of bsmap will be\nskipped. BAM files can only be generated by BSMAP.\n\
      Different files should be seperated by ','. If there's\nno bam file for part
      of the samples, leave the space\nblank. For example: a.bam,b.bam,,,,f.bam"
    inputBinding:
      position: 101
      prefix: --bam
  - id: quality_control
    type:
      - 'null'
      - boolean
    doc: Do quality control
    inputBinding:
      position: 101
      prefix: --QualityControl
  - id: reference_genome
    type: File
    doc: Required. Reference genome file name.
    inputBinding:
      position: 101
      prefix: --ref
  - id: run_as_moabs_module
    type:
      - 'null'
      - boolean
    doc: "Run LiBis as MOABS module. Please only apply this when\nintegrating LiBis
      to MOABS."
    inputBinding:
      position: 101
      prefix: --MOABSmodule
  - id: run_mcall
    type:
      - 'null'
      - boolean
    doc: Run mcall for mapped bams or not
    inputBinding:
      position: 101
      prefix: --mcall
  - id: sample_labels
    type:
      - 'null'
      - type: array
        items: string
    doc: Labels for samples
    inputBinding:
      position: 101
      prefix: --label
  - id: setting_file
    type:
      - 'null'
      - File
    doc: Setting txt file name. Ignore if -f is 0.
    inputBinding:
      position: 101
      prefix: --settingfile
  - id: skip_checking
    type:
      - 'null'
      - boolean
    doc: "Skip the checking step for result folders. Using this\nparameter may rewrite
      the previous results."
    inputBinding:
      position: 101
      prefix: --nocheck
  - id: step_size
    type:
      - 'null'
      - int
    doc: Step size for clipping mode.
    inputBinding:
      position: 101
      prefix: --step
  - id: trimming
    type:
      - 'null'
      - boolean
    doc: Do trimming.
    inputBinding:
      position: 101
      prefix: --trim
  - id: unmapped_reads_bam
    type:
      - 'null'
      - boolean
    doc: "Given processed bam file contains unmapped reads. Only\nuse with -bam is
      open."
    inputBinding:
      position: 101
      prefix: --bamu
  - id: window_length
    type:
      - 'null'
      - int
    doc: Window length for clipping mode, default=30
    default: 30
    inputBinding:
      position: 101
      prefix: --window
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/libis:0.1.6--py_0
stdout: libis_LiBis.out
