cwlVersion: v1.2
class: CommandLineTool
baseCommand: haphpipe build_tree_NG
label: haphpipe_build_tree_NG
doc: "Build phylogenetic trees using RAxML-NG\n\nTool homepage: https://github.com/gwcbi/haphpipe"
inputs:
  - id: all
    type:
      - 'null'
      - boolean
    doc: Run bootstrap search and find best ML tree
    default: false
    inputBinding:
      position: 101
      prefix: --all
  - id: bootstrap
    type:
      - 'null'
      - boolean
    doc: Run non-parametric bootstrap analysis
    default: false
    inputBinding:
      position: 101
      prefix: --bootstrap
  - id: branch_length
    type:
      - 'null'
      - string
    doc: 'Branch length estimation mode: linked, scaled, unlinked (partitioned analysis
      only)'
    inputBinding:
      position: 101
      prefix: --branch_length
  - id: bs_metric
    type:
      - 'null'
      - string
    doc: 'Options: tbe or fbp,tbe'
    inputBinding:
      position: 101
      prefix: --bs_metric
  - id: bs_msa
    type:
      - 'null'
      - boolean
    doc: Generate bootstrap replicate alignments
    default: false
    inputBinding:
      position: 101
      prefix: --bs_msa
  - id: bs_tree_cutoff
    type:
      - 'null'
      - string
    doc: Change the bootstopping cutoff value to make the test more or less 
      stringent
    inputBinding:
      position: 101
      prefix: --bs_tree_cutoff
  - id: bs_trees
    type:
      - 'null'
      - string
    doc: Number of bootstrap trees OR autoMRE
    inputBinding:
      position: 101
      prefix: --bs_trees
  - id: bsconverge
    type:
      - 'null'
      - boolean
    doc: A posteriori bootstrap convergence test
    default: false
    inputBinding:
      position: 101
      prefix: --bsconverge
  - id: check
    type:
      - 'null'
      - boolean
    doc: Check alignment file and remove any columns consisting entirely of gaps
    default: false
    inputBinding:
      position: 101
      prefix: --check
  - id: consense
    type:
      - 'null'
      - string
    doc: 'Consensus tree building options: STRICT, MR, or MRE'
    inputBinding:
      position: 101
      prefix: --consense
  - id: constraint_tree
    type:
      - 'null'
      - File
    doc: Specify a constraint tree to e.g. enforce monophyly of certain groups
    inputBinding:
      position: 101
      prefix: --constraint_tree
  - id: debug
    type:
      - 'null'
      - boolean
    doc: Print commands but do not run
    default: false
    inputBinding:
      position: 101
      prefix: --debug
  - id: in_type
    type:
      - 'null'
      - string
    doc: 'File format: FASTA or PHYLIP'
    default: FASTA
    inputBinding:
      position: 101
      prefix: --in_type
  - id: keep_tmp
    type:
      - 'null'
      - boolean
    doc: Keep temporary directory
    default: false
    inputBinding:
      position: 101
      prefix: --keep_tmp
  - id: log
    type:
      - 'null'
      - string
    doc: 'Options for output verbosity: ERROR, WARNING, RESULT, INFO, PROGRESS, VERBOSE,
      or DEBUG'
    inputBinding:
      position: 101
      prefix: --log
  - id: logfile
    type:
      - 'null'
      - File
    doc: Append console output to this file
    inputBinding:
      position: 101
      prefix: --logfile
  - id: loglh
    type:
      - 'null'
      - boolean
    doc: Compute log-likelihood of a given tree without any optimization
    default: false
    inputBinding:
      position: 101
      prefix: --loglh
  - id: model
    type:
      - 'null'
      - string
    doc: Substitution model OR path to partition file
    inputBinding:
      position: 101
      prefix: --model
  - id: ncpu
    type:
      - 'null'
      - int
    doc: Number of CPU to use
    default: 1
    inputBinding:
      position: 101
      prefix: --ncpu
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: Output directory
    default: .
    inputBinding:
      position: 101
      prefix: --outdir
  - id: outgroup
    type:
      - 'null'
      - string
    doc: Outgroup(s) for tree
    inputBinding:
      position: 101
      prefix: --outgroup
  - id: output_name
    type:
      - 'null'
      - string
    doc: Run name for trees
    inputBinding:
      position: 101
      prefix: --output_name
  - id: pars_tree
    type:
      - 'null'
      - File
    doc: Start from a tree generated by the parsimony-based randomized stepwise 
      addition algorithm
    inputBinding:
      position: 101
      prefix: --pars_tree
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Do not write output to console (silence stdout and stderr)
    default: false
    inputBinding:
      position: 101
      prefix: --quiet
  - id: rand_tree
    type:
      - 'null'
      - string
    doc: Start from a random topology
    inputBinding:
      position: 101
      prefix: --rand_tree
  - id: redo
    type:
      - 'null'
      - boolean
    doc: Run even if there are existing files with the same name (use with 
      caution!)
    default: false
    inputBinding:
      position: 101
      prefix: --redo
  - id: search
    type:
      - 'null'
      - boolean
    doc: Find best scoring ML tree (default)
    default: false
    inputBinding:
      position: 101
      prefix: --search
  - id: search_1random
    type:
      - 'null'
      - boolean
    doc: Find best scoring ML tree with 1 random tree
    default: false
    inputBinding:
      position: 101
      prefix: --search_1random
  - id: seed
    type:
      - 'null'
      - int
    doc: Seed for random numbers
    default: 12345
    inputBinding:
      position: 101
      prefix: --seed
  - id: seqs
    type:
      - 'null'
      - File
    doc: Input alignment in FASTA or PHYLIP format
    inputBinding:
      position: 101
      prefix: --seqs
  - id: terrace
    type:
      - 'null'
      - boolean
    doc: Check whether a tree lies on a phylogenetic terrace
    default: false
    inputBinding:
      position: 101
      prefix: --terrace
  - id: user_tree
    type:
      - 'null'
      - File
    doc: Load a custom starting tree from the NEWICK file
    inputBinding:
      position: 101
      prefix: --user_tree
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/haphpipe:1.0.3--py_0
stdout: haphpipe_build_tree_NG.out
