cwlVersion: v1.2
class: CommandLineTool
baseCommand: metaphlan
label: metaphlan
doc: "METAgenomic PHyLogenetic ANalysis for metagenomic taxonomic profiling.\n\nTool
  homepage: https://github.com/biobakery/metaphlan"
inputs:
  - id: input_file
    type:
      - 'null'
      - File
    doc: 'the input file can be: * a fastq file containing metagenomic reads OR *
      a BowTie2 produced SAM file. OR * a minimap2 produced SAM file (for long reads).
      OR * an intermediary mapping file of the metagenome generated by a previous
      MetaPhlAn run (mapout) If the input file is missing, the script assumes that
      the input is provided using the standard input, or named pipes. IMPORTANT: the
      type of input needs to be specified with --input_type'
    inputBinding:
      position: 1
  - id: analysis_type
    type:
      - 'null'
      - string
    doc: 'Type of analysis to perform: * rel_ab: profiling a metagenomes in terms
      of relative abundances * rel_ab_w_read_stats: profiling a metagenomes in terms
      of relative abundances and estimate the number of reads coming from each clade.
      * clade_profiles: normalized marker counts for clades with at least a non-null
      marker * marker_ab_table: normalized marker counts (only when > 0.0 and normalized
      by metagenome size if --nreads is specified) * marker_pres_table: list of markers
      present in the sample (threshold at 1.0 if not differently specified with --pres_th'
    inputBinding:
      position: 102
      prefix: --analysis_type
  - id: avoid_disqm
    type:
      - 'null'
      - boolean
    doc: Deactivate the procedure of disambiguating the quasi-markers based on 
      the marker abundance pattern found in the sample. It is generally 
      recommended to keep the disambiguation procedure in order to minimize 
      false positives
    inputBinding:
      position: 102
      prefix: --avoid_disqm
  - id: biom_format_output
    type:
      - 'null'
      - boolean
    doc: Report the profiling using the biom output format
    inputBinding:
      position: 102
      prefix: --biom_format_output
  - id: biom_mdelim
    type:
      - 'null'
      - string
    doc: Delimiter for metadata in the biom output format [default '|']
    inputBinding:
      position: 102
      prefix: --biom_mdelim
  - id: bowtie2_build
    type:
      - 'null'
      - File
    doc: Full path to the bowtie2-build command to use, deafult assumes that 
      'bowtie2-build is present in the system path
    inputBinding:
      position: 102
      prefix: --bowtie2_build
  - id: bowtie2_exe
    type:
      - 'null'
      - File
    doc: Full path and name of the BowTie2 executable. This option 
      allowsMetaPhlAn to reach the executable even when it is not in the system 
      PATH or the system PATH is unreachable
    inputBinding:
      position: 102
      prefix: --bowtie2_exe
  - id: bt2_ps
    type:
      - 'null'
      - string
    doc: 'Presets options for BowTie2 (applied only when a FASTA file is provided)
      The choices enabled in MetaPhlAn are: * sensitive * very-sensitive * sensitive-local
      * very-sensitive-local'
    inputBinding:
      position: 102
      prefix: --bt2_ps
  - id: cami_format_output
    type:
      - 'null'
      - boolean
    doc: Report the profiling using the CAMI output format
    inputBinding:
      position: 102
      prefix: --CAMI_format_output
  - id: db_dir
    type:
      - 'null'
      - Directory
    doc: Folder containing the MetaPhlAn database. You can specify the location 
      by exporting the DEFAULT_DB_FOLDER variable in the shell (old --bowtie2db 
      option).
      /usr/local/lib/python3.13/site-packages/metaphlan/metaphlan_databases
    inputBinding:
      position: 102
      prefix: --db_dir
  - id: force
    type:
      - 'null'
      - boolean
    doc: Force profiling of the input file by removing the mapout file
    inputBinding:
      position: 102
      prefix: --force
  - id: force_download
    type:
      - 'null'
      - boolean
    doc: Force the re-download of the latest MetaPhlAn database.
    inputBinding:
      position: 102
      prefix: --force_download
  - id: forward_reads
    type:
      - 'null'
      - File
    doc: Specify the fastq file with forward reads of the input metagenomes. 
      Reads are assumed to be in the same order in the forward and reverse 
      files! [default None]
    inputBinding:
      position: 102
      prefix: --forward_reads
  - id: ignore_archaea
    type:
      - 'null'
      - boolean
    doc: Do not profile archeal organisms
    inputBinding:
      position: 102
      prefix: --ignore_archaea
  - id: ignore_bacteria
    type:
      - 'null'
      - boolean
    doc: Do not profile bacterial organisms
    inputBinding:
      position: 102
      prefix: --ignore_bacteria
  - id: ignore_eukaryotes
    type:
      - 'null'
      - boolean
    doc: Do not profile eukaryotic organisms
    inputBinding:
      position: 102
      prefix: --ignore_eukaryotes
  - id: ignore_ksgbs
    type:
      - 'null'
      - boolean
    doc: Do not profile known SGBs (together with --sgb option)
    inputBinding:
      position: 102
      prefix: --ignore_ksgbs
  - id: ignore_markers
    type:
      - 'null'
      - File
    doc: File containing a list of markers to ignore.
    inputBinding:
      position: 102
      prefix: --ignore_markers
  - id: ignore_usgbs
    type:
      - 'null'
      - boolean
    doc: Do not profile unknown SGBs (together with --sgb option)
    inputBinding:
      position: 102
      prefix: --ignore_usgbs
  - id: index
    type:
      - 'null'
      - string
    doc: Specify the id of the database version to use. If "latest", MetaPhlAn 
      will get the latest version. If an index name is provided, MetaPhlAn will 
      try to use it, if available, and skip the online check. If the database 
      files are not found on the local MetaPhlAn installation they will be 
      automatically downloaded
    inputBinding:
      position: 102
      prefix: --index
  - id: input_type
    type: string
    doc: set whether the input is the FASTA file of metagenomic reads or the SAM
      file of the mapping of the reads against the MetaPhlAn db.
    inputBinding:
      position: 102
      prefix: --input_type
  - id: install
    type:
      - 'null'
      - boolean
    doc: Only checks if the MetaPhlAn DB is installed and installs it if not. 
      All other parameters are ignored.
    inputBinding:
      position: 102
      prefix: --install
  - id: long_reads
    type:
      - 'null'
      - boolean
    doc: Add this parameter to profile long reads.
    inputBinding:
      position: 102
      prefix: --long_reads
  - id: mapout
    type:
      - 'null'
      - File
    doc: The file for saving the mapping output (old --bowtie2out option)
    inputBinding:
      position: 102
      prefix: --mapout
  - id: mapping_subsampling
    type:
      - 'null'
      - boolean
    doc: If used, the subsamping will be done on the mapping results instead of 
      on the reads.
    inputBinding:
      position: 102
      prefix: --mapping_subsampling
  - id: max_gcsd
    type:
      - 'null'
      - float
    doc: Specify the max gap-compressed sequence divergence (minimap2) allowed 
      between marker and read, default value is 0.10
    inputBinding:
      position: 102
      prefix: --max_gcsd
  - id: min_alignment_len
    type:
      - 'null'
      - int
    doc: The sam records for aligned reads with the longest subalignment length 
      smaller than this threshold will be discarded.
    inputBinding:
      position: 102
      prefix: --min_alignment_len
  - id: min_mapq_val
    type:
      - 'null'
      - int
    doc: Minimum mapping quality value (MAPQ)
    inputBinding:
      position: 102
      prefix: --min_mapq_val
  - id: minimap2_exe
    type:
      - 'null'
      - File
    doc: Full path and name of the Minimap2 executable. This option 
      allowsMetaPhlAn to reach the executable even when it is not in the system 
      PATH or the system PATH is unreachable
    inputBinding:
      position: 102
      prefix: --minimap2_exe
  - id: minimap2_ps
    type:
      - 'null'
      - string
    doc: "Presets options for Minimap2 (applied only when a FASTA/Q file is provided)
      Please refer to the minimap2 documentation and provide the options in a string
      such as: '-x asm20 -B 3 -O 3,12'"
    inputBinding:
      position: 102
      prefix: --minimap2_ps
  - id: nbases
    type:
      - 'null'
      - int
    doc: The total number of bases in the original metagenome. It is mandatory 
      when the --input_type is a SAM file from long reads mapping (--long_reads 
      is selected)
    inputBinding:
      position: 102
      prefix: --nbases
  - id: no_map
    type:
      - 'null'
      - boolean
    doc: Avoid storing the --mapout map file
    inputBinding:
      position: 102
      prefix: --no_map
  - id: nproc
    type:
      - 'null'
      - int
    doc: The number of CPUs to use for parallelizing the mapping [default 4]
    inputBinding:
      position: 102
      prefix: --nproc
  - id: nreads
    type:
      - 'null'
      - int
    doc: The total number of reads in the original metagenome. It is mandatory 
      when the --input_type is a SAM file.
    inputBinding:
      position: 102
      prefix: --nreads
  - id: offline
    type:
      - 'null'
      - boolean
    doc: If used, MetaPhlAn will not check for new database updates.
    inputBinding:
      position: 102
      prefix: --offline
  - id: perc_nonzero
    type:
      - 'null'
      - float
    doc: Percentage of markers with a non zero relative abundance for 
      misidentify a species
    inputBinding:
      position: 102
      prefix: --perc_nonzero
  - id: pres_th
    type:
      - 'null'
      - float
    doc: Threshold for calling a marker present by the -t marker_pres_table 
      option
    inputBinding:
      position: 102
      prefix: --pres_th
  - id: profile_vsc
    type:
      - 'null'
      - boolean
    doc: Add this parameter to profile Viruses with VSCs approach.
    inputBinding:
      position: 102
      prefix: --profile_vsc
  - id: read_min_len
    type:
      - 'null'
      - int
    doc: Specify the minimum length of the reads to be considered when parsing 
      the input file with 'read_fastx.py' script, default value is 70
    inputBinding:
      position: 102
      prefix: --read_min_len
  - id: reverse_reads
    type:
      - 'null'
      - File
    doc: Specify the fastq file with reverse reads of the input metagenomes. 
      Reads are assumed to be in the same order in the forward and reverse 
      files! [default None]
    inputBinding:
      position: 102
      prefix: --reverse_reads
  - id: sample_id
    type:
      - 'null'
      - string
    doc: Specify the sample ID for this analysis. Defaults to 
      'Metaphlan_Analysis'.
    inputBinding:
      position: 102
      prefix: --sample_id
  - id: sample_id_key
    type:
      - 'null'
      - string
    doc: Specify the sample ID key for this analysis. Defaults to 'SampleID'.
    inputBinding:
      position: 102
      prefix: --sample_id_key
  - id: skip_unclassified_estimation
    type:
      - 'null'
      - boolean
    doc: Do not scale relative abundances to the estimate unclassified taxa
    inputBinding:
      position: 102
      prefix: --skip_unclassified_estimation
  - id: split_readlen
    type:
      - 'null'
      - int
    doc: Specify length of the reads to be split into when using --split_reads, 
      default value is 150
    inputBinding:
      position: 102
      prefix: --split_readlen
  - id: split_reads
    type:
      - 'null'
      - boolean
    doc: Add this parameter to profile long reads by splitting into short reads.
    inputBinding:
      position: 102
      prefix: --split_reads
  - id: stat
    type:
      - 'null'
      - string
    doc: "Statistical approach for converting marker abundances into clade abundances
      'avg_g' : clade global (i.e. normalizing all markers together) average 'avg_l'
      : average of length-normalized marker counts 'tavg_g' : truncated clade global
      average at --stat_q quantile 'tavg_l' : truncated average of length-normalized
      marker counts (at --stat_q) 'wavg_g' : winsorized clade global average (at --stat_q)
      'wavg_l' : winsorized average of length-normalized marker counts (at --stat_q)
      'med' : median of length-normalized marker counts"
    inputBinding:
      position: 102
      prefix: --stat
  - id: stat_q
    type:
      - 'null'
      - float
    doc: Quantile value for the robust average
    inputBinding:
      position: 102
      prefix: --stat_q
  - id: subsampling
    type:
      - 'null'
      - int
    doc: Specify the number of reads to be considered from the input metagenomes
      (number of bases if --long_reads) [default None]
    inputBinding:
      position: 102
      prefix: --subsampling
  - id: subsampling_paired
    type:
      - 'null'
      - int
    doc: Specify the number of paired reads to be considered from the input 
      metagenomes [default None]
    inputBinding:
      position: 102
      prefix: --subsampling_paired
  - id: subsampling_seed
    type:
      - 'null'
      - string
    doc: Random seed to use in the selection of the subsampled reads. Choose 
      "random" for a random behaviour
    inputBinding:
      position: 102
      prefix: --subsampling_seed
  - id: tax_lev
    type:
      - 'null'
      - string
    doc: "The taxonomic level for the relative abundance output: 'a' : all taxonomic
      levels 'k' : kingdoms 'p' : phyla only 'c' : classes only 'o' : orders only
      'f' : families only 'g' : genera only 's' : species only 't' : SGBs only"
    inputBinding:
      position: 102
      prefix: --tax_lev
  - id: tmp_dir
    type:
      - 'null'
      - Directory
    doc: The folder used to store temporary files [default is the OS dependent 
      tmp dir]
    inputBinding:
      position: 102
      prefix: --tmp_dir
  - id: use_group_representative
    type:
      - 'null'
      - boolean
    doc: Use a species as representative for species groups.
    inputBinding:
      position: 102
      prefix: --use_group_representative
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Makes MetaPhlAn verbose
    inputBinding:
      position: 102
      prefix: --verbose
  - id: vsc_breadth
    type:
      - 'null'
      - float
    doc: Minimum Breadth of Coverage for a Viral Group to be reported. Default 
      is 0.75 (at least 75 percent breadth to report), 0.5 for long reads
    inputBinding:
      position: 102
      prefix: --vsc_breadth
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: The output file (if not specified stdout)
    outputBinding:
      glob: $(inputs.output_file)
  - id: samout
    type:
      - 'null'
      - File
    doc: The sam output file
    outputBinding:
      glob: $(inputs.samout)
  - id: vsc_out
    type:
      - 'null'
      - File
    doc: Path to the VSCs breadth-of-coverage output file
    outputBinding:
      glob: $(inputs.vsc_out)
  - id: subsampling_output
    type:
      - 'null'
      - File
    doc: The output file for the subsampled reads. If the extension is bz2 or 
      gzip, the files will be compressed. If not specified the subsampled reads 
      will not be saved.
    outputBinding:
      glob: $(inputs.subsampling_output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/metaphlan:4.2.4--pyhdfd78af_0
