cwlVersion: v1.2
class: CommandLineTool
baseCommand: ggcaller
label: ggcaller
doc: "Generates ORFs from a Bifrost graph.\n\nTool homepage: https://github.com/samhorsfield96/ggCaller"
inputs:
  - id: aligner
    type:
      - 'null'
      - string
    doc: "Specify an aligner. Options: 'ref' for reference-guided MSA and 'def' for
      default standard MSA"
    inputBinding:
      position: 101
      prefix: --aligner
  - id: alignment
    type:
      - 'null'
      - string
    doc: Output alignments of core genes or all genes. Options are 'core' and 
      'pan'.
    inputBinding:
      position: 101
      prefix: --alignment
  - id: all_seq_in_graph
    type:
      - 'null'
      - boolean
    doc: Retains all DNA sequence for each gene cluster in the Panaroo graph 
      output. Off by default as it uses a large amount of space.
    inputBinding:
      position: 101
      prefix: --all-seq-in-graph
  - id: annotation
    type:
      - 'null'
      - string
    doc: Annotate genes using diamond default (fast), diamond sensitive 
      (sensitive) or diamond and HMMscan (ultrasensitive). Specify 'none' if 
      annotation not required.
    inputBinding:
      position: 101
      prefix: --annotation
  - id: balrog_db
    type:
      - 'null'
      - File
    doc: Path to save BALROG and default annotation databases. If not specified 
      will downloadautomatically on first run.
    inputBinding:
      position: 101
      prefix: --balrog-db
  - id: clean_mode
    type:
      - 'null'
      - string
    doc: "The stringency mode at which to run panaroo. Must be one of 'strict', 'moderate'
      or 'sensitive'. Each of these modes can be fine tuned using the additional parameters
      in the 'Graph correction' section. strict: Requires fairly strong evidence (present
      in at least 5% of genomes) to keep likely contaminant genes. moderate: Requires
      moderate evidence (present in at least 1% of genomes) to keep likely contaminant
      genes. sensitive: Does not delete any genes and only performes merge and refinding
      operations. Useful if rare plasmids are of interest as these are often hard
      to disguish from contamination. Results will likely include higher number of
      spurious annotations."
    inputBinding:
      position: 101
      prefix: --clean-mode
  - id: codons
    type:
      - 'null'
      - File
    doc: JSON file containing start and stop codon sequences.
    inputBinding:
      position: 101
      prefix: --codons
  - id: colours
    type:
      - 'null'
      - File
    doc: Bifrost colours file generated by Bifrost build.
    inputBinding:
      position: 101
      prefix: --colours
  - id: core_threshold
    type:
      - 'null'
      - float
    doc: Core-genome sample threshold.
    inputBinding:
      position: 101
      prefix: --core-threshold
  - id: diamonddb
    type:
      - 'null'
      - File
    doc: Diamond database. Defaults are 'Bacteria' or 'Viruses'. Can also 
      specify path to fasta file for custom database generation
    inputBinding:
      position: 101
      prefix: --diamonddb
  - id: edge_support_threshold
    type:
      - 'null'
      - int
    doc: minimum support required to keep an edge that has been flagged as a 
      possible mis-assembly
    inputBinding:
      position: 101
      prefix: --edge-support-threshold
  - id: evalue
    type:
      - 'null'
      - float
    doc: Maximum e-value to return for DIAMOND and HMMER searches during 
      annotation
    inputBinding:
      position: 101
      prefix: --evalue
  - id: family_threshold
    type:
      - 'null'
      - float
    doc: protein family sequence identity threshold
    inputBinding:
      position: 101
      prefix: --family-threshold
  - id: gene_finding_only
    type:
      - 'null'
      - boolean
    doc: Only run ggCaller gene-finding and generate a gff compatible with other
      clustering tools.
    inputBinding:
      position: 101
      prefix: --gene-finding-only
  - id: graph
    type:
      - 'null'
      - File
    doc: Bifrost GFA file generated by Bifrost build.
    inputBinding:
      position: 101
      prefix: --graph
  - id: hmmdb
    type:
      - 'null'
      - File
    doc: HMMER hmm profile file. Default is Uniprot HAMAP. Can alsospecify path 
      to pre-built hmm profile file generated using hmmbuild
    inputBinding:
      position: 101
      prefix: --hmmdb
  - id: identity_cutoff
    type:
      - 'null'
      - float
    doc: Minimum identity at amino acid level between two ORFs for clustering.
    inputBinding:
      position: 101
      prefix: --identity-cutoff
  - id: ignore_pseduogenes
    type:
      - 'null'
      - boolean
    doc: Ignore ORFs annotated as 'potential pseudogenes' in alignment
    inputBinding:
      position: 101
      prefix: --ignore-pseduogenes
  - id: kmer
    type:
      - 'null'
      - int
    doc: K-mer size used in Bifrost build (bp).
    inputBinding:
      position: 101
      prefix: --kmer
  - id: len_diff_cutoff
    type:
      - 'null'
      - float
    doc: Minimum ratio of length between two ORFs for clustering.
    inputBinding:
      position: 101
      prefix: --len-diff-cutoff
  - id: length_outlier_support_proportion
    type:
      - 'null'
      - float
    doc: proportion of genomes supporting a gene with a length more than 1.5x 
      outside the interquatile range for genes in the same cluster.Genes failing
      this test will be re-annotated at the shorter length
    inputBinding:
      position: 101
      prefix: --length-outlier-support-proportion
  - id: max_orf_orf_distance
    type:
      - 'null'
      - int
    doc: Maximum distance for graph traversal during ORF connection (bp).
    inputBinding:
      position: 101
      prefix: --max-orf-orf-distance
  - id: max_orf_overlap
    type:
      - 'null'
      - int
    doc: Maximum overlap allowed between overlapping ORFs.
    inputBinding:
      position: 101
      prefix: --max-ORF-overlap
  - id: max_path_length
    type:
      - 'null'
      - int
    doc: Maximum path length during ORF finding (bp).
    inputBinding:
      position: 101
      prefix: --max-path-length
  - id: merge_paralogs
    type:
      - 'null'
      - boolean
    doc: don't split paralogs
    inputBinding:
      position: 101
      prefix: --merge-paralogs
  - id: min_edge_support_sv
    type:
      - 'null'
      - int
    doc: minimum edge support required to call structural variants in the 
      presence/absence sv file
    inputBinding:
      position: 101
      prefix: --min-edge-support-sv
  - id: min_orf_length
    type:
      - 'null'
      - int
    doc: Minimum ORF length to return (bp).
    inputBinding:
      position: 101
      prefix: --min-orf-length
  - id: min_orf_score
    type:
      - 'null'
      - int
    doc: Minimum individual Balrog score for an ORF to be returned.
    inputBinding:
      position: 101
      prefix: --min-orf-score
  - id: min_path_score
    type:
      - 'null'
      - int
    doc: Minimum total Balrog score for a path of ORFs to be returned.
    inputBinding:
      position: 101
      prefix: --min-path-score
  - id: min_trailing_support
    type:
      - 'null'
      - int
    doc: minimum cluster size to keep a gene called at the end of a contig
    inputBinding:
      position: 101
      prefix: --min-trailing-support
  - id: no_clean_edges
    type:
      - 'null'
      - boolean
    doc: Turn off edge filtering in the final output graph.
    inputBinding:
      position: 101
      prefix: --no-clean-edges
  - id: no_clustering
    type:
      - 'null'
      - boolean
    doc: Do not cluster ORFs.
    inputBinding:
      position: 101
      prefix: --no-clustering
  - id: no_filter
    type:
      - 'null'
      - boolean
    doc: Do not filter ORF calls using Balrog. Will return all ORF calls.
    inputBinding:
      position: 101
      prefix: --no-filter
  - id: no_refind
    type:
      - 'null'
      - boolean
    doc: Do not refind uncalled genes
    inputBinding:
      position: 101
      prefix: --no-refind
  - id: no_variants
    type:
      - 'null'
      - boolean
    doc: Do not call variants using SNP-sites after alignment.
    inputBinding:
      position: 101
      prefix: --no-variants
  - id: no_write_graph
    type:
      - 'null'
      - boolean
    doc: Do not write Bifrost GFA and colours to file.
    inputBinding:
      position: 101
      prefix: --no-write-graph
  - id: no_write_idx
    type:
      - 'null'
      - boolean
    doc: Do not write FMIndexes to file.
    inputBinding:
      position: 101
      prefix: --no-write-idx
  - id: not_ref
    type:
      - 'null'
      - boolean
    doc: If using existing graph, was not graph built exclusively with assembled
      genomes.
    inputBinding:
      position: 101
      prefix: --not-ref
  - id: prev_run
    type:
      - 'null'
      - Directory
    doc: Directory containing data from previous ggCaller run. Must have been 
      run with "--save"
    inputBinding:
      position: 101
      prefix: --prev-run
  - id: query
    type:
      - 'null'
      - type: array
        items: File
    doc: List of unitig sequences to query (either FASTA or one sequence per 
      line)
    inputBinding:
      position: 101
      prefix: --query
  - id: query_id
    type:
      - 'null'
      - float
    doc: Ratio of query-kmers to required to match in graph.
    inputBinding:
      position: 101
      prefix: --query-id
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: suppress additional output
    inputBinding:
      position: 101
      prefix: --quiet
  - id: reads
    type:
      - 'null'
      - type: array
        items: File
    doc: List of read files (one file path per line).
    inputBinding:
      position: 101
      prefix: --reads
  - id: refind_prop_match
    type:
      - 'null'
      - float
    doc: the proportion of an accessory gene that must be found in order to 
      consider it a match
    inputBinding:
      position: 101
      prefix: --refind-prop-match
  - id: refs
    type:
      - 'null'
      - type: array
        items: File
    doc: List of reference genomes (one file path per line).
    inputBinding:
      position: 101
      prefix: --refs
  - id: repeat
    type:
      - 'null'
      - boolean
    doc: Enable traversal of nodes multiple times.
    inputBinding:
      position: 101
      prefix: --repeat
  - id: save
    type:
      - 'null'
      - boolean
    doc: Save graph objects for sequence querying.
    inputBinding:
      position: 101
      prefix: --save
  - id: score_tolerance
    type:
      - 'null'
      - float
    doc: Length probability tolerance for shorter alternative start sites. If 
      within tolerance,ggCaller will check if start coverage and BALROG score 
      are both higher in shorter ORF.
    inputBinding:
      position: 101
      prefix: --score-tolerance
  - id: search_radius
    type:
      - 'null'
      - int
    doc: the distance in nucleotides surronding the neighbour of an accessory 
      gene in which to search for it
    inputBinding:
      position: 101
      prefix: --search-radius
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use.
    inputBinding:
      position: 101
      prefix: --threads
  - id: trailing_recursive
    type:
      - 'null'
      - int
    doc: number of times to perform recursive trimming of low support nodes near
      the end of contigs
    inputBinding:
      position: 101
      prefix: --trailing-recursive
  - id: truncation_threshold
    type:
      - 'null'
      - float
    doc: Sequences in a gene family cluster below this proportion of the length 
      of thecentroid will be annotated as 'potential pseudogene'
    inputBinding:
      position: 101
      prefix: --truncation-threshold
outputs:
  - id: out
    type:
      - 'null'
      - Directory
    doc: Output directory
    outputBinding:
      glob: $(inputs.out)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ggcaller:1.4.3--py39h3961c5e_0
