cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - treesapp
  - phylotu
label: treesapp_phylotu
doc: "A tool for sorting query sequences placed on a phylogeny into phylogenetically-inferred
  clusters.\n\nTool homepage: https://github.com/hallamlab/TreeSAPP"
inputs:
  - id: alpha
    type:
      - 'null'
      - string
    doc: The evolutionary distance threshold defining the cluster boundaries.
    default: auto
    inputBinding:
      position: 101
      prefix: --alpha
  - id: assign_output
    type:
      type: array
      items: Directory
    doc: Path to one or more output directories of treesapp assign.
    inputBinding:
      position: 101
      prefix: --assign_output
  - id: centroid_proportion
    type:
      - 'null'
      - float
    doc: The proportion of the reference package profile HMM a candidate 
      centroid must exceed.No sequence convering less than this proportion will 
      be used as a centroid.
    default: 0.6
    inputBinding:
      position: 101
      prefix: --centroid_proportion
  - id: delete
    type:
      - 'null'
      - boolean
    doc: Delete all intermediate files to save disk space.
    inputBinding:
      position: 101
      prefix: --delete
  - id: jplace
    type:
      type: array
      items: File
    doc: Path to one or more JPlace files generated by placement on a reference 
      package's phylogeny.
    inputBinding:
      position: 101
      prefix: --jplace
  - id: mode
    type:
      - 'null'
      - string
    doc: The phylogentic clustering mode to use.
    default: ref_guided
    inputBinding:
      position: 101
      prefix: --mode
  - id: num_threads
    type:
      - 'null'
      - int
    doc: The number of CPU threads or parallel processes to use in various 
      pipeline steps
    default: 2
    inputBinding:
      position: 101
      prefix: --num_procs
  - id: overwrite
    type:
      - 'null'
      - boolean
    doc: Overwrites previously written output files and directories
    inputBinding:
      position: 101
      prefix: --overwrite
  - id: pre_cluster
    type:
      - 'null'
      - string
    doc: The method to use for pre-clustering the classified sequences, based on
      either placement-space ('psc') or pairwise alignment ('align').
    default: psc
    inputBinding:
      position: 101
      prefix: --pre_cluster
  - id: refpkg_name
    type: string
    doc: Name of the reference package to use, referenced by its 'prefix' 
      attribute, from the set packaged with TreeSAPP. Use `treesapp info -v` to 
      get the available list.
    inputBinding:
      position: 101
      prefix: --refpkg_name
  - id: refpkg_path
    type: File
    doc: Path to the reference package pickle (.pkl) file.
    inputBinding:
      position: 101
      prefix: --refpkg_path
  - id: sample_regex
    type:
      - 'null'
      - string
    doc: "A regular expression for parsing the sample name from a query sequence name.
      Example: '^(\\d+)\\.a:.*'."
    default: None
    inputBinding:
      position: 101
      prefix: --sample_regex
  - id: tax_rank
    type:
      - 'null'
      - string
    doc: The taxonomic rank the cluster radius should approximately represent.
    default: species
    inputBinding:
      position: 101
      prefix: --tax_rank
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Prints a more verbose runtime log
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output
    type:
      - 'null'
      - Directory
    doc: Path to an output directory
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/treesapp:0.11.4--py39h2de1943_2
