cwlVersion: v1.2
class: CommandLineTool
baseCommand: ema
label: ema_preproc
doc: "EMA is a tool for processing and aligning barcoded sequencing data.\n\nTool
  homepage: http://ema.csail.mit.edu/"
inputs:
  - id: output_prefixes
    type:
      - 'null'
      - type: array
        items: string
    doc: list of all output prefixes generated by count stage
    inputBinding:
      position: 1
  - id: apply_hamming_correction
    type:
      - 'null'
      - boolean
    doc: apply Hamming-2 correction [off]
    inputBinding:
      position: 102
      prefix: -h
  - id: haplotag_barcodes
    type:
      - 'null'
      - boolean
    doc: using haplotag barcodes
    inputBinding:
      position: 102
      prefix: -p
  - id: num_buckets
    type:
      - 'null'
      - int
    doc: number of barcode buckets to make
    inputBinding:
      position: 102
      prefix: -n
  - id: output_bx_fastq
    type:
      - 'null'
      - boolean
    doc: output BX:Z-formatted FASTQs [off]
    inputBinding:
      position: 102
      prefix: -b
  - id: output_directory
    type: Directory
    doc: specify output directory [required]
    inputBinding:
      position: 102
      prefix: -o
  - id: output_prefix
    type: string
    doc: specify output prefix [required]
    inputBinding:
      position: 102
      prefix: -o
  - id: threads
    type:
      - 'null'
      - int
    doc: set number of threads
    inputBinding:
      position: 102
      prefix: -t
  - id: whitelist_path
    type:
      - 'null'
      - File
    doc: specify barcode whitelist [required, unless using -p option]
    inputBinding:
      position: 102
      prefix: -w
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ema:0.7.0--h5ca1c30_2
stdout: ema_preproc.out
