cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ema
  - preproc
label: ema_preproc
doc: "preprocess barcoded FASTQ files (takes interleaved FASTQ via stdin)\n\nTool
  homepage: https://github.com/arshajii/ema"
inputs:
  - id: interleaved_fastq
    type: File
    doc: interleaved barcoded FASTQ, read from standard input
  - id: ncnt_files
    type:
      - 'null'
      - type: array
        items: File
    doc: list of all .ema-ncnt files generated by the count stage
    inputBinding:
      position: 200
      valueFrom: $(self.map(function(f) { return f.basename; }))
  - id: fcnt_files
    type:
      - 'null'
      - type: array
        items: File
    doc: the matching .ema-fcnt files of the count stage (read beside the 
      .ema-ncnt files)
  - id: apply_hamming_correction
    type:
      - 'null'
      - boolean
    doc: apply Hamming-2 correction [off]
    inputBinding:
      position: 102
      prefix: -h
  - id: haplotag_barcodes
    type:
      - 'null'
      - boolean
    doc: using haplotag barcodes
    inputBinding:
      position: 102
      prefix: -p
  - id: num_buckets
    type:
      - 'null'
      - int
    doc: number of barcode buckets to make [500]
    inputBinding:
      position: 102
      prefix: -n
  - id: output_bx_fastq
    type:
      - 'null'
      - boolean
    doc: output BX:Z-formatted FASTQs [off]
    inputBinding:
      position: 102
      prefix: -b
  - id: output_directory
    type: string
    doc: specify output directory [required]
    inputBinding:
      position: 102
      prefix: -o
  - id: threads
    type:
      - 'null'
      - int
    doc: set number of threads [1]
    inputBinding:
      position: 102
      prefix: -t
  - id: whitelist_path
    type:
      - 'null'
      - File
    doc: specify barcode whitelist [required, unless using -p option]
    inputBinding:
      position: 102
      prefix: -w
outputs:
  - id: output_directory_dir
    type: Directory
    doc: output directory with the barcode bins (ema-bin-NNN) and ema-nobc
    outputBinding:
      glob: $(inputs.output_directory)
  - id: stderr_log
    type: stderr
    doc: log messages written to standard error
stdin: $(inputs.interleaved_fastq.path)
stderr: ema_preproc.log
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ema:0.7.0--h5ca1c30_2
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - $(inputs.ncnt_files)
      - $(inputs.fcnt_files)
