cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_greater-than
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute. See COMMANDS section for options.
    inputBinding:
      position: 1
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input meryl databases or files to process.
    inputBinding:
      position: 2
  - id: threshold
    type: int
    doc: Threshold value N for comparison commands (less-than, greater-than, 
      equal-to, not-equal-to).
    inputBinding:
      position: 3
  - id: value_to_modify
    type: string
    doc: Value X for arithmetic modification commands (increase, decrease, 
      multiply, divide, divide-round, modulo).
    inputBinding:
      position: 4
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: Compress homopolymer runs to a single letter.
    inputBinding:
      position: 105
      prefix: compress
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: Expect N mers in the input (optional; for precise memory sizing).
    inputBinding:
      position: 105
      prefix: n
  - id: kmer_size
    type: int
    doc: Create mers of size K bases (mandatory for count operations).
    inputBinding:
      position: 105
      prefix: k
  - id: memory_limit
    type:
      - 'null'
      - string
    doc: Use no more than (about) M GB memory.
    inputBinding:
      position: 105
      prefix: memory
  - id: threads
    type:
      - 'null'
      - int
    doc: Use no more than T threads.
    inputBinding:
      position: 105
outputs:
  - id: output_database
    type:
      - 'null'
      - File
    doc: Write kmers generated by the present command to an output meryl 
      database O. Mandatory for count operations.
    outputBinding:
      glob: $(inputs.output_database)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
