cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - meryl
  - modulo
label: meryl_modulo
doc: "set the count of each kmer to the remainder of the count divided by X.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: value
    type: long
    doc: "Value X"
    inputBinding:
      position: 1
  - id: input_db
    type: Directory
    doc: "Input meryl database"
    inputBinding:
      position: 100
  - id: output
    type: string
    default: "modified.meryl"
    doc: "write kmers generated by the present command to an output meryl database O"
    inputBinding:
      position: 200
      prefix: output
outputs:
  - id: database
    type: Directory
    doc: "Output meryl database"
    outputBinding:
      glob: $(inputs.output)
requirements:
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 2048
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
