cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_compress
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute (e.g., statistics, histogram, print, 
      count, less-than N, etc.)
    inputBinding:
      position: 1
  - id: N
    type: int
    doc: Number for comparison (used with less-than, greater-than, equal-to, 
      not-equal-to)
    inputBinding:
      position: 2
  - id: X
    type: float
    doc: Value for arithmetic operations (increase, decrease, multiply, divide, 
      modulo)
    inputBinding:
      position: 3
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input files for the command
    inputBinding:
      position: 4
  - id: compress
    type:
      - 'null'
      - boolean
    doc: compress homopolymer runs to a single letter
    inputBinding:
      position: 105
  - id: grouping
    type:
      - 'null'
      - boolean
    doc: Indicates that commands and files are grouped using square brackets
    inputBinding:
      position: 105
  - id: k
    type:
      - 'null'
      - int
    doc: create mers of size K bases (mandatory for count operations)
    inputBinding:
      position: 105
  - id: memory
    type:
      - 'null'
      - string
    doc: use no more than (about) M GB memory
    inputBinding:
      position: 105
  - id: n
    type:
      - 'null'
      - int
    doc: expect N mers in the input (optional; for precise memory sizing)
    inputBinding:
      position: 105
  - id: threads
    type:
      - 'null'
      - int
    doc: use no more than T threads
    inputBinding:
      position: 105
  - id: output_path
    type: string
    doc: Output or path parameter `output_path`
    inputBinding:
      position: 106
      prefix: --output
outputs:
  - id: output
    type:
      - 'null'
      - File
    doc: write kmers generated by the present command to an output meryl 
      database O (mandatory for count operations)
    outputBinding:
      glob: $(inputs.output_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
