cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_not-equal-to
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The primary command to execute (e.g., statistics, histogram, print, 
      count, less-than, etc.)
    inputBinding:
      position: 1
  - id: difference_operation
    type: string
    doc: Difference operation.
    inputBinding:
      position: 2
  - id: intersect_operation
    type: string
    doc: Intersection operation type (intersect, intersect-min, intersect-max, 
      intersect-sum).
    inputBinding:
      position: 3
  - id: subtract_operation
    type: string
    doc: Subtract operation.
    inputBinding:
      position: 4
  - id: symmetric_difference_operation
    type: string
    doc: Symmetric difference operation.
    inputBinding:
      position: 5
  - id: union_operation
    type: string
    doc: Union operation type (union, union-min, union-max, union-sum).
    inputBinding:
      position: 6
  - id: add_value
    type: int
    doc: Value X to add to counts.
    inputBinding:
      position: 7
  - id: divide_round_value
    type: int
    doc: Value X to divide counts by and round results. Count < X will become 1.
    inputBinding:
      position: 8
  - id: divide_value
    type: int
    doc: Value X to divide counts by.
    inputBinding:
      position: 9
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input files for the command. Can be meryl databases or FASTA/FASTQ 
      files for count operations.
    inputBinding:
      position: 10
  - id: modulo_value
    type: int
    doc: Value X to set the remainder of the count divided by X.
    inputBinding:
      position: 11
  - id: multiply_value
    type: int
    doc: Value X to multiply counts by.
    inputBinding:
      position: 12
  - id: subtract_value
    type: int
    doc: Value X to subtract from counts.
    inputBinding:
      position: 13
  - id: threshold_N
    type: int
    doc: Threshold value N for comparison commands (less-than, greater-than, 
      equal-to, not-equal-to).
    inputBinding:
      position: 14
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: Compress homopolymer runs to a single letter.
    inputBinding:
      position: 115
      prefix: compress
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: Expect N mers in the input (optional; for precise memory sizing).
    inputBinding:
      position: 115
      prefix: n
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: Create mers of size K bases (mandatory for count operations).
    inputBinding:
      position: 115
      prefix: k
  - id: memory
    type:
      - 'null'
      - string
    doc: Use no more than (about) M GB memory.
    inputBinding:
      position: 115
  - id: threads
    type:
      - 'null'
      - int
    doc: Use no more than T threads.
    inputBinding:
      position: 115
outputs:
  - id: output_database
    type:
      - 'null'
      - File
    doc: Write kmers generated by the present command to an output meryl 
      database O. Mandatory for count operations.
    outputBinding:
      glob: $(inputs.output_database)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
