cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_statistics
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute (e.g., statistics, histogram, print, 
      count, less-than N, etc.)
    inputBinding:
      position: 1
  - id: add_value
    type:
      - 'null'
      - float
    doc: Value X for increase, decrease, multiply, divide, divide-round, modulo 
      commands
    inputBinding:
      position: 2
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input meryl databases or files
    inputBinding:
      position: 3
  - id: threshold_n
    type:
      - 'null'
      - int
    doc: Threshold value N for less-than, greater-than, equal-to, not-equal-to 
      commands
    inputBinding:
      position: 4
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: compress homopolymer runs to a single letter
    inputBinding:
      position: 105
      prefix: compress
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: expect N mers in the input (optional; for precise memory sizing)
    inputBinding:
      position: 105
      prefix: n
  - id: grouping
    type:
      - 'null'
      - boolean
    doc: Indicates grouping of commands using square brackets
    inputBinding:
      position: 105
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: create mers of size K bases (mandatory for count operations)
    inputBinding:
      position: 105
      prefix: k
  - id: memory
    type:
      - 'null'
      - string
    doc: use no more than (about) M GB memory
    inputBinding:
      position: 105
  - id: threads
    type:
      - 'null'
      - int
    doc: use no more than T threads
    inputBinding:
      position: 105
outputs:
  - id: output_database
    type:
      - 'null'
      - File
    doc: write kmers generated by the present command to an output meryl 
      database O
    outputBinding:
      glob: $(inputs.output_database)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
