cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - meryl
  - intersect-sum
label: meryl_intersect-sum
doc: "return kmers that occur in all inputs, set the count to the sum of the counts.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: input_dbs
    type: Directory[]
    doc: "Input meryl databases (two or more; order matters for subtract and difference)"
    inputBinding:
      position: 100
  - id: output
    type: string
    default: "combined.meryl"
    doc: "write kmers generated by the present command to an output meryl database O"
    inputBinding:
      position: 200
      prefix: output
outputs:
  - id: database
    type: Directory
    doc: "Output meryl database"
    outputBinding:
      glob: $(inputs.output)
requirements:
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 2048
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
