cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_less-than
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute (e.g., statistics, histogram, print, 
      count, less-than, etc.)
    inputBinding:
      position: 1
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input meryl databases or files to operate on.
    inputBinding:
      position: 2
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: Compress homopolymer runs to a single letter.
    inputBinding:
      position: 103
      prefix: compress
  - id: decrease_by
    type:
      - 'null'
      - int
    doc: Subtract X from the count of each kmer.
    inputBinding:
      position: 103
      prefix: decrease
  - id: divide_by
    type:
      - 'null'
      - float
    doc: Divide the count of each kmer by X.
    inputBinding:
      position: 103
      prefix: divide
  - id: divide_round_by
    type:
      - 'null'
      - float
    doc: Divide the count of each kmer by X and round results. Count < X will 
      become 1.
    inputBinding:
      position: 103
      prefix: divide-round
  - id: equal_to_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur exactly N times in the input.
    inputBinding:
      position: 103
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: Expect N mers in the input (optional; for precise memory sizing).
    inputBinding:
      position: 103
      prefix: n
  - id: greater_than_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur more than N times in the input.
    inputBinding:
      position: 103
  - id: increase_by
    type:
      - 'null'
      - int
    doc: Add X to the count of each kmer.
    inputBinding:
      position: 103
      prefix: increase
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: Create mers of size K bases (mandatory for count operations).
    inputBinding:
      position: 103
      prefix: k
  - id: less_than_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur fewer than N times in the input.
    inputBinding:
      position: 103
  - id: memory
    type:
      - 'null'
      - string
    doc: Use no more than (about) M GB memory.
    inputBinding:
      position: 103
  - id: modulo_by
    type:
      - 'null'
      - int
    doc: Set the count of each kmer to the remainder of the count divided by X.
    inputBinding:
      position: 103
      prefix: modulo
  - id: multiply_by
    type:
      - 'null'
      - float
    doc: Multiply the count of each kmer by X.
    inputBinding:
      position: 103
      prefix: multiply
  - id: not_equal_to_n
    type:
      - 'null'
      - int
    doc: Return kmers that do not occur exactly N times in the input.
    inputBinding:
      position: 103
  - id: threads
    type:
      - 'null'
      - int
    doc: Use no more than T threads.
    inputBinding:
      position: 103
outputs:
  - id: output_db
    type:
      - 'null'
      - File
    doc: Write kmers generated by the present command to an output meryl 
      database O. Mandatory for count operations.
    outputBinding:
      glob: $(inputs.output_db)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
