cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - meryl
  - greater-than
label: meryl_greater-than
doc: "return kmers that occur more than N times in the input. Accepts exactly one input meryl database.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: threshold
    type: long
    doc: "Count threshold N"
    inputBinding:
      position: 1
  - id: input_db
    type: Directory
    doc: "Input meryl database"
    inputBinding:
      position: 100
  - id: output
    type: string
    default: "filtered.meryl"
    doc: "write kmers generated by the present command to an output meryl database O"
    inputBinding:
      position: 200
      prefix: output
outputs:
  - id: database
    type: Directory
    doc: "Output meryl database"
    outputBinding:
      glob: $(inputs.output)
requirements:
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 2048
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
