cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_print
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute. See COMMANDS section for options.
    inputBinding:
      position: 1
  - id: decrease_by
    type:
      - 'null'
      - int
    doc: Subtract X from the count of each kmer.
    inputBinding:
      position: 2
  - id: divide_by
    type:
      - 'null'
      - int
    doc: Divide the count of each kmer by X.
    inputBinding:
      position: 3
  - id: divide_round_by
    type:
      - 'null'
      - int
    doc: Divide the count of each kmer by X and round results. count < X will 
      become 1.
    inputBinding:
      position: 4
  - id: equal_to_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur exactly N times in the input.
    inputBinding:
      position: 5
  - id: greater_than_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur more than N times in the input.
    inputBinding:
      position: 6
  - id: increase_by
    type:
      - 'null'
      - int
    doc: Add X to the count of each kmer.
    inputBinding:
      position: 7
  - id: less_than_n
    type:
      - 'null'
      - int
    doc: Return kmers that occur fewer than N times in the input.
    inputBinding:
      position: 8
  - id: modulo_by
    type:
      - 'null'
      - int
    doc: Set the count of each kmer to the remainder of the count divided by X.
    inputBinding:
      position: 9
  - id: multiply_by
    type:
      - 'null'
      - int
    doc: Multiply the count of each kmer by X.
    inputBinding:
      position: 10
  - id: not_equal_to_n
    type:
      - 'null'
      - int
    doc: Return kmers that do not occur exactly N times in the input.
    inputBinding:
      position: 11
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input files for the command. The number of required input files varies 
      by command.
    inputBinding:
      position: 12
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: Compress homopolymer runs to a single letter.
    inputBinding:
      position: 113
      prefix: compress
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: Expect N mers in the input (optional; for precise memory sizing).
    inputBinding:
      position: 113
      prefix: n
  - id: kmer_size
    type:
      - 'null'
      - int
    doc: Create mers of size K bases (mandatory for count operations).
    inputBinding:
      position: 113
      prefix: k
  - id: memory_limit
    type:
      - 'null'
      - string
    doc: Use no more than (about) M GB memory.
    inputBinding:
      position: 113
      prefix: memory
  - id: threads
    type:
      - 'null'
      - int
    doc: Use no more than T threads.
    inputBinding:
      position: 113
      prefix: threads
outputs:
  - id: output_database
    type:
      - 'null'
      - Directory
    doc: Write kmers generated by the present command to an output meryl 
      database. Mandatory for count operations.
    outputBinding:
      glob: $(inputs.output_database)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
