cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - meryl
  - count-reverse
label: meryl_count-reverse
doc: "Count the occurrences of reverse kmers in the input. Writes a meryl database.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: k
    type: int
    doc: "create mers of size K bases (mandatory)."
    inputBinding:
      position: 1
      prefix: k=
      separate: false
  - id: n
    type:
      - 'null'
      - long
    doc: "expect N mers in the input (optional; for precise memory sizing)."
    inputBinding:
      position: 1
      prefix: n=
      separate: false
  - id: memory
    type:
      - 'null'
      - float
    doc: "use no more than (about) M GB memory."
    inputBinding:
      position: 1
      prefix: memory=
      separate: false
  - id: threads
    type:
      - 'null'
      - int
    doc: "use no more than T threads."
    inputBinding:
      position: 1
      prefix: threads=
      separate: false
  - id: compress
    type:
      - 'null'
      - boolean
    doc: "compress homopolymer runs to a single letter."
    inputBinding:
      position: 1
      prefix: compress
  - id: input_files
    type: File[]
    doc: "Input sequence files (FASTA or FASTQ, optionally gzip-compressed)"
    inputBinding:
      position: 100
  - id: output
    type: string
    default: "reads.meryl"
    doc: "write kmers generated by the present command to an output meryl database O"
    inputBinding:
      position: 200
      prefix: output
outputs:
  - id: database
    type: Directory
    doc: "Output meryl database"
    outputBinding:
      glob: $(inputs.output)
requirements:
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 2048
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
