cwlVersion: v1.2
class: CommandLineTool
baseCommand: meryl
label: meryl_Kmers
doc: "A meryl command line is formed as a series of commands and files, possibly grouped
  using square brackets. Each command operates on the file(s) that are listed after
  it.\n\nTool homepage: https://github.com/marbl/meryl"
inputs:
  - id: command
    type: string
    doc: The meryl command to execute (e.g., statistics, histogram, print, 
      count, union, intersect, etc.)
    inputBinding:
      position: 1
  - id: input_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Input meryl databases or files for the command
    inputBinding:
      position: 2
  - id: intersect_type
    type:
      - 'null'
      - string
    doc: Type of intersect operation (min, max, sum).
    inputBinding:
      position: 3
  - id: threshold_N
    type: int
    doc: Threshold value N for less-than, greater-than, equal-to, or 
      not-equal-to commands.
    inputBinding:
      position: 4
  - id: union_type
    type:
      - 'null'
      - string
    doc: Type of union operation (min, max, sum).
    inputBinding:
      position: 5
  - id: value_X
    type: float
    doc: Value X for increase, decrease, multiply, divide, divide-round, or 
      modulo commands.
    inputBinding:
      position: 6
  - id: compress_homopolymer
    type:
      - 'null'
      - boolean
    doc: Compress homopolymer runs to a single letter.
    inputBinding:
      position: 107
      prefix: compress
  - id: expected_mers
    type:
      - 'null'
      - int
    doc: Expect N mers in the input (optional; for precise memory sizing).
    inputBinding:
      position: 107
      prefix: n
  - id: kmer_size
    type: int
    doc: Create mers of size K bases (mandatory for count operations).
    inputBinding:
      position: 107
      prefix: k
  - id: memory
    type:
      - 'null'
      - string
    doc: Use no more than (about) M GB memory.
    inputBinding:
      position: 107
  - id: threads
    type:
      - 'null'
      - int
    doc: Use no more than T threads.
    inputBinding:
      position: 107
outputs:
  - id: output_database
    type:
      - 'null'
      - File
    doc: Write kmers generated by the present command to an output meryl 
      database O. Mandatory for count operations.
    outputBinding:
      glob: $(inputs.output_database)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/meryl:1.4.1--h9948957_2
