cwlVersion: v1.2
class: CommandLineTool
baseCommand: predictosaurus peptides
label: predictosaurus_peptides
doc: "Output all distinct peptides from the given features to a fastq file per given
  CDS in the feature file\n\nTool homepage: https://github.com/fxwiegand/predictosaurus"
inputs:
  - id: background_events
    type:
      - 'null'
      - string
    inputBinding:
      position: 101
      prefix: --background-events
  - id: events
    type:
      - 'null'
      - string
    inputBinding:
      position: 101
      prefix: --events
  - id: features
    type: File
    doc: Path to the gff file containing the features of interest
    inputBinding:
      position: 101
      prefix: --features
  - id: graph
    type: File
    doc: Path to the graph file generated by the build command
    inputBinding:
      position: 101
      prefix: --graph
  - id: interval
    type:
      - 'null'
      - string
    doc: Interval for peptide lengths to be generated in the format `start-end`
    inputBinding:
      position: 101
      prefix: --interval
  - id: max_background_event_prob
    type: float
    inputBinding:
      position: 101
      prefix: --max-background-event-prob
  - id: max_cds_length
    type:
      - 'null'
      - int
    doc: Maximum CDS length to consider for processing. Transcripts containing 
      longer CDSs will be ignored with a warning
    inputBinding:
      position: 101
      prefix: --max-cds-length
  - id: min_event_prob
    type: float
    inputBinding:
      position: 101
      prefix: --min-event-prob
  - id: reference
    type: File
    doc: Path to reference genome fasta file
    inputBinding:
      position: 101
      prefix: --reference
  - id: sample
    type: string
    doc: Sample name used to retrieve allele frequencies from the graph
    inputBinding:
      position: 101
      prefix: --sample
  - id: verbose
    type:
      - 'null'
      - boolean
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output
    type: Directory
    doc: Path to the output directory for the fastq files
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/predictosaurus:0.8.4--hbcba35e_0
