cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - predictosaurus
  - process
label: predictosaurus_process
doc: "Retrieve subgraphs for individual features from the given GFF file\n\nTool homepage:
  https://github.com/fxwiegand/predictosaurus"
inputs:
  - id: distance_metric
    type:
      - 'null'
      - string
    doc: Distance metric to use for calculating distances between amino acids
    default: grantham
    inputBinding:
      position: 101
      prefix: --distance-metric
  - id: features
    type: File
    doc: Path to the gff file containing the features of interest
    inputBinding:
      position: 101
      prefix: --features
  - id: graph
    type: File
    doc: Path to the graph file generated by the build command
    inputBinding:
      position: 101
      prefix: --graph
  - id: haplotype_metric
    type:
      - 'null'
      - string
    doc: Metric to use for haplotype quantification
    default: minimum
    inputBinding:
      position: 101
      prefix: --haplotype-metric
  - id: max_cds_length
    type:
      - 'null'
      - int
    doc: Maximum CDS length to consider for processing. Transcripts containing 
      longer CDSs will be ignored with a warning
    default: 5000
    inputBinding:
      position: 101
      prefix: --max-cds-length
  - id: reference
    type: File
    doc: Path to reference genome fasta file
    inputBinding:
      position: 101
      prefix: --reference
  - id: verbose
    type:
      - 'null'
      - boolean
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output
    type: File
    doc: Path to the output file containing the paths for the features given via
      the GFF file
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/predictosaurus:0.8.4--hbcba35e_0
