cwlVersion: v1.2
class: CommandLineTool
baseCommand: python
label: stacks_summary_python
doc: "Python interpreter\n\nTool homepage: https://github.com/Jayrajsinh-Gohil/ResearchGPT"
inputs:
  - id: script_file
    type:
      - 'null'
      - File
    doc: program read from script file
    inputBinding:
      position: 1
  - id: stdin_program
    type:
      - 'null'
      - string
    doc: program read from stdin (default; interactive mode if a tty)
    inputBinding:
      position: 2
  - id: program_arguments
    type:
      - 'null'
      - type: array
        items: string
    doc: arguments passed to program in sys.argv[1:]
    inputBinding:
      position: 3
  - id: command
    type:
      - 'null'
      - string
    doc: program passed in as string (terminates option list)
    inputBinding:
      position: 104
      prefix: -c
  - id: debug_parser
    type:
      - 'null'
      - boolean
    doc: debug output from parser; also PYTHONDEBUG=x
    inputBinding:
      position: 104
      prefix: -d
  - id: division_options
    type:
      - 'null'
      - string
    doc: 'division options: -Qold (default), -Qwarn, -Qwarnall, -Qnew'
    inputBinding:
      position: 104
      prefix: -Q
  - id: ignore_environment
    type:
      - 'null'
      - boolean
    doc: ignore PYTHON* environment variables (such as PYTHONPATH)
    inputBinding:
      position: 104
      prefix: -E
  - id: inspect_interactively
    type:
      - 'null'
      - boolean
    doc: "inspect interactively after running script; forces a prompt even\n     \
      \    if stdin does not appear to be a terminal; also PYTHONINSPECT=x"
    inputBinding:
      position: 104
      prefix: -i
  - id: module_as_script
    type:
      - 'null'
      - string
    doc: run library module as a script (terminates option list)
    inputBinding:
      position: 104
      prefix: -m
  - id: no_import_site
    type:
      - 'null'
      - boolean
    doc: don't imply 'import site' on initialization
    inputBinding:
      position: 104
      prefix: -S
  - id: no_usersite
    type:
      - 'null'
      - boolean
    doc: don't add user site directory to sys.path; also PYTHONNOUSERSITE
    inputBinding:
      position: 104
      prefix: -s
  - id: no_write_bytecode
    type:
      - 'null'
      - boolean
    doc: don't write .py[co] files on import; also PYTHONDONTWRITEBYTECODE=x
    inputBinding:
      position: 104
      prefix: -B
  - id: optimize_bytecode
    type:
      - 'null'
      - boolean
    doc: optimize generated bytecode slightly; also PYTHONOPTIMIZE=x
    inputBinding:
      position: 104
      prefix: -O
  - id: random_salt
    type:
      - 'null'
      - boolean
    doc: "use a pseudo-random salt to make hash() values of various types be\n   \
      \      unpredictable between separate invocations of the interpreter, as\n \
      \        a defense against denial-of-service attacks"
    inputBinding:
      position: 104
      prefix: -R
  - id: remove_docstrings
    type:
      - 'null'
      - boolean
    doc: remove doc-strings in addition to the -O optimizations
    inputBinding:
      position: 104
      prefix: -OO
  - id: skip_first_line
    type:
      - 'null'
      - boolean
    doc: 'skip first line of source, allowing use of non-Unix forms of #!cmd'
    inputBinding:
      position: 104
      prefix: -x
  - id: tab_usage_warnings
    type:
      - 'null'
      - string
    doc: 'issue warnings about inconsistent tab usage (-tt: issue errors)'
    inputBinding:
      position: 104
      prefix: -t
  - id: unbuffered_stdout_stderr
    type:
      - 'null'
      - boolean
    doc: "unbuffered binary stdout and stderr; also PYTHONUNBUFFERED=x\n         see
      man page for details on internal buffering relating to '-u'"
    inputBinding:
      position: 104
      prefix: -u
  - id: verbose_import
    type:
      - 'null'
      - type: array
        items: boolean
    doc: "verbose (trace import statements); also PYTHONVERBOSE=x\n         can be
      supplied multiple times to increase verbosity"
    inputBinding:
      position: 104
      prefix: -v
  - id: warn_python3_incompatibilities
    type:
      - 'null'
      - boolean
    doc: warn about Python 3.x incompatibilities that 2to3 cannot trivially fix
    inputBinding:
      position: 104
      prefix: '-3'
  - id: warning_control
    type:
      - 'null'
      - string
    doc: "warning control; arg is action:message:category:module:lineno\n        \
      \ also PYTHONWARNINGS=arg"
    inputBinding:
      position: 104
      prefix: -W
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/stacks_summary:1.1--py27_0
stdout: stacks_summary_python.out
