cwlVersion: v1.2
class: CommandLineTool
baseCommand: plink
label: plink
doc: "A whole-genome association analysis toolset\n\nTool homepage: https://www.cog-genomics.org/plink"
inputs:
  - id: allow_extra_chr
    type:
      - 'null'
      - boolean
    doc: Permit unrecognized chromosome codes.
    inputBinding:
      position: 101
      prefix: --allow-extra-chr
  - id: assoc
    type:
      - 'null'
      - boolean
    doc: Basic association analysis report.
    inputBinding:
      position: 101
      prefix: --assoc
  - id: bcf
    type:
      - 'null'
      - File
    doc: Specify full name of BCF2 file.
    inputBinding:
      position: 101
      prefix: --bcf
  - id: bed
    type:
      - 'null'
      - File
    doc: Specify full name of .bed file.
    inputBinding:
      position: 101
      prefix: --bed
  - id: bfile
    type:
      - 'null'
      - string
    doc: Specify .bed + .bim + .fam prefix (default 'plink').
    inputBinding:
      position: 101
      prefix: --bfile
  - id: bim
    type:
      - 'null'
      - File
    doc: Specify full name of .bim file.
    inputBinding:
      position: 101
      prefix: --bim
  - id: bmerge
    type:
      - 'null'
      - type: array
        items: string
    doc: Merge the given binary fileset with the initially loaded fileset.
    inputBinding:
      position: 101
      prefix: --bmerge
  - id: covar
    type:
      - 'null'
      - File
    doc: Specify covariate file.
    inputBinding:
      position: 101
      prefix: --covar
  - id: exclude
    type:
      - 'null'
      - File
    doc: Exclude all variants named in the file.
    inputBinding:
      position: 101
      prefix: --exclude
  - id: extract
    type:
      - 'null'
      - File
    doc: Exclude all variants not named in the file.
    inputBinding:
      position: 101
      prefix: --extract
  - id: fam
    type:
      - 'null'
      - File
    doc: Specify full name of .fam file.
    inputBinding:
      position: 101
      prefix: --fam
  - id: file
    type:
      - 'null'
      - string
    doc: Specify .ped + .map filename prefix (default 'plink').
    inputBinding:
      position: 101
      prefix: --file
  - id: geno
    type:
      - 'null'
      - float
    doc: Exclude variants with missing call frequencies greater than a threshold (default
      0.1).
    inputBinding:
      position: 101
      prefix: --geno
  - id: hwe
    type:
      - 'null'
      - float
    doc: Exclude variants with Hardy-Weinberg equilibrium exact test p-values below
      a threshold.
    inputBinding:
      position: 101
      prefix: --hwe
  - id: keep
    type:
      - 'null'
      - File
    doc: Exclude all samples not named in the file.
    inputBinding:
      position: 101
      prefix: --keep
  - id: keep_autoconv
    type:
      - 'null'
      - boolean
    doc: Don't delete autogenerated binary fileset at end of run.
    inputBinding:
      position: 101
      prefix: --keep-autoconv
  - id: linear
    type:
      - 'null'
      - boolean
    doc: Multi-covariate association analysis on a quantitative phenotype.
    inputBinding:
      position: 101
      prefix: --linear
  - id: logistic
    type:
      - 'null'
      - boolean
    doc: Multi-covariate association analysis on a case/control phenotype.
    inputBinding:
      position: 101
      prefix: --logistic
  - id: maf
    type:
      - 'null'
      - float
    doc: Exclude variants with minor allele frequency lower than a threshold (default
      0.01).
    inputBinding:
      position: 101
      prefix: --maf
  - id: make_bed
    type:
      - 'null'
      - boolean
    doc: Create a new binary fileset.
    inputBinding:
      position: 101
      prefix: --make-bed
  - id: map
    type:
      - 'null'
      - File
    doc: Specify full name of .map file.
    inputBinding:
      position: 101
      prefix: --map
  - id: memory
    type:
      - 'null'
      - int
    doc: Set size, in MB, of initial workspace malloc attempt.
    inputBinding:
      position: 101
      prefix: --memory
  - id: merge
    type:
      - 'null'
      - type: array
        items: string
    doc: Merge the given fileset with the initially loaded fileset.
    inputBinding:
      position: 101
      prefix: --merge
  - id: mind
    type:
      - 'null'
      - float
    doc: Exclude samples with missing call frequencies greater than a threshold (default
      0.1).
    inputBinding:
      position: 101
      prefix: --mind
  - id: pca
    type:
      - 'null'
      - int
    doc: Extracts the top principal components (default 20).
    inputBinding:
      position: 101
      prefix: --pca
  - id: ped
    type:
      - 'null'
      - File
    doc: Specify full name of .ped file.
    inputBinding:
      position: 101
      prefix: --ped
  - id: pheno
    type:
      - 'null'
      - File
    doc: Load phenotype data from the specified file.
    inputBinding:
      position: 101
      prefix: --pheno
  - id: recode
    type:
      - 'null'
      - type: array
        items: string
    doc: Create a new text fileset with all filters applied. Accepts format and modifiers.
    inputBinding:
      position: 101
      prefix: --recode
  - id: remove
    type:
      - 'null'
      - File
    doc: Exclude all samples named in the file.
    inputBinding:
      position: 101
      prefix: --remove
  - id: threads
    type:
      - 'null'
      - int
    doc: Set maximum number of concurrent threads.
    inputBinding:
      position: 101
      prefix: --threads
  - id: vcf
    type:
      - 'null'
      - File
    doc: Specify full name of .vcf or .vcf.gz file.
    inputBinding:
      position: 101
      prefix: --vcf
outputs:
  - id: out
    type:
      - 'null'
      - File
    doc: Specify prefix for output files.
    outputBinding:
      glob: $(inputs.out)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/plink:1.9.0b.7.7--h7b50bb2_0
