cwlVersion: v1.2
class: CommandLineTool
baseCommand: bigslice
label: bigslice
doc: "Biosynthetic Gene clusters - Super Linear Clustering Engine\n\nTool homepage:
  https://github.com/satriaphd/bigslice"
inputs:
  - id: output_folder_path
    type: Directory
    doc: the path to the (newly created or existing) output folder.
    inputBinding:
      position: 1
  - id: complete
    type:
      - 'null'
      - boolean
    doc: When building GCF models, use only complete BGCs (antiSMASH > 4.2 BGCs 
      annotated with 'on_contig_edge' = False).
    inputBinding:
      position: 102
      prefix: --complete
  - id: early_dumping
    type:
      - 'null'
      - boolean
    doc: Dump the in-memory Sqlite3 db into a file after finishing every phase 
      (will enable resume in case of crashes, but will increase overall 
      runtime).
    inputBinding:
      position: 102
      prefix: --early_dumping
  - id: extraction_chunk_size
    type:
      - 'null'
      - int
    doc: 'Split features extraction into chunks of N BGCs (default: 100)'
    default: 100
    inputBinding:
      position: 102
      prefix: --extraction_chunk_size
  - id: hmmscan_chunk_size
    type:
      - 'null'
      - int
    doc: 'Split biosyn_pfam scanning into chunks of N BGCs (default: 100)'
    default: 100
    inputBinding:
      position: 102
      prefix: --hmmscan_chunk_size
  - id: input_folder
    type:
      - 'null'
      - Directory
    doc: Path to input folder containing 'datasets.tsv' file and dataset 
      subfolders.
    inputBinding:
      position: 102
      prefix: --input_folder
  - id: n_ranks
    type:
      - 'null'
      - int
    doc: "Takes N-best GCF hits for each BGC's membership assignment procedure (default:
      1)."
    default: 1
    inputBinding:
      position: 102
      prefix: --n_ranks
  - id: no_normalize_feature
    type:
      - 'null'
      - boolean
    doc: Do not normalize the feature when querying. This is useful to keep the 
      same distance value defined in previous version of bigslice, for example 
      querying against the BiG-FAM database generated by BiG-SLICE v1.0.0.
    inputBinding:
      position: 102
      prefix: --no_normalize_feature
  - id: num_threads
    type:
      - 'null'
      - int
    doc: 'The number of parallel jobs to run (default: 20).'
    default: 20
    inputBinding:
      position: 102
      prefix: --num_threads
  - id: program_db_folder
    type:
      - 'null'
      - Directory
    doc: 'Path to the HMM libraries (default: /usr/local/bin/bigslice-models).'
    default: /usr/local/bin/bigslice-models
    inputBinding:
      position: 102
      prefix: --program_db_folder
  - id: query
    type:
      - 'null'
      - Directory
    doc: Path to input folder containing allcluster genbank files (needs to be 
      either clusterXXX.gbk of antiSMASH4, regionXXX.gbk of antiSMASH5, or 
      BGCXXXXXXX.gbk of MIBiG >= 2.0 files).
    inputBinding:
      position: 102
      prefix: --query
  - id: query_name
    type:
      - 'null'
      - string
    doc: Give a unique name to the query run so that it will be easier to trace 
      within the output visualization.
    inputBinding:
      position: 102
      prefix: --query_name
  - id: resume
    type:
      - 'null'
      - boolean
    doc: Continue the last clustering run (do not specifiy --input_folder in 
      combination with this parameter).
    inputBinding:
      position: 102
      prefix: --resume
  - id: run_id
    type:
      - 'null'
      - string
    doc: Rather than taking the latest run, perform query (or resume clustering)
      on the specific run id (you can check the list of run ids in the output 
      visualization).
    inputBinding:
      position: 102
      prefix: --run_id
  - id: scratch
    type:
      - 'null'
      - boolean
    doc: Don't load the Sqlite3 database into memory (lower RAM usage, but 
      potentially slower).
    inputBinding:
      position: 102
      prefix: --scratch
  - id: subpfam_chunk_size
    type:
      - 'null'
      - int
    doc: 'Split sub_pfam scanning into chunks of N BGCs (default: 100)'
    default: 100
    inputBinding:
      position: 102
      prefix: --subpfam_chunk_size
  - id: threshold
    type:
      - 'null'
      - float
    doc: "Clustering threshold (T) used in GCF models building (BIRCH algorithm) and
      membership assignment [0-1.2]. Mutually exclusive with --threshold_pct, use
      '-1' to turn off this parameter (default: 0.4)."
    default: 0.4
    inputBinding:
      position: 102
      prefix: --threshold
  - id: threshold_pct
    type:
      - 'null'
      - int
    doc: "Calculate clustering threshold (T) based on a random sampling of pairwise
      distances between the data, taking the N-th percentile value as the threshold.
      Mutually exclusive with --threshold, use '-1' to turn off this parameter (default:
      -1)."
    default: -1
    inputBinding:
      position: 102
      prefix: --threshold_pct
outputs:
  - id: export_tsv
    type:
      - 'null'
      - Directory
    doc: Export existing pre-calculated output data into TSVs (specify the 
      target folder path)
    outputBinding:
      glob: $(inputs.export_tsv)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bigslice:2.0.2--pyh8ed023e_0
