cwlVersion: v1.2
class: CommandLineTool
baseCommand: summary_get_organelle_output.py
label: getorganelle_summary_get_organelle_output.py
doc: "Summarize the output folders of get_organelle_from_reads.py into one csv table.\n\nTool homepage: http://github.com/Kinggerm/GetOrganelle"
inputs:
  - id: folders
    type:
      type: array
      items: Directory
    doc: "Folders generated by get_organelle_from_reads.py."
    inputBinding:
      position: 2
  - id: output_file
    type: string
    doc: "Output csv file."
    inputBinding:
      position: 1
      prefix: -o
outputs:
  - id: summary_table
    type: File
    doc: "Summary csv table."
    outputBinding:
      glob: "$(inputs.output_file)"
  - id: stdout
    type: stdout
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/getorganelle:1.7.7.1--pyhdfd78af_0
stdout: getorganelle_summary_get_organelle_output.py.out
