cwlVersion: v1.2
class: CommandLineTool
baseCommand: eblocks
label: haplomap_eblocks
doc: "Finds haploblocks from a set of strains, alleles, and gene annotations.\n\n\
  Tool homepage: https://github.com/zqfang/haplomap"
inputs:
  - id: alleles_file
    type: File
    doc: The file generated by (haplomap convert)
    inputBinding:
      position: 101
      prefix: --alleles
  - id: block_variant_file
    type:
      - 'null'
      - File
    doc: 'Used for viewing variants in a certain haploblocks. NOTE:: If set (-r) correctly,
      ref: 0, alternate: 1-3, unkwnon: ?. If not, ref could be any of 0-3.'
    inputBinding:
      position: 101
      prefix: --block-variant
  - id: genes_file
    type: File
    doc: The file generated by (haplomap annotate)
    inputBinding:
      position: 101
      prefix: --genes
  - id: min_variants_per_block
    type:
      - 'null'
      - int
    doc: Minimum variants per block.
    inputBinding:
      position: 101
      prefix: --minblock-variant
  - id: non_overlapping
    type:
      - 'null'
      - boolean
    doc: Run non-overlapping haploblock finding algorthim
    inputBinding:
      position: 101
      prefix: --non-overlapping
  - id: reference_genome
    type:
      - 'null'
      - string
    doc: 'Input one of the strain names from the header of (-a) input. Default: C57BL/6J.
      Only affect the pattern output of (-p).'
    inputBinding:
      position: 101
      prefix: --reference
  - id: strains_file
    type: File
    doc: The same input file as (haplomap ghmap -p)
    inputBinding:
      position: 101
      prefix: --strains
  - id: verbose
    type:
      - 'null'
      - boolean
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_file
    type: File
    doc: Input file for (haplomap ghmap -b)
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/haplomap:0.1.2--h4656aac_1
