cwlVersion: v1.2
class: CommandLineTool
baseCommand: groot report
label: groot_report
doc: "Generate a report from the output of groot align.\n\nTool homepage: https://github.com/will-rowe/groot"
inputs:
  - id: bam_file
    type:
      - 'null'
      - File
    doc: BAM file generated by groot alignment (will use STDIN if not provided)
    inputBinding:
      position: 101
      prefix: --bamFile
  - id: cov_cutoff
    type:
      - 'null'
      - float
    doc: coverage cutoff for reporting ARGs
    default: 0.97
    inputBinding:
      position: 101
      prefix: --covCutoff
  - id: index_dir
    type:
      - 'null'
      - Directory
    doc: directory for to write/read the GROOT index files
    inputBinding:
      position: 101
      prefix: --indexDir
  - id: log
    type:
      - 'null'
      - string
    doc: filename for log file
    default: groot.log
    inputBinding:
      position: 101
      prefix: --log
  - id: low_cov
    type:
      - 'null'
      - boolean
    doc: reports ARGs which don't have 5' or 3' coverage (overrides -c option)
    inputBinding:
      position: 101
      prefix: --lowCov
  - id: processors
    type:
      - 'null'
      - int
    doc: number of processors to use
    default: 1
    inputBinding:
      position: 101
      prefix: --processors
  - id: profiling
    type:
      - 'null'
      - boolean
    doc: create the files needed to profile GROOT using the go tool pprof
    inputBinding:
      position: 101
      prefix: --profiling
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/groot:1.1.2--h047eeb3_7
stdout: groot_report.out
