cwlVersion: v1.2
class: CommandLineTool
baseCommand: python OutputTranscriptInfo
label: ribominer_OutputTranscriptInfo
doc: "Output transcript information.\n\nTool homepage: https://github.com/xryanglab/RiboMiner"
inputs:
  - id: coordinate_file
    type: File
    doc: The file should contain the coordinate of start and stop codon of each 
      transcript. Generated by RiboCode.
    inputBinding:
      position: 101
      prefix: --coordinateFile
  - id: gtf_file
    type: File
    doc: Reference gene annotation in gtf format.
    inputBinding:
      position: 101
      prefix: --gtfFile
  - id: transcript_file
    type: File
    doc: transcript file with fasta format generated by RiboCode.
    inputBinding:
      position: 101
      prefix: --transcriptFile
  - id: output_all_transcripts_path
    type:
      - 'null'
      - string
    doc: Output or path parameter `output_all_transcripts_path`
    inputBinding:
      position: 102
      prefix: --output-all-transcripts
  - id: output_longest_transcripts_path
    type:
      - 'null'
      - string
    doc: Output or path parameter `output_longest_transcripts_path`
    inputBinding:
      position: 103
      prefix: --output-longest-transcripts
outputs:
  - id: output_longest_transcripts
    type:
      - 'null'
      - File
    doc: Longest transcripts information.
    outputBinding:
      glob: $(inputs.output_longest_transcripts_path)
  - id: output_all_transcripts
    type:
      - 'null'
      - File
    doc: All transcripts information.
    outputBinding:
      glob: $(inputs.output_all_transcripts_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ribominer:0.2.3.2--pyh5e36f6f_0
