cwlVersion: v1.2
class: CommandLineTool
baseCommand: metaplots
label: ribominer_metaplots
doc: "This script create aggregate plots of distances from the 5'end of reads to start
  or stop codons, which help determine the length range of the PRF reads that are
  most likely originated from the translating ribosomes and identify the P-site locations
  for each reads lengths.\n\nTool homepage: https://github.com/xryanglab/RiboMiner"
inputs:
  - id: annot_dir
    type: Directory
    doc: transcripts annotation directory, generated by prepare_transcripts.
    inputBinding:
      position: 101
      prefix: --annot_dir
  - id: frame0_percent
    type:
      - 'null'
      - float
    doc: proportion threshold of the number of reads in frame0, defined by 
      f0/(f0+f1+f2)
    default: 0.65
    inputBinding:
      position: 101
      prefix: --frame0_percent
  - id: input_file
    type: File
    doc: the file list the ribo-seq BAM/SAM files aligned to the transcriptome.
    inputBinding:
      position: 101
      prefix: --input_file
  - id: maximum_length
    type:
      - 'null'
      - int
    doc: maximum length of read to output
    default: 36
    inputBinding:
      position: 101
      prefix: --maximum-length
  - id: minimum_length
    type:
      - 'null'
      - int
    doc: minimum length of read to output
    default: 24
    inputBinding:
      position: 101
      prefix: --minimum-length
  - id: outname
    type:
      - 'null'
      - string
    doc: name of output pdf file
    default: metaplots
    inputBinding:
      position: 101
      prefix: --outname
  - id: pvalue1_cutoff
    type:
      - 'null'
      - float
    doc: pvalue cutoff of frame0 > frame2 for automatically predicting P-site 
      location
    default: 0.001
    inputBinding:
      position: 101
      prefix: --pvalue1_cutoff
  - id: pvalue2_cutoff
    type:
      - 'null'
      - float
    doc: pvalue cutoff of frame0 > frame2 for automatically predicting P-site 
      location
    default: 0.001
    inputBinding:
      position: 101
      prefix: --pvalue2_cutoff
  - id: rpf_mapping_file
    type: File
    doc: ribo-seq BAM/SAM file aligned to the transcriptome.
    inputBinding:
      position: 101
      prefix: --rpf_mapping_file
  - id: stranded
    type:
      - 'null'
      - string
    doc: whether the data is strand-specific, reverse means reversed strand 
      interpretation.
    default: yes
    inputBinding:
      position: 101
      prefix: --stranded
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ribominer:0.2.3.2--pyh5e36f6f_0
stdout: ribominer_metaplots.out
