#!/usr/bin/env cwl-runner

cwlVersion: v1.2
class: Workflow
requirements:
   - class: StepInputExpressionRequirement
   - class: SubworkflowFeatureRequirement
   - class: InlineJavascriptRequirement
   - class: MultipleInputFeatureRequirement

label: Sylph profile and sylph-tax
doc:  Taxonomic profiling of long reads using Sylph and convert to taxonomy abundances with sylph-tax. Including quality filtering (optional)
      
outputs:
  sylph_profile:
    type: File
    doc: Output directory
    outputSource: sylph_profile_run/sylph_profile

  tax_file:
    type: File
    doc: Output directory
    outputSource: sylph_tax/sylph_tax
  filtered_reads:
    type: File?
    doc: Filtered reads output file
    outputSource: step_output_filtered_reads/reads_out
  quality_reports:
    type: Directory?
    doc: Quality reports output directory
    outputSource: workflow_longread_quality/reports_folder

inputs:
  identifier:
    type: string
    doc: Identifier for this dataset used in this workflow.
    label: identifier used
  threads:
    type: int
    doc: Maximum threads to use. (Default 3)
    label: Threads
    default: 3

  longreads:
    type: File[]
    doc: Long reads sequence files (fastx/gzip)
    label: Long reads
  readtype:
    type:
      - type: enum
        symbols:
          - nanopore
          - pacbio
    doc: Type of read PacBio or Nanopore.
    label: Read type

  # Sylph parameters
  database:
    type: File
    doc: "Sylph database file"
    label: Database
  taxonomy_metadata:
    type:
      - type: record
        name: builtin_taxonomy_metadata
        fields:
          builtin_taxonomy_metadata:
            type:
              - "null"
              - type: enum
                symbols:
                  - GTDB_r214
                  - GTDB_r220
                  - GTDB_r226
                  - IMGVR_4.1
                  - SoilSMAG
                  - OceanDNA
                  - TaraEukaryoticSMAG
                  - FungiRefSeq-2024-07-25
            doc: "Provided taxonomy metadata from default sylph databases. (only available when running with the container image)"
            label: Taxonomy metadata
      - type: record
        name: taxonomy_metadata_file
        fields:
          taxonomy_metadata_file:
            type: File
            doc: "Taxonomy metadata file(s) that are not incorporated in the docker image."
            label: Taxonomy metadata file
  estimate_unknown:
    type: boolean
    doc: "Estimate true coverage and scale sequence abundance in `profile` by estimated unknown sequence percentage. Default false"
    label: Estimate unknown
    default: true
  annotate_virus_hosts:
    type: boolean
    doc: "Add additional column(s) by integrating viral-host information available (currently available for IMGVR4.1). Default false"
    label: Annotate virus hosts
    default: false

  fastq_rich_ont:
    type: boolean
    doc: |
          Input fastq is generated by albacore, MinKNOW or guppy  with additional information concerning channel and time. 
          Used to creating more informative quality plots (Default false)
    label: Fastq rich (ONT)
    default: false

  # Read filtering parameters
  skip_read_filter:
    type: boolean
    label: Skip quality filtering
    doc: "Skip quality reporting, filtering and contamination. (Default false)"
    default: false

  qualified_quality_phred:
    type: int?
    default: 9
    label: Qualified_quality_phred
    doc: "The quality value that a base is qualified. Default 9 means phred quality >=Q9 is qualified."
  mean_qual:
    type: int?
    label: Mean quality
    doc: "If one read's mean_qual quality score < mean_qual, then this read is discarded. (Default 10)"
    default: 10
  minimum_length:
    type: int?
    label: Minimum length required
    doc: "Reads shorter will be discarded. (Default 100)"
  length_limit:
    type: int?
    label: Maximum length limit
    doc: "Reads longer than length_limit will be discarded. (Default no limit)"
  trim_front:
    type: int?
    label: Trim_front
    doc: "Trimming how many bases in front for read. (Default 0)"
  trim_tail:
    type: int?
    label: trim_tail
    doc: "Trimming how many bases in tail for read, Default 0)"

  cut_front:
    type: boolean?
    label: Cut front
    doc: "Move a sliding window from front (5') to tail, drop the bases in the window if its mean quality < threshold, stop otherwise. Default false"
  cut_tail:
    type: boolean?
    label: Cut tail
    doc: "Move a sliding window from tail (3') to front, drop the bases in the window if its mean quality < threshold, stop otherwise Default false."
  cut_window_size:
    type: int?
    default: 4
    label: Cut window size
    doc: "The window size option shared by cut_front, cut_tail or cut_sliding. Range: 1~1000. Default 4"
  cut_mean_quality:
    type: int?
    label: Cut mean quality
    doc: "The mean quality requirement option shared by cut_front, cut_tail or cut_sliding. Range: 1~36. Default 20"

  trim_poly_x:
    type: boolean?
    label: Trim_poly_x
    doc: "Enable polyX trimming in 3' ends. (Default false)"
  poly_x_min_len:
    type: int?
    label: Poly_x_min_len
    doc: "The minimum length to detect polyX in the read tail. (Default 10 when trim_poly_x is true)"
  start_adapter:
    type: string?
    label: start_adapter
    doc: "The adapter sequence at read start (5'). (Default auto-detect)"
  end_adapter:
    type: string?
    label: End adapter
    doc: "The adapter sequence at read end (3'). (Default auto-detect)"
  adapter_fasta:
    type: File?
    label: Adapter fasta
    doc: "Specify a FASTA file to trim both read ends by all the sequences in this FASTA file. (Default None)"
  disable_adapter_trimming:
    type: boolean?
    label: Disable adapter trimming
    doc: "Adapter trimming is enabled by default. If this option is specified, adapter trimming is disabled. Default false"

  humandb:
    type: File?
    doc: "A fasta file or minimap2 indexed filed (.mmi) index needs to be provided. Preindexed is much faster. (Default None)"
    label: Filter human reads
    loadListing: no_listing
  reference_filter_db:
    type: File?
    doc: "A fasta file or minimap2 indexed filed (.mmi) index needs to be provided. Preindexed is much faster. (Default none)"
    label: Filter reference file(s)
    loadListing: no_listing
  use_reference_mapped_reads:
    type: boolean
    doc: "Use mapped reads mapped to the custom reference db. (Default false, discard mapped)"
    label: Use mapped reads
    default: false

  output_filtered_reads:
    type: boolean
    label: Output filtered reads
    doc: "Output filtered reads when filtering is applied. (Default false)"
    default: false
 
  destination:
    type: string?
    label: Output Destination
    doc: "Output destination used for cwl-prov reporting."

steps:
#############################################
#### Merge reads
  workflow_merge_reads:
    label: Merge paired reads
    doc: Creates a single file object. Also merges reads if multiple files are given.
    when: $(inputs.skip_read_filter)
    run: workflow_merge_se_reads.cwl
    in:
      skip_read_filter: skip_read_filter
      filename: 
        source: identifier
        valueFrom: $(self)_merged
      reads: longreads
    out: [merged_reads]
#############################################
#### Quality workflow Oxford Nanopore
  workflow_longread_quality:
    label: Oxford Nanopore quality workflow
    doc: Quality, filtering and taxonomic classification workflow for Oxford Nanopore reads
    when: $(!inputs.skip_read_filter)
    run: workflow_longread_quality.cwl
    in:
      skip_read_filter: skip_read_filter

      identifier: identifier
      fastq_rich: fastq_rich_ont
      longreads: longreads
      readtype: readtype
      
      humandb: humandb      
      reference_filter_db: reference_filter_db
      keep_reference_mapped_reads: use_reference_mapped_reads

      minimum_length: minimum_length
      length_limit: length_limit
      
      qualified_quality_phred: qualified_quality_phred
      mean_qual: mean_qual
      
      trim_front: trim_front
      trim_tail: trim_tail

      cut_front: cut_front
      cut_tail: cut_tail
      cut_window_size: cut_window_size
      cut_mean_quality: cut_mean_quality

      trim_poly_x: trim_poly_x
      poly_x_min_len: poly_x_min_len
      
      start_adapter: start_adapter
      end_adapter: end_adapter
      
      adapter_fasta: adapter_fasta
      disable_adapter_trimming: disable_adapter_trimming


      threads: threads
    out: [filtered_reads, reports_folder]
    
#############################################
#### Sylph
  sylph_profile_run:
    run: ../tools/sylph/sylph_profile.cwl
    in:
      output_filename_prefix: identifier
      single_end_reads: 
        source:
        - workflow_longread_quality/filtered_reads
        - workflow_merge_reads/merged_reads
        pickValue: first_non_null

      estimate_unknown: estimate_unknown
      database: database
      threads: threads
    out: [sylph_profile]

  sylph_tax:
    run: ../tools/sylph/sylph_tax.cwl
    in:
      output_filename_prefix: identifier
      sylph_profile: sylph_profile_run/sylph_profile
      taxonomy_metadata: taxonomy_metadata
      annotate_virus_hosts: annotate_virus_hosts
    out: [sylph_tax]

#############################################
#### Output reads 
  step_output_filtered_reads:
    label: Output reads
    doc: Step needed to output filtered reads.
    when: $(!inputs.skip_read_filter && inputs.output_filtered_reads)
    run:
      class: ExpressionTool
      requirements:
        InlineJavascriptRequirement: {}
      inputs:
        reads_in: File?
      outputs:
        reads_out: File
      expression: |
        ${ return {'reads_out': inputs.reads_in}; }
    in:
      skip_read_filter: skip_read_filter
      output_filtered_reads: output_filtered_reads

      reads_in: workflow_longread_quality/filtered_reads
    out:
      [reads_out]


s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-9524-5964
    s:email: mailto:bart.nijsse@wur.nl
    s:name: Bart Nijsse

s:citation: https://m-unlock.nl
s:codeRepository: https://gitlab.com/m-unlock/cwl
s:dateModified: "2025-08-22"
s:dateCreated: "2025-02-26"
s:license: https://spdx.org/licenses/Apache-2.0 
s:copyrightHolder: "UNLOCK - Unlocking Microbial Potential"

$namespaces:
  s: https://schema.org/