cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - trgt
  - deepdive
label: trgt_deepdive
doc: "Locus-specific Deep Dive\n\nTool homepage: https://github.com/PacificBiosciences/trgt"
inputs:
  - id: color
    type:
      - 'null'
      - string
    doc: 'Enable or disable color output in logging [possible values: always, auto,
      never]'
    default: auto
    inputBinding:
      position: 101
      prefix: --color
  - id: genome
    type: File
    doc: Path to reference genome FASTA
    inputBinding:
      position: 101
      prefix: --genome
  - id: repeat_id
    type: string
    doc: ID of the repeat to realign
    inputBinding:
      position: 101
      prefix: --repeat-id
  - id: repeats
    type: File
    doc: BED file with repeat coordinates
    inputBinding:
      position: 101
      prefix: --repeats
  - id: spanning_reads
    type: File
    doc: BAM file with spanning reads generated by trgt genotype
    inputBinding:
      position: 101
      prefix: --spanning-reads
  - id: vcf
    type: File
    doc: VCF file generated by trgt genotype
    inputBinding:
      position: 101
      prefix: --vcf
  - id: verbose
    type:
      - 'null'
      - type: array
        items: boolean
    doc: Specify multiple times to increase verbosity level (e.g., -vv for more verbosity)
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: output_prefix
    type: File
    doc: Prefix for output files (.fasta, .bed, and .bam)
    outputBinding:
      glob: $(inputs.output_prefix)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/trgt:5.0.0--h9ee0642_0
