cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - trgt
  - plot
label: trgt_plot
doc: "Tandem Repeat Plotter\n\nTool homepage: https://github.com/PacificBiosciences/trgt"
inputs:
  - id: color
    type:
      - 'null'
      - string
    doc: 'Enable or disable color output in logging [possible values: always, auto,
      never]'
    default: auto
    inputBinding:
      position: 101
      prefix: --color
  - id: flank_len
    type:
      - 'null'
      - int
    doc: Length of flanking regions
    default: 50
    inputBinding:
      position: 101
      prefix: --flank-len
  - id: font_family
    type:
      - 'null'
      - string
    doc: Font family to use for text elements
    default: Roboto Mono
    inputBinding:
      position: 101
      prefix: --font-family
  - id: genome
    type: File
    doc: Path to reference genome FASTA
    inputBinding:
      position: 101
      prefix: --genome
  - id: max_allele_reads
    type:
      - 'null'
      - int
    doc: Max number of reads per allele to plot
    inputBinding:
      position: 101
      prefix: --max-allele-reads
  - id: plot_type
    type:
      - 'null'
      - string
    doc: 'Type of plot to generate [possible values: allele, waterfall]'
    default: allele
    inputBinding:
      position: 101
      prefix: --plot-type
  - id: repeat_id
    type: string
    doc: ID of the repeat to plot
    inputBinding:
      position: 101
      prefix: --repeat-id
  - id: repeats
    type: File
    doc: BED file with repeat coordinates
    inputBinding:
      position: 101
      prefix: --repeats
  - id: show
    type:
      - 'null'
      - string
    doc: 'What to show in the plot [possible values: motifs, meth]'
    default: motifs
    inputBinding:
      position: 101
      prefix: --show
  - id: spanning_reads
    type: File
    doc: BAM file with spanning reads generated by TRGT
    inputBinding:
      position: 101
      prefix: --spanning-reads
  - id: squished
    type:
      - 'null'
      - boolean
    doc: Horizontally compress the plot
    inputBinding:
      position: 101
      prefix: --squished
  - id: vcf
    type: File
    doc: VCF file generated by TRGT
    inputBinding:
      position: 101
      prefix: --vcf
  - id: verbose
    type:
      - 'null'
      - type: array
        items: boolean
    doc: Specify multiple times to increase verbosity level (e.g., -vv for more verbosity)
    inputBinding:
      position: 101
      prefix: --verbose
outputs:
  - id: image
    type: File
    doc: Output image path
    outputBinding:
      glob: $(inputs.image)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/trgt:5.0.0--h9ee0642_0
