cwlVersion: v1.2
class: CommandLineTool
baseCommand: graphtyper_vcf_concatenate
label: graphtyper_vcf_concatenate
doc: "Concatenates VCF files generated by Graphtyper.\n\nTool homepage: https://github.com/DecodeGenetics/graphtyper"
inputs:
  - id: input_vcfs
    type:
      type: array
      items: File
    doc: List of input VCF files to concatenate.
    inputBinding:
      position: 1
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use for concatenation.
    inputBinding:
      position: 102
      prefix: --threads
outputs:
  - id: output_vcf
    type: File
    doc: Path to the output VCF file.
    outputBinding:
      glob: $(inputs.output_vcf)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/graphtyper:2.7.7--h7594796_1
