cwlVersion: v1.2
class: CommandLineTool
baseCommand: genomad find-proviruses
label: genomad_find-proviruses
doc: "Find integrated viruses within the sequences in INPUT file using the geNomad
  markers (located in the DATABASE directory) and write the results to the OUTPUT
  directory. This command depends on the data generated by the annotate module.\n\n\
  Tool homepage: https://portal.nersc.gov/genomad/"
inputs:
  - id: input
    type: File
    doc: Input file
    inputBinding:
      position: 1
  - id: database
    type: Directory
    doc: Directory containing geNomad markers
    inputBinding:
      position: 2
  - id: cleanup
    type:
      - 'null'
      - boolean
    doc: Delete intermediate files after execution.
    inputBinding:
      position: 103
      prefix: --cleanup
  - id: crf_threshold
    type:
      - 'null'
      - float
    doc: Minimum gene-level score to flag a provirus gene using the conditional 
      random field model. Lower values will result in longer proviruses but will
      increase the probability of host genes being flagged as part of 
      proviruses.
    default: 0.4
    inputBinding:
      position: 103
      prefix: --crf-threshold
  - id: evalue
    type:
      - 'null'
      - float
    doc: Maximum accepted E-value in the MMseqs2 integrase search.
    default: 0.001
    inputBinding:
      position: 103
      prefix: --evalue
  - id: full_ictv_lineage
    type:
      - 'null'
      - boolean
    doc: Output the full ICTV lineage of each virus genome, including ranks that
      are hidden by default (subrealm, subkingdom, subphylum, subclass, 
      suborder, subfamily, and, subgenus). The subfamily and subgenus ranks are 
      only shown if --lenient-taxonomy is also used.
    inputBinding:
      position: 103
      prefix: --full-ictv-lineage
  - id: lenient_taxonomy
    type:
      - 'null'
      - boolean
    doc: Allow classification of virus genomes to taxa below the family rank 
      (subfamily, genus, subgenus, and species). The subfamily and subgenus 
      ranks are only shown if --full-ictv-lineage is also used.
    inputBinding:
      position: 103
      prefix: --lenient-taxonomy
  - id: marker_threshold
    type:
      - 'null'
      - float
    doc: Minimum total virus marker score allowed for proviruses that do not 
      encode integrases or are not located at scaffold edges. Lower values will 
      increase the sensitivity but reduce the precision of the provirus 
      identification procedure.
    default: 12.0
    inputBinding:
      position: 103
      prefix: --marker-threshold
  - id: marker_threshold_edge
    type:
      - 'null'
      - float
    doc: Minimum total virus marker score allowed for proviruses that are 
      located at scaffold edges.
    default: 8.0
    inputBinding:
      position: 103
      prefix: --marker-threshold-edge
  - id: marker_threshold_integrase
    type:
      - 'null'
      - float
    doc: Minimum total virus marker score allowed for proviruses that encode 
      integrases.
    default: 8.0
    inputBinding:
      position: 103
      prefix: --marker-threshold-integrase
  - id: max_integrase_distance
    type:
      - 'null'
      - int
    doc: Maximum allowed distance between provirus boundaries and the integrases
      used for boundary extension.
    default: 10000
    inputBinding:
      position: 103
      prefix: --max-integrase-distance
  - id: max_trna_distance
    type:
      - 'null'
      - int
    doc: Maximum allowed distance between provirus boundaries and the tRNAs used
      for boundary extension.
    default: 5000
    inputBinding:
      position: 103
      prefix: --max-trna-distance
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Display the execution log.
    inputBinding:
      position: 103
      prefix: --quiet
  - id: restart
    type:
      - 'null'
      - boolean
    doc: Overwrite existing intermediate files.
    inputBinding:
      position: 103
      prefix: --restart
  - id: sensitivity
    type:
      - 'null'
      - float
    doc: MMseqs2 integrase search sensitivity. Higher values will identify more 
      integrases, but the search will be slower and consume more memory.
    default: 8.2
    inputBinding:
      position: 103
      prefix: --sensitivity
  - id: skip_integrase_identification
    type:
      - 'null'
      - boolean
    doc: Disable provirus boundary extension using nearby integrases.
    inputBinding:
      position: 103
      prefix: --skip-integrase-identification
  - id: skip_trna_identification
    type:
      - 'null'
      - boolean
    doc: Disable provirus boundary extension using nearby tRNAs.
    inputBinding:
      position: 103
      prefix: --skip-trna-identification
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use.
    default: 20
    inputBinding:
      position: 103
      prefix: --threads
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Display the execution log.
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: output
    type: Directory
    doc: Output directory
    outputBinding:
      glob: '*.out'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/genomad:1.11.2--pyhdfd78af_0
