cwlVersion: v1.2
class: CommandLineTool
baseCommand: genomad marker-classification
label: genomad_marker-classification
doc: "Classify the sequences in the INPUT file (FASTA format) based on the presence
  of geNomad markers (located in the DATABASE directory) and write the results to
  the OUTPUT directory. This command depends on the data generated by the annotate
  module.\n\nTool homepage: https://portal.nersc.gov/genomad/"
inputs:
  - id: input
    type: File
    doc: Input FASTA file
    inputBinding:
      position: 1
  - id: database
    type: Directory
    doc: Directory containing geNomad markers
    inputBinding:
      position: 2
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: Display the execution log.
    inputBinding:
      position: 103
      prefix: --quiet
  - id: restart
    type:
      - 'null'
      - boolean
    doc: Overwrite existing intermediate files.
    inputBinding:
      position: 103
      prefix: --restart
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use.
    inputBinding:
      position: 103
      prefix: --threads
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Display the execution log.
    inputBinding:
      position: 103
      prefix: --verbose
outputs:
  - id: output
    type: Directory
    doc: Output directory for results
    outputBinding:
      glob: '*.out'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/genomad:1.11.2--pyhdfd78af_0
