cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - mehari
  - annotate
  - strucvars
label: mehari_annotate_strucvars
doc: "Annotate structural variant VCF files\n\nTool homepage: https://github.com/varfish-org/mehari"
inputs:
  - id: path_input_ped
    type: File
    doc: "Path to the input PED file"
    inputBinding:
      position: 1
      prefix: --path-input-ped
  - id: path_input_vcf
    type:
      - type: array
        items: File
        inputBinding:
          prefix: --path-input-vcf
    doc: "Path to the input VCF files"
    inputBinding:
      position: 2
  - id: path_output_vcf
    type:
      - 'null'
      - string
    doc: "Path to the output VCF file (give this or path_output_tsv)"
    inputBinding:
      position: 3
      prefix: --path-output-vcf
  - id: path_output_tsv
    type:
      - 'null'
      - string
    doc: "Path to the output TSV file (for import into VarFish) (give this or path_output_vcf)"
    inputBinding:
      position: 4
      prefix: --path-output-tsv
  - id: genome_release
    type:
      - 'null'
      - string
    doc: "Genome release to use, default is to auto-detect (grch37, grch38)"
    inputBinding:
      position: 5
      prefix: --genome-release
  - id: max_var_count
    type:
      - 'null'
      - int
    doc: "For debug purposes, maximal number of variants to annotate"
    inputBinding:
      position: 6
      prefix: --max-var-count
  - id: path_cov_vcf
    type:
      - 'null'
      - type: array
        items: File
        inputBinding:
          prefix: --path-cov-vcf
    doc: "Paths to the per-sample VCF files with coverage and mapping quality information as generated by maelstrom-core"
    secondaryFiles:
      - pattern: .tbi
        required: false
    inputBinding:
      position: 7
  - id: min_overlap
    type:
      - 'null'
      - float
    doc: "Minimal reciprocal overlap to require (default: 0.8)"
    inputBinding:
      position: 8
      prefix: --min-overlap
  - id: slack_bnd
    type:
      - 'null'
      - int
    doc: "Slack to use around break-ends (default: 50)"
    inputBinding:
      position: 9
      prefix: --slack-bnd
  - id: slack_ins
    type:
      - 'null'
      - int
    doc: "Slack to use around insertions (default: 50)"
    inputBinding:
      position: 10
      prefix: --slack-ins
  - id: rng_seed
    type:
      - 'null'
      - int
    doc: "Seed for random number generator (UUIDs), if any"
    inputBinding:
      position: 11
      prefix: --rng-seed
  - id: file_date
    type:
      - 'null'
      - string
    doc: "Optionally, value to write to ##fileDate"
    inputBinding:
      position: 12
      prefix: --file-date
  - id: tsv_contig_style
    type:
      - 'null'
      - string
    doc: "Style for contig names in TSV output: passthrough, with-chr, without-chr, auto (default: auto)"
    inputBinding:
      position: 13
      prefix: --tsv-contig-style
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: "Increase logging verbosity"
    inputBinding:
      position: 14
      prefix: --verbose
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: "Decrease logging verbosity"
    inputBinding:
      position: 15
      prefix: --quiet
outputs:
  - id: output_vcf
    type:
      - 'null'
      - File
    doc: "Annotated VCF file"
    outputBinding:
      glob: $(inputs.path_output_vcf)
  - id: output_tsv
    type:
      - 'null'
      - File
    doc: "Annotated TSV file"
    outputBinding:
      glob: $(inputs.path_output_tsv)
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mehari:0.39.0--h13c227e_0
stdout: mehari_annotate_strucvars.out
