cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - cellranger-arc
  - reanalyze
label: cellranger-arc_reanalyze
doc: Re-run secondary analysis (dimensionality reduction, clustering, feature 
  linkage etc.) on a completed `cellranger-arc count` or `cellranger-arc aggr` 
  run
inputs:
  - id: id
    type: string
    doc: A unique run id and output folder name [a-zA-Z0-9_-]+ of maximum length
      64 characters
    inputBinding:
      position: 101
      prefix: --id
  - id: description
    type:
      - 'null'
      - string
    doc: Sample description to embed in output files
    inputBinding:
      position: 101
      prefix: --description
  - id: reference
    type: Directory
    doc: 'Path to folder containing cellranger-arc-compatible reference. Reference
      packages can be downloaded from support.10xgenomics.com or constructed using
      the `cellranger-arc mkref` command. Note: this reference must match the reference
      used for the initial `cellranger-arc count` run'
    inputBinding:
      position: 101
      prefix: --reference
  - id: matrix
    type: File
    doc: Path to a feature barcode matrix H5 generated by cellranger-arc `count`
      or `aggr`. If you intend to subset to a set of barcodes then use the raw 
      matrix, otherwise use the filtered feature barcode matrix
    inputBinding:
      position: 101
      prefix: --matrix
  - id: atac_fragments
    type: File
    doc: Path to the atac_fragments.tsv.gz generated by cellranger-arc `count` 
      or `aggr`. Note it is assumed that the tabix index file 
      atac_fragments.tsv.gz.tbi is present in the same directory
    inputBinding:
      position: 101
      prefix: --atac-fragments
  - id: params
    type:
      - 'null'
      - File
    doc: 'Specify key-value pairs in CSV format for analysis: any subset of `random_seed`,
      `k_means_max_clusters`, `feature_linkage_max_dist_mb`, `num_gex_pcs`, `num_atac_pcs`.'
    inputBinding:
      position: 101
      prefix: --params
  - id: barcodes
    type:
      - 'null'
      - File
    doc: Specify barcodes to use in analysis. The barcodes could be specified in
      a text file that contains one barcode per line or a CSV whose first column
      will be used
    inputBinding:
      position: 101
      prefix: --barcodes
  - id: min_atac_count
    type:
      - 'null'
      - int
    doc: 'Cell caller override: define the minimum number of ATAC transposition events
      in peaks (ATAC counts) for a cell barcode. Note: this option must be specified
      in conjunction with `min-gex-count`.'
    inputBinding:
      position: 101
      prefix: --min-atac-count
  - id: min_gex_count
    type:
      - 'null'
      - int
    doc: 'Cell caller override: define the minimum number of GEX UMI counts for a
      cell barcode. Note: this option must be specified in conjunction with `min-atac-count`.'
    inputBinding:
      position: 101
      prefix: --min-gex-count
  - id: peaks
    type:
      - 'null'
      - File
    doc: 'Override peak caller: specify peaks to use in secondary analyses from supplied
      3-column BED file. The supplied peaks file must be sorted by position and not
      contain overlapping peaks; comment lines beginning with `#` are allowed'
    inputBinding:
      position: 101
      prefix: --peaks
  - id: agg
    type:
      - 'null'
      - File
    doc: If the input matrix was produced by 'cellranger-arc aggr', it's 
      possible to pass the same aggregation CSV in order to retain per-library 
      tag information in the resulting .cloupe file
    inputBinding:
      position: 101
      prefix: --agg
  - id: dry
    type:
      - 'null'
      - boolean
    doc: Do not execute the pipeline. Generate a pipeline invocation (.mro) file
      and stop
    inputBinding:
      position: 101
      prefix: --dry
  - id: jobmode
    type:
      - 'null'
      - string
    doc: 'Job manager to use. Valid options: local (default), sge, lsf, slurm or path
      to a .template file.'
    inputBinding:
      position: 101
      prefix: --jobmode
  - id: localcores
    type:
      - 'null'
      - int
    doc: Set max cores the pipeline may request at one time. Only applies to 
      local jobs
    inputBinding:
      position: 101
      prefix: --localcores
  - id: localmem
    type:
      - 'null'
      - int
    doc: Set max GB the pipeline may request at one time. Only applies to local 
      jobs
    inputBinding:
      position: 101
      prefix: --localmem
  - id: localvmem
    type:
      - 'null'
      - int
    doc: Set max virtual address space in GB for the pipeline. Only applies to 
      local jobs
    inputBinding:
      position: 101
      prefix: --localvmem
  - id: mempercore
    type:
      - 'null'
      - int
    doc: Reserve enough threads for each job to ensure enough memory will be 
      available, assuming each core on your cluster has at least this much 
      memory available. Only applies to cluster jobmodes
    inputBinding:
      position: 101
      prefix: --mempercore
  - id: maxjobs
    type:
      - 'null'
      - int
    doc: Set max jobs submitted to cluster at one time. Only applies to cluster 
      jobmodes
    inputBinding:
      position: 101
      prefix: --maxjobs
  - id: jobinterval
    type:
      - 'null'
      - int
    doc: Set delay between submitting jobs to cluster, in ms. Only applies to 
      cluster jobmodes
    inputBinding:
      position: 101
      prefix: --jobinterval
  - id: overrides
    type:
      - 'null'
      - File
    doc: The path to a JSON file that specifies stage-level overrides for cores 
      and memory. Finer-grained than --localcores, --mempercore and --localmem.
    inputBinding:
      position: 101
      prefix: --overrides
  - id: output_dir
    type:
      - 'null'
      - string
    doc: Output the results to this directory
    inputBinding:
      position: 101
      prefix: --output-dir
  - id: uiport
    type:
      - 'null'
      - int
    doc: Serve web UI at http://localhost:PORT
    inputBinding:
      position: 101
      prefix: --uiport
  - id: disable_ui
    type:
      - 'null'
      - boolean
    doc: Do not serve the web UI
    inputBinding:
      position: 101
      prefix: --disable-ui
  - id: noexit
    type:
      - 'null'
      - boolean
    doc: Keep web UI running after pipestance completes or fails
    inputBinding:
      position: 101
      prefix: --noexit
  - id: nopreflight
    type:
      - 'null'
      - boolean
    doc: Skip preflight checks
    inputBinding:
      position: 101
      prefix: --nopreflight
outputs:
  - id: output_output_dir
    type:
      - 'null'
      - Directory
    doc: Output the results to this directory
    outputBinding:
      glob: $(inputs.output_dir || inputs.id)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: cumulusprod/cellranger-arc:2.2.0
s:url: https://github.com/mattgalbraith/cellrangerARC-docker-singularity
$namespaces:
  s: https://schema.org/
