cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - methylpy
  - DMRfind
label: methylpy_dmrfind
doc: "Find differentially methylated regions (DMRs) from ALLC files.\n\nTool homepage:
  https://github.com/yupenghe/methylpy"
inputs:
  - id: allc_files
    type:
      type: array
      items: File
    doc: List of ALLC files for DMR finding (staged writable, the tool writes .idx
      files beside them).
    inputBinding:
      position: 101
      prefix: --allc-files
      valueFrom: $(self.map(function(f) { return f.basename; }))
  - id: chroms
    type:
      - 'null'
      - type: array
        items: string
    doc: Space-separated list of chromosomes to process.
    inputBinding:
      position: 101
      prefix: --chroms
  - id: dmr_max_dist
    type:
      - 'null'
      - int
    doc: Maximum distance between DMRs to be merged.
    inputBinding:
      position: 101
      prefix: --dmr-max-dist
  - id: mc_max_dist
    type:
      - 'null'
      - int
    doc: Maximum distance between sites to be included in the same DMR.
    inputBinding:
      position: 101
      prefix: --mc-max-dist
  - id: mc_type
    type:
      - 'null'
      - type: array
        items: string
    doc: Type of methylation to consider (e.g., CG, CHG, CHH).
    inputBinding:
      position: 101
      prefix: --mc-type
  - id: min_cov
    type:
      - 'null'
      - int
    doc: Minimum coverage for a site to be considered.
    inputBinding:
      position: 101
      prefix: --min-cov
  - id: min_num_dms
    type:
      - 'null'
      - int
    doc: Minimum number of DMCs in a DMR.
    inputBinding:
      position: 101
      prefix: --min-num-dms
  - id: num_procs
    type:
      - 'null'
      - int
    doc: Number of processors to use.
    inputBinding:
      position: 101
      prefix: --num-procs
  - id: num_sims
    type:
      - 'null'
      - int
    doc: Number of simulations for permutation test.
    inputBinding:
      position: 101
      prefix: --num-sims
  - id: sample_category
    type:
      - 'null'
      - type: array
        items: string
    doc: Category for each sample.
    inputBinding:
      position: 101
      prefix: --sample-category
  - id: samples
    type:
      - 'null'
      - type: array
        items: string
    doc: List of space separated samples matching allc files. By default sample
      names will be inferred from allc filenames.
    inputBinding:
      position: 101
      prefix: --samples
  - id: sig_cutoff
    type:
      - 'null'
      - float
    doc: P-value cutoff for significance.
    inputBinding:
      position: 101
      prefix: --sig-cutoff
  - id: min_tests
    type:
      - 'null'
      - int
    doc: Minimum number of permuation tests you would like to run for each mC
    inputBinding:
      position: 101
      prefix: --min-tests
  - id: resid_cutoff
    type:
      - 'null'
      - float
    doc: Results will have to show deviations in the contingency table in the same
      direction as the rest of the window
    inputBinding:
      position: 101
      prefix: --resid-cutoff
  - id: keep_temp_files
    type:
      - 'null'
      - string
    doc: Boolean indicating that you would like to keep the intermediate files
      generated by this function.
    inputBinding:
      position: 101
      prefix: --keep-temp-files
  - id: min_cluster
    type:
      - 'null'
      - int
    doc: The minimum number of each sample category that must be present in every
      block that is output.
    inputBinding:
      position: 101
      prefix: --min-cluster
  - id: seed
    type:
      - 'null'
      - int
    doc: A seed to provide to the random number generator for permutation testing.
    inputBinding:
      position: 101
      prefix: --seed
  - id: output_prefix_path
    type: string
    inputBinding:
      position: 102
      prefix: --output-prefix
outputs:
  - id: output_prefix
    type:
      type: array
      items: File
    doc: DMR result tables (rms_results, rms_results_collapsed and the DMR/DMS bed files)
    outputBinding:
      glob: $(inputs.output_prefix_path)_rms_results*
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.allc_files)
        writable: true
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/methylpy:1.4.7--py39h0ae133c_0
