cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - methylpy
  - single-end-pipeline
label: methylpy_single-end-pipeline
doc: "Methylpy pipeline for single-end bisulfite sequencing data, including read alignment
  and methylation calling.\n\nTool homepage: https://github.com/yupenghe/methylpy"
inputs:
  - id: adapter_seq
    type:
      - 'null'
      - string
    doc: sequence of an adapter that was ligated to the 3' end.
    inputBinding:
      position: 101
      prefix: --adapter-seq
  - id: add_snp_info
    type:
      - 'null'
      - boolean
    doc: Boolean indicates whether to add extra two columns in the output (allc)
      file regarding the genotype information of each site.
    inputBinding:
      position: 101
      prefix: --add-snp-info
  - id: aligner
    type:
      - 'null'
      - string
    doc: Aligner to use. Currently, methylpy supports bowtie, bowtie2 and 
      minimap2.
    inputBinding:
      position: 101
      prefix: --aligner
  - id: aligner_options
    type:
      - 'null'
      - type: array
        items: string
    doc: list of strings indicating options you would like passed to bowtie 
      (e.g., "-k 1 -l 2")
    inputBinding:
      position: 101
      prefix: --aligner-options
  - id: bgzip
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to bgzip compressed allc files and tabix 
      index.
    inputBinding:
      position: 101
      prefix: --bgzip
  - id: binom_test
    type:
      - 'null'
      - boolean
    doc: Indicates that you would like to perform a binomial test on each 
      cytosine.
    inputBinding:
      position: 101
      prefix: --binom-test
  - id: check_dependency
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to check dependency requirements are met.
    inputBinding:
      position: 101
      prefix: --check-dependency
  - id: compress_output
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to compress (by gzip) the final output (allc
      file(s)).
    inputBinding:
      position: 101
      prefix: --compress-output
  - id: error_rate
    type:
      - 'null'
      - float
    doc: maximum allowed error rate (no. of errors divided by the length of the 
      matching region)
    inputBinding:
      position: 101
      prefix: --error-rate
  - id: forward_ref
    type: File
    doc: string indicating the path to the forward strand reference created by 
      build_ref
    inputBinding:
      position: 101
      prefix: --forward-ref
  - id: generate_allc_file
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to generate the final output file that 
      contains the methylation state of each cytosine.
    inputBinding:
      position: 101
      prefix: --generate-allc-file
  - id: generate_mpileup_file
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to generate intermediate mpileup file to 
      save space.
    inputBinding:
      position: 101
      prefix: --generate-mpileup-file
  - id: java_options
    type:
      - 'null'
      - string
    doc: String indicating the option pass the java when running picard.
    inputBinding:
      position: 101
      prefix: --java-options
  - id: keep_clonal_stats
    type:
      - 'null'
      - boolean
    doc: Boolean indicates whether to store the metric file from picard.
    inputBinding:
      position: 101
      prefix: --keep-clonal-stats
  - id: keep_temp_files
    type:
      - 'null'
      - boolean
    doc: Boolean indicating that you would like to keep the intermediate files 
      generated by this function.
    inputBinding:
      position: 101
      prefix: --keep-temp-files
  - id: libraries
    type:
      - 'null'
      - type: array
        items: string
    doc: list of library IDs (in the same order as the files list) indiciating 
      which libraries each set of fastq files belong to.
      - libA
    inputBinding:
      position: 101
      prefix: --libraries
  - id: max_adapter_removal
    type:
      - 'null'
      - int
    doc: Indicates the maximum number of times to try to remove adapters.
    inputBinding:
      position: 101
      prefix: --max-adapter-removal
  - id: merge_by_max_mapq
    type:
      - 'null'
      - boolean
    doc: Boolean indicates whether to merge alignment results from two converted
      genomes by MAPQ score.
    inputBinding:
      position: 101
      prefix: --merge-by-max-mapq
  - id: min_base_quality
    type:
      - 'null'
      - int
    doc: Integer indicating the minimum PHRED quality score for a base to be 
      included in the mpileup file.
    inputBinding:
      position: 101
      prefix: --min-base-quality
  - id: min_cov
    type:
      - 'null'
      - int
    doc: Integer indicating the minimum number of reads for a site to be tested.
    inputBinding:
      position: 101
      prefix: --min-cov
  - id: min_mapq
    type:
      - 'null'
      - int
    doc: Minimum MAPQ for reads to be included.
    inputBinding:
      position: 101
      prefix: --min-mapq
  - id: min_qual_score
    type:
      - 'null'
      - int
    doc: allows you to trim low-quality ends from reads before adapter removal.
    inputBinding:
      position: 101
      prefix: --min-qual-score
  - id: min_read_len
    type:
      - 'null'
      - int
    doc: indicates the minimum length a read must be to be kept.
    inputBinding:
      position: 101
      prefix: --min-read-len
  - id: num_downstream_bases
    type:
      - 'null'
      - int
    doc: Number of base(s) downstream of each cytosine that you wish to include 
      in output file.
    inputBinding:
      position: 101
      prefix: --num-downstream-bases
  - id: num_procs
    type:
      - 'null'
      - int
    doc: Number of processors you wish to use to parallelize this function
    inputBinding:
      position: 101
      prefix: --num-procs
  - id: num_upstream_bases
    type:
      - 'null'
      - int
    doc: Number of base(s) upstream of each cytosine that you wish to include in
      output file.
    inputBinding:
      position: 101
      prefix: --num-upstream-bases
  - id: overlap_length
    type:
      - 'null'
      - int
    doc: Minimum overlap length.
    inputBinding:
      position: 101
      prefix: --overlap-length
  - id: path_to_aligner
    type:
      - 'null'
      - File
    doc: Path to bowtie/bowtie2 installation
    inputBinding:
      position: 101
      prefix: --path-to-aligner
  - id: path_to_bgzip
    type:
      - 'null'
      - File
    doc: Path to bgzip installation
    inputBinding:
      position: 101
      prefix: --path-to-bgzip
  - id: path_to_cutadapt
    type:
      - 'null'
      - File
    doc: Path to cutadapt installation
    inputBinding:
      position: 101
      prefix: --path-to-cutadapt
  - id: path_to_picard
    type:
      - 'null'
      - File
    doc: The path to the picard.jar in picard tools.
    inputBinding:
      position: 101
      prefix: --path-to-picard
  - id: path_to_samtools
    type:
      - 'null'
      - File
    doc: Path to samtools installation
    inputBinding:
      position: 101
      prefix: --path-to-samtools
  - id: path_to_tabix
    type:
      - 'null'
      - File
    doc: Path to tabix installation
    inputBinding:
      position: 101
      prefix: --path-to-tabix
  - id: pbat
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to process data in PBAT (Post-Bisulfite 
      Adaptor Tagging) mode.
    inputBinding:
      position: 101
      prefix: --pbat
  - id: read_files
    type:
      type: array
      items: File
    doc: list of all the fastq files you would like to run through the pipeline.
      Note that globbing is supported here.
    inputBinding:
      position: 101
      prefix: --read-files
  - id: ref_fasta
    type: File
    doc: string indicating the path to a fasta file containing the sequences you
      used for mapping
    inputBinding:
      position: 101
      prefix: --ref-fasta
  - id: remove_chr_prefix
    type:
      - 'null'
      - boolean
    doc: Boolean indicates whether to remove in the final output the "chr" 
      prefix in the chromosome name
    inputBinding:
      position: 101
      prefix: --remove-chr-prefix
  - id: remove_clonal
    type:
      - 'null'
      - boolean
    doc: Boolean indicates whether to remove clonal reads or not
    inputBinding:
      position: 101
      prefix: --remove-clonal
  - id: reverse_ref
    type: File
    doc: string indicating the path to the reverse strand reference created by 
      build_ref
    inputBinding:
      position: 101
      prefix: --reverse-ref
  - id: sample
    type: string
    doc: String indicating the name of the sample you are processing. It will be
      included in the output files.
    inputBinding:
      position: 101
      prefix: --sample
  - id: sig_cutoff
    type:
      - 'null'
      - float
    doc: float indicating the adjusted p-value cutoff you wish to use for 
      determining whether or not a site is methylated
    inputBinding:
      position: 101
      prefix: --sig-cutoff
  - id: sort_mem
    type:
      - 'null'
      - string
    doc: Parameter to pass to unix sort with -S/--buffer-size command
    inputBinding:
      position: 101
      prefix: --sort-mem
  - id: trim_reads
    type:
      - 'null'
      - boolean
    doc: Boolean indicating whether to trim reads using cutadapt.
    inputBinding:
      position: 101
      prefix: --trim-reads
  - id: unmethylated_control
    type:
      - 'null'
      - string
    doc: name of the chromosome/region that you want to use to estimate the 
      non-conversion rate of your sample, or the non-conversion rate you would 
      like to use.
    inputBinding:
      position: 101
      prefix: --unmethylated-control
  - id: zero_cap
    type:
      - 'null'
      - boolean
    doc: Flag that causes negative quality values to be set to zero
    inputBinding:
      position: 101
      prefix: --zero-cap
outputs:
  - id: path_to_output
    type:
      - 'null'
      - Directory
    doc: Path to a directory where you would like the output to be stored.
    outputBinding:
      glob: $(inputs.path_to_output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/methylpy:1.4.7--py39h0ae133c_0
