cwlVersion: v1.2
class: CommandLineTool
baseCommand: dindel
label: dindel
doc: "dindel\n\nTool homepage: https://github.com/genome/dindel-tgi"
inputs:
  - id: analysis
    type: string
    doc: 'Analysis type: getCIGARindels: Extract indels from CIGARs of mapped reads,
      and infer libary insert size distributions indels: infer indels realignCandidates:
      Realign/reposition candidates in candidate file'
    default: indels
    inputBinding:
      position: 101
      prefix: --analysis
  - id: bam_file
    type: File
    doc: read alignment file (should be indexed)
    inputBinding:
      position: 101
      prefix: --bamFile
  - id: bam_files
    type: File
    doc: file containing filepaths for BAMs to be jointly analysed (not possible
      for --analysis==indels
    inputBinding:
      position: 101
      prefix: --bamFiles
  - id: bayes_a0
    type:
      - 'null'
      - float
    doc: Dirichlet a0 parameter haplotype frequency prior
    default: 0.001
    inputBinding:
      position: 101
      prefix: --bayesa0
  - id: bayes_type
    type:
      - 'null'
      - string
    doc: Bayesian EM program type (all or singlevariant or priorpersite)
    default: singlevariant
    inputBinding:
      position: 101
      prefix: --bayesType
  - id: cap_map_qual_fast
    type:
      - 'null'
      - int
    doc: 'cap mapping quality in alignment using fast ungapped method (WARNING: setting
      it too high (>50) might result in significant overcalling!)'
    default: 45
    inputBinding:
      position: 101
      prefix: --capMapQualFast
  - id: cap_map_qual_threshold
    type:
      - 'null'
      - int
    doc: upper limit for read mapping quality in observationmodel_old (phred 
      units)
    default: 100
    inputBinding:
      position: 101
      prefix: --capMapQualThreshold
  - id: change_ins_to_n
    type:
      - 'null'
      - boolean
    doc: change sequence of inserted sequence to 'N', so that no penalty is 
      incurred if a read mismatches the inserted sequence
    inputBinding:
      position: 101
      prefix: --changeINStoN
  - id: check_all_cigars
    type:
      - 'null'
      - int
    doc: include all indels at the position of the call site
    default: 1
    inputBinding:
      position: 101
      prefix: --checkAllCIGARs
  - id: compare_read_hap
    type:
      - 'null'
      - boolean
    doc: compare likelihood differences in reads against haplotypes
    inputBinding:
      position: 101
      prefix: --compareReadHap
  - id: compare_read_hap_threshold
    type:
      - 'null'
      - float
    doc: difference threshold for viewing
    default: 0.5
    inputBinding:
      position: 101
      prefix: --compareReadHapThreshold
  - id: do_diploid
    type:
      - 'null'
      - boolean
    doc: analyze data assuming a diploid sequence
    inputBinding:
      position: 101
      prefix: --doDiploid
  - id: do_pooled
    type:
      - 'null'
      - boolean
    doc: estimate haplotype frequencies using Bayesian EM algorithm. May be 
      applied to single individual and pools.
    inputBinding:
      position: 101
      prefix: --doPooled
  - id: faster
    type:
      - 'null'
      - boolean
    doc: use faster but less accurate ungapped read-haplotype alignment model
    inputBinding:
      position: 101
      prefix: --faster
  - id: filter_haplotypes
    type:
      - 'null'
      - boolean
    doc: prefilter haplotypes based on coverage
    inputBinding:
      position: 101
      prefix: --filterHaplotypes
  - id: filter_read_aux
    type:
      - 'null'
      - string
    doc: match string for exclusion of reads based on auxilary information
    inputBinding:
      position: 101
      prefix: --filterReadAux
  - id: flank_max_mismatch
    type:
      - 'null'
      - int
    doc: max number of mismatches in indel region
    default: 2
    inputBinding:
      position: 101
      prefix: --flankMaxMismatch
  - id: flank_ref_seq
    type:
      - 'null'
      - int
    doc: '#bases of reference sequence of indel region'
    default: 2
    inputBinding:
      position: 101
      prefix: --flankRefSeq
  - id: inference_method
    type:
      - 'null'
      - string
    doc: inference method
    default: empirical
    inputBinding:
      position: 101
      prefix: --inferenceMethod
  - id: lib_file
    type:
      - 'null'
      - File
    doc: file with library insert histograms (as generated by --analysis 
      getCIGARindels)
    inputBinding:
      position: 101
      prefix: --libFile
  - id: map_qual_threshold
    type:
      - 'null'
      - float
    doc: lower limit for read mapping quality
    default: 0.99
    inputBinding:
      position: 101
      prefix: --mapQualThreshold
  - id: max_hap
    type:
      - 'null'
      - int
    doc: maximum number of haplotypes in likelihood computation
    default: 8
    inputBinding:
      position: 101
      prefix: --maxHap
  - id: max_hap_read_prod
    type:
      - 'null'
      - int
    doc: skip if product of number of reads and haplotypes exceeds this value
    default: 10000000
    inputBinding:
      position: 101
      prefix: --maxHapReadProd
  - id: max_length_indel
    type:
      - 'null'
      - int
    doc: maximum length of a _sequencing error_ indel in read [not for --faster 
      option]
    default: 5
    inputBinding:
      position: 101
      prefix: --maxLengthIndel
  - id: max_read
    type:
      - 'null'
      - int
    doc: maximum number of reads in likelihood computation
    default: 10000
    inputBinding:
      position: 101
      prefix: --maxRead
  - id: max_read_length
    type:
      - 'null'
      - int
    doc: maximum length of reads
    default: 500
    inputBinding:
      position: 101
      prefix: --maxReadLength
  - id: min_count
    type:
      - 'null'
      - int
    doc: minimum number of WS observations of indel
    default: 1
    inputBinding:
      position: 101
      prefix: --minCount
  - id: min_read_overlap
    type:
      - 'null'
      - int
    doc: minimum overlap between read and haplotype
    default: 20
    inputBinding:
      position: 101
      prefix: --minReadOverlap
  - id: opl
    type:
      - 'null'
      - boolean
    doc: output likelihoods for every read and haplotype
    inputBinding:
      position: 101
      prefix: --opl
  - id: output_file
    type: string
    doc: file-prefix for output results
    inputBinding:
      position: 101
      prefix: --outputFile
  - id: p_error
    type:
      - 'null'
      - float
    doc: probability of a read indel
    default: 0.0005
    inputBinding:
      position: 101
      prefix: --pError
  - id: p_mut
    type:
      - 'null'
      - float
    doc: probability of a mutation in the read
    default: 1e-05
    inputBinding:
      position: 101
      prefix: --pMut
  - id: prior_indel
    type:
      - 'null'
      - float
    doc: prior probability of a detected indel not being a sequencing error
    default: 0.0001
    inputBinding:
      position: 101
      prefix: --priorIndel
  - id: prior_snp
    type:
      - 'null'
      - float
    doc: prior probability of a SNP site
    default: 0.001
    inputBinding:
      position: 101
      prefix: --priorSNP
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: quiet output
    inputBinding:
      position: 101
      prefix: --quiet
  - id: ref
    type: File
    doc: fasta reference sequence (should be indexed with .fai file)
    inputBinding:
      position: 101
      prefix: --ref
  - id: region
    type: string
    doc: region to be analysed in format start-end, eg. 1000-2000
    inputBinding:
      position: 101
      prefix: --region
  - id: show_cand_hap
    type:
      - 'null'
      - boolean
    doc: show candidate haplotypes for fast method
    inputBinding:
      position: 101
      prefix: --showCandHap
  - id: show_empirical
    type:
      - 'null'
      - boolean
    doc: show empirical distribution over nucleotides
    inputBinding:
      position: 101
      prefix: --showEmpirical
  - id: show_hap_alignments
    type:
      - 'null'
      - boolean
    doc: show for each haplotype which reads map to it
    inputBinding:
      position: 101
      prefix: --showHapAlignments
  - id: show_reads
    type:
      - 'null'
      - boolean
    doc: show reads
    inputBinding:
      position: 101
      prefix: --showReads
  - id: skip_max_hap
    type:
      - 'null'
      - int
    doc: skip computation if number of haplotypes exceeds this number
    default: 200
    inputBinding:
      position: 101
      prefix: --skipMaxHap
  - id: tid
    type: string
    doc: target sequence (eg 'X')
    inputBinding:
      position: 101
      prefix: --tid
  - id: var_file
    type: File
    doc: file with candidate variants to be tested.
    inputBinding:
      position: 101
      prefix: --varFile
  - id: var_file_is_one_based
    type:
      - 'null'
      - boolean
    doc: coordinates in varFile are one-based
    inputBinding:
      position: 101
      prefix: --varFileIsOneBased
  - id: width
    type:
      - 'null'
      - int
    doc: number of bases to left and right of indel
    default: 60
    inputBinding:
      position: 101
      prefix: --width
outputs:
  - id: output_realigned_bam
    type:
      - 'null'
      - File
    doc: output BAM file with realigned reads
    outputBinding:
      glob: $(inputs.output_realigned_bam)
  - id: process_realigned_bam
    type:
      - 'null'
      - File
    doc: ABSOLUTE path to script to process realigned BAM file
    outputBinding:
      glob: $(inputs.process_realigned_bam)
hints:
  - class: DockerRequirement
    dockerPull: biocontainers/dindel:v1.01-wu1-3dfsg-1b1-deb_cv1
