cwlVersion: v1.2
class: CommandLineTool
baseCommand: NanoStat
label: nanopack_NanoStat
doc: "NanoStat: Calculate statistics of long read sequencing data and generate plots.\n
  \nTool homepage: https://github.com/wdecoster/nanopack"
inputs:
  - id: bam
    type:
      - 'null'
      - type: array
        items: File
    doc: Input sorted bam file(s)
    inputBinding:
      position: 101
      prefix: --bam
  - id: barcoded
    type:
      - 'null'
      - boolean
    doc: Use if you want to split the summary file by barcode
    inputBinding:
      position: 101
      prefix: --barcoded
  - id: fasta
    type:
      - 'null'
      - type: array
        items: File
    doc: Input fasta file(s)
    inputBinding:
      position: 101
      prefix: --fasta
  - id: fastq
    type:
      - 'null'
      - type: array
        items: File
    doc: Input fastq file(s)
    inputBinding:
      position: 101
      prefix: --fastq
  - id: html
    type:
      - 'null'
      - boolean
    doc: Output statistics in an html file
    inputBinding:
      position: 101
      prefix: --html
  - id: prefix
    type:
      - 'null'
      - string
    doc: Prefix for the output files
    inputBinding:
      position: 101
      prefix: --prefix
  - id: readtype
    type:
      - 'null'
      - string
    doc: 'Which read type to extract information about from summary. Options: 1D,
      2D, 1D2'
    inputBinding:
      position: 101
      prefix: --readtype
  - id: summary
    type:
      - 'null'
      - type: array
        items: File
    doc: Input sequencing_summary file(s) generated by albacore or guppy
    inputBinding:
      position: 101
      prefix: --summary
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use
    default: 1
    inputBinding:
      position: 101
      prefix: --threads
  - id: tsv
    type:
      - 'null'
      - boolean
    doc: Output statistics in a tab-separated values file
    inputBinding:
      position: 101
      prefix: --tsv
outputs:
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: Directory to write output files to
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/nanopack:1.1.1--hdfd78af_0
