cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - anchorwave
  - genoAli
label: anchorwave_genoAli
doc: "Perform genome alignment using anchorwave\n\nTool homepage: https://github.com/baoxingsong/AnchorWave"
inputs:
  - id: anchor_sequence_file
    type: File
    doc: anchor sequence file. (output from the gff2seq command)
    inputBinding:
      position: 101
      prefix: -as
  - id: call_inversions
    type:
      - 'null'
      - boolean
    doc: whether to call inversions
    inputBinding:
      position: 101
      prefix: -IV
  - id: drop_anchor_ratio
    type:
      - 'null'
      - float
    doc: minimal ratio of e+1 similarity to 1 similarity to drop an anchor
    inputBinding:
      position: 101
      prefix: -y
  - id: gap_extension_penalty_1
    type:
      - 'null'
      - int
    doc: gap extension penalty
    inputBinding:
      position: 101
      prefix: -E1
  - id: gap_extension_penalty_2
    type:
      - 'null'
      - int
    doc: gap extension penalty 2
    inputBinding:
      position: 101
      prefix: -E2
  - id: gap_open_penalty_1
    type:
      - 'null'
      - int
    doc: gap open penalty
    inputBinding:
      position: 101
      prefix: -O1
  - id: gap_open_penalty_2
    type:
      - 'null'
      - int
    doc: gap open penalty 2
    inputBinding:
      position: 101
      prefix: -O2
  - id: inter_anchor_threshold
    type:
      - 'null'
      - int
    doc: if the inter-anchor length is shorter than this value, stop trying to find
      new anchors
    inputBinding:
      position: 101
      prefix: -fa3
  - id: inversion_penalty
    type:
      - 'null'
      - float
    doc: penalty for having a non-linear match in inversion region
    inputBinding:
      position: 101
      prefix: -IC
  - id: max_copy_number
    type:
      - 'null'
      - int
    doc: maximum expected copy number of each gene on each chromosome
    inputBinding:
      position: 101
      prefix: -e
  - id: min_cds_similarity
    type:
      - 'null'
      - float
    doc: minimum full-length CDS anchor hit similarity to use
    inputBinding:
      position: 101
      prefix: -mi
  - id: min_exon_length
    type:
      - 'null'
      - int
    doc: minimum exon length to use (should be identical with the setting of gff2seq
      function)
    inputBinding:
      position: 101
      prefix: -m
  - id: min_inversion_score
    type:
      - 'null'
      - float
    doc: minimum score to keep an inversion
    inputBinding:
      position: 101
      prefix: -I
  - id: min_novel_similarity
    type:
      - 'null'
      - float
    doc: minimum novel anchor hit similarity to use
    inputBinding:
      position: 101
      prefix: -mi2
  - id: mismatch_penalty
    type:
      - 'null'
      - int
    doc: mismatching penalty
    inputBinding:
      position: 101
      prefix: -B
  - id: no_new_anchors
    type:
      - 'null'
      - boolean
    doc: do not search for new anchors
    inputBinding:
      position: 101
      prefix: -ns
  - id: query_sam
    type: File
    doc: sam file generated by mapping conserved sequence to query genome
    inputBinding:
      position: 101
      prefix: -a
  - id: ref_genome
    type: File
    doc: reference genome sequence file in fasta format
    inputBinding:
      position: 101
      prefix: -r
  - id: ref_gff_file
    type: File
    doc: reference GFF/GTF file
    inputBinding:
      position: 101
      prefix: -i
  - id: ref_sam
    type: File
    doc: sam file generated by mapping conserved sequence to reference genome
    inputBinding:
      position: 101
      prefix: -ar
  - id: target_genome
    type: File
    doc: target genome sequence file in fasta format
    inputBinding:
      position: 101
      prefix: -s
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads
    inputBinding:
      position: 101
      prefix: -t
  - id: use_exon_records
    type:
      - 'null'
      - boolean
    doc: use exon records instead of CDS from the GFF file
    inputBinding:
      position: 101
      prefix: -x
  - id: window_width
    type:
      - 'null'
      - int
    doc: sequence alignment window width
    inputBinding:
      position: 101
      prefix: -w
outputs:
  - id: output_anchors_file
    type: File
    doc: output anchors file
    outputBinding:
      glob: $(inputs.output_anchors_file)
  - id: output_maf
    type: File
    doc: output file in maf format
    outputBinding:
      glob: $(inputs.output_maf)
  - id: output_fragmentation_maf
    type: File
    doc: output sequence alignment for each anchor/inter-anchor region in maf format
    outputBinding:
      glob: $(inputs.output_fragmentation_maf)
  - id: output_bed
    type:
      - 'null'
      - File
    doc: output the sequence alignment method used for each anchor/inter-anchor region,
      in bed format
    outputBinding:
      glob: $(inputs.output_bed)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/anchorwave:1.2.6--h077b44d_0
