cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - chewBBACA.py
  - AlleleCallEvaluator
label: chewbbaca_AlleleCallEvaluator
doc: "Build an interactive report for allele calling results evaluation.\n\nTool homepage: https://github.com/B-UMMI/chewBBACA"
inputs:
  - id: input_files
    type: Directory
    doc: "Path to the directory that contains the allele calling results generated by the AlleleCall module."
    inputBinding:
      position: 1
      prefix: --input-files
  - id: schema_directory
    type: Directory
    doc: "Path to the schema's directory."
    inputBinding:
      position: 1
      prefix: --schema-directory
  - id: output_directory
    type: string
    doc: "Path to the output directory where the module will store intermediate files and create the report HTML files."
    default: "allelecall_report"
    inputBinding:
      position: 1
      prefix: --output-directory
  - id: annotations
    type:
      - 'null'
      - File
    doc: "Path to the TSV file created by the UniprotFinder module."
    inputBinding:
      position: 1
      prefix: --annotations
  - id: cpu_cores
    type:
      - 'null'
      - int
    doc: "Number of CPU cores that will be used to run the process (chewie resets to a lower value if it is equal to or exceeds the total number of available CPU cores). (default: 1)"
    inputBinding:
      position: 1
      prefix: --cpu-cores
  - id: light
    type:
      - 'null'
      - boolean
    doc: "Do not compute the presence-absence matrix, the distance matrix and the Neighbor-Joining tree."
    inputBinding:
      position: 1
      prefix: --light
  - id: no_pa
    type:
      - 'null'
      - boolean
    doc: "Do not compute the presence-absence matrix."
    inputBinding:
      position: 1
      prefix: --no-pa
  - id: no_dm
    type:
      - 'null'
      - boolean
    doc: "Do not compute the distance matrix."
    inputBinding:
      position: 1
      prefix: --no-dm
  - id: no_tree
    type:
      - 'null'
      - boolean
    doc: "Do not compute the Neighbor-Joining tree."
    inputBinding:
      position: 1
      prefix: --no-tree
  - id: cg_alignment
    type:
      - 'null'
      - boolean
    doc: "Compute the MSA of the core genome loci, even if --no-tree is provided."
    inputBinding:
      position: 1
      prefix: --cg-alignment
outputs:
  - id: results_dir
    type: Directory
    doc: "Allele calling evaluation report directory."
    outputBinding:
      glob: $(inputs.output_directory)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/chewbbaca:3.5.1--pyhdfd78af_0
