cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - blobtools
  - filter
label: blobtoolkit_filter
doc: "Filter a BlobDir.\n\nTool homepage: https://github.com/blobtoolkit/blobtoolkit"
inputs:
  - id: blobdir
    type: Directory
    doc: Existing BlobDir dataset directory.
    inputBinding:
      position: 2
  - id: param
    type:
      - 'null'
      - type: array
        items: string
        inputBinding:
          prefix: --param
    doc: String of type param=value.
    inputBinding:
      position: 1
  - id: query_string
    type: ['null', string]
    doc: List of param=value pairs from url query string.
    inputBinding:
      position: 1
      prefix: --query-string
  - id: json
    type: ['null', File]
    doc: JSON format list file as generated by BlobtoolKit Viewer.
    inputBinding:
      position: 1
      prefix: --json
  - id: list
    type: ['null', File]
    doc: Space or newline separated list of identifiers.
    inputBinding:
      position: 1
      prefix: --list
  - id: invert
    type: ['null', boolean]
    doc: Invert filter (exclude matching records).
    inputBinding:
      position: 1
      prefix: --invert
  - id: output
    type: ['null', string]
    doc: Path to directory to generate a new, filtered BlobDir.
    inputBinding:
      position: 1
      prefix: --output
  - id: fasta
    type: ['null', File]
    doc: FASTA format assembly file to be filtered. The filtered copy is written beside the staged file and collected.
    inputBinding:
      position: 1
      prefix: --fasta
  - id: fastq
    type:
      - 'null'
      - type: array
        items: File
        inputBinding:
          prefix: --fastq
    doc: FASTQ format read file to be filtered (requires --cov). The filtered copies are collected.
    inputBinding:
      position: 1
  - id: suffix
    type: ['null', string]
    doc: 'String to be added to filtered filename. [Default: filtered]'
    inputBinding:
      position: 1
      prefix: --suffix
  - id: cov
    type: ['null', File]
    doc: BAM/SAM/CRAM read alignment file.
    inputBinding:
      position: 1
      prefix: --cov
  - id: summary
    type: ['null', string]
    doc: Generate a JSON-format summary of the filtered dataset (file name).
    inputBinding:
      position: 1
      prefix: --summary
  - id: summary_rank
    type: ['null', string]
    doc: 'Taxonomic level for summary. [Default: phylum]'
    inputBinding:
      position: 1
      prefix: --summary-rank
  - id: table
    type: ['null', string]
    doc: Tabular output of filtered dataset (file name).
    inputBinding:
      position: 1
      prefix: --table
  - id: table_fields
    type: ['null', string]
    doc: 'Comma separated list of field IDs to include in the table output. Use ''plot'' to include all plot axes. [Default: plot]'
    inputBinding:
      position: 1
      prefix: --table-fields
  - id: taxdump
    type: ['null', Directory]
    doc: Location of NCBI new_taxdump directory.
    inputBinding:
      position: 1
      prefix: --taxdump
  - id: taxrule
    type: ['null', string]
    doc: Taxrule used when processing hits.
    inputBinding:
      position: 1
      prefix: --taxrule
  - id: text
    type: ['null', File]
    doc: generic text file to be filtered. The filtered copy is collected.
    inputBinding:
      position: 1
      prefix: --text
  - id: text_header
    type: ['null', boolean]
    doc: 'Flag to indicate first row of text file contains field names. [Default: False]'
    inputBinding:
      position: 1
      prefix: --text-header
  - id: text_delimiter
    type: ['null', string]
    doc: 'text file delimiter. [Default: whitespace]'
    inputBinding:
      position: 1
      prefix: --text-delimiter
  - id: text_id_column
    type: ['null', int]
    doc: 'index of column containing identifiers (1-based). [Default: 1]'
    inputBinding:
      position: 1
      prefix: --text-id-column
outputs:
  - id: output_blobdir
    type: ['null', Directory]
    doc: Filtered BlobDir (--output)
    outputBinding:
      glob: $(inputs.output)
  - id: filtered_fasta
    type: ['null', File]
    doc: Filtered FASTA file
    outputBinding:
      glob: '$(inputs.fasta ? inputs.fasta.nameroot + ''.'' + (inputs.suffix ? inputs.suffix : ''filtered'') + ''*'' : [])'
  - id: filtered_fastq
    type:
      type: array
      items: File
    doc: Filtered FASTQ files
    outputBinding:
      glob: '$(inputs.fastq ? inputs.fastq.map(function(f){ return f.basename.replace(/\.(fastq|fq)(\.gz)?$/, '''') + ''.'' + (inputs.suffix ? inputs.suffix : ''filtered'') + ''*''; }) : [])'
  - id: filtered_text
    type: ['null', File]
    doc: Filtered text file
    outputBinding:
      glob: '$(inputs.text ? inputs.text.nameroot + ''.'' + (inputs.suffix ? inputs.suffix : ''filtered'') + ''*'' : [])'
  - id: summary_file
    type: ['null', File]
    doc: JSON summary (--summary)
    outputBinding:
      glob: $(inputs.summary)
  - id: table_file
    type: ['null', File]
    doc: Table of the filtered dataset (--table)
    outputBinding:
      glob: $(inputs.table)
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.fasta)
        writable: true
      - entry: $(inputs.fastq)
        writable: true
      - entry: $(inputs.text)
        writable: true
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/blobtoolkit:4.5.1--pyhdfd78af_0
