cwlVersion: v1.2
class: CommandLineTool
baseCommand: pints_visualizer
label: pypints_pints_visualizer
doc: "Visualize BAM files with PINTs.\n\nTool homepage: https://pints.yulab.org"
inputs:
  - id: bam_file
    type: File
    doc: Input BAM file
    inputBinding:
      position: 101
      prefix: --bam
  - id: bam_parser
    type:
      - 'null'
      - string
    doc: "Type of experiment, acceptable values are: CoPRO/GROcap/GROseq/PROcap/PROseq,
      or if you know the position of RNA ends which you're interested on the reads,
      you can specify R_5, R_3, R1_5, R1_3, R2_5 or R2_3"
    default: None
    inputBinding:
      position: 101
      prefix: --exp-type
  - id: cache
    type:
      - 'null'
      - boolean
    doc: Set this switch if you want to reuse the intermediate .npy files.
    default: false
    inputBinding:
      position: 101
      prefix: --cache
  - id: chromosome_startswith
    type:
      - 'null'
      - string
    doc: Only keep reads mapped to chromosomes with this prefix
    default: chr
    inputBinding:
      position: 101
      prefix: --chromosome-start-with
  - id: filters
    type:
      - 'null'
      - type: array
        items: string
    doc: Reads from chromosomes whose names contain any matches in filters will 
      be ignored
    default: None
    inputBinding:
      position: 101
      prefix: --filters
  - id: mapq_threshold
    type:
      - 'null'
      - int
    doc: Minimum mapping quality
    default: 30
    inputBinding:
      position: 101
      prefix: --mapq-threshold
  - id: norm_fact
    type:
      - 'null'
      - float
    doc: Normalization factor, can be generated by normalizer.py
    default: 1.0
    inputBinding:
      position: 101
      prefix: --norm-fact
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: Output prefix
    inputBinding:
      position: 101
      prefix: --output-prefix
  - id: reverse_complement
    type:
      - 'null'
      - boolean
    doc: Set this switch if reads in this library represent the reverse 
      complement of nascent RNAs, like PROseq
    default: false
    inputBinding:
      position: 101
      prefix: --reverse-complement
  - id: rpm
    type:
      - 'null'
      - boolean
    doc: Set this switch if you want to use RPM to normalize the outputs
    default: false
    inputBinding:
      position: 101
      prefix: --rpm
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/pypints:1.2.1--pyh7e72e81_0
stdout: pypints_pints_visualizer.out
