cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - radsex
  - map
label: radsex_map
doc: "Map markers to a reference genome. This command aligns marker sequences from
  a table generated by 'radsex process' to a reference genome and computes mapping
  statistics.\n\nTool homepage: https://github.com/RomainFeron/RadSex"
inputs:
  - id: genome_file
    type: File
    doc: Path to the reference genome in FASTA format
    inputBinding:
      position: 101
      prefix: --genome
  - id: min_identity
    type:
      - 'null'
      - float
    doc: Minimum identity to consider a marker as mapped
    inputBinding:
      position: 101
      prefix: --min-identity
  - id: min_quality
    type:
      - 'null'
      - int
    doc: Minimum mapping quality to consider a marker as mapped
    inputBinding:
      position: 101
      prefix: --min-quality
  - id: table_file
    type: File
    doc: Path to the table of markers generated by 'radsex process'
    inputBinding:
      position: 101
      prefix: --table
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use for mapping
    inputBinding:
      position: 101
      prefix: --threads
outputs:
  - id: output_file
    type: File
    doc: Path to the output file containing mapping results
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/radsex:1.2.0--h43eeafb_3
