cwlVersion: v1.2
class: CommandLineTool
baseCommand: igua
label: igua
doc: "A method for content-agnostic high-throughput identification of Gene Cluster
  Families (GCFs) from gene clusters of genomic and metagenomic origin.\n\nTool homepage:
  https://github.com/zellerlab/IGUA"
inputs:
  - id: input
    type:
      type: array
      items: File
      inputBinding:
        prefix: -i
    doc: The GenBank files containing the clusters to process (one -i per file).
    inputBinding:
      position: 1
  - id: output_path
    type: string
    default: gcfs.tsv
    doc: The name of the output file to generate.
    inputBinding:
      position: 2
      prefix: -o
  - id: compositions_path
    type: ['null', string]
    doc: A file where to write compositional data for GCF representatives.
    inputBinding:
      position: 3
      prefix: -C
  - id: features_path
    type: ['null', string]
    doc: A file where to write protein cluster representatives in FASTA format.
    inputBinding:
      position: 4
      prefix: -F
  - id: jobs
    type: ['null', int]
    doc: The number of threads to use in parallel sections.
    inputBinding:
      position: 5
      prefix: -j
  - id: workdir
    type: ['null', string]
    doc: A folder to use for temporary data produced by MMSeqs2.
    inputBinding:
      position: 6
      prefix: -w
  - id: prefix
    type: ['null', string]
    doc: The prefix for GCF identifiers generated by the pipeline.
    inputBinding:
      position: 7
      prefix: --prefix
  - id: no_clustering
    type: ['null', boolean]
    doc: Disable the protein-level clustering.
    inputBinding:
      position: 8
      prefix: --no-clustering
  - id: clustering_method
    type: ['null', string]
    doc: 'The hierarchical method to use for protein-level clustering: centroid,
      average, single, ward, median, weighted or complete.'
    inputBinding:
      position: 9
      prefix: --clustering-method
  - id: clustering_distance
    type: ['null', double]
    doc: The distance threshold after which to stop merging clusters.
    inputBinding:
      position: 10
      prefix: --clustering-distance
  - id: precision
    type: ['null', string]
    doc: 'The numerical precision to use for computing distances for hierarchical
      clustering: half, single or double.'
    inputBinding:
      position: 11
      prefix: --precision
outputs:
  - id: gcf_table
    type: File
    doc: Table of gene cluster families
    outputBinding:
      glob: $(inputs.output_path)
  - id: compositions
    type: ['null', File]
    doc: Compositional data for GCF representatives
    outputBinding:
      glob: $(inputs.compositions_path)
  - id: features
    type: ['null', File]
    doc: Protein cluster representatives in FASTA format
    outputBinding:
      glob: $(inputs.features_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/igua:0.1.0--py39h5b94c0b_0
