cwlVersion: v1.2
class: CommandLineTool
baseCommand: mageck_plot
label: mageck_plot
doc: "Plotting function for MAGeCK\n\nTool homepage: http://mageck.sourceforge.net"
inputs:
  - id: control_gene
    type:
      - 'null'
      - string
    doc: A list of genes whose sgRNAs are used as control sgRNAs for 
      normalization and for generating the null distribution of RRA.
    inputBinding:
      position: 101
      prefix: --control-gene
  - id: control_sgrna
    type:
      - 'null'
      - string
    doc: A list of control sgRNAs for normalization and for generating the null 
      distribution of RRA.
    inputBinding:
      position: 101
      prefix: --control-sgrna
  - id: count_table
    type: File
    doc: Provide a tab-separated count table instead of sam files. Each line in 
      the table should include sgRNA name (1st column), gene name (2nd column) 
      and read counts in each sample.
    inputBinding:
      position: 101
      prefix: --count-table
  - id: gene_summary
    type: File
    doc: The gene summary file generated by the test command.
    inputBinding:
      position: 101
      prefix: --gene-summary
  - id: genes
    type:
      - 'null'
      - string
    doc: A list of genes to be plotted, separated by comma.
    inputBinding:
      position: 101
      prefix: --genes
  - id: keep_tmp
    type:
      - 'null'
      - boolean
    doc: Keep intermediate files.
    inputBinding:
      position: 101
      prefix: --keep-tmp
  - id: norm_method
    type:
      - 'null'
      - string
    doc: Method for normalization, including "none" (no normalization), "median"
      (median normalization, default), "total" (normalization by total read 
      counts), "control" (normalization by control sgRNAs specified by the 
      --control-sgrna option).
    inputBinding:
      position: 101
      prefix: --norm-method
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: The prefix of the output file(s).
    inputBinding:
      position: 101
      prefix: --output-prefix
  - id: samples
    type:
      - 'null'
      - string
    doc: A list of samples to be plotted, separated by comma.
    inputBinding:
      position: 101
      prefix: --samples
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mageck:0.5.9.5--py310h184ae93_8
stdout: mageck_plot.out
