cwlVersion: v1.2
class: CommandLineTool
baseCommand: mageck pathway
label: mageck_pathway
doc: "Pathway enrichment analysis.\n\nTool homepage: http://mageck.sourceforge.net"
inputs:
  - id: gene_ranking
    type: File
    doc: The gene summary file (containing both positive and negative selection 
      tests) generated by the gene test step. Pathway enrichment will be 
      performed in both directions.
    inputBinding:
      position: 101
      prefix: --gene-ranking
  - id: gmt_file
    type: File
    doc: The pathway file in GMT format.
    inputBinding:
      position: 101
      prefix: --gmt-file
  - id: keep_tmp
    type:
      - 'null'
      - boolean
    doc: Keep intermediate files.
    inputBinding:
      position: 101
      prefix: --keep-tmp
  - id: method
    type:
      - 'null'
      - string
    doc: Method for testing pathway enrichment, including gsea (Gene Set 
      Enrichment Analysis) or rra.
    default: gsea
    inputBinding:
      position: 101
      prefix: --method
  - id: output_prefix
    type:
      - 'null'
      - string
    doc: The prefix of the output file(s).
    default: sample1
    inputBinding:
      position: 101
      prefix: --output-prefix
  - id: pathway_alpha
    type:
      - 'null'
      - float
    doc: The default alpha value for RRA pathway enrichment.
    default: 0.25
    inputBinding:
      position: 101
      prefix: --pathway-alpha
  - id: permutation
    type:
      - 'null'
      - int
    doc: The perumtation for gsea.
    default: 1000
    inputBinding:
      position: 101
      prefix: --permutation
  - id: ranking_column
    type:
      - 'null'
      - string
    doc: Column number or label in gene summary file for gene ranking; can be 
      either an integer of column number, or a string of column label. Default 
      "2" (the 3rd column), the column of the negative selection RRA score in 
      gene_summary file.
    default: '2'
    inputBinding:
      position: 101
      prefix: --ranking-column
  - id: ranking_column_2
    type:
      - 'null'
      - string
    doc: Column number or label in gene summary file for gene ranking; can be 
      either an integer of column number, or a string of column label. This 
      option is used to determine the column for positive selections and is 
      disabled if --single-ranking is specified. Default "8" (the 9th column), 
      the column of positive selection RRA score in gene_summary file.
    default: '8'
    inputBinding:
      position: 101
      prefix: --ranking-column-2
  - id: single_ranking
    type:
      - 'null'
      - boolean
    doc: The provided file is a (single) gene ranking file, either positive or 
      negative selection. Only one enrichment comparison will be performed.
    inputBinding:
      position: 101
      prefix: --single-ranking
  - id: sort_criteria
    type:
      - 'null'
      - string
    doc: Sorting criteria, either by negative selection (neg) or positive 
      selection (pos).
    default: neg
    inputBinding:
      position: 101
      prefix: --sort-criteria
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mageck:0.5.9.5--py310h184ae93_8
stdout: mageck_pathway.out
