cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - bwa
  - samse
label: bwa_samse
doc: "Generate alignments in the SAM format given single-end reads\n\nTool homepage:
  https://github.com/lh3/bwa"
inputs:
  - id: prefix
    type: File
    doc: The bwa index, given as its .bwt file (for example ref.fa.bwt from bwa_index) or
      as the file named like the index prefix (for example ref.fa); the .amb, .ann,
      .bwt, .pac and .sa files must sit beside it
    secondaryFiles:
      - pattern: "${ var b = self.basename.replace(/\\.bwt$/, ''); var s = ['.amb', '.ann', '.pac', '.sa']; if (b === self.basename) { s.push('.bwt'); } return s.map(function (e) { return b + e; }); }"
        required: true
    inputBinding:
      position: 201
      valueFrom: $(self.path.replace(/\.bwt$/, ''))
  - id: in_sai
    type: File
    doc: Input SAI file generated by bwa aln
    inputBinding:
      position: 202
  - id: in_fq
    type: File
    doc: Input FASTQ file
    inputBinding:
      position: 203
  - id: max_occ
    type:
      - 'null'
      - int
    doc: Maximum occurrences for one read
    inputBinding:
      position: 104
      prefix: -n
  - id: rg_line
    type:
      - 'null'
      - string
    doc: Read group line
    inputBinding:
      position: 104
      prefix: -r
  - id: output_sam_path
    type: string
    doc: Name of the SAM file to write; any directory part is dropped
    inputBinding:
      position: 150
      prefix: -f
      valueFrom: $(self.split('/').pop())
outputs:
  - id: output_sam
    type: File
    doc: The SAM file with the alignments
    outputBinding:
      glob: $(inputs.output_sam_path.split('/').pop())
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwa:0.7.19--h577a1d6_1
