cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - CIRI-AS
label: ciri-full_CIRI-AS
doc: "CIRI-AS: detection of circRNA internal components and alternative splicing events\n\nTool homepage: https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html"
inputs:
  - id: sam
    type: File
    doc: 'input SAM file (required; generated by BWA-MEM using PAIRED END mode)'
    inputBinding:
      position: 101
      prefix: '--sam'
  - id: ciri
    type: File
    doc: 'input circRNA list (required; generated by CIRI)'
    inputBinding:
      position: 101
      prefix: '--ciri'
  - id: out
    type: string
    doc: 'prefix of output files (required)'
    inputBinding:
      position: 101
      prefix: '--out'
  - id: ref_dir
    type:
      - 'null'
      - Directory
    doc: 'directory of reference sequences (FASTA files in this directory must be the same ones provided to CIRI). Either this argument or --ref_file is required.'
    inputBinding:
      position: 101
      prefix: '--ref_dir'
  - id: ref_file
    type:
      - 'null'
      - File
    doc: 'FASTA file of all reference sequences (must be the same one provided to CIRI). Either this argument or --ref_dir is required.'
    inputBinding:
      position: 101
      prefix: '--ref_file'
  - id: anno
    type:
      - 'null'
      - File
    doc: 'GTF formatted annotation file (optional)'
    inputBinding:
      position: 101
      prefix: '--anno'
  - id: output_all
    type:
      - 'null'
      - string
    doc: 'if output all processing info (Choose ''yes'' would require more disk space. default: no)'
    inputBinding:
      position: 101
      prefix: '--output_all'
  - id: log
    type:
      - 'null'
      - string
    doc: 'output log file name (optional)'
    inputBinding:
      position: 101
      prefix: '--log'
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: 'Files written with the output prefix'
    outputBinding:
      glob: $(inputs.out)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ciri-full:2.1.2--hdfd78af_1
stdout: ciri-full_CIRI-AS.out
