cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - CIRI-full
  - RO2
label: ciri-full_RO2
doc: "RO2 verifies RO merged-reads from candidates by processing the SAM file generated by bwa-mem\n\nTool homepage: https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html"
requirements:
  - class: InlineJavascriptRequirement
inputs:
  - id: reference
    type: File
    doc: 'reference genome in fasta format, the same file used in preparation step when building bwa index (required)'
    inputBinding:
      position: 101
      prefix: '-r'
  - id: sam
    type: File
    doc: 'sam file of prefix_ro1.fq generated by bwa-mem (required)'
    inputBinding:
      position: 101
      prefix: '-s'
  - id: read_length
    type: int
    doc: 'the read length of given RNA-seq paired end data (required)'
    inputBinding:
      position: 101
      prefix: '-l'
  - id: prefix
    type:
      - 'null'
      - string
    doc: 'prefix of output files in the RO2 module (optional, default: user_dir/out)'
    inputBinding:
      position: 101
      prefix: '-o'
  - id: range
    type:
      - 'null'
      - int
    doc: 'the maximum range of circRNA components on reference position (optional, integer, default 100000)'
    inputBinding:
      position: 101
      prefix: '-range'
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: 'Files written with the output prefix (prefix_ro2_info.list and others)'
    outputBinding:
      glob: $((inputs.prefix || 'out') + '*')
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ciri-full:2.1.2--hdfd78af_1
stdout: ciri-full_RO2.out
