cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - CIRI
label: ciri-full_CIRI
doc: "CIRI2 (circRNA identifier2): identifies circRNAs from a BWA-MEM SAM file\n\nTool homepage: https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html"
inputs:
  - id: in_sam
    type: File
    doc: 'input SAM file name (required; generated by BWA-MEM)'
    inputBinding:
      position: 101
      prefix: '-I'
  - id: out
    type: string
    doc: 'output circRNA list name (required)'
    inputBinding:
      position: 101
      prefix: '-O'
  - id: ref_file
    type:
      - 'null'
      - File
    doc: 'FASTA file of all reference sequences. Please make sure this file is the same one provided to BWA-MEM. Either this argument or -R/--ref-dir is required.'
    inputBinding:
      position: 101
      prefix: '-F'
  - id: ref_dir
    type:
      - 'null'
      - Directory
    doc: 'directory of reference sequence(s). Please make sure fasta files in this directory are from the FASTA file(s) provided to BWA-MEM. Either this argument or -F/--ref-file is required.'
    inputBinding:
      position: 101
      prefix: '-R'
  - id: anno
    type:
      - 'null'
      - File
    doc: 'input GTF/GFF3 formatted annotation file name (optional)'
    inputBinding:
      position: 101
      prefix: '-A'
  - id: log
    type:
      - 'null'
      - string
    doc: 'output log file name (optional)'
    inputBinding:
      position: 101
      prefix: '-G'
  - id: max_span
    type:
      - 'null'
      - int
    doc: 'max spanning distance of circRNAs (default: 200000)'
    inputBinding:
      position: 101
      prefix: '-S'
  - id: high_strigency
    type:
      - 'null'
      - boolean
    doc: 'use high strigency: only output circRNAs supported by more than 2 distinct PCC signals (default)'
    inputBinding:
      position: 101
      prefix: '-high'
  - id: low_strigency
    type:
      - 'null'
      - boolean
    doc: 'use low strigency: only output circRNAs supported by more than 2 junction reads'
    inputBinding:
      position: 101
      prefix: '-low'
  - id: no_strigency
    type:
      - 'null'
      - boolean
    doc: 'output all circRNAs regardless junction read or PCC signal counts'
    inputBinding:
      position: 101
      prefix: '-0'
  - id: mapq_uni
    type:
      - 'null'
      - int
    doc: 'set threshold for mappqing quality of each segment of junction reads (default: 10; should be within [0,30])'
    inputBinding:
      position: 101
      prefix: '-U'
  - id: rel_exp
    type:
      - 'null'
      - float
    doc: 'set threshold for relative expression calculated based on counts of junction reads and non-junction reads (optional: e.g. 0.1)'
    inputBinding:
      position: 101
      prefix: '-E'
  - id: chrM
    type:
      - 'null'
      - string
    doc: 'tell CIRI2 the ID of mitochondrion in reference file(s) (default: chrM)'
    inputBinding:
      position: 101
      prefix: '-M'
  - id: thread_num
    type:
      - 'null'
      - int
    doc: 'set number of threads for parallel running (default: 1)'
    inputBinding:
      position: 101
      prefix: '-T'
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: 'keep quiet when running'
    inputBinding:
      position: 101
      prefix: '-Q'
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: ciri_output
    type: File
    doc: 'circRNA list'
    outputBinding:
      glob: $(inputs.out)
  - id: log_file
    type:
      - 'null'
      - File
    doc: 'log file'
    outputBinding:
      glob: $(inputs.log)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ciri-full:2.1.2--hdfd78af_1
stdout: ciri-full_CIRI.out
