cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - CIRI-full
  - Merge
label: ciri-full_Merge
doc: "The Merge module combines the result of RO2 and CIRI-AS to reconstruct full-length circRNAs\n\nTool homepage: https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html"
inputs:
  - id: ciri
    type: File
    doc: 'output file of CIRI (required)'
    inputBinding:
      position: 101
      prefix: '-c'
  - id: as_list
    type: File
    doc: 'all processing info of CIRI-AS output file (CIRI-AS run with -D yes; the _jav.list file) (required)'
    inputBinding:
      position: 101
      prefix: '-as'
  - id: ro
    type: File
    doc: 'RO read information file generated by RO2 module (required)'
    inputBinding:
      position: 101
      prefix: '-ro'
  - id: prefix
    type: string
    doc: 'output prefix of Merge module (required)'
    inputBinding:
      position: 101
      prefix: '-o'
  - id: reference
    type: File
    doc: 'reference genome in fasta format (required)'
    inputBinding:
      position: 101
      prefix: '-r'
  - id: annotation
    type:
      - 'null'
      - File
    doc: 'annotation file of reference genome in GTF format (optional)'
    inputBinding:
      position: 101
      prefix: '-a'
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: output_files
    type:
      type: array
      items: File
    doc: 'Files written with the output prefix'
    outputBinding:
      glob: $(inputs.prefix)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ciri-full:2.1.2--hdfd78af_1
stdout: ciri-full_Merge.out
