cwlVersion: v1.2
class: CommandLineTool
baseCommand: crux param-medic
label: crux_param-medic
doc: "Parse fragmentation spectra to estimate measurement error.\n\nTool homepage:
  https://github.com/redbadger/crux"
inputs:
  - id: spectrum_file
    type:
      type: array
      items: File
    doc: File from which to parse fragmentation spectra.
    inputBinding:
      position: 1
  - id: pm_charge
    type:
      - 'null'
      - int
    doc: Precursor charge state to consider MS/MS spectra from, in measurement 
      error estimation. Ideally, this should be the most frequently occurring 
      charge state in the given data.
    default: 2
    inputBinding:
      position: 102
      prefix: --pm-charge
  - id: pm_max_frag_mz
    type:
      - 'null'
      - float
    doc: Maximum fragment m/z value to use in measurement error estimation.
    default: 1800.0
    inputBinding:
      position: 102
      prefix: --pm-max-frag-mz
  - id: pm_max_precursor_delta_ppm
    type:
      - 'null'
      - float
    doc: Maximum ppm distance between precursor m/z values to consider two scans
      potentially generated by the same peptide for measurement error 
      estimation.
    default: 50.0
    inputBinding:
      position: 102
      prefix: --pm-max-precursor-delta-ppm
  - id: pm_max_precursor_mz
    type:
      - 'null'
      - float
    doc: Minimum precursor m/z value to use in measurement error estimation.
    default: 1800.0
    inputBinding:
      position: 102
      prefix: --pm-max-precursor-mz
  - id: pm_max_scan_separation
    type:
      - 'null'
      - int
    doc: Maximum number of scans two spectra can be separated by in order to be 
      considered potentially generated by the same peptide, for measurement 
      error estimation.
    default: 1000
    inputBinding:
      position: 102
      prefix: --pm-max-scan-separation
  - id: pm_min_common_frag_peaks
    type:
      - 'null'
      - int
    doc: Number of the most-intense peaks that two spectra must share in order 
      to potentially be generated by the same peptide, for measurement error 
      estimation.
    default: 20
    inputBinding:
      position: 102
      prefix: --pm-min-common-frag-peaks
  - id: pm_min_frag_mz
    type:
      - 'null'
      - float
    doc: Minimum fragment m/z value to use in measurement error estimation.
    default: 150.0
    inputBinding:
      position: 102
      prefix: --pm-min-frag-mz
  - id: pm_min_peak_pairs
    type:
      - 'null'
      - int
    doc: Minimum number of peak pairs (for precursor or fragment) that must be 
      successfully paired in order to attempt to estimate measurement error 
      distribution.
    default: 100
    inputBinding:
      position: 102
      prefix: --pm-min-peak-pairs
  - id: pm_min_precursor_mz
    type:
      - 'null'
      - float
    doc: Minimum precursor m/z value to use in measurement error estimation.
    default: 400.0
    inputBinding:
      position: 102
      prefix: --pm-min-precursor-mz
  - id: pm_min_scan_frag_peaks
    type:
      - 'null'
      - int
    doc: Minimum fragment peaks an MS/MS scan must contain to be used in 
      measurement error estimation.
    default: 40
    inputBinding:
      position: 102
      prefix: --pm-min-scan-frag-peaks
  - id: pm_pair_top_n_frag_peaks
    type:
      - 'null'
      - int
    doc: Number of fragment peaks per spectrum pair to be used in fragment error
      estimation.
    default: 5
    inputBinding:
      position: 102
      prefix: --pm-pair-top-n-frag-peaks
  - id: pm_top_n_frag_peaks
    type:
      - 'null'
      - int
    doc: Number of most-intense fragment peaks to consider for measurement error
      estimation, per MS/MS spectrum.
    default: 30
    inputBinding:
      position: 102
      prefix: --pm-top-n-frag-peaks
  - id: spectrum_parser
    type:
      - 'null'
      - string
    doc: Specify the parser to use for reading in MS/MS spectra.
    default: pwiz
    inputBinding:
      position: 102
      prefix: --spectrum-parser
  - id: verbosity
    type:
      - 'null'
      - int
    doc: 'Specify the verbosity of the current processes. Each level prints the following
      messages, including all those at lower verbosity levels: 0-fatal errors, 10-non-fatal
      errors, 20-warnings, 30-information on the progress of execution, 40-more progress
      information, 50-debug info, 60-detailed debug info.'
    default: 30
    inputBinding:
      position: 102
      prefix: --verbosity
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: biocontainers/crux:v3.2_cv3
stdout: crux_param-medic.out
