cwlVersion: v1.2
class: CommandLineTool
baseCommand: percolator
label: crux_percolator
doc: "Percolator is a widely used tool for the statistical validation and rescoring
  of peptide identification results from mass spectrometry.\n\nTool homepage: https://github.com/redbadger/crux"
inputs:
  - id: input_pin_file
    type: File
    doc: 'The tab delimited output file generated by e.g. sqt2pin. The tab delimited
      fields should be: id <tab> label <tab> scannr <tab> feature1 <tab> ... <tab>
      featureN <tab> peptide <tab> proteinId1 <tab> .. <tab> proteinIdM. Labels are
      interpreted as 1 -- positive set and test set, -1 -- negative set.'
    inputBinding:
      position: 1
  - id: Cneg
    type:
      - 'null'
      - float
    doc: Cneg, penalty for mistakes made on negative examples. Set by cross 
      validation if not specified or if -p is not specified.
    inputBinding:
      position: 102
      prefix: --Cneg
  - id: Cpos
    type:
      - 'null'
      - float
    doc: Cpos, penalty for mistakes made on positive examples. Set by cross 
      validation if not specified.
    inputBinding:
      position: 102
      prefix: --Cpos
  - id: decoy_xml_output
    type:
      - 'null'
      - boolean
    doc: Include decoys (PSMs, peptides and/or proteins) in the xml-output. Only
      available if -X is set.
    inputBinding:
      position: 102
      prefix: --decoy-xml-output
  - id: default_direction
    type:
      - 'null'
      - string
    doc: Use given feature name as initial search direction, can be negated to 
      indicate that a lower value is better.
    inputBinding:
      position: 102
      prefix: --default-direction
  - id: doc
    type:
      - 'null'
      - boolean
    doc: Include description of correct features, i.e. features describing the 
      difference between the observed and predicted isoelectric point, retention
      time and precursor mass.
    inputBinding:
      position: 102
      prefix: --doc
  - id: fido_alpha
    type:
      - 'null'
      - float
    doc: Set Fido's probability with which a present protein emits an associated
      peptide. Set by grid search if not specified.
    inputBinding:
      position: 102
      prefix: --fido-alpha
  - id: fido_beta
    type:
      - 'null'
      - float
    doc: Set Fido's probability of creation of a peptide from noise. Set by grid
      search if not specified.
    inputBinding:
      position: 102
      prefix: --fido-beta
  - id: fido_empirical_protein_q
    type:
      - 'null'
      - boolean
    doc: Output empirical p-values and q-values for Fido using target-decoy 
      analysis to XML output (only valid if -X flag is present).
    inputBinding:
      position: 102
      prefix: --fido-empirical-protein-q
  - id: fido_fast_gridsearch
    type:
      - 'null'
      - float
    doc: Apply the specified threshold to PSM, peptide and protein probabilities
      to obtain a faster estimate of the alpha, beta and gamma parameters. 
      Default = 0; Recommended when set = 0.2.
    inputBinding:
      position: 102
      prefix: --fido-fast-gridsearch
  - id: fido_gamma
    type:
      - 'null'
      - float
    doc: Set Fido's prior probability that a protein is present in the sample. 
      Set by grid search if not specified.
    inputBinding:
      position: 102
      prefix: --fido-gamma
  - id: fido_gridsearch_depth
    type:
      - 'null'
      - int
    doc: Setting the gridsearch-depth to 0 (fastest), 1 or 2 (slowest) controls 
      how much computational time is required for the estimation of alpha, beta 
      and gamma parameters for Fido. Default = 0.
    inputBinding:
      position: 102
      prefix: --fido-gridsearch-depth
  - id: fido_gridsearch_mse_threshold
    type:
      - 'null'
      - float
    doc: Q-value threshold that will be used in the computation of the MSE and 
      ROC AUC score in the grid search. Recommended 0.05 for normal size 
      datasets and 0.1 for large datasets.
    inputBinding:
      position: 102
      prefix: --fido-gridsearch-mse-threshold
  - id: fido_no_split_large_components
    type:
      - 'null'
      - boolean
    doc: Do not approximate the posterior distribution by allowing large graph 
      components to be split into subgraphs. The splitting is done by 
      duplicating peptides with low probabilities. Splitting continues until the
      number of possible configurations of each subgraph is below 2^18.
    inputBinding:
      position: 102
      prefix: --fido-no-split-large-components
  - id: fido_protein
    type:
      - 'null'
      - boolean
    doc: Use the Fido algorithm to infer protein probabilities
    inputBinding:
      position: 102
      prefix: --fido-protein
  - id: fido_protein_truncation_threshold
    type:
      - 'null'
      - float
    doc: To speed up inference, proteins for which none of the associated 
      peptides has a probability exceeding the specified threshold will be 
      assigned probability = 0.
    inputBinding:
      position: 102
      prefix: --fido-protein-truncation-threshold
  - id: init_weights_file
    type:
      - 'null'
      - File
    doc: Read initial weights from given file (one per line)
    inputBinding:
      position: 102
      prefix: --init-weights
  - id: klammer
    type:
      - 'null'
      - boolean
    doc: Retention time features are calculated as in Klammer et al. Only 
      available if -D is set.
    inputBinding:
      position: 102
      prefix: --klammer
  - id: maxiter
    type:
      - 'null'
      - int
    doc: Maximal number of iterations.
    inputBinding:
      position: 102
      prefix: --maxiter
  - id: nested_xval_bins
    type:
      - 'null'
      - int
    doc: Number of nested cross validation bins within each cross validation 
      bin. This should reduce overfitting of the hyperparameters.
    inputBinding:
      position: 102
      prefix: --nested-xval-bins
  - id: no_schema_validation
    type:
      - 'null'
      - boolean
    doc: Skip validation of input file against xml schema.
    inputBinding:
      position: 102
      prefix: --no-schema-validation
  - id: no_terminate
    type:
      - 'null'
      - boolean
    doc: Do not stop execution when encountering questionable SVM inputs or 
      results.
    inputBinding:
      position: 102
      prefix: --no-terminate
  - id: only_psms
    type:
      - 'null'
      - boolean
    doc: Do not remove redundant peptides, keep all PSMS and exclude peptide 
      level probabilities.
    inputBinding:
      position: 102
      prefix: --only-psms
  - id: override
    type:
      - 'null'
      - boolean
    doc: Override error check and do not fall back on default score vector in 
      case of suspect score vector from SVM.
    inputBinding:
      position: 102
      prefix: --override
  - id: parameter_file
    type:
      - 'null'
      - File
    doc: Read flags from a parameter file. If flags are specified on the command
      line as well, these will override the ones in the parameter file.
    inputBinding:
      position: 102
      prefix: --parameter-file
  - id: picked_protein_fasta
    type:
      - 'null'
      - File
    doc: Use the picked protein-level FDR to infer protein probabilities. 
      Provide the fasta file as the argument to this flag, which will be used 
      for protein grouping based on an in-silico digest. If no fasta file is 
      available or protein grouping is not desired, set this flag to "auto" to 
      skip protein grouping.
    inputBinding:
      position: 102
      prefix: --picked-protein
  - id: post_processing_mix_max
    type:
      - 'null'
      - boolean
    doc: Use the mix-max method to assign q-values and PEPs. Note that this 
      option only has an effect if the input PSMs are from separate target and 
      decoy searches. This is the default setting.
    inputBinding:
      position: 102
      prefix: --post-processing-mix-max
  - id: post_processing_tdc
    type:
      - 'null'
      - boolean
    doc: Replace the mix-max method by target-decoy competition for assigning 
      q-values and PEPs. If the input PSMs are from separate target and decoy 
      searches, Percolator's SVM scores will be used to eliminate the lower 
      scoring target or decoy PSM(s) of each scan+expMass combination. If the 
      input PSMs are detected to be coming from a concatenated search, this 
      option will be turned on automatically, as this is incompatible with the 
      mix-max method. In case this detection fails, turn this option on 
      explicitly.
    inputBinding:
      position: 102
      prefix: --post-processing-tdc
  - id: protein_decoy_pattern
    type:
      - 'null'
      - string
    doc: Define the text pattern to identify decoy proteins in the database for 
      the picked-protein algorithm. This will have no effect on the target/decoy
      labels specified in the input file.
    inputBinding:
      position: 102
      prefix: --protein-decoy-pattern
  - id: protein_enzyme
    type:
      - 'null'
      - string
    doc: Type of enzyme 
      "no_enzyme","elastase","pepsin","proteinasek","thermolysin","trypsinp","chymotrypsin","lys-n","lys-c","arg-c","asp-n","glu-c","trypsin".
      Default="trypsin".
    inputBinding:
      position: 102
      prefix: --protein-enzyme
  - id: protein_report_duplicates
    type:
      - 'null'
      - boolean
    doc: If this option is set and multiple database proteins contain exactly 
      the same set of peptides, then the IDs of these duplicated proteins will 
      be reported as a comma-separated list, instead of the default behavior of 
      randomly discarding all but one of the proteins. Commas inside protein IDs
      will be replaced by semicolons. Not available for Fido.
    inputBinding:
      position: 102
      prefix: --protein-report-duplicates
  - id: protein_report_fragments
    type:
      - 'null'
      - boolean
    doc: By default, if the peptides associated with protein A are a proper 
      subset of the peptides associated with protein B, then protein A is 
      eliminated and all the peptides are considered as evidence for protein B. 
      Note that this filtering is done based on the complete set of peptides in 
      the database, not based on the identified peptides in the search results. 
      Alternatively, if this option is set and if all of the identified peptides
      associated with protein B are also associated with protein A, then 
      Percolator will report a comma-separated list of protein IDs, where the 
      full-length protein B is first in the list and the fragment protein A is 
      listed second. Commas inside protein IDs will be replaced by semicolons. 
      Not available for Fido.
    inputBinding:
      position: 102
      prefix: --protein-report-fragments
  - id: quick_validation
    type:
      - 'null'
      - boolean
    doc: Quicker execution by reduced internal cross-validation.
    inputBinding:
      position: 102
      prefix: --quick-validation
  - id: search_input
    type:
      - 'null'
      - string
    doc: 'Specify the type of target-decoy search: "auto" (Percolator attempts to
      detect the search type automatically), "concatenated" (single search on concatenated
      target-decoy protein db) or "separate" (two searches, one against target and
      one against decoy protein db).'
    inputBinding:
      position: 102
      prefix: --search-input
  - id: seed
    type:
      - 'null'
      - int
    doc: Set seed of the random number generator.
    inputBinding:
      position: 102
      prefix: --seed
  - id: spectral_counting_fdr
    type:
      - 'null'
      - float
    doc: Activates spectral counting on protein level (either --fido-protein or 
      --picked-protein has to be set) at the specified PSM q-value threshold. 
      Adds two columns, "spec_count_unique" and "spec_count_all", to the protein
      tab separated output, containing the spectral count for the peptides 
      unique to the protein and the spectral count including shared peptides 
      respectively.
    inputBinding:
      position: 102
      prefix: --spectral-counting-fdr
  - id: stdinput_tab
    type:
      - 'null'
      - boolean
    doc: Read percolator tab-input format (pin-tab) from standard input
    inputBinding:
      position: 102
      prefix: --stdinput-tab
  - id: stdinput_xml
    type:
      - 'null'
      - boolean
    doc: Read percolator xml-input format (pin-xml) from standard input
    inputBinding:
      position: 102
      prefix: --stdinput-xml
  - id: subset_max_train
    type:
      - 'null'
      - int
    doc: Only train an SVM on a subset of <x> PSMs, and use the resulting score 
      vector to evaluate the other PSMs. Recommended when analyzing huge numbers
      (>1 million) of PSMs. When set to 0, all PSMs are used for training as 
      normal.
    inputBinding:
      position: 102
      prefix: --subset-max-train
  - id: tab_in_file
    type:
      - 'null'
      - File
    doc: '[set by default] Input file given in pin-tab format. This is the default
      setting, flag only present for backwards compatibility.'
    inputBinding:
      position: 102
      prefix: --tab-in
  - id: testFDR
    type:
      - 'null'
      - float
    doc: False discovery rate threshold for evaluating best cross validation 
      result and reported end result.
    inputBinding:
      position: 102
      prefix: --testFDR
  - id: test_each_iteration
    type:
      - 'null'
      - boolean
    doc: Measure performance on test set each iteration
    inputBinding:
      position: 102
      prefix: --test-each-iteration
  - id: trainFDR
    type:
      - 'null'
      - float
    doc: False discovery rate threshold to define positive examples in training.
      Set to testFDR if 0.
    inputBinding:
      position: 102
      prefix: --trainFDR
  - id: train_best_positive
    type:
      - 'null'
      - boolean
    doc: Enforce that, for each spectrum, at most one PSM is included in the 
      positive set during each training iteration. If the user only provides one
      PSM per spectrum, this filter will have no effect.
    inputBinding:
      position: 102
      prefix: --train-best-positive
  - id: train_fdr_initial
    type:
      - 'null'
      - float
    doc: Set the FDR threshold for the first iteration. This is useful in cases 
      where the original features do not display a good separation between 
      targets and decoys. In subsequent iterations, the normal --trainFDR will 
      be used.
    inputBinding:
      position: 102
      prefix: --train-fdr-initial
  - id: unitnorm
    type:
      - 'null'
      - boolean
    doc: Use unit normalization [0-1] instead of standard deviation 
      normalization
    inputBinding:
      position: 102
      prefix: --unitnorm
  - id: verbose
    type:
      - 'null'
      - int
    doc: 'Set verbosity of output: 0=no processing info, 5=all.'
    inputBinding:
      position: 102
      prefix: --verbose
  - id: xml_in_file
    type:
      - 'null'
      - File
    doc: Input file given in deprecated pin-xml format generated by e.g. sqt2pin
      with the -k option
    inputBinding:
      position: 102
      prefix: --xml-in
outputs:
  - id: xml_output_file
    type:
      - 'null'
      - File
    doc: Path to xml-output (pout) file. pout.xml is where the output will be 
      written (ensure to have read and write access on the file).
    outputBinding:
      glob: $(inputs.xml_output_file)
  - id: tab_out_file
    type:
      - 'null'
      - File
    doc: Output computed features to given file in pin-tab format.
    outputBinding:
      glob: $(inputs.tab_out_file)
  - id: weights_file
    type:
      - 'null'
      - File
    doc: Output final weights to given file
    outputBinding:
      glob: $(inputs.weights_file)
  - id: results_peptides_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results of peptides to a file instead of stdout 
      (will be ignored if used with -U option)
    outputBinding:
      glob: $(inputs.results_peptides_file)
  - id: decoy_results_peptides_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy peptides into a file (will be 
      ignored if used with -U option)
    outputBinding:
      glob: $(inputs.decoy_results_peptides_file)
  - id: results_psms_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results of PSMs to a file instead of stdout
    outputBinding:
      glob: $(inputs.results_psms_file)
  - id: decoy_results_psms_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy PSMs into a file
    outputBinding:
      glob: $(inputs.decoy_results_psms_file)
  - id: results_proteins_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results of proteins to a file instead of stdout 
      (Only valid if option -A or -f is active)
    outputBinding:
      glob: $(inputs.results_proteins_file)
  - id: decoy_results_proteins_file
    type:
      - 'null'
      - File
    doc: Output tab delimited results for decoy proteins into a file (Only valid
      if option -A or -f is active)
    outputBinding:
      glob: $(inputs.decoy_results_proteins_file)
hints:
  - class: DockerRequirement
    dockerPull: biocontainers/crux:v3.2_cv3
