cwlVersion: v1.2
class: CommandLineTool
baseCommand: combine_mpa.py
label: krakentools_combine_mpa.py
doc: "Combine multiple mpa-style reports made by kreport2mpa.py into a single mpa report.\n\nTool homepage: https://github.com/jenniferlu717/KrakenTools"
inputs:
  - id: input_files
    type:
      type: array
      items: File
    doc: "Input files for this program (files generated by kreport2mpa.py)"
    inputBinding:
      position: 1
      prefix: -i
  - id: output_file_path
    type: string
    doc: "Single mpa-report file name"
    inputBinding:
      position: 102
      prefix: -o
outputs:
  - id: output_file
    type: File
    doc: "Combined mpa report"
    outputBinding:
      glob: $(inputs.output_file_path)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/krakentools:1.2.1--pyh7e72e81_0
