cwlVersion: v1.2
class: CommandLineTool
baseCommand: suvtk_comments
label: suvtk_comments
doc: "Generate a structured comment file based on MIUVIG standards.\n\nTool homepage:
  https://github.com/LanderDC/suvtk"
inputs:
  - id: assembly
    type: File
    doc: TSV file with Genbank Assembly information.
    inputBinding:
      position: 101
      prefix: --assembly
  - id: checkv
    type:
      - 'null'
      - File
    doc: CheckV's quality_summary.tsv file.
    inputBinding:
      position: 101
      prefix: --checkv
  - id: features
    type: File
    doc: MIUVIG TSV file generated by the `features` subcommand.
    inputBinding:
      position: 101
      prefix: --features
  - id: miuvig
    type: File
    doc: TSV file with MIUVIG information.
    inputBinding:
      position: 101
      prefix: --miuvig
  - id: taxonomy
    type: File
    doc: MIUVIG TSV file generated by the `taxonomy` or `segment-info` 
      subcommand.
    inputBinding:
      position: 101
      prefix: --taxonomy
outputs:
  - id: output
    type: File
    doc: Output filename.
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/suvtk:0.1.6--pyh64700be_0
