cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - run_midas.py
  - genes
label: midas_run_midas_genes
doc: "Map metagenomic reads to bacterial pangenomes and quantify these genes in your data.\n\nTool homepage:\
  \ https://github.com/snayfach/MIDAS"
inputs:
  - id: remove_temp
    type:
      - 'null'
      - boolean
    doc: Remove intermediate files generated by MIDAS (False). Useful to reduce disk space of MIDAS output.
    inputBinding:
      position: 101
      prefix: --remove_temp
  - id: build_db
    type:
      - 'null'
      - boolean
    doc: Build bowtie2 database of pangenomes.
    inputBinding:
      position: 101
      prefix: --build_db
  - id: align
    type:
      - 'null'
      - boolean
    doc: Align reads to pangenome database.
    inputBinding:
      position: 101
      prefix: --align
  - id: call_genes
    type:
      - 'null'
      - boolean
    doc: Compute coverage of genes in pangenome database.
    inputBinding:
      position: 101
      prefix: --call_genes
  - id: db
    type:
      - 'null'
      - Directory
    doc: Path to reference database. By default, the MIDAS_DB environmental variable is used.
    inputBinding:
      position: 101
      prefix: -d
  - id: species_cov
    type:
      - 'null'
      - float
    doc: Include species with >X coverage (3.0).
    inputBinding:
      position: 101
      prefix: --species_cov
  - id: species_topn
    type:
      - 'null'
      - int
    doc: Include top N most abundant species.
    inputBinding:
      position: 101
      prefix: --species_topn
  - id: species_id
    type:
      - 'null'
      - string
    doc: Include specified species. Separate ids with a comma.
    inputBinding:
      position: 101
      prefix: --species_id
  - id: m1
    type:
      - 'null'
      - File
    doc: FASTA/FASTQ file containing 1st mate if using paired-end reads. Otherwise FASTA/FASTQ containing
      unpaired reads. Can be gzip'ed or bzip2'ed.
    inputBinding:
      position: 101
      prefix: '-1'
  - id: m2
    type:
      - 'null'
      - File
    doc: FASTA/FASTQ file containing 2nd mate if using paired-end reads. Can be gzip'ed or bzip2'ed.
    inputBinding:
      position: 101
      prefix: '-2'
  - id: interleaved
    type:
      - 'null'
      - boolean
    doc: FASTA/FASTQ file in -1 are paired and contain forward AND reverse reads.
    inputBinding:
      position: 101
      prefix: --interleaved
  - id: speed
    type:
      - 'null'
      - string
    doc: 'Alignment speed/sensitivity: very-fast, fast, sensitive or very-sensitive (very-sensitive).'
    inputBinding:
      position: 101
      prefix: -s
  - id: mode
    type:
      - 'null'
      - string
    doc: 'Global/local read alignment: local or global (local).'
    inputBinding:
      position: 101
      prefix: -m
  - id: max_reads
    type:
      - 'null'
      - int
    doc: Number of reads to use from input file(s) (use all).
    inputBinding:
      position: 101
      prefix: -n
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use (1).
    inputBinding:
      position: 101
      prefix: -t
  - id: readq
    type:
      - 'null'
      - int
    doc: Discard reads with mean quality < READQ (20).
    inputBinding:
      position: 101
      prefix: --readq
  - id: mapid
    type:
      - 'null'
      - float
    doc: Discard reads with alignment identity < MAPID (94.0).
    inputBinding:
      position: 101
      prefix: --mapid
  - id: aln_cov
    type:
      - 'null'
      - float
    doc: Discard reads with alignment coverage < ALN_COV (0.75).
    inputBinding:
      position: 101
      prefix: --aln_cov
  - id: trim
    type:
      - 'null'
      - int
    doc: Trim N base-pairs from 3'/right end of read (0).
    inputBinding:
      position: 101
      prefix: --trim
  - id: outdir
    type: string
    doc: Path to directory to store results. Directory name should correspond to sample identifier.
    inputBinding:
      position: 201
outputs:
  - id: out_dir
    type: Directory
    doc: Output directory with the results.
    outputBinding:
      glob: $(inputs.outdir)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/midas:1.3.2--py35_0
