cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - run_midas.py
  - species
label: midas_run_midas_species
doc: "Map reads to a database of phylogenetic marker genes and estimate species abundance.\n\nTool homepage:\
  \ https://github.com/snayfach/MIDAS"
inputs:
  - id: m1
    type:
      - 'null'
      - File
    doc: FASTA/FASTQ file containing 1st mate if using paired-end reads. Otherwise FASTA/FASTQ containing
      unpaired reads. Can be gzip'ed or bzip2'ed.
    inputBinding:
      position: 101
      prefix: '-1'
  - id: m2
    type:
      - 'null'
      - File
    doc: FASTA/FASTQ file containing 2nd mate if using paired-end reads. Can be gzip'ed or bzip2'ed.
    inputBinding:
      position: 101
      prefix: '-2'
  - id: max_reads
    type:
      - 'null'
      - int
    doc: Number of reads to use from input file(s) (use all).
    inputBinding:
      position: 101
      prefix: -n
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads to use for database search (1).
    inputBinding:
      position: 101
      prefix: -t
  - id: db
    type:
      - 'null'
      - Directory
    doc: Path to reference database. By default, the MIDAS_DB environmental variable is used.
    inputBinding:
      position: 101
      prefix: -d
  - id: remove_temp
    type:
      - 'null'
      - boolean
    doc: Remove intermediate files generated by MIDAS (False). Useful to reduce disk space of MIDAS output.
    inputBinding:
      position: 101
      prefix: --remove_temp
  - id: word_size
    type:
      - 'null'
      - int
    doc: Word size for BLAST search (28). Use word sizes > 16 for greatest efficiency.
    inputBinding:
      position: 101
      prefix: --word_size
  - id: mapid
    type:
      - 'null'
      - float
    doc: Discard reads with alignment identity < MAPID. By default gene-specific species-level cutoffs
      are used. Values between 0-100 accepted.
    inputBinding:
      position: 101
      prefix: --mapid
  - id: aln_cov
    type:
      - 'null'
      - float
    doc: Discard reads with alignment coverage < ALN_COV (0.75). Values between 0-1 accepted.
    inputBinding:
      position: 101
      prefix: --aln_cov
  - id: read_length
    type:
      - 'null'
      - int
    doc: Trim reads to READ_LENGTH and discard reads with length < READ_LENGTH. By default, reads are
      not trimmed or filtered.
    inputBinding:
      position: 101
      prefix: --read_length
  - id: outdir
    type: string
    doc: Path to directory to store results. Directory name should correspond to sample identifier.
    inputBinding:
      position: 201
outputs:
  - id: out_dir
    type: Directory
    doc: Output directory with the results.
    outputBinding:
      glob: $(inputs.outdir)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/midas:1.3.2--py35_0
