cwlVersion: v1.2
class: CommandLineTool
baseCommand: extract_gubbins_clade.py
label: gubbins_extract_gubbins_clade
doc: "Extract a clade from a Gubbins output\n\nTool homepage: https://github.com/nickjcroucher/gubbins"
inputs:
  - id: list_file
    type: File
    doc: "List of sequences to extract"
    inputBinding:
      position: 101
      prefix: --list
  - id: aln
    type: File
    doc: "Input alignment (FASTA format)"
    inputBinding:
      position: 102
      prefix: --aln
  - id: gff
    type: File
    doc: "GFF of recombinant regions detected by Gubbins"
    inputBinding:
      position: 103
      prefix: --gff
  - id: tree
    type: File
    doc: "Final tree generated by Gubbins"
    inputBinding:
      position: 104
      prefix: --tree
  - id: out
    type: string
    doc: "Output file prefix"
    inputBinding:
      position: 105
      prefix: --out
  - id: out_fmt
    type:
      - 'null'
      - string
    doc: "Format of output alignment"
    inputBinding:
      position: 106
      prefix: --out-fmt
  - id: missing_char
    type:
      - 'null'
      - string
    doc: "Character used to replace recombinant sequence"
    inputBinding:
      position: 107
      prefix: --missing-char
outputs:
  - id: clade_files
    type:
      type: array
      items: File
    doc: "Files written for the extracted clade"
    outputBinding:
      glob: $(inputs.out)*
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/gubbins:3.4.3--py39h746d604_0
