cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ExtractCogs.py
label: desman_ExtractCogs.py
doc: "Assign COGs to genes from tabular RPS-BLAST output against the COG
  database and print the COG, contig, start, end, gene and strand of each hit
  that passes the coverage and identity thresholds.\n\nTool homepage: https://github.com/chrisquince/DESMAN"
inputs:
  - id: blastoutfile
    type: File
    doc: 'Output of rpsblast run, assumed to be in tabular format whith columns: 
      qseqid sseqid evalue pident score qstart qend sstart send length slen.'
    inputBinding:
      position: 1
      prefix: -b
  - id: scovs_threshold
    type:
      - 'null'
      - float
    doc: Threshold covered in percent, default=50.0
    inputBinding:
      position: 1
      prefix: -s
  - id: pident_threshold
    type:
      - 'null'
      - float
    doc: Threshold identity in percent, default=0.0
    inputBinding:
      position: 1
      prefix: -p
  - id: cdd_cog_file
    type:
      - 'null'
      - File
    doc: Supply a cdd to cog mapping file in a tsv format to take precedence 
      over eutils fetching of name.
    inputBinding:
      position: 1
      prefix: --cdd_cog_file
  - id: gfffile
    type:
      - 'null'
      - File
    doc: GFF file generated by e.g. prodigal only needed if the contig names are
      not recoverable from the blast output file.
    inputBinding:
      position: 1
      prefix: -g
  - id: output_name
    type: string
    doc: Name of the file that receives the COG table written to stdout
    default: cogs.csv
outputs:
  - id: cogs
    type: File
    doc: COG assignments (CSV)
    outputBinding:
      glob: $(inputs.output_name)
stdout: $(inputs.output_name)
requirements:
  - class: NetworkAccess
    networkAccess: true
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/desman:2.1--py39h4747326_10
