cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ExtractGenes.py
label: desman_ExtractGenes.py
doc: "Write the gene positions (gene_id,contig,start,end,strand) of the gene,
  mRNA and CDS features longer than 100 bp in a Prodigal or Prokka GFF file, in
  the gene file format used by ExtractCountFreqGenes.py -g.\n\nTool homepage: https://github.com/chrisquince/DESMAN"
inputs:
  - id: gfffile
    type: File
    doc: GFF file generated by e.g. prodigal
    inputBinding:
      position: 1
      prefix: -g
  - id: output_name
    type: string
    doc: Name of the file that receives the gene table written to stdout
    default: genes.csv
outputs:
  - id: genes
    type: File
    doc: Gene positions (CSV without header)
    outputBinding:
      glob: $(inputs.output_name)
stdout: $(inputs.output_name)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/desman:2.1--py39h4747326_10
