cwlVersion: v1.2
class: CommandLineTool
baseCommand: ervmancer
label: ervmancer
doc: "ervmancer\n\nTool homepage: https://github.com/AuslanderLab/ervmancer"
inputs:
  - id: advanced
    type:
      - 'null'
      - File
    doc: User provided absolute path to CSV file with user-provided read counts 
      from other methods.
    inputBinding:
      position: 101
      prefix: --advanced
  - id: bowtie_index
    type:
      - 'null'
      - Directory
    doc: Absolute path to the Bowtie2 index to be used for processing. If not 
      provided, uses the built-in GRCh38_noalt_as index.
    inputBinding:
      position: 101
      prefix: --bowtie_index
  - id: bt2
    type:
      - 'null'
      - File
    doc: User provided absolute path to self provided bowtie2 alignment file.
    inputBinding:
      position: 101
      prefix: --bt2
  - id: keep_files
    type:
      - 'null'
      - boolean
    doc: Keeps intermediate outputs from Samtools and Bedtools.
    inputBinding:
      position: 101
      prefix: --keep_files
  - id: kmer_dict
    type:
      - 'null'
      - File
    doc: Absolute path to the kmer dictionary file 
      (clean_kmer_31_60_percent_cutoff.pkl).
    inputBinding:
      position: 101
      prefix: --kmer_dict
  - id: num_cores
    type:
      - 'null'
      - int
    doc: Number of CPU cores used for processing.
    inputBinding:
      position: 101
      prefix: --num_cores
  - id: r1
    type:
      - 'null'
      - File
    doc: Absolute path to paired-end R1 fastq file. A file is also needed for 
      normalization
    inputBinding:
      position: 101
      prefix: --r1
  - id: r2
    type:
      - 'null'
      - File
    doc: Absolute path to paired-end R2 fastq file.
    inputBinding:
      position: 101
      prefix: --r2
  - id: s1
    type:
      - 'null'
      - File
    doc: Absolute path to single strand S1 fastq file.
    inputBinding:
      position: 101
      prefix: --s1
outputs:
  - id: output_dir
    type: Directory
    doc: Absolute path to base output directory for CSV output and intermediate 
      files. (Output folders are autogenerated if they do not exist already!)
    outputBinding:
      glob: $(inputs.output_dir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ervmancer:0.0.4--pyhdfd78af_0
