cwlVersion: v1.2
class: CommandLineTool
baseCommand: nanostat
label: nanostat
doc: "Calculate statistics of Oxford Nanopore sequencing data.\n\nTool homepage: https://github.com/wdecoster/nanostat"
inputs:
  - id: bam
    type:
      - 'null'
      - type: array
        items: File
    doc: Input bam file(s).
    inputBinding:
      position: 101
      prefix: --bam
  - id: barcoded
    type:
      - 'null'
      - boolean
    doc: The input is barcoded.
    inputBinding:
      position: 101
      prefix: --barcoded
  - id: cram
    type:
      - 'null'
      - type: array
        items: File
    doc: Input cram file(s).
    inputBinding:
      position: 101
      prefix: --cram
  - id: dataset_name
    type:
      - 'null'
      - string
    doc: Specify a name for the dataset, to be used in the output file.
    inputBinding:
      position: 101
      prefix: --name
  - id: fasta
    type:
      - 'null'
      - type: array
        items: File
    doc: Input fasta file(s).
    inputBinding:
      position: 101
      prefix: --fasta
  - id: fastq
    type:
      - 'null'
      - type: array
        items: File
    doc: Input fastq file(s).
    inputBinding:
      position: 101
      prefix: --fastq
  - id: no_progress
    type:
      - 'null'
      - boolean
    doc: Do not show progress bar.
    inputBinding:
      position: 101
      prefix: --no-progress
  - id: prefix
    type:
      - 'null'
      - string
    doc: Specify an optional prefix for the output file.
    inputBinding:
      position: 101
      prefix: --prefix
  - id: readtype
    type:
      - 'null'
      - string
    doc: Specify the read type (1D, 2D, or 1D2).
    inputBinding:
      position: 101
      prefix: --readtype
  - id: summary
    type:
      - 'null'
      - type: array
        items: File
    doc: Input summary file(s) generated by Albacore or Guppy.
    inputBinding:
      position: 101
      prefix: --summary
  - id: threads
    type:
      - 'null'
      - int
    doc: Set the allowed number of threads to be used by the script
    inputBinding:
      position: 101
      prefix: --threads
  - id: ubam
    type:
      - 'null'
      - type: array
        items: File
    doc: Input unaligned bam file(s).
    inputBinding:
      position: 101
      prefix: --ubam
outputs:
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: Specify the output directory.
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/nanostat:1.6.0--pyhdfd78af_0
