cwlVersion: v1.2
class: CommandLineTool
baseCommand: caspeak_peak
label: caspeak_peak
doc: "Detects peaks of mobile element insertions in sequencing data.\n\nTool homepage:
  https://github.com/Rye-lxy/CasPeak"
inputs:
  - id: bedtools_genome
    type:
      - 'null'
      - string
    doc: genome data for bedtools
    inputBinding:
      position: 101
      prefix: --bedtools-genome
  - id: exog
    type:
      - 'null'
      - boolean
    doc: set the insertion exogenous
    inputBinding:
      position: 101
      prefix: --exog
  - id: genome_maf
    type:
      - 'null'
      - File
    doc: alignment to the genome
    inputBinding:
      position: 101
      prefix: --genome-maf
  - id: insert_file
    type: File
    doc: consensus sequence of the MEI FASTA file
    inputBinding:
      position: 101
      prefix: --insert
  - id: insert_maf
    type:
      - 'null'
      - File
    doc: alignment to the insertion sequence
    inputBinding:
      position: 101
      prefix: --insert-maf
  - id: mask
    type:
      - 'null'
      - File
    doc: rmsk file on the reference genome generated by RepeatMasker
    inputBinding:
      position: 101
      prefix: --mask
  - id: max_prop
    type:
      - 'null'
      - float
    doc: maximum proportion of the read aligned to the reference genome
    inputBinding:
      position: 101
      prefix: --max-prop
  - id: max_trim_length
    type:
      - 'null'
      - int
    doc: maximum length of the adaptor to be trimmed
    inputBinding:
      position: 101
      prefix: --max-trim-length
  - id: min_cov
    type:
      - 'null'
      - int
    doc: minimum coverage for a peak
    inputBinding:
      position: 101
      prefix: --min-cov
  - id: min_prop
    type:
      - 'null'
      - float
    doc: minimum proportion of the read aligned to the reference genome
    inputBinding:
      position: 101
      prefix: --min-prop
  - id: min_read_length
    type:
      - 'null'
      - int
    doc: minimum read length
    inputBinding:
      position: 101
      prefix: --min-read-length
  - id: padding
    type:
      - 'null'
      - int
    doc: padding for the target region
    inputBinding:
      position: 101
      prefix: --padding
  - id: read_file
    type: File
    doc: the read FASTA/FATSQ file
    inputBinding:
      position: 101
      prefix: --read
  - id: ref_file
    type: File
    doc: the reference genome FASTA file
    inputBinding:
      position: 101
      prefix: --ref
  - id: target_end
    type: string
    doc: end position of the target in the insert sequence
    inputBinding:
      position: 101
      prefix: --target-end
  - id: target_start
    type: string
    doc: start position of the target in the insert sequence
    inputBinding:
      position: 101
      prefix: --target-start
  - id: thread
    type:
      - 'null'
      - int
    doc: number of threads
    inputBinding:
      position: 101
      prefix: --thread
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: show progress messages and data
    inputBinding:
      position: 101
      prefix: --verbose
  - id: workdir
    type:
      - 'null'
      - Directory
    doc: working directory
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/caspeak:1.1.5--pyhdfd78af_0
stdout: caspeak_peak.out
