cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - caspeak
  - exec
label: caspeak_exec
doc: "Execute the CASpeak pipeline for detecting mobile element insertions.\n\nTool
  homepage: https://github.com/Rye-lxy/CasPeak"
inputs:
  - id: bedtools_genome
    type:
      - 'null'
      - File
    doc: 'genome data for bedtools (default: hg38 file in bedtools)'
    inputBinding:
      position: 101
      prefix: --bedtools-genome
  - id: exog
    type:
      - 'null'
      - boolean
    doc: set the insertion exogenous
    inputBinding:
      position: 101
      prefix: --exog
  - id: insert_file
    type: File
    doc: consensus sequence of the MEI FASTA file (required)
    inputBinding:
      position: 101
      prefix: --insert
  - id: lib
    type:
      - 'null'
      - File
    doc: the library (a set of closely related sequences) used to distinguish 
      true insertion from these related sequences
    inputBinding:
      position: 101
      prefix: --lib
  - id: mask_rmsk
    type:
      - 'null'
      - File
    doc: rmsk file on the reference genome generated by RepeatMasker
    inputBinding:
      position: 101
      prefix: --mask
  - id: max_prop
    type:
      - 'null'
      - float
    doc: 'maximum proportion of the read aligned to the reference genome (default:
      1)'
    inputBinding:
      position: 101
      prefix: --max-prop
  - id: max_trim_length
    type:
      - 'null'
      - int
    doc: 'maximum length of the adaptor to be trimmed (default: 100)'
    inputBinding:
      position: 101
      prefix: --max-trim-length
  - id: min_asb_seq
    type:
      - 'null'
      - int
    doc: 'minimum number of assembled sequences (default: 1)'
    inputBinding:
      position: 101
      prefix: --min-asb-seq
  - id: min_cov
    type:
      - 'null'
      - int
    doc: 'minimum coverage for a peak (default: 2)'
    inputBinding:
      position: 101
      prefix: --min-cov
  - id: min_inslen
    type:
      - 'null'
      - int
    doc: 'minimum length of the MEI in the insert sequence (default: 80)'
    inputBinding:
      position: 101
      prefix: --min-inslen
  - id: min_insprop
    type:
      - 'null'
      - float
    doc: 'minimum proportion of the MEI in the insert sequence (default: 0.2)'
    inputBinding:
      position: 101
      prefix: --min-insprop
  - id: min_prop
    type:
      - 'null'
      - float
    doc: 'minimum proportion of the read aligned to the reference genome (default:
      0)'
    inputBinding:
      position: 101
      prefix: --min-prop
  - id: min_read_length
    type:
      - 'null'
      - int
    doc: 'minimum read length (default: 500)'
    inputBinding:
      position: 101
      prefix: --min-read-length
  - id: names
    type:
      - 'null'
      - string
    doc: names of the insertion sequences in the library
    inputBinding:
      position: 101
      prefix: --names
  - id: names_re
    type:
      - 'null'
      - string
    doc: regular expression to match the name of the insertion sequences
    inputBinding:
      position: 101
      prefix: --names-re
  - id: padding
    type:
      - 'null'
      - int
    doc: 'padding for the target region (default: 20)'
    inputBinding:
      position: 101
      prefix: --padding
  - id: read_file
    type: File
    doc: the read FASTA/FATSQ file (required)
    inputBinding:
      position: 101
      prefix: --read
  - id: ref_file
    type: File
    doc: the reference genome FASTA file (required)
    inputBinding:
      position: 101
      prefix: --ref
  - id: sample
    type:
      - 'null'
      - int
    doc: 'at most N reads are selected for assembly (default: 20)'
    inputBinding:
      position: 101
      prefix: --sample
  - id: target_end
    type: int
    doc: end position of the target in the insert sequence (required)
    inputBinding:
      position: 101
      prefix: --target-end
  - id: target_start
    type: int
    doc: start position of the target in the insert sequence (required)
    inputBinding:
      position: 101
      prefix: --target-start
  - id: thread
    type:
      - 'null'
      - int
    doc: 'number of threads (default: 1)'
    inputBinding:
      position: 101
      prefix: --thread
  - id: vcf
    type:
      - 'null'
      - boolean
    doc: output the validated result in VCF format
    inputBinding:
      position: 101
      prefix: --vcf
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: show progress messages and data
    inputBinding:
      position: 101
      prefix: --verbose
  - id: workdir
    type:
      - 'null'
      - string
    doc: 'working directory to create (default: current directory)'
    inputBinding:
      position: 101
      prefix: --workdir
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
  - id: result
    type:
      - 'null'
      - Directory
    doc: Validated insertions (validate.bed, .fasta, .maf, .vcf)
    outputBinding:
      glob: "$((inputs.workdir ? inputs.workdir + '/' : '') + 'result')"
  - id: peak
    type:
      - 'null'
      - Directory
    doc: Peaks and trimmed reads
    outputBinding:
      glob: "$((inputs.workdir ? inputs.workdir + '/' : '') + 'peak')"
  - id: lastal
    type:
      - 'null'
      - Directory
    doc: Read alignments
    outputBinding:
      glob: "$((inputs.workdir ? inputs.workdir + '/' : '') + 'lastal')"
  - id: work_dir
    type:
      - 'null'
      - Directory
    doc: The whole working directory (only when workdir is set)
    outputBinding:
      glob: '$(inputs.workdir ? inputs.workdir : [])'
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/caspeak:1.1.5--pyhdfd78af_0
stdout: caspeak_exec.out
