cwlVersion: v1.2
class: CommandLineTool
baseCommand: imodview
label: imods_imodview
doc: "Cartesian Normal Modes and Springs Visualization tool.\n\nTool homepage: https://chaconlab.org/multiscale-simulations/imod"
inputs:
  - id: pdb
    type: File
    doc: "PDB input file. Warning: It must match exactly that used in NMA. (required)"
    inputBinding:
      position: 1
  - id: ptraj_kfile
    type: File
    doc: "Input eigenvectors (ptraj) or force constants (Kfile) file. Warning: Only Cartesian modes allowed. (required)"
    inputBinding:
      position: 2
  - id: vmd
    type: string
    doc: "Ouput VMD file. (required)"
    inputBinding:
      position: 3
  - id: nev
    type:
      - 'null'
      - int
    doc: "Normal Mode index (1,2,...,size) (default=1)."
    inputBinding:
      position: 104
      prefix: --nev
  - id: color
    type:
      - 'null'
      - string
    doc: "Set color. All VMD colors available (default=black)."
    inputBinding:
      position: 105
      prefix: --color
  - id: op
    type:
      - 'null'
      - int
    doc: "Sets the operation method, 1=Arrows, 2=Springs, 3=Bryden's (default=1)."
    inputBinding:
      position: 106
      prefix: --op
  - id: max
    type:
      - 'null'
      - float
    doc: "Maximum arrow length [A] (default=10)."
    inputBinding:
      position: 107
      prefix: --max
  - id: thick
    type:
      - 'null'
      - float
    doc: "Arrow/spring thickness factor (default=0.05)."
    inputBinding:
      position: 108
      prefix: --thick
  - id: level
    type:
      - 'null'
      - int
    doc: "Sets the averaging level to compute arrows, 0=atoms, 1=residues, 2=segments, 3=chains (default=0)."
    inputBinding:
      position: 109
      prefix: --level
  - id: nresidues
    type:
      - 'null'
      - int
    doc: "Sets the number of residues for averaging (only used by \"--level 1\" option (default=1)."
    inputBinding:
      position: 110
      prefix: --nresidues
  - id: pthr
    type:
      - 'null'
      - float
    doc: "Minimum percentual amplitude (from maximum) to show arrows (default=0 , all arrows)."
    inputBinding:
      position: 111
      prefix: --pthr
  - id: kthr
    type:
      - 'null'
      - float
    doc: "Only those springs with force constants above this threshold will be shown (default=disabled)."
    inputBinding:
      position: 112
      prefix: --kthr
  - id: kthr2
    type:
      - 'null'
      - float
    doc: "Only those springs with force constants below this threshold will be shown (default=disabled)."
    inputBinding:
      position: 113
      prefix: --kthr2
  - id: name
    type:
      - 'null'
      - string
    doc: "Output files basename (default=disabled)."
    inputBinding:
      position: 114
      prefix: --name
  - id: nclusters
    type:
      - 'null'
      - int
    doc: "Number of requested clusters. (Default=10)"
    inputBinding:
      position: 115
      prefix: --nclusters
  - id: fix_file
    type:
      - 'null'
      - File
    doc: "Input ASCII file defining the ICs that were fixed during NMA (default=disabled). If modes were computed removing arbitrary ICs, the user must introduce here the file generated by iMode's --save_fixfile option."
    inputBinding:
      position: 116
      prefix: --fixFile
  - id: adj_cutoff
    type:
      - 'null'
      - float
    doc: "Adjacency cutoff (in Angstroms). (Default=6A)"
    inputBinding:
      position: 117
      prefix: --adj_cutoff
  - id: extend_size
    type:
      - 'null'
      - int
    doc: "Number of atoms threshold to consider cluster extension. Only clusters with less or equal number atoms will be extended. (Default=5)"
    inputBinding:
      position: 118
      prefix: --extend_size
  - id: extend_cutoff
    type:
      - 'null'
      - float
    doc: "Distance (in Angstroms) to extend small clusters. (Default=10A)"
    inputBinding:
      position: 119
      prefix: --extend_cutoff
  - id: save_pdb_clusters
    type:
      - 'null'
      - boolean
    doc: "Save pdbs with cluster information stored in the B-factors. (default=disabled)"
    inputBinding:
      position: 120
      prefix: --save_pdb_clusters
  - id: format
    type:
      - 'null'
      - int
    doc: "Arrows output format: 1=VMD, 2=JMol(PMESH). Only for arrows. (Default=JMol)"
    inputBinding:
      position: 121
      prefix: --format
  - id: save_affine
    type:
      - 'null'
      - boolean
    doc: "Plot the arrows obtained from the calculated affine model (in arbitrary units). (default=disabled)"
    inputBinding:
      position: 122
      prefix: --save_affine
  - id: save_axis
    type:
      - 'null'
      - boolean
    doc: "Plot the cluster axis or rotation assuming rigid body motion. (default=disabled)"
    inputBinding:
      position: 123
      prefix: --save_axis
  - id: save_paths
    type:
      - 'null'
      - boolean
    doc: "Plot the full paths obtained from every valid point. (default=disabled)"
    inputBinding:
      position: 124
      prefix: --save_paths
  - id: save_valid
    type:
      - 'null'
      - boolean
    doc: "Plot the valid points, i.e. those not colliding with any atom. (default=disabled)"
    inputBinding:
      position: 125
      prefix: --save_valid
  - id: save_sphere
    type:
      - 'null'
      - boolean
    doc: "Plot the points homogeneously distributed over a sphere centered on each cluster. (default=disabled)"
    inputBinding:
      position: 126
      prefix: --save_sphere
  - id: server
    type:
      - 'null'
      - boolean
    doc: "Enable \"server mode\" to maximize the automatic selection of parameters. (default=disabled)"
    inputBinding:
      position: 127
      prefix: --server
outputs:
  - id: vmd_file
    type: File
    doc: "Output VMD file."
    outputBinding:
      glob: $(inputs.vmd)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imods:1.0.4--h9ee0642_3
