cwlVersion: v1.2
class: CommandLineTool
baseCommand: imove
label: imods_imove
doc: "Internal coordinates MOVEment tool.\n\nTool homepage: https://chaconlab.org/multiscale-simulations/imod"
inputs:
  - id: in_pdb
    type: File
    doc: "PDB input file. (required)"
    inputBinding:
      position: 1
  - id: ptraj
    type: File
    doc: "Normal modes input file (.evec). (required)"
    inputBinding:
      position: 2
  - id: out_pdb
    type: string
    doc: "Output Multi-PDB file. (required)"
    inputBinding:
      position: 3
  - id: mode_number
    type: int
    doc: "Mode number to be moved (1,2,...,size). If --proj option enabled, then it sets the number of components to be used in ED-trajectory filtration. (required)"
    inputBinding:
      position: 4
  - id: model
    type:
      - 'null'
      - int
    doc: "Input modes Coarse-Graining model: 0=CA, 1=C5, 2=Heavy-Atom, 3=NCAC, 4=CA-only (default=2)."
    inputBinding:
      position: 105
      prefix: --model
  - id: chi
    type:
      - 'null'
      - boolean
    doc: "Considers first CHI dihedral angle (default=disabled)."
    inputBinding:
      position: 106
      prefix: --chi
  - id: frames
    type:
      - 'null'
      - int
    doc: "Number of conformations generated (default=11). It should be an odd number!"
    inputBinding:
      position: 107
      prefix: --frames
  - id: amp
    type:
      - 'null'
      - float
    doc: "Amplitude linear factor to scale motion (default=2)."
    inputBinding:
      position: 108
      prefix: --amp
  - id: temperature
    type:
      - 'null'
      - double
    doc: "Temperature [K] (default=300)."
    inputBinding:
      position: 109
      prefix: --temperature
  - id: fix_file
    type:
      - 'null'
      - File
    doc: "Input ASCII file defining the ICs that were fixed during NMA (default=disabled). If modes were computed removing arbitrary ICs, the user must introduce here the file generated by iMode's --save_fixfile option."
    inputBinding:
      position: 110
      prefix: --fixFile
  - id: cart
    type:
      - 'null'
      - boolean
    doc: "Mandatory if Cartesian modes are supplied, otherwise moving in Internal Coordinates (default=disabled)."
    inputBinding:
      position: 111
      prefix: --cart
  - id: model_out
    type:
      - 'null'
      - int
    doc: "Output Coarse-Graining model: 0=CA, 1=C5, 2=Heavy-Atom. The default output model will be that selected with the -m option."
    inputBinding:
      position: 112
      prefix: --model_out
  - id: linear
    type:
      - 'null'
      - boolean
    doc: "Enables linear motion instead of sinusoidal bounce (default=disabled)."
    inputBinding:
      position: 113
      prefix: --linear
  - id: mov
    type:
      - 'null'
      - int
    doc: "Motion Type (default=2): 0=K-matrix, 1=V/W-arrays, 2=Simple-Rotations , 3=Linear (if Cartesian modes)."
    inputBinding:
      position: 114
      prefix: --mov
  - id: proj
    type:
      - 'null'
      - File
    doc: "ED-trajectory projection file for filtration. The projection file with the components for each frame should be provided here."
    inputBinding:
      position: 115
      prefix: --proj
  - id: initial
    type:
      - 'null'
      - int
    doc: "Initial frame index as defined in proj file (default= first)"
    inputBinding:
      position: 116
      prefix: --initial
  - id: final
    type:
      - 'null'
      - int
    doc: "Final frame index as defined in proj file (default= last) (only active if --proj option is enabled)"
    inputBinding:
      position: 117
      prefix: --final
  - id: nthreads
    type:
      - 'null'
      - int
    doc: "Number of threads for parallel processing (only used if --mov 1)"
    inputBinding:
      position: 118
      prefix: --nthreads
  - id: nomodel
    type:
      - 'null'
      - boolean
    doc: "Disables PDB model building. Warning: introduced PDB model must match the CG selected with the -m option (default=disabled)."
    inputBinding:
      position: 119
      prefix: --nomodel
  - id: chi_out
    type:
      - 'null'
      - boolean
    doc: "Considers first CHI dihedral angle in output models (default=disabled) (DEVELOPER's)."
    inputBinding:
      position: 120
      prefix: --chi_out
  - id: fix_ic
    type:
      - 'null'
      - File
    doc: "Plain-text file defining the fixed Internal Coordinates. Each line will contain the index (0,1,...) of the ICs to be removed (DEVELOPER's)."
    inputBinding:
      position: 121
      prefix: --fixIC
  - id: energy
    type:
      - 'null'
      - File
    doc: "Enables harmonic energy calculations from the provided force constants file (Kfile) (DEVELOPER's)."
    inputBinding:
      position: 122
      prefix: --energy
outputs:
  - id: out_pdb_file
    type: File
    doc: "Output Multi-PDB file."
    outputBinding:
      glob: $(inputs.out_pdb)
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imods:1.0.4--h9ee0642_3
