cwlVersion: v1.2
class: CommandLineTool
baseCommand: imodview
label: imods_imodview
doc: "Cartesian Normal Modes and Springs Visualization tool\n\nTool homepage: https://chaconlab.org/multiscale-simulations/imod"
inputs:
  - id: pdb
    type: File
    doc: 'PDB input file. Warning: It must match exactly that used in NMA.'
    inputBinding:
      position: 1
  - id: ptraj_kfile
    type: File
    doc: 'Input eigenvectors (ptraj) or force constants (Kfile) file. Warning: Only
      Cartesian modes allowed.'
    inputBinding:
      position: 2
  - id: vmd
    type: File
    doc: Ouput VMD file.
    inputBinding:
      position: 3
  - id: adjacency_cutoff
    type:
      - 'null'
      - float
    doc: Adjacency cutoff (in Angstroms).
    default: 6A
    inputBinding:
      position: 104
      prefix: --adj_cutoff
  - id: arrows_output_format
    type:
      - 'null'
      - int
    doc: 'Arrows output format: 1=VMD, 2=JMol(PMESH). Only for arrows.'
    default: JMol
    inputBinding:
      position: 104
      prefix: --format
  - id: averaging_level
    type:
      - 'null'
      - int
    doc: Sets the averaging level to compute arrows, 0=atoms, 1=residues, 
      2=segments, 3=chains
    default: 0
    inputBinding:
      position: 104
      prefix: --level
  - id: color
    type:
      - 'null'
      - string
    doc: Set color. All VMD colors available
    default: black
    inputBinding:
      position: 104
      prefix: --color
  - id: extend_cluster_distance_cutoff
    type:
      - 'null'
      - float
    doc: Distance (in Angstroms) to extend small clusters.
    default: 10A
    inputBinding:
      position: 104
      prefix: --extend_cutoff
  - id: extend_cluster_size_threshold
    type:
      - 'null'
      - int
    doc: Number of atoms threshold to consider cluster extension. Only clusters 
      with less or equal number atoms will be extended.
    default: 5
    inputBinding:
      position: 104
      prefix: --extend_size
  - id: fix_file
    type:
      - 'null'
      - string
    doc: Input ASCII file defining the ICs that were fixed during NMA 
      (default=disabled). If modes were computed removing arbitrary ICs, the 
      user must introduce here the file generated by iMode's --save_fixfile 
      option.
    default: disabled
    inputBinding:
      position: 104
      prefix: --fixFile
  - id: ignore_rest
    type:
      - 'null'
      - boolean
    doc: Ignores the rest of the labeled arguments following this flag.
    inputBinding:
      position: 104
      prefix: --
  - id: max_arrow_length
    type:
      - 'null'
      - float
    doc: Maximum arrow length [A]
    default: 10.0
    inputBinding:
      position: 104
      prefix: --max
  - id: min_percentual_amplitude
    type:
      - 'null'
      - float
    doc: Minimum percentual amplitude (from maximum) to show arrows (default=0 ,
      all arrows).
    default: 0.0
    inputBinding:
      position: 104
      prefix: --pthr
  - id: nev
    type:
      - 'null'
      - int
    doc: Normal Mode index (1,2,...,size)
    default: 1
    inputBinding:
      position: 104
      prefix: --nev
  - id: num_clusters
    type:
      - 'null'
      - int
    doc: Number of requested clusters.
    default: 10
    inputBinding:
      position: 104
      prefix: --nclusters
  - id: num_residues_for_averaging
    type:
      - 'null'
      - int
    doc: Sets the number of residues for averaging (only used by "--level 1" 
      option
    default: 1
    inputBinding:
      position: 104
      prefix: --nresidues
  - id: operation_method
    type:
      - 'null'
      - int
    doc: Sets the operation method, 1=Arrows, 2=Springs, 3=Bryden's
    default: 1
    inputBinding:
      position: 104
      prefix: --op
  - id: output_basename
    type:
      - 'null'
      - string
    doc: Output files basename
    default: disabled
    inputBinding:
      position: 104
      prefix: --name
  - id: save_affine_model_arrows
    type:
      - 'null'
      - boolean
    doc: Plot the arrows obtained from the calculated affine model (in arbitrary
      units). (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_affine
  - id: save_cluster_axis
    type:
      - 'null'
      - boolean
    doc: Plot the cluster axis or rotation assuming rigid body motion. 
      (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_axis
  - id: save_paths
    type:
      - 'null'
      - boolean
    doc: Plot the full paths obtained from every valid point. (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_paths
  - id: save_pdb_clusters
    type:
      - 'null'
      - boolean
    doc: Save pdbs with cluster information stored in the B-factors. 
      (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_pdb_clusters
  - id: save_sphere_points
    type:
      - 'null'
      - boolean
    doc: Plot the points homogeneously distributed over a sphere centered on 
      each cluster. (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_sphere
  - id: save_valid_points
    type:
      - 'null'
      - boolean
    doc: Plot the valid points, i.e. those not colliding with any atom. 
      (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --save_valid
  - id: server_mode
    type:
      - 'null'
      - boolean
    doc: Enable "server mode" to maximize the automatic selection of parameters.
      (default=disabled)
    default: false
    inputBinding:
      position: 104
      prefix: --server
  - id: spring_force_constant_threshold_high
    type:
      - 'null'
      - float
    doc: Only those springs with force constants above this threshold will be 
      shown (default=disabled).
    inputBinding:
      position: 104
      prefix: --kthr
  - id: spring_force_constant_threshold_low
    type:
      - 'null'
      - float
    doc: Only those springs with force constants below this threshold will be 
      shown (default=disabled).
    inputBinding:
      position: 104
      prefix: --kthr2
  - id: thickness_factor
    type:
      - 'null'
      - float
    doc: Arrow/spring thickness factor
    default: 0.05
    inputBinding:
      position: 104
      prefix: --thick
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imods:1.0.4--h9ee0642_3
stdout: imods_imodview.out
