cwlVersion: v1.2
class: CommandLineTool
baseCommand: imc
label: imods_imc
doc: "Monte-Carlo IC-NMA based program v1.11\n\nTool homepage: https://chaconlab.org/multiscale-simulations/imod"
inputs:
  - id: pdb
    type: File
    doc: PDB input file.
    inputBinding:
      position: 1
  - id: ptraj
    type: File
    doc: Normal modes input file (.evec), either from NMA or PCA.
    inputBinding:
      position: 2
  - id: amp
    type:
      - 'null'
      - float
    doc: Amplitude linear factor to scale motion
    inputBinding:
      position: 103
      prefix: --amp
  - id: cart
    type:
      - 'null'
      - boolean
    doc: Mandatory if Cartesian modes are supplied, otherwise moving in Internal
      Coordinates (default=disabled).
    inputBinding:
      position: 103
      prefix: --cart
  - id: chi
    type:
      - 'null'
      - boolean
    doc: Considers first CHI dihedral angle (default=disabled).
    inputBinding:
      position: 103
      prefix: --chi
  - id: efact
    type:
      - 'null'
      - double
    doc: Energy/Stiffness scaling factor (mode energy will be multiplied by this
      value)
    inputBinding:
      position: 103
      prefix: --efact
  - id: fix_file
    type:
      - 'null'
      - string
    doc: Input ASCII file defining the ICs that were fixed during NMA 
      (default=disabled). If modes were computed removing arbitrary ICs, the 
      user must introduce here the file generated by iMode's --save_fixfile 
      option.
    inputBinding:
      position: 103
      prefix: --fixFile
  - id: fix_ic
    type:
      - 'null'
      - string
    doc: Plain-text file defining the fixed Internal Coordinates. Each line will
      contain the index (0,1,...) of the ICs to be removed (DEVELOPER's).
    inputBinding:
      position: 103
      prefix: --fixIC
  - id: frames
    type:
      - 'null'
      - int
    doc: Number of output conformations
    inputBinding:
      position: 103
      prefix: --frames
  - id: ignore_rest
    type:
      - 'null'
      - boolean
    doc: Ignores the rest of the labeled arguments following this flag.
    inputBinding:
      position: 103
      prefix: --ignore_rest
  - id: include_first
    type:
      - 'null'
      - boolean
    doc: Includes input model as first frame in the Multi-PDB trajectory 
      (default=disabled).
    inputBinding:
      position: 103
      prefix: --include_first
  - id: iter
    type:
      - 'null'
      - int
    doc: Number of MC iterations per output structure
    inputBinding:
      position: 103
      prefix: --iter
  - id: model
    type:
      - 'null'
      - int
    doc: 'Input Coarse-Graining model: 0=CA, 1=C5, 2=Heavy-Atom'
    inputBinding:
      position: 103
      prefix: --model
  - id: mov
    type:
      - 'null'
      - int
    doc: "Motion Type (default=2): 0=K-matrix, 1=V/W-arrays, 2=Simple-Rotations ,
      3=Linear (if Cartesian modes) (DEVELOPER's)."
    inputBinding:
      position: 103
      prefix: --mov
  - id: name
    type:
      - 'null'
      - string
    doc: Output files basename
    inputBinding:
      position: 103
      prefix: --name
  - id: nevs
    type:
      - 'null'
      - int
    doc: Number of eigenvectors to be employed, either number [1,N] <integer>, 
      or ratio from maximum available [0,1) <float>
    inputBinding:
      position: 103
      prefix: --nevs
  - id: opt_rmsd
    type:
      - 'null'
      - float
    doc: Finds the optimal energy/stiffness scaling factor to obtain the desired
      average RMSD (A) from the initial model (default=disabled).
    inputBinding:
      position: 103
      prefix: --optRmsd
  - id: optf
    type:
      - 'null'
      - float
    doc: Factor to scale the optimal energy/stiffness factor (default=disabled) 
      (DEVELOPER's).
    inputBinding:
      position: 103
      prefix: --optf
  - id: otraj
    type:
      - 'null'
      - int
    doc: 'Output trajectory format: 0-Normal-Mode, 1-Multi-PDB, 2-AMBER'
    inputBinding:
      position: 103
      prefix: --otraj
  - id: perc
    type:
      - 'null'
      - float
    doc: Enable filtering by tolerance percentage (default=1, i.e. 1%).
    inputBinding:
      position: 103
      prefix: --perc
  - id: rfact
    type:
      - 'null'
      - double
    doc: Agressivity factor (default=7.778) (DEVELOPER's).
    inputBinding:
      position: 103
      prefix: --rfact
  - id: rg
    type:
      - 'null'
      - float
    doc: Filter models by target radius of gyration (default=disabled).
    inputBinding:
      position: 103
      prefix: --Rg
  - id: rmsd
    type:
      - 'null'
      - float
    doc: Filter models by target RMSD (default=disabled).
    inputBinding:
      position: 103
      prefix: --Rmsd
  - id: seed
    type:
      - 'null'
      - string
    doc: Set the random number generator SEED (Mersenne Twister)
    inputBinding:
      position: 103
      prefix: --seed
  - id: temperature
    type:
      - 'null'
      - double
    doc: Temperature [K]
    inputBinding:
      position: 103
      prefix: --temperature
  - id: thr
    type:
      - 'null'
      - float
    doc: Enable filtering by absolute tolerance (default=disabled).
    inputBinding:
      position: 103
      prefix: --thr
  - id: unweight
    type:
      - 'null'
      - boolean
    doc: Un-mass-weights the input vectors (default=false). The Mass-weighted 
      modes (wcart) will be converted into Cartesian coordiantes (cart) 
      (DEVELOPER's).
    inputBinding:
      position: 103
      prefix: --unweight
  - id: var
    type:
      - 'null'
      - boolean
    doc: Input eigenvalues will be considered as variance (pca), otherwise the 
      will be force constants (nma) (default=false).
    inputBinding:
      position: 103
      prefix: --var
  - id: verb
    type:
      - 'null'
      - boolean
    doc: Enables verbose.
    inputBinding:
      position: 103
      prefix: --verb
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imods:1.0.4--h9ee0642_3
stdout: imods_imc.out
