cwlVersion: v1.2
class: CommandLineTool
baseCommand: imc
label: imods_imc
doc: "Monte-Carlo IC-NMA based program.\n\nTool homepage: https://chaconlab.org/multiscale-simulations/imod"
inputs:
  - id: pdb
    type: File
    doc: "PDB input file. (required)"
    inputBinding:
      position: 1
  - id: ptraj
    type: File
    doc: "Normal modes input file (.evec), either from NMA or PCA. (required)"
    inputBinding:
      position: 2
  - id: model
    type:
      - 'null'
      - int
    doc: "Input Coarse-Graining model: 0=CA, 1=C5, 2=Heavy-Atom (default=2)."
    inputBinding:
      position: 103
      prefix: --model
  - id: name
    type:
      - 'null'
      - string
    doc: "Output files basename (default=imc)."
    default: imc
    inputBinding:
      position: 104
      prefix: --name
  - id: fix_file
    type:
      - 'null'
      - File
    doc: "Input ASCII file defining the ICs that were fixed during NMA (default=disabled). If modes were computed removing arbitrary ICs, the user must introduce here the file generated by iMode's --save_fixfile option."
    inputBinding:
      position: 105
      prefix: --fixFile
  - id: opt_rmsd
    type:
      - 'null'
      - float
    doc: "Finds the optimal energy/stiffness scaling factor to obtain the desired average RMSD (A) from the initial model (default=disabled)."
    inputBinding:
      position: 106
      prefix: --optRmsd
  - id: rg
    type:
      - 'null'
      - float
    doc: "Filter models by target radius of gyration (default=disabled)."
    inputBinding:
      position: 107
      prefix: --Rg
  - id: nevs
    type:
      - 'null'
      - int
    doc: "Number of eigenvectors to be employed, either number [1,N] <integer>, or ratio from maximum available [0,1) <float> (default=5)."
    inputBinding:
      position: 108
      prefix: --nevs
  - id: frames
    type:
      - 'null'
      - int
    doc: "Number of output conformations (default= 100)."
    inputBinding:
      position: 109
      prefix: --frames
  - id: efact
    type:
      - 'null'
      - double
    doc: "Energy/Stiffness scaling factor (mode energy will be multiplied by this value) (default=1.0)."
    inputBinding:
      position: 110
      prefix: --efact
  - id: iter
    type:
      - 'null'
      - int
    doc: "Number of MC iterations per output structure (default=1000)."
    inputBinding:
      position: 111
      prefix: --iter
  - id: chi
    type:
      - 'null'
      - boolean
    doc: "Considers first CHI dihedral angle (default=disabled)."
    inputBinding:
      position: 112
      prefix: --chi
  - id: temperature
    type:
      - 'null'
      - double
    doc: "Temperature [K] (default=300)."
    inputBinding:
      position: 113
      prefix: --temperature
  - id: amp
    type:
      - 'null'
      - float
    doc: "Amplitude linear factor to scale motion (default=1)."
    inputBinding:
      position: 114
      prefix: --amp
  - id: perc
    type:
      - 'null'
      - float
    doc: "Enable filtering by tolerance percentage (default=1, i.e. 1%)."
    inputBinding:
      position: 115
      prefix: --perc
  - id: thr
    type:
      - 'null'
      - float
    doc: "Enable filtering by absolute tolerance (default=disabled)."
    inputBinding:
      position: 116
      prefix: --thr
  - id: rmsd
    type:
      - 'null'
      - float
    doc: "Filter models by target RMSD (default=disabled)."
    inputBinding:
      position: 117
      prefix: --Rmsd
  - id: otraj
    type:
      - 'null'
      - int
    doc: "Output trajectory format: 0-Normal-Mode, 1-Multi-PDB, 2-AMBER (default=1)."
    inputBinding:
      position: 118
      prefix: --otraj
  - id: cart
    type:
      - 'null'
      - boolean
    doc: "Mandatory if Cartesian modes are supplied, otherwise moving in Internal Coordinates (default=disabled)."
    inputBinding:
      position: 119
      prefix: --cart
  - id: seed
    type:
      - 'null'
      - int
    doc: "Set the random number generator SEED (Mersenne Twister) (default=random-seed from /dev/urandom)."
    inputBinding:
      position: 120
      prefix: --seed
  - id: include_first
    type:
      - 'null'
      - boolean
    doc: "Includes input model as first frame in the Multi-PDB trajectory (default=disabled)."
    inputBinding:
      position: 121
      prefix: --include_first
  - id: var
    type:
      - 'null'
      - boolean
    doc: "Input eigenvalues will be considered as variance (pca), otherwise the will be force constants (nma) (default=false)."
    inputBinding:
      position: 122
      prefix: --var
  - id: unweight
    type:
      - 'null'
      - boolean
    doc: "Un-mass-weights the input vectors (default=false). The Mass-weighted modes (wcart) will be converted into Cartesian coordiantes (cart) (DEVELOPER's)."
    inputBinding:
      position: 123
      prefix: --unweight
  - id: optf
    type:
      - 'null'
      - float
    doc: "Factor to scale the optimal energy/stiffness factor (default=disabled) (DEVELOPER's)."
    inputBinding:
      position: 124
      prefix: --optf
  - id: rfact
    type:
      - 'null'
      - double
    doc: "Agressivity factor (default=7.778) (DEVELOPER's)."
    inputBinding:
      position: 125
      prefix: --rfact
  - id: mov
    type:
      - 'null'
      - int
    doc: "Motion Type (default=2): 0=K-matrix, 1=V/W-arrays, 2=Simple-Rotations , 3=Linear (if Cartesian modes) (DEVELOPER's)."
    inputBinding:
      position: 126
      prefix: --mov
  - id: fix_ic
    type:
      - 'null'
      - File
    doc: "Plain-text file defining the fixed Internal Coordinates. Each line will contain the index (0,1,...) of the ICs to be removed (DEVELOPER's)."
    inputBinding:
      position: 127
      prefix: --fixIC
  - id: verb
    type:
      - 'null'
      - boolean
    doc: "Enables verbose."
    inputBinding:
      position: 128
      prefix: --verb
outputs:
  - id: result_files
    type:
      type: array
      items: File
    doc: Files written with the output basename
    outputBinding:
      glob: $(inputs.name)*
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/imods:1.0.4--h9ee0642_3
