cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - enrichm
  - annotate
label: enrichm_annotate
doc: "Genome annotation pipeline: annotate genomes with KO, Pfam, TIGRFAM, dbCAN, EC and cluster ids and write a frequency matrix per annotation type.\n\nTool homepage: https://github.com/geronimp/enrichM"
inputs:
  - id: log
    type:
      - 'null'
      - string
    doc: "Output logging information to this file."
    inputBinding:
      position: 1
      prefix: --log
  - id: verbosity
    type:
      - 'null'
      - int
    doc: "Level of verbosity (1 - 5 - default = 4) 5 = Very verbose, 1 = Silent"
    inputBinding:
      position: 1
      prefix: --verbosity
  - id: output
    type:
      - 'null'
      - string
    doc: "Output directory"
    inputBinding:
      position: 1
      prefix: --output
  - id: force
    type:
      - 'null'
      - boolean
    doc: "Overwrite previous run"
    inputBinding:
      position: 1
      prefix: --force
  - id: genome_files
    type:
      - 'null'
      - type: array
        items: File
    doc: "Space separated list of genomes to annotate"
    inputBinding:
      position: 1
      prefix: --genome_files
  - id: genome_directory
    type:
      - 'null'
      - Directory
    doc: "Directory containing genomes to annotate"
    inputBinding:
      position: 1
      prefix: --genome_directory
  - id: protein_files
    type:
      - 'null'
      - type: array
        items: File
    doc: "Space separated list of .faa files of genomes to annotate. Protein files need to be generated by prodigal."
    inputBinding:
      position: 1
      prefix: --protein_files
  - id: protein_directory
    type:
      - 'null'
      - Directory
    doc: "Directory containing .faa files of genomes to annotate. Protein files need to be generated by prodigal."
    inputBinding:
      position: 1
      prefix: --protein_directory
  - id: ko
    type:
      - 'null'
      - boolean
    doc: "Annotate with KO ids"
    inputBinding:
      position: 1
      prefix: --ko
  - id: ko_hmm
    type:
      - 'null'
      - boolean
    doc: "Annotate with KO ids"
    inputBinding:
      position: 1
      prefix: --ko_hmm
  - id: pfam
    type:
      - 'null'
      - boolean
    doc: "Annotate with Pfam HMMs"
    inputBinding:
      position: 1
      prefix: --pfam
  - id: tigrfam
    type:
      - 'null'
      - boolean
    doc: "Annotate with TIGRFAM HMMs"
    inputBinding:
      position: 1
      prefix: --tigrfam
  - id: clusters
    type:
      - 'null'
      - boolean
    doc: "Annotate with cluster ids"
    inputBinding:
      position: 1
      prefix: --clusters
  - id: orthologs
    type:
      - 'null'
      - boolean
    doc: "Annotate with ortholog ids"
    inputBinding:
      position: 1
      prefix: --orthologs
  - id: orthogroup
    type:
      - 'null'
      - boolean
    doc: "Annotate with orthogroup ids with OrthoFinder"
    inputBinding:
      position: 1
      prefix: --orthogroup
  - id: cazy
    type:
      - 'null'
      - boolean
    doc: "Annotate with dbCAN HMMs"
    inputBinding:
      position: 1
      prefix: --cazy
  - id: ec
    type:
      - 'null'
      - boolean
    doc: "Annotate with EC ids"
    inputBinding:
      position: 1
      prefix: --ec
  - id: cut_ga_pfam
    type:
      - 'null'
      - boolean
    doc: "For PFAM searches: use profiles GA gathering cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_ga_pfam
  - id: cut_nc_pfam
    type:
      - 'null'
      - boolean
    doc: "For PFAM searches: use profiles NC noise cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_nc_pfam
  - id: cut_tc_pfam
    type:
      - 'null'
      - boolean
    doc: "For PFAM searches: use profiles TC trusted cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_tc_pfam
  - id: cut_ga_tigrfam
    type:
      - 'null'
      - boolean
    doc: "For TIGRfam searches: use profiles GA gathering cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_ga_tigrfam
  - id: cut_nc_tigrfam
    type:
      - 'null'
      - boolean
    doc: "For TIGRfam searches: use profiles NC noise cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_nc_tigrfam
  - id: cut_tc_tigrfam
    type:
      - 'null'
      - boolean
    doc: "For TIGRfam searches: use profiles TC trusted cutoffs to set all thresholding"
    inputBinding:
      position: 1
      prefix: --cut_tc_tigrfam
  - id: cut_ko
    type:
      - 'null'
      - boolean
    doc: "For KO HMM annotation searches: use cutoffs defined by KEGG to maximise F-score."
    inputBinding:
      position: 1
      prefix: --cut_ko
  - id: evalue
    type:
      - 'null'
      - float
    doc: "Use this evalue cutoff to filter false positives (default: 1e-05)"
    inputBinding:
      position: 1
      prefix: --evalue
  - id: bit
    type:
      - 'null'
      - float
    doc: "Use this bit score cutoff to filter false positives (default: 0)"
    inputBinding:
      position: 1
      prefix: --bit
  - id: id
    type:
      - 'null'
      - float
    doc: "Use this percent identity cutoff to filter false positives (default: 0.3)"
    inputBinding:
      position: 1
      prefix: --id
  - id: aln_query
    type:
      - 'null'
      - float
    doc: "This fraction of the query must align to the reference (default: 0.7)"
    inputBinding:
      position: 1
      prefix: --aln_query
  - id: aln_reference
    type:
      - 'null'
      - float
    doc: "This fraction of the reference must align to the query (default: 0.7)"
    inputBinding:
      position: 1
      prefix: --aln_reference
  - id: c
    type:
      - 'null'
      - float
    doc: "When clustering, use matches above this fraction of aligned (covered) query and target residues (default: 0.8)"
    inputBinding:
      position: 1
      prefix: --c
  - id: threads
    type:
      - 'null'
      - string
    doc: "Use this number of threads when annotating with BLAST and HMMsearch (default: 1)"
    inputBinding:
      position: 1
      prefix: --threads
  - id: parallel
    type:
      - 'null'
      - string
    doc: "Run this number of jobs in parallel when annotating with HMMsearch (default: 5)"
    inputBinding:
      position: 1
      prefix: --parallel
  - id: inflation
    type:
      - 'null'
      - float
    doc: "Inflation factor to use when calling clusters in ortholog (default = 1.5)"
    inputBinding:
      position: 1
      prefix: --inflation
  - id: suffix
    type:
      - 'null'
      - string
    doc: "Treat files ending with this suffix within the --genome_directory as genomes (default: .fna for --genome_directory and .faa for )"
    inputBinding:
      position: 1
      prefix: --suffix
  - id: light
    type:
      - 'null'
      - boolean
    doc: "Don't store metadata for genome files (can't use enrichM compare downstream, default=False)"
    inputBinding:
      position: 1
      prefix: --light
  - id: count_domains
    type:
      - 'null'
      - boolean
    doc: "Fill the frequency matrix with the total number of times an annotation was detected (for example, when one domain more than once within a protein), rather than the count of proteins with with that annotation"
    inputBinding:
      position: 1
      prefix: --count_domains
  - id: chunk_number
    type:
      - 'null'
      - float
    doc: "Split loading of genomes into this many chunks (default = 4)"
    inputBinding:
      position: 1
      prefix: --chunk_number
  - id: chunk_max
    type:
      - 'null'
      - float
    doc: "Maximum number of genomes to load per chunk (default = 2500)"
    inputBinding:
      position: 1
      prefix: --chunk_max
outputs:
  - id: output_dir
    type:
      - 'null'
      - Directory
    doc: Output directory
    outputBinding:
      glob: $(inputs.output)
  - id: log_file
    type:
      - 'null'
      - File
    doc: Log file written by the tool (named after the subcommand)
    outputBinding:
      glob: annotate.log
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/enrichm:0.6.6--pyhdfd78af_0
