cwlVersion: v1.2
class: CommandLineTool
baseCommand: snap
label: mimodd_snap
doc: "Sequencing mode reference genome or index directory input files\n\nTool homepage:
  http://sourceforge.net/projects/mimodd"
inputs:
  - id: sequencing_mode
    type: string
    doc: specify "single" or "paired" to indicate the sequencing mode
    inputBinding:
      position: 1
  - id: reference_genome_or_index_directory
    type: File
    doc: an existing index directory generated by snap_index or a fasta 
      reference genome (will be used to create the index)
    inputBinding:
      position: 2
  - id: input_files
    type:
      type: array
      items: File
    doc: one or two (in "paired" mode with "fastq" input format) input files
    inputBinding:
      position: 3
  - id: bind_threads
    type:
      - 'null'
      - boolean
    doc: bind each thread to its processor (off by default)
    inputBinding:
      position: 104
      prefix: -b
  - id: clipping
    type:
      - 'null'
      - string
    doc: 'specify a combination of two + or x symbols to indicate whether to clip
      low-quality bases from the front and back of reads respectively; default: clip
      from front and back (-C ++)'
    default: ++
    inputBinding:
      position: 104
      prefix: -C
  - id: confadapt
    type:
      - 'null'
      - int
    doc: confidence adaptation threshold
    default: 7
    inputBinding:
      position: 104
      prefix: --confadapt
  - id: confdiff
    type:
      - 'null'
      - int
    doc: confidence threshold
    default: 2
    inputBinding:
      position: 104
      prefix: --confdiff
  - id: discard_overlapping_mates
    type:
      - 'null'
      - type: array
        items: string
    doc: 'consider overlapping mate pairs of the given orientation type(s) anomalous
      and discard them; default: keep all overlapping mate pairs'
    inputBinding:
      position: 104
      prefix: --discard-overlapping-mates
  - id: error_rep
    type:
      - 'null'
      - boolean
    doc: compute error rate assuming wgsim-generated reads
    inputBinding:
      position: 104
      prefix: -e
  - id: explore
    type:
      - 'null'
      - boolean
    doc: explore some hits of overly popular seeds (useful for filtering)
    inputBinding:
      position: 104
      prefix: -x
  - id: filter_output
    type:
      - 'null'
      - string
    doc: retain only certain read classes in output (a=aligned only, s=single 
      hit only, u=unaligned only)
    inputBinding:
      position: 104
      prefix: --filter-output
  - id: gap_penalty
    type:
      - 'null'
      - int
    doc: specify a gap penalty to use when generating CIGAR strings
    inputBinding:
      position: 104
      prefix: --gap-penalty
  - id: header
    type:
      - 'null'
      - File
    doc: a SAM file providing header information to be used for the output 
      (required for input in fastq format and with unheadered SAM/BAM input, 
      optional for headered SAM/BAM input; replaces header information found in 
      the input file
    inputBinding:
      position: 104
      prefix: --header
  - id: idx_overflow_factor
    type:
      - 'null'
      - int
    doc: factor (between 1 and 1000) to set the size of the index build overflow
      space
    default: 40
    inputBinding:
      position: 104
      prefix: --idx-overflow
  - id: idx_seedsize
    type:
      - 'null'
      - int
    doc: Seed size used in building the index
    default: 20
    inputBinding:
      position: 104
      prefix: --idx-seedsize
  - id: idx_slack
    type:
      - 'null'
      - float
    doc: Hash table slack for indexing
    default: 0.3
    inputBinding:
      position: 104
      prefix: --idx-slack
  - id: ignore_non_matching_ids
    type:
      - 'null'
      - boolean
    doc: ignore non-matching IDs in the paired-end aligner
    inputBinding:
      position: 104
      prefix: -I
  - id: input_format
    type:
      - 'null'
      - string
    doc: input file format; must be fastq, gz, sam or bam
    default: bam
    inputBinding:
      position: 104
      prefix: --iformat
  - id: maxdist
    type:
      - 'null'
      - int
    doc: maximum edit distance allowed per read or pair
    default: 8
    inputBinding:
      position: 104
      prefix: --maxdist
  - id: maxhits
    type:
      - 'null'
      - int
    doc: maximum hits to consider per seed
    default: 250
    inputBinding:
      position: 104
      prefix: --maxhits
  - id: maxseeds
    type:
      - 'null'
      - int
    doc: number of seeds to use per read
    default: 25
    inputBinding:
      position: 104
      prefix: --maxseeds
  - id: memory
    type:
      - 'null'
      - string
    doc: maximal amount of memory to be used in GB (overrides config setting); 
      will be respected during sorting only
    inputBinding:
      position: 104
      prefix: --memory
  - id: mmatch_notation
    type:
      - 'null'
      - boolean
    doc: legacy option retained for backwards compatibility; indicates that 
      CIGAR strings in the output should use M (alignment match) rather than = 
      and X (sequence (mis-)match); -M is implied by default, use -X to turn off
    inputBinding:
      position: 104
      prefix: --mmatch-notation
  - id: no_prefetch
    type:
      - 'null'
      - boolean
    doc: disables cache prefetching in the genome; may be helpful for machines 
      with small caches or lots of cores/cache
    inputBinding:
      position: 104
      prefix: -P
  - id: no_sort
    type:
      - 'null'
      - boolean
    doc: output reads in their original order, i.e., do not sort by alignment 
      location
    inputBinding:
      position: 104
      prefix: --no-sort
  - id: output_format
    type:
      - 'null'
      - string
    doc: 'output file format (sam or bam; default: bam)'
    default: bam
    inputBinding:
      position: 104
      prefix: --oformat
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: suppress original messages from SNAP
    inputBinding:
      position: 104
      prefix: --quiet
  - id: selectivity
    type:
      - 'null'
      - int
    doc: selectivity; randomly choose 1/selectivity of the reads to score
    inputBinding:
      position: 104
      prefix: --selectivity
  - id: sort
    type:
      - 'null'
      - boolean
    doc: legacy option retained for backwards compatibility; sort output file by
      alignment location; implied by default, use --no-sort to turn off
    inputBinding:
      position: 104
      prefix: --sort
  - id: spacing
    type:
      - 'null'
      - type: array
        items: int
    doc: min and max spacing to allow between paired ends
    default:
      - 100
      - 10000
    inputBinding:
      position: 104
      prefix: --spacing
  - id: stop_on_first
    type:
      - 'null'
      - boolean
    doc: stop on first match within edit distance limit (filtering mode)
    inputBinding:
      position: 104
      prefix: -f
  - id: threads
    type:
      - 'null'
      - int
    doc: number of threads to use (overrides config setting)
    inputBinding:
      position: 104
      prefix: --threads
  - id: use_equal_and_x_for_cigar
    type:
      - 'null'
      - boolean
    doc: CIGAR strings in the output should use = and X to indicate 
      matches/mismatches rather than M (alignment match); USE OF THIS OPTION IS 
      DISCOURAGED as =/X CIGAR strings are still not fully supported by useful 
      third- party tools like IGV
    inputBinding:
      position: 104
      prefix: -X
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: verbose output (independent of SNAP)
    inputBinding:
      position: 104
      prefix: --verbose
outputs:
  - id: output_file
    type: File
    doc: name of the output file
    outputBinding:
      glob: $(inputs.output_file)
  - id: idx_out_dir
    type:
      - 'null'
      - Directory
    doc: name of the index directory to be created; if given, the index 
      directory will be permanent, otherwise a temporary directory will be used
    outputBinding:
      glob: $(inputs.idx_out_dir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mimodd:0.1.9--py35_0
