cwlVersion: v1.2
class: CommandLineTool
baseCommand: map
label: mimodd_map
doc: "MiModD mapping tool for variant analysis.\n\nTool homepage: http://sourceforge.net/projects/mimodd"
inputs:
  - id: analysis_mode
    type: string
    doc: specify "SVD" for Simple Variant Density analysis, "VAF" for Variant 
      Allele Frequency analysis or "VAC" for Variant Allele Contrast analysis.
    inputBinding:
      position: 1
  - id: input_file
    type: File
    doc: valid input files are VCF files or per-variant report files (as 
      generated by this tool with the "-t" option or by the CloudMap Hawaiian 
      Variant Density Mapping tool).
    inputBinding:
      position: 2
  - id: bin_sizes
    type:
      - 'null'
      - type: array
        items: int
    doc: 'list of bin sizes to be used for histogram plots and linkage reports (default:
      1Mb and 500Kb)'
    inputBinding:
      position: 103
      prefix: --bin-sizes
  - id: cloudmap
    type:
      - 'null'
      - boolean
    doc: generate valid input for the original CloudMap Mapping tools and save 
      it to the text output file specified by the "-t" option. This option can 
      only be used in "SVD" or "VAF" mode, which have an equivalent in CloudMap.
    inputBinding:
      position: 103
      prefix: --cloudmap
  - id: contrast_sample
    type:
      - 'null'
      - string
    doc: name of the sample (as appearing in the input vcf file) that provides 
      the contrast for the mapping sample
    inputBinding:
      position: 103
      prefix: --contrast-sample
  - id: fit_width
    type:
      - 'null'
      - boolean
    doc: do not autoscale x-axes to size of largest contig
    inputBinding:
      position: 103
      prefix: --fit-width
  - id: hist_colors
    type:
      - 'null'
      - type: array
        items: string
    doc: 'list of colors to be used for plotting histogram bars of different width
      (default: darkgrey and red)'
    inputBinding:
      position: 103
      prefix: --hist-colors
  - id: infer_missing
    type:
      - 'null'
      - boolean
    doc: if variant data for either the related or the unrelated parent strain 
      is not provided, the tool can try to infer the alleles present in that 
      parent from the allele spectrum found in the mapping sample. Use with 
      caution on carefully filtered variant lists only!
    inputBinding:
      position: 103
      prefix: --infer, --infer-missing
  - id: loess_colors
    type:
      - 'null'
      - type: array
        items: string
    doc: color(s) for regression line(s) through scatter plot data
    inputBinding:
      position: 103
      prefix: --loess-colors
  - id: loess_span
    type:
      - 'null'
      - float
    doc: 'span parameter for the Loess regression line through the linkage data (default:
      0.1, specify 0 to skip calculation)'
    inputBinding:
      position: 103
      prefix: --loess-span
  - id: mapping_sample
    type:
      - 'null'
      - string
    doc: name of the sample (as appearing in the input vcf file) for which 
      variants should be mapped (cannot be used in SVD mode)
    inputBinding:
      position: 103
      prefix: --mapping-sample
  - id: no_hist
    type:
      - 'null'
      - boolean
    doc: do not produce linkage histogram plots; only generate scatter plots
    inputBinding:
      position: 103
      prefix: --no-hist
  - id: no_kde
    type:
      - 'null'
      - boolean
    doc: do not add kernel density estimate lines to histogram plots
    inputBinding:
      position: 103
      prefix: --no-kde
  - id: no_scatter
    type:
      - 'null'
      - boolean
    doc: do not produce scatter plots of observed segregation rates; just plot 
      histograms
    inputBinding:
      position: 103
      prefix: --no-scatter
  - id: plot_file
    type:
      - 'null'
      - File
    doc: 'generate graphical output and store it in the given file (default: no graphical
      output)'
    inputBinding:
      position: 103
      prefix: --plot-file
  - id: points_colors
    type:
      - 'null'
      - type: array
        items: string
    doc: color(s) for scatter plot data points
    inputBinding:
      position: 103
      prefix: --points-colors
  - id: quiet
    type:
      - 'null'
      - boolean
    doc: suppress warning messages about plotting problems.
    inputBinding:
      position: 103
      prefix: --quiet
  - id: related_parent
    type:
      - 'null'
      - string
    doc: name of the sample to provide related parent strain (mutagenesis 
      strain) variants for the analysis in Variant Allele Frequency (VAF) mode.
    inputBinding:
      position: 103
      prefix: --related-parent
  - id: seqinfo
    type:
      - 'null'
      - File
    doc: if an input file does not specify required contig information 
      (chromosome names and sizes), extract this information from SEQINFO_FILE. 
      This file can be a reference genome file in fasta format or a 
      CloudMap-style sequence dictionary file. This option is never necessary 
      with MiModD-generated input, but can be useful with input files generated 
      by third-party tools that do not record contig information in their 
      output.
    inputBinding:
      position: 103
      prefix: --seqinfo
  - id: text_file
    type:
      - 'null'
      - File
    doc: generate text-based output for every variant position and save it to 
      the specified file. This file can be used as input during later runs of 
      the tool, which will speed up replotting.
    inputBinding:
      position: 103
      prefix: --text-file
  - id: unrelated_parent
    type:
      - 'null'
      - string
    doc: name of the sample to provide unrelated parent strain (mapping strain) 
      variants for the analysis in Variant Allele Frequency (VAF) mode.
    inputBinding:
      position: 103
      prefix: --unrelated-parent
  - id: ylim_hist
    type:
      - 'null'
      - float
    doc: 'upper limit for histogram plot y-axis (default: auto)'
    inputBinding:
      position: 103
      prefix: --ylim-hist
  - id: ylim_scatter
    type:
      - 'null'
      - float
    doc: 'upper limit for scatter plot y-axis (default: 1)'
    inputBinding:
      position: 103
      prefix: --ylim-scatter
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: 'redirect the binned variant counts to this file (default: stdout).'
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/mimodd:0.1.9--py35_0
