cwlVersion: v1.2
class: CommandLineTool
baseCommand: bacpage phylogeny
label: bacpage_phylogeny
doc: "Reconstructs maximum likelihood phylogeny from consensus sequences.\n\nTool
  homepage: https://github.com/CholGen/bacpage"
inputs:
  - id: directory
    type: Directory
    doc: Path to valid project directory
    inputBinding:
      position: 1
  - id: configfile
    type:
      - 'null'
      - File
    doc: Path to assembly configuration file
    inputBinding:
      position: 102
      prefix: --configfile
  - id: detect
    type:
      - 'null'
      - File
    doc: Bypass computationally intensive recombination detection by supplying a
      GFF file previous generated by gubbins.
    inputBinding:
      position: 102
      prefix: --detect
  - id: mask
    type:
      - 'null'
      - File
    doc: gff file used to mask to all sequences prior to tree building. If not 
      specified, sequences will not be masked
    inputBinding:
      position: 102
      prefix: --mask
  - id: minimum_completeness
    type:
      - 'null'
      - float
    doc: minimum coverage required to be included in analysis
    inputBinding:
      position: 102
      prefix: --minimum-completeness
  - id: no_detect
    type:
      - 'null'
      - boolean
    doc: Skip performing recombinant region detection
    inputBinding:
      position: 102
      prefix: --no-detect
  - id: terra
    type:
      - 'null'
      - boolean
    doc: Generate input for Terra and print instructions.
    inputBinding:
      position: 102
      prefix: --terra
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads available for command
    inputBinding:
      position: 102
      prefix: --threads
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print lots of stuff to screen.
    inputBinding:
      position: 102
      prefix: --verbose
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bacpage:2025.08.21--pyhdfd78af_0
stdout: bacpage_phylogeny.out
