cwlVersion: v1.2
class: CommandLineTool
baseCommand: phyluce_assembly_get_fastas_from_match_counts
label: phyluce_phyluce_assembly_get_fastas_from_match_counts
doc: "Given an input SQL database of UCE locus matches, a config file containing the
  loci in your data matrix, and the contigs you have assembled, extract the fastas
  for each locus for each taxon in the assembled contigs, and rename those to the
  appropriate UCE loci, outputting the results as a single monolithic FASTA file containing
  all records. Can also incorporate data from genome-enabled taxa or other studies
  using the --extend-db and --extend- contigs parameters.\n\nTool homepage: https://github.com/faircloth-lab/phyluce"
inputs:
  - id: contigs
    type: Directory
    doc: The directory containing the assembled contigs in which you searched 
      for UCE loci.
    inputBinding:
      position: 101
      prefix: --contigs
  - id: extend_locus_contigs
    type:
      - 'null'
      - Directory
    doc: A directory holding the assembled contigs (from genomes or another 
      study) referenced by --extend- locus-db.
    inputBinding:
      position: 101
      prefix: --extend-locus-contigs
  - id: extend_locus_db
    type:
      - 'null'
      - File
    doc: An SQLlite database file holding probe matches to other targeted loci.
    inputBinding:
      position: 101
      prefix: --extend-locus-db
  - id: incomplete_matrix
    type:
      - 'null'
      - File
    doc: The path to the outfile for incomplete-matrix records. Required when 
      processing an incomplete data matrix.
    inputBinding:
      position: 101
      prefix: --incomplete-matrix
  - id: locus_db
    type: File
    doc: The SQL database file holding probe matches to targeted loci (usually 
      "lastz/probe.matches.sqlite").
    inputBinding:
      position: 101
      prefix: --locus-db
  - id: log_path
    type:
      - 'null'
      - Directory
    doc: The path to a directory to hold logs.
    inputBinding:
      position: 101
      prefix: --log-path
  - id: match_count_output
    type: File
    doc: The output file containing taxa and loci in complete/incomplete 
      matrices generated by get_match_counts.py.
    inputBinding:
      position: 101
      prefix: --match-count-output
  - id: verbosity
    type:
      - 'null'
      - string
    doc: The logging level to use.
    inputBinding:
      position: 101
      prefix: --verbosity
outputs:
  - id: output
    type: File
    doc: The path to the output FASTA file you want to create.
    outputBinding:
      glob: $(inputs.output)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/phyluce:1.6.8--py_0
