cwlVersion: v1.2
class: CommandLineTool
baseCommand: domainsMergeToBed.pl
label: hiddendomains_domainsMergeToBed.pl
doc: "This program merges all consecutive domains with posterior greater than a threshold
  (default is 0; all domains are merged) into a single domain.\n\nTool homepage: http://hiddendomains.sourceforge.net/"
inputs:
  - id: domain_file
    type: File
    doc: domainFile.txt should be a file generated by the hiddenDomains R 
      function.
    inputBinding:
      position: 1
  - id: bin_width
    type:
      - 'null'
      - int
    doc: The width of the bin.
    inputBinding:
      position: 102
      prefix: -b
  - id: chrom_info_file
    type:
      - 'null'
      - File
    doc: If you get an out of bounds error when uploading a bed file to the UCSC
      genome browser, you can use this option to trim the bounds to the size of 
      the chromosomes.
    inputBinding:
      position: 102
      prefix: -g
  - id: create_trackline
    type:
      - 'null'
      - boolean
    doc: Create a trackline.
    inputBinding:
      position: 102
      prefix: -t
  - id: min_posterior
    type:
      - 'null'
      - float
    doc: Toss out parts of domains that have posterior values that are less than
      MIN_POSTERIOR.
    inputBinding:
      position: 102
      prefix: -p
  - id: track_name
    type:
      - 'null'
      - string
    doc: The name you want to give your track.
    inputBinding:
      position: 102
      prefix: -n
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hiddendomains:3.1--pl526r36_0
stdout: hiddendomains_domainsMergeToBed.pl.out
