cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - MuSE
  - sump
label: muse_MuSE sump
doc: "Summarize MuSE variant calls\n\nTool homepage: http://bioinformatics.mdanderson.org/main/MuSE"
inputs:
  - id: cores
    type:
      - 'null'
      - int
    doc: number of cores specified
    default: 1
    inputBinding:
      position: 101
      prefix: -n
  - id: dbSNP_vcf
    type:
      - 'null'
      - File
    doc: dbSNP vcf file that should be bgzip compressed, tabix indexed and based
      on the same reference genome used in 'MuSE call'
    inputBinding:
      position: 101
      prefix: -D
  - id: input_file
    type: File
    doc: single input file generated by 'MuSE call'
    inputBinding:
      position: 101
      prefix: -I
  - id: whole_exome
    type:
      - 'null'
      - boolean
    doc: input generated from whole exome sequencing data
    inputBinding:
      position: 101
      prefix: -E
  - id: whole_genome
    type:
      - 'null'
      - boolean
    doc: input generated from whole genome sequencing data
    inputBinding:
      position: 101
      prefix: -G
outputs:
  - id: output_file
    type:
      - 'null'
      - File
    doc: output file name (VCF format)
    outputBinding:
      glob: $(inputs.output_file)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/muse:2.1.2--h3b3e331_3
