FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --tool-path /tools ProteomIQon.MzMLToMzLite --version 0.0.9
RUN dotnet tool install --tool-path /tools ProteomIQon.PSMStatistics --version 0.0.9
RUN dotnet tool install --tool-path /tools ProteomIQon.PeptideDB --version 0.0.9
RUN dotnet tool install --tool-path /tools ProteomIQon.PeptideSpectrumMatching --version 0.0.8
RUN dotnet tool install --tool-path /tools ProteomIQon.PSMBasedQuantification --version 0.0.11
RUN dotnet tool install --tool-path /tools ProteomIQon.ProteinInference --version 0.0.9
RUN dotnet tool install --tool-path /tools ProteomIQon.JoinQuantPepIonsWithProteins --version 0.0.4
RUN dotnet tool install --tool-path /tools ProteomIQon.QuantBasedAlignment_linux_x64 --version 0.0.3
RUN dotnet tool install --tool-path /tools ProteomIQon.AlignmentBasedQuantification --version 0.0.3
RUN dotnet tool install --tool-path /tools ProteomIQon.AlignmentBasedQuantStatistics --version 0.0.4
RUN dotnet tool install --tool-path /tools ProteomIQon.AddDeducedPeptides --version 0.0.3
RUN dotnet tool install --tool-path /tools ProteomIQon.LabeledProteinQuantification --version 0.0.4

