cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ampcombi
  - signal_peptide
label: ampcombi_signal_peptide
doc: "Identify signal peptides using SignalP models and Ampcombi cluster summaries.\n
  \nTool homepage: https://github.com/Darcy220606/AMPcombi"
inputs:
  - id: ampcombi_cluster
    type:
      - 'null'
      - File
    doc: Enter a file path corresponding to the Ampcombi_summary_cluster.tsv that
      can be generated by running --ampcombi cluster.
    inputBinding:
      position: 101
      prefix: --ampcombi_cluster
  - id: signalp_model
    type:
      - 'null'
      - Directory
    doc: Enter a directory path corresponding to the signalp models. More information
      can be found in signalp documentation at https://services.healthtech.dtu.dk/services/SignalP-6.0/
    inputBinding:
      position: 101
      prefix: --signalp_model
outputs:
  - id: log
    type:
      - 'null'
      - File
    doc: Silences the standard output and captures it in a log file
    outputBinding:
      glob: $(inputs.log)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ampcombi:2.0.1--pyhdfd78af_0
