cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - ampcombi
  - signal_peptide
label: ampcombi_signal_peptide
doc: "Identify signal peptides using SignalP models and Ampcombi cluster summaries.\n\
  \ \nTool homepage: https://github.com/Darcy220606/AMPcombi"
inputs:
  - id: ampcombi_cluster
    type:
      - 'null'
      - File
    doc: Enter a file path corresponding to the Ampcombi_summary_cluster.tsv 
      that can be generated by running --ampcombi cluster.
    inputBinding:
      position: 101
      prefix: --ampcombi_cluster
  - id: signalp_model
    type:
      - 'null'
      - Directory
    doc: Enter a directory path corresponding to the signalp models. More 
      information can be found in signalp documentation at 
      https://services.healthtech.dtu.dk/services/SignalP-6.0/
    inputBinding:
      position: 101
      prefix: --signalp_model
  - id: log
    type:
      - 'null'
      - boolean
    doc: Silence the standard output and capture it in a log file with a fixed 
      name.
    inputBinding:
      position: 102
      prefix: --log
      valueFrom: '$(self ? "True" : null)'
outputs:
  - id: signal_peptide_summary
    type:
      - 'null'
      - File
    doc: Cluster summary with signal peptide predictions
    outputBinding:
      glob: Ampcombi_summary_cluster_SP.tsv
  - id: signal_peptide_only
    type:
      - 'null'
      - File
    doc: Clusters that contain a signal peptide
    outputBinding:
      glob: Ampcombi_summary_cluster_SP_onlyclusterswithSP.tsv
  - id: log_file
    type:
      - 'null'
      - File
    doc: Log file written when log is set
    outputBinding:
      glob: Ampcombi_signalpeptide.log
requirements:
  - class: InlineJavascriptRequirement
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/ampcombi:2.0.1--pyhdfd78af_0
