cwlVersion: v1.2
class: CommandLineTool
baseCommand: make_hub.py
label: makehub_make_hub.py
doc: "Generate UCSC assembly hub (e.g. from BRAKER or MAKER output).\n\nTool homepage:
  https://github.com/Gaius-Augustus/MakeHub"
inputs:
  - id: add_track
    type:
      - 'null'
      - boolean
    doc: Add track(s) to existing hub
    inputBinding:
      position: 101
      prefix: --add_track
  - id: annot
    type:
      - 'null'
      - File
    doc: GTF file with reference annotation
    inputBinding:
      position: 101
      prefix: --annot
  - id: assembly_version
    type:
      - 'null'
      - string
    doc: Assembly version, e.g. "BDGP R4/dm3". This argument must be provided if
      the hub is supposed to be added to the public UCSC list.
    inputBinding:
      position: 101
      prefix: --assembly_version
  - id: aug_ab_initio
    type:
      - 'null'
      - File
    doc: GTF file with ab initio AUGUSTUS predictions
    inputBinding:
      position: 101
      prefix: --aug_ab_initio
  - id: aug_ab_initio_utr
    type:
      - 'null'
      - File
    doc: GTF file with ab initio AUGUSTUS predictions with UTRs
    inputBinding:
      position: 101
      prefix: --aug_ab_initio_utr
  - id: aug_hints
    type:
      - 'null'
      - File
    doc: GTF file with AUGUSTUS predictions with hints
    inputBinding:
      position: 101
      prefix: --aug_hints
  - id: aug_hints_utr
    type:
      - 'null'
      - File
    doc: GTF file with AUGUSTUS predictions with hints with UTRs
    inputBinding:
      position: 101
      prefix: --aug_hints_utr
  - id: bam
    type:
      - 'null'
      - type: array
        items: File
    doc: BAM file(s) - space separated - with RNA-Seq information, by default 
      will be displayed as bigWig
    inputBinding:
      position: 101
      prefix: --bam
  - id: bam2wig_path
    type:
      - 'null'
      - string
    doc: Path to bam2wig executable
    inputBinding:
      position: 101
      prefix: --BAM2WIG_PATH
  - id: braker_genes
    type:
      - 'null'
      - File
    doc: GTF file with BRAKER genes (generated by TSEBRA).
    inputBinding:
      position: 101
      prefix: --braker_genes
  - id: braker_out_dir
    type:
      - 'null'
      - Directory
    doc: BRAKER output directory with GTF files; works also for GALBA, warnings 
      are expected in case of GALBA as input.
    inputBinding:
      position: 101
      prefix: --braker_out_dir
  - id: display_bam_as_bam
    type:
      - 'null'
      - boolean
    doc: Display BAM file(s) as bam tracks
    inputBinding:
      position: 101
      prefix: --display_bam_as_bam
  - id: email
    type:
      - 'null'
      - string
    doc: Contact e-mail adress for assembly hub
    inputBinding:
      position: 101
      prefix: --email
  - id: gemoma_filtered_predictions
    type:
      - 'null'
      - File
    doc: GFF3 output file of Gemoma
    inputBinding:
      position: 101
      prefix: --gemoma_filtered_predictions
  - id: gene_track
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Gene track with user specified label, argument must be formatted as follows:
      --gene_track file.gtf tracklabel'
    inputBinding:
      position: 101
      prefix: --gene_track
  - id: genemark
    type:
      - 'null'
      - File
    doc: GTF file with GeneMark predictions
    inputBinding:
      position: 101
      prefix: --genemark
  - id: genome
    type:
      - 'null'
      - File
    doc: Genome fasta file (possibly softmasked)
    inputBinding:
      position: 101
      prefix: --genome
  - id: glimmer_gff
    type:
      - 'null'
      - File
    doc: GFF3 output file of GlimmerHMM
    inputBinding:
      position: 101
      prefix: --glimmer_gff
  - id: hints
    type:
      - 'null'
      - File
    doc: GFF file with AUGUSTUS hints
    inputBinding:
      position: 101
      prefix: --hints
  - id: latin_name
    type:
      - 'null'
      - string
    doc: Latin species name, e.g. "Drosophila melanogaster". This argument must 
      be provided if the hub is supposed to be added to the public UCSC list.
    inputBinding:
      position: 101
      prefix: --latin_name
  - id: long_label
    type:
      - 'null'
      - string
    doc: Long label for hub, e.g. species name in english and latin, pass in 
      single quotation marks, e.g. --long_label 'Dorosphila melanogster (fruit 
      fly)'
    inputBinding:
      position: 101
      prefix: --long_label
  - id: maker_gff
    type:
      - 'null'
      - File
    doc: MAKER2 output file in GFF3 format
    inputBinding:
      position: 101
      prefix: --maker_gff
  - id: no_genepred_to_biggenepred
    type:
      - 'null'
      - boolean
    doc: Option for the special case in which the precompiled UCSC binaries are 
      not working on your system, and you installed kentutils from the older 
      ENCODE github repository; if activated, gene prediction tracks will be 
      output to bigBed instead of bigGenePred format and amino acid display will
      not be possible in gene tracks.
    inputBinding:
      position: 101
      prefix: --no_genePredToBigGenePred
  - id: no_repeats
    type:
      - 'null'
      - boolean
    doc: Disable repeat track generation from softmasked genome sequence (saves 
      time)
    inputBinding:
      position: 101
      prefix: --no_repeats
  - id: no_tmp_rm
    type:
      - 'null'
      - boolean
    doc: Do not delete temporary files
    inputBinding:
      position: 101
      prefix: --no_tmp_rm
  - id: print_usage_examples
    type:
      - 'null'
      - boolean
    doc: Print usage examples for make_hub.py
    inputBinding:
      position: 101
      prefix: --printUsageExamples
  - id: samtools_path
    type:
      - 'null'
      - string
    doc: Path to samtools executable
    inputBinding:
      position: 101
      prefix: --SAMTOOLS_PATH
  - id: short_label
    type:
      - 'null'
      - string
    doc: Short label for hub, will also be used as directory name for hub, 
      should not contain spaces or special characters, e.g. --short_label fly
    inputBinding:
      position: 101
      prefix: --short_label
  - id: snap_gff
    type:
      - 'null'
      - File
    doc: SNAP output file in GFF3 format
    inputBinding:
      position: 101
      prefix: --snap_gff
  - id: threads
    type:
      - 'null'
      - int
    doc: Number of threads for samtools sort processes
    inputBinding:
      position: 101
      prefix: --threads
  - id: traingenes
    type:
      - 'null'
      - File
    doc: GTF file with training genes
    inputBinding:
      position: 101
      prefix: --traingenes
  - id: verbosity
    type:
      - 'null'
      - int
    doc: If INT>0 verbose output log is produced
    inputBinding:
      position: 101
      prefix: --verbosity
outputs:
  - id: outdir
    type:
      - 'null'
      - Directory
    doc: output directory to write hub to
    outputBinding:
      glob: $(inputs.outdir)
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/makehub:1.0.8--hdfd78af_1
