cwlVersion: v1.2
class: CommandLineTool
baseCommand: snakemake
label: hybracter_install
doc: "Snakemake is a Python based language and execution environment for GNU Make-like
  workflows.\n\nTool homepage: https://github.com/gbouras13/hybracter"
inputs:
  - id: targets
    type:
      - 'null'
      - type: array
        items: string
    doc: Targets to build. May be rules or files.
    inputBinding:
      position: 1
  - id: all_temp
    type:
      - 'null'
      - boolean
    doc: Mark all output files as temp files. This can be useful for CI testing,
      in order to save space.
    inputBinding:
      position: 102
      prefix: --all-temp
  - id: allow_ambiguity
    type:
      - 'null'
      - boolean
    doc: Don't check for ambiguous rules and simply use the first if several can
      produce the same file. This allows the user to prioritize rules by their 
      order in the snakefile.
    inputBinding:
      position: 102
      prefix: --allow-ambiguity
  - id: allowed_rules
    type:
      - 'null'
      - type: array
        items: string
    doc: Only consider given rules. If omitted, all rules in Snakefile are used.
      Note that this is intended primarily for internal use and may lead to 
      unexpected results otherwise. Meant for internal use or debugging.
    inputBinding:
      position: 102
      prefix: --allowed-rules
  - id: apptainer_args
    type:
      - 'null'
      - string
    doc: Pass additional args to apptainer/singularity.
    inputBinding:
      position: 102
      prefix: --singularity-args
  - id: apptainer_prefix
    type:
      - 'null'
      - Directory
    doc: Specify a directory in which apptainer/singularity images will be 
      stored.If not supplied, the value is set to the `.snakemake` directory 
      relative to the invocation directory. If supplied, the `--use- apptainer` 
      flag must also be set. The value may be given as a relative path, which 
      will be extrapolated to the invocation directory, or as an absolute path. 
      If not supplied, APPTAINER_CACHEDIR is used. In any case, the prefix may 
      contain environment variables which will be properly expanded. Note that 
      if you use remote execution e.g. on a cluster and you have node specific 
      values for this, you should disable assuming shared fs for 
      software-deployment (see `--shared-fs- usage`).
    inputBinding:
      position: 102
      prefix: --singularity-prefix
  - id: archive
    type:
      - 'null'
      - File
    doc: Archive the workflow into the given tar archive FILE. The archive will 
      be created such that the workflow can be re-executed on a vanilla system. 
      The function needs conda and git to be installed. It will archive every 
      file that is under git version control. Note that it is best practice to 
      have the Snakefile, config files, and scripts under version control. 
      Hence, they will be included in the archive. Further, it will add input 
      files that are not generated by by the workflow itself and conda 
      environments. Note that symlinks are dereferenced. Supported formats are 
      .tar, .tar.gz, .tar.bz2 and .tar.xz.
    inputBinding:
      position: 102
      prefix: --archive
  - id: attempt
    type:
      - 'null'
      - int
    doc: 'Internal use only: define the initial value of the attempt parameter.'
    inputBinding:
      position: 102
      prefix: --attempt
  - id: batch
    type:
      - 'null'
      - string
    doc: Only create the given BATCH of the input files of the given RULE. This 
      can be used to iteratively run parts of very large workflows. Only the 
      execution plan of the relevant part of the workflow has to be calculated, 
      thereby speeding up DAG computation. It is recommended to provide the most
      suitable rule for batching when documenting a workflow. It should be some 
      aggregating rule that would be executed only once, and has a large number 
      of input files. For example, it can be a rule that aggregates over 
      samples.
    inputBinding:
      position: 102
      prefix: --batch
  - id: benchmark_extended
    type:
      - 'null'
      - boolean
    doc: Write extended benchmarking metrics.
    inputBinding:
      position: 102
      prefix: --benchmark-extended
  - id: cache
    type:
      - 'null'
      - type: array
        items: string
    doc: Store output files of given rules in a central cache given by the 
      environment variable `$SNAKEMAKE_OUTPUT_CACHE`. Likewise, retrieve output 
      files of the given rules from this cache if they have been created before 
      (by anybody writing to the same cache), instead of actually executing the 
      rules. Output files are identified by hashing all steps, parameters and 
      software stack (conda envs or containers) needed to create them. If no 
      rules are given, all rules that are eligible for caching (have a cache 
      directive, see docs) are cached.
    inputBinding:
      position: 102
      prefix: --cache
  - id: cleanup_metadata
    type:
      - 'null'
      - type: array
        items: File
    doc: Cleanup the metadata of given files. That means that snakemake removes 
      any tracked version info, and any marks that files are incomplete.
    inputBinding:
      position: 102
      prefix: --cleanup-metadata
  - id: cleanup_shadow
    type:
      - 'null'
      - boolean
    doc: Cleanup old shadow directories which have not been deleted due to 
      failures or power loss.
    inputBinding:
      position: 102
      prefix: --cleanup-shadow
  - id: conda_base_path
    type:
      - 'null'
      - Directory
    doc: Path of conda base installation (home of conda, mamba, activate) 
      (internal use only).
    inputBinding:
      position: 102
      prefix: --conda-base-path
  - id: conda_cleanup_envs
    type:
      - 'null'
      - boolean
    doc: Cleanup unused conda environments.
    inputBinding:
      position: 102
      prefix: --conda-cleanup-envs
  - id: conda_cleanup_pkgs
    type:
      - 'null'
      - type: array
        items: string
    doc: Cleanup conda packages after creating environments. In case of 
      `tarballs` mode, will clean up all downloaded package tarballs. In case of
      `cache` mode, will additionally clean up unused package caches.
      - tarballs
    inputBinding:
      position: 102
      prefix: --conda-cleanup-pkgs
  - id: conda_create_envs_only
    type:
      - 'null'
      - boolean
    doc: If specified, only creates the job-specific conda environments then 
      exits. The `--use-conda` flag must also be set.
    inputBinding:
      position: 102
      prefix: --conda-create-envs-only
  - id: conda_frontend
    type:
      - 'null'
      - string
    doc: Choose the conda frontend for installing environments.
    inputBinding:
      position: 102
      prefix: --conda-frontend
  - id: conda_not_block_search_path_envvars
    type:
      - 'null'
      - boolean
    doc: Do not block environment variables that modify the search path (R_LIBS,
      PYTHONPATH, PERL5LIB, PERLLIB) when using conda environments.
    inputBinding:
      position: 102
      prefix: --conda-not-block-search-path-envvars
  - id: conda_prefix
    type:
      - 'null'
      - Directory
    doc: Specify a directory in which the `conda` and `conda- archive` 
      directories are created. These are used to store conda environments and 
      their archives, respectively. If not supplied, the value is set to the 
      `.snakemake` directory relative to the invocation directory. If supplied, 
      the `--use-conda` flag must also be set. The value may be given as a 
      relative path, which will be extrapolated to the invocation directory, or 
      as an absolute path. The value can also be provided via the environment 
      variable $SNAKEMAKE_CONDA_PREFIX. In any case, the prefix may contain 
      environment variables which will be properly expanded. Note that if you 
      use remote execution e.g. on a cluster and you have node specific values 
      for this, you should disable assuming shared fs for software-deployment 
      (see `--shared-fs-usage`).
    inputBinding:
      position: 102
      prefix: --conda-prefix
  - id: config
    type:
      - 'null'
      - type: array
        items: string
    doc: Set or overwrite values in the workflow config object. The workflow 
      config object is accessible as variable config inside the workflow. 
      Default values can be set by providing a YAML JSON file (see 
      `--configfile` and Documentation).
    inputBinding:
      position: 102
      prefix: --config
  - id: configfile
    type:
      - 'null'
      - type: array
        items: File
    doc: Specify or overwrite the config file of the workflow (see the docs). 
      Values specified in JSON or YAML format are available in the global config
      dictionary inside the workflow. Multiple files overwrite each other in the
      given order. Thereby missing keys in previous config files are extended by
      following configfiles. Note that this order also includes a config file 
      defined in the workflow definition itself (which will come first).
    inputBinding:
      position: 102
      prefix: --configfile
  - id: consider_ancient
    type:
      - 'null'
      - type: array
        items: string
    doc: Consider given input items of given rules as ancient, i.e. not 
      triggering re-runs if they are newer than the output files. Putting this 
      into a workflow specific profile (or specifying as argument) allows to 
      overrule rerun triggers caused by file modification dates where the user 
      knows better. RULE is the name of the rule, INPUTITEMS is a comma 
      separated list of input items of the rule (given as name or index 
      (0-based)).
    inputBinding:
      position: 102
      prefix: --consider-ancient
  - id: container_cleanup_images
    type:
      - 'null'
      - boolean
    doc: 'Remove unused containers (default: False)'
    inputBinding:
      position: 102
      prefix: --container-cleanup-images
  - id: container_image
    type:
      - 'null'
      - string
    doc: Docker image to use, e.g., when submitting jobs to kubernetes. Defaults
      to https://hub.docker.com/r/snakemake/snakemake, tagged with the same 
      version as the currently running Snakemake instance. Note that overwriting
      this value is up to your responsibility. Any used image has to contain a 
      working snakemake installation that is compatible with (or ideally the 
      same as) the currently running version.
    inputBinding:
      position: 102
      prefix: --container-image
  - id: containerize
    type:
      - 'null'
      - boolean
    doc: Print a Dockerfile that provides an execution environment for the 
      workflow, including all conda environments.
    inputBinding:
      position: 102
      prefix: --containerize
  - id: cores
    type:
      - 'null'
      - int
    doc: Use at most N CPU cores/jobs in parallel. If N is omitted or `all`, the
      limit is set to the number of available CPU cores. In case of 
      cluster/cloud execution, this argument sets the maximum number of cores 
      requested from the cluster or cloud scheduler. (See 
      https://snakemake.readthedocs.io/en/stable/snakef 
      iles/rules.html#resources-remote-execution for more info.) This number is 
      available to rules via workflow.cores.
    inputBinding:
      position: 102
      prefix: --cores
  - id: d3dag
    type:
      - 'null'
      - boolean
    doc: Print the DAG in D3.js compatible JSON format.
    inputBinding:
      position: 102
      prefix: --d3dag
  - id: dag
    type:
      - 'null'
      - string
    doc: 'Do not execute anything and print the directed acyclic graph of jobs in
      the dot language or in mermaid-js. Recommended use on Unix systems: `snakemake
      --dag | dot | display`. Note print statements in your Snakefile may interfere
      with visualization.'
    inputBinding:
      position: 102
      prefix: --dag
  - id: debug
    type:
      - 'null'
      - boolean
    doc: Allow to debug rules with e.g. PDB. This flag allows to set breakpoints
      in run blocks.
    inputBinding:
      position: 102
      prefix: --debug
  - id: debug_dag
    type:
      - 'null'
      - boolean
    doc: Print candidate and selected jobs (including their wildcards) while 
      inferring DAG. This can help to debug unexpected DAG topology or errors.
    inputBinding:
      position: 102
      prefix: --debug-dag
  - id: default_resources
    type:
      - 'null'
      - type: array
        items: string
    doc: Define default values of resources for rules that do not define their 
      own values. In addition to plain integers, python expressions over 
      inputsize are allowed (e.g. `2*input.size_mb`). The inputsize is the sum 
      of the sizes of all input files of a rule. By default, Snakemake assumes a
      default for mem_mb, disk_mb, and tmpdir (see below). This option allows to
      add further defaults (e.g. account and partition for slurm) or to 
      overwrite these default values. The defaults are 
      `mem_mb=min(max(2*input.size_mb, 1000), 8000)`, 
      `disk_mb=max(2*input.size_mb, 1000)` (i.e., default disk and mem usage is 
      twice the input file size but at least 1GB), and the system temporary 
      directory (as given by $TMPDIR, $TEMP, or $TMP) is used for the tmpdir 
      resource. The tmpdir resource is automatically used by shell commands, 
      scripts and wrappers to store temporary data (as it is mirrored into 
      $TMPDIR, $TEMP, and $TMP for the executed subprocesses). If this argument 
      is not specified at all, Snakemake just uses the tmpdir resource as 
      outlined above. The tmpdir resource can also be overwritten in the same 
      way as e.g. mem_mb above. Thereby, it is even possible to use 
      shutil.disk_usage(system_tmpdir).free and comparing this to input.size in 
      order to determine if one can expect the system_tmpdir to be big enough 
      and switch to another tmpdir in case it is not.
    inputBinding:
      position: 102
      prefix: --default-resources
  - id: default_storage_prefix
    type:
      - 'null'
      - string
    doc: Specify prefix for default storage provider. E.g. a bucket name.
    inputBinding:
      position: 102
      prefix: --default-storage-prefix
  - id: default_storage_provider
    type:
      - 'null'
      - string
    doc: Specify default storage provider to be used for all input and output 
      files that don't yet specify one (e.g. `s3`). See 
      https://snakemake.github.io/snakemake-plugin-catalog for available storage
      provider plugins. If not set or explicitly `none`, no default storage 
      provider will be used.
    inputBinding:
      position: 102
      prefix: --default-storage-provider
  - id: delete_all_output
    type:
      - 'null'
      - boolean
    doc: Remove all files generated by the workflow. Use together with 
      `--dry-run` to list files without actually deleting anything. Note that 
      this will not recurse into subworkflows. Write-protected files are not 
      removed. Nevertheless, use with care!
    inputBinding:
      position: 102
      prefix: --delete-all-output
  - id: delete_temp_output
    type:
      - 'null'
      - boolean
    doc: Remove all temporary files generated by the workflow. Use together with
      `--dry-run` to list files without actually deleting anything. Note that 
      this will not recurse into subworkflows.
    inputBinding:
      position: 102
      prefix: --delete-temp-output
  - id: deploy_sources
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Internal use only: Deploy sources archive from given storage provider query
      to the current working subdirectory and control for archive checksum to proceed.'
    inputBinding:
      position: 102
      prefix: --deploy-sources
  - id: detailed_summary
    type:
      - 'null'
      - boolean
    doc: 'Print a summary of all files created by the workflow. The has the following
      columns: filename, modification time, rule version, input file(s), shell command,
      status, plan. Thereby rule version contains the version the file was created
      with (see the version keyword of rules), and status denotes whether the file
      is missing, its input files are newer or if version or implementation of the
      rule changed since file creation. The input file and shell command columns are
      self explanatory. Finally the last column denotes whether the file will be updated
      or created during the next workflow execution.'
    inputBinding:
      position: 102
      prefix: --detailed-summary
  - id: directory
    type:
      - 'null'
      - Directory
    doc: Specify working directory (relative paths in the snakefile will use 
      this as their origin).
    inputBinding:
      position: 102
      prefix: --directory
  - id: draft_notebook
    type:
      - 'null'
      - string
    doc: Draft a skeleton notebook for the rule used to generate the given 
      target file. This notebook can then be opened in a jupyter server, 
      executed and implemented until ready. After saving, it will automatically 
      be reused in non-interactive mode by Snakemake for subsequent jobs.
    inputBinding:
      position: 102
      prefix: --draft-notebook
  - id: drop_metadata
    type:
      - 'null'
      - boolean
    doc: Drop metadata file tracking information after job finishes. 
      Provenance-information based reports (e.g. `--report` and the 
      `--list_x_changes` functions) will be empty or incomplete.
    inputBinding:
      position: 102
      prefix: --drop-metadata
  - id: dry_run
    type:
      - 'null'
      - boolean
    doc: Do not execute anything, and display what would be done. If you have a 
      very large workflow, use `--dry-run --quiet` to just print a summary of 
      the DAG of jobs.
    inputBinding:
      position: 102
      prefix: --dry-run
  - id: edit_notebook
    type:
      - 'null'
      - string
    doc: Interactively edit the notebook associated with the rule used to 
      generate the given target file. This will start a local jupyter notebook 
      server. Any changes to the notebook should be saved, and the server has to
      be stopped by closing the notebook and hitting the `Quit` button on the 
      jupyter dashboard. Afterwards, the updated notebook will be automatically 
      stored in the path defined in the rule. If the notebook is not yet 
      present, this will create an empty draft.
    inputBinding:
      position: 102
      prefix: --edit-notebook
  - id: envvars
    type:
      - 'null'
      - type: array
        items: string
    doc: Environment variables to pass to cloud jobs.
    inputBinding:
      position: 102
      prefix: --envvars
  - id: executor
    type:
      - 'null'
      - string
    doc: 'Specify a custom executor, available via an executor plugin: snakemake_executor_<name>'
    inputBinding:
      position: 102
      prefix: --executor
  - id: export_cwl
    type:
      - 'null'
      - File
    doc: Compile workflow to CWL and store it in given FILE.
    inputBinding:
      position: 102
      prefix: --export-cwl
  - id: filegraph
    type:
      - 'null'
      - boolean
    doc: 'Do not execute anything and print the dependency graph of rules with their
      input and output files in the dot language. This is an intermediate solution
      between above DAG of jobs and the rule graph. Note that each rule is displayed
      once, hence the displayed graph will be cyclic if a rule appears in several
      steps of the workflow. Use this if above option leads to a DAG that is too large.
      Recommended use on Unix systems: snakemake --filegraph | dot | display. Note
      print statements in your Snakefile may interfere with visualization.'
    inputBinding:
      position: 102
      prefix: --filegraph
  - id: force
    type:
      - 'null'
      - boolean
    doc: Force the execution of the selected target or the first rule regardless
      of already created output.
    inputBinding:
      position: 102
      prefix: --force
  - id: force_use_threads
    type:
      - 'null'
      - boolean
    doc: Force threads rather than processes. Helpful if shared memory 
      (/dev/shm) is full or unavailable.
    inputBinding:
      position: 102
      prefix: --force-use-threads
  - id: forceall
    type:
      - 'null'
      - boolean
    doc: Force the execution of the selected (or the first) rule and all rules 
      it is dependent on regardless of already created output.
    inputBinding:
      position: 102
      prefix: --forceall
  - id: forcerun
    type:
      - 'null'
      - type: array
        items: string
    doc: Force the re-execution or creation of the given rules or files. Use 
      this option if you changed a rule and want to have all its output in your 
      workflow updated.
    inputBinding:
      position: 102
      prefix: --forcerun
  - id: generate_unit_tests
    type:
      - 'null'
      - Directory
    doc: Automatically generate unit tests for each workflow rule. This assumes 
      that all input files of each job are already present. Jobs without present
      input files will be skipped (a warning will be issued). For each rule, one
      test case will be created and, after successful execution, tests can be 
      run with `pytest TESTPATH`.
    inputBinding:
      position: 102
      prefix: --generate-unit-tests
  - id: group_components
    type:
      - 'null'
      - type: array
        items: string
    doc: Set the number of connected components a group is allowed to span. By 
      default, this is 1, but this flag allows to extend this. This can be used 
      to run e.g. 3 jobs of the same rule in the same group, although they are 
      not connected. It can be helpful for putting together many small jobs or 
      benefitting of shared memory setups.
    inputBinding:
      position: 102
      prefix: --group-components
  - id: groups
    type:
      - 'null'
      - type: array
        items: string
    doc: Assign rules to groups (this overwrites any group definitions from the 
      workflow).
    inputBinding:
      position: 102
      prefix: --groups
  - id: ignore_incomplete
    type:
      - 'null'
      - boolean
    doc: Do not check for incomplete output files.
    inputBinding:
      position: 102
      prefix: --ignore-incomplete
  - id: immediate_submit
    type:
      - 'null'
      - boolean
    doc: "Immediately submit all jobs to the cluster instead of waiting for present
      input files. This will fail, unless you make the cluster aware of job dependencies,
      e.g. via: `$ snakemake --cluster 'sbatch --dependency {dependencies}'`. Assuming
      that your submit script (here sbatch) outputs the generated job id to the first
      stdout line, {dependencies} will be filled with space separated job ids this
      job depends on. Does not work for workflows that contain checkpoint rules, and
      localrules will be skipped. The additional argument `--notemp` should be specified.
      Most often, `--not- retrieve-storage` is also recommended to avoid Snakemake
      trying to download output files before the jobs producing them are executed."
    inputBinding:
      position: 102
      prefix: --immediate-submit
  - id: job_deploy_sources
    type:
      - 'null'
      - boolean
    doc: Whether the workflow sources shall be deployed before a remote job is 
      started. Only applies if `--no-shared- fs` is set or executors are used 
      that imply no shared FS (e.g. the kubernetes executor).
    inputBinding:
      position: 102
      prefix: --job-deploy-sources
  - id: jobname
    type:
      - 'null'
      - string
    doc: Provide a custom name for the jobscript that is submitted to the 
      cluster (see `--cluster`). The wildcard `{jobid}` has to be present in the
      name.
    inputBinding:
      position: 102
      prefix: --jobname
  - id: jobs
    type:
      - 'null'
      - string
    doc: 'Use at most N CPU cluster/cloud jobs in parallel. For local execution this
      is an alias for `--cores` (it is though recommended to use `--cores` in that
      case). Note: Set to `unlimited` to allow any number of parallel jobs.'
    inputBinding:
      position: 102
      prefix: --jobs
  - id: jobscript
    type:
      - 'null'
      - File
    doc: Provide a custom job script for submission to the cluster. The default 
      script resides as `jobscript.sh` in the installation directory.
    inputBinding:
      position: 102
      prefix: --jobscript
  - id: keep_going
    type:
      - 'null'
      - boolean
    doc: Go on with independent jobs if a job fails during execution. This only 
      applies to runtime failures in job execution, not to errors during 
      workflow parsing or DAG construction.
    inputBinding:
      position: 102
      prefix: --keep-going
  - id: keep_incomplete
    type:
      - 'null'
      - boolean
    doc: Do not remove incomplete output files by failed jobs.
    inputBinding:
      position: 102
      prefix: --keep-incomplete
  - id: keep_storage_local_copies
    type:
      - 'null'
      - boolean
    doc: Keep local copies of remote input and output files.
    inputBinding:
      position: 102
      prefix: --keep-storage-local-copies
  - id: latency_wait
    type:
      - 'null'
      - int
    doc: Wait given seconds if an output file of a job is not present after the 
      job finished. This helps if your filesystem suffers from latency.
    inputBinding:
      position: 102
      prefix: --latency-wait
  - id: lint
    type:
      - 'null'
      - string
    doc: Perform linting on the given workflow. This will print snakemake 
      specific suggestions to improve code quality (work in progress, more lints
      to be added in the future). If no argument is provided, plain text output 
      is used.
    inputBinding:
      position: 102
      prefix: --lint
  - id: list_changes
    type:
      - 'null'
      - type: array
        items: string
    doc: List all output files for which the given items (code, input, params) 
      have changed since creation.
    inputBinding:
      position: 102
      prefix: --list-changes
  - id: list_conda_envs
    type:
      - 'null'
      - boolean
    doc: List all conda environments and their location on disk.
    inputBinding:
      position: 102
      prefix: --list-conda-envs
  - id: list_input_changes
    type:
      - 'null'
      - boolean
    doc: List all output files for which the defined input files have changed in
      the Snakefile (e.g. new input files were added in the rule definition or 
      files were renamed). For listing input file modification in the 
      filesystem, use `--summary`.
    inputBinding:
      position: 102
      prefix: --list-input-changes
  - id: list_params_changes
    type:
      - 'null'
      - boolean
    doc: List all output files for which the defined params have changed in the 
      Snakefile.
    inputBinding:
      position: 102
      prefix: --list-params-changes
  - id: list_rules
    type:
      - 'null'
      - boolean
    doc: Show available rules in given Snakefile.
    inputBinding:
      position: 102
      prefix: --list-rules
  - id: list_target_rules
    type:
      - 'null'
      - boolean
    doc: Show available target rules in given Snakefile.
    inputBinding:
      position: 102
      prefix: --list-target-rules
  - id: list_untracked
    type:
      - 'null'
      - boolean
    doc: List all files in the working directory that are not used in the 
      workflow. This can be used e.g. for identifying leftover files. Hidden 
      files and directories are ignored.
    inputBinding:
      position: 102
      prefix: --list-untracked
  - id: local_cores
    type:
      - 'null'
      - int
    doc: 'In cluster/cloud mode, use at most N cores of the host machine in parallel
      (default: number of CPU cores of the host). The cores are used to execute local
      rules. This option is ignored when not in cluster/cloud mode.'
    inputBinding:
      position: 102
      prefix: --local-cores
  - id: local_groupid
    type:
      - 'null'
      - string
    doc: 'Internal use only: Name for local groupid.'
    inputBinding:
      position: 102
      prefix: --local-groupid
  - id: local_storage_prefix
    type:
      - 'null'
      - Directory
    doc: 'Specify prefix for storing local copies of storage files and folders (e.g.
      local scratch disk). Environment variables will be expanded. (default: .snakemake/storage)'
    inputBinding:
      position: 102
      prefix: --local-storage-prefix
  - id: logger
    type:
      - 'null'
      - type: array
        items: string
    doc: Specify one or more custom loggers, available via logger plugins.
    inputBinding:
      position: 102
      prefix: --logger
  - id: max_checksum_file_size
    type:
      - 'null'
      - string
    doc: Compute the checksum during DAG computation and job postprocessing only
      for files that are smaller than the provided threshold (given in any valid
      size unit, e.g. 1MB, which is also the default).
    inputBinding:
      position: 102
      prefix: --max-checksum-file-size
  - id: max_inventory_time
    type:
      - 'null'
      - int
    doc: Spend at most SECONDS seconds to create a file inventory for the 
      working directory. The inventory vastly speeds up file modification and 
      existence checks when computing which jobs need to be executed. However, 
      creating the inventory itself can be slow, e.g. on network file systems. 
      Hence, we do not spend more than a given amount of time and fall back to 
      individual checks for the rest.
    inputBinding:
      position: 102
      prefix: --max-inventory-time
  - id: max_jobs_per_second
    type:
      - 'null'
      - string
    doc: Maximal number of job submissions/executions per second. Deprecated in 
      favor of `--max-jobs-per-timespan`.
    inputBinding:
      position: 102
      prefix: --max-jobs-per-second
  - id: max_jobs_per_timespan
    type:
      - 'null'
      - string
    doc: 'Maximal number of job submissions/executions per timespan. Format: <number><timespan>,
      e.g. 50/1m or 0.5/1s.'
    inputBinding:
      position: 102
      prefix: --max-jobs-per-timespan
  - id: max_status_checks_per_second
    type:
      - 'null'
      - float
    doc: Maximal number of job status checks per second; fractions allowed.
    inputBinding:
      position: 102
      prefix: --max-status-checks-per-second
  - id: max_threads
    type:
      - 'null'
      - int
    doc: Define a global maximum number of threads available to any rule. Rules 
      requesting more threads (via the threads keyword) will have their values 
      reduced to the maximum. This can be useful when you want to restrict the 
      maximum number of threads without modifying the workflow definition or 
      overwriting rules individually with `--set-threads`.
    inputBinding:
      position: 102
      prefix: --max-threads
  - id: mode
    type:
      - 'null'
      - string
    doc: 'Internal use only: Set execution mode of Snakemake.'
    inputBinding:
      position: 102
      prefix: --mode
  - id: no_hooks
    type:
      - 'null'
      - boolean
    doc: Do not invoke onstart, onsuccess or onerror hooks after execution.
    inputBinding:
      position: 102
      prefix: --no-hooks
  - id: no_subworkflows
    type:
      - 'null'
      - boolean
    doc: Do not evaluate or execute subworkflows.
    inputBinding:
      position: 102
      prefix: --no-subworkflows
  - id: nocolor
    type:
      - 'null'
      - boolean
    doc: Do not use a colored output.
    inputBinding:
      position: 102
      prefix: --nocolor
  - id: nolock
    type:
      - 'null'
      - boolean
    doc: Do not lock the working directory
    inputBinding:
      position: 102
      prefix: --nolock
  - id: not_retrieve_storage
    type:
      - 'null'
      - boolean
    doc: Do not retrieve remote files (default is to retrieve remote files).
    inputBinding:
      position: 102
      prefix: --not-retrieve-storage
  - id: notebook_listen
    type:
      - 'null'
      - string
    doc: The IP address and PORT the notebook server used for editing the 
      notebook (`--edit-notebook`) will listen on.
    inputBinding:
      position: 102
      prefix: --notebook-listen
  - id: notemp
    type:
      - 'null'
      - boolean
    doc: Ignore temp() declarations. This is useful when running only a part of 
      the workflow, since temp() would lead to deletion of probably needed files
      by other parts of the workflow.
    inputBinding:
      position: 102
      prefix: --notemp
  - id: omit_flags
    type:
      - 'null'
      - type: array
        items: string
    doc: Omit the given input and output file flags (e.g. pipe). This can be 
      useful for debugging.
    inputBinding:
      position: 102
      prefix: --omit-flags
  - id: omit_from
    type:
      - 'null'
      - type: array
        items: string
    doc: Prevent the execution or creation of the given rules or files as well 
      as any rules or files that are downstream of these targets in the DAG. 
      Also runs jobs in sibling DAGs that are independent of the rules or files 
      specified here.
    inputBinding:
      position: 102
      prefix: --omit-from
  - id: precommand
    type:
      - 'null'
      - string
    doc: Only used in case of remote execution. Command to be executed before 
      Snakemake executes each job on the remote compute node.
    inputBinding:
      position: 102
      prefix: --precommand
  - id: preemptible_retries
    type:
      - 'null'
      - int
    doc: Number of retries that shall be made in order to finish a job from of 
      rule that has been marked as preemptible via the --preemptible-rules 
      setting.
    inputBinding:
      position: 102
      prefix: --preemptible-retries
  - id: preemptible_rules
    type:
      - 'null'
      - type: array
        items: string
    doc: Define which rules shall use a preemptible machine which can be 
      prematurely killed by e.g. a cloud provider (also called spot instances). 
      This is currently only supported by the Google Life Sciences executor and 
      ignored by all other executors. If no rule names are provided, all rules 
      are considered to be preemptible.
    inputBinding:
      position: 102
      prefix: --preemptible-rules
  - id: print_compilation
    type:
      - 'null'
      - boolean
    doc: Print the python representation of the workflow.
    inputBinding:
      position: 102
      prefix: --print-compilation
  - id: printshellcmds
    type:
      - 'null'
      - boolean
    doc: Print out the shell commands that will be executed.
    inputBinding:
      position: 102
      prefix: --printshellcmds
  - id: prioritize
    type:
      - 'null'
      - type: array
        items: string
    doc: Tell the scheduler to assign creation of given targets (and all their 
      dependencies) highest priority.
    inputBinding:
      position: 102
      prefix: --prioritize
  - id: profile
    type:
      - 'null'
      - string
    doc: 'Name of profile to use for configuring Snakemake. Snakemake will search
      for a corresponding folder in `/etc/xdg/snakemake` and `/root/.config/snakemake`.
      Alternatively, this can be an absolute or relative path. The profile folder
      has to contain a file `config.yaml`. This file can be used to set default values
      for command line options in YAML format. For example, `--cluster qsub` becomes
      `cluster: qsub` in the YAML file. Profiles can be obtained from https://github.com/snakemake-profiles.
      The profile can also be set via the environment variable `$SNAKEMAKE_PROFILE`.
      To override this variable and use no profile at all, provide the value `none`
      to this argument.'
    inputBinding:
      position: 102
      prefix: --profile
  - id: queue_input_wait_time
    type:
      - 'null'
      - int
    doc: Set the interval in seconds to check for new input in rules that use 
      from_queue to obtain input files.
    inputBinding:
      position: 102
      prefix: --queue-input-wait-time
  - id: quiet
    type:
      - 'null'
      - type: array
        items: string
    doc: Do not output certain information. If used without arguments, do not 
      output any progress or rule information. Defining `all` results in no 
      information being printed at all.
    inputBinding:
      position: 102
      prefix: --quiet
  - id: remote_job_local_storage_prefix
    type:
      - 'null'
      - Directory
    doc: 'Specify prefix for storing local copies of storage files and folders (e.g.
      local scratch disk) in case of remote jobs (e.g. cluster or cloud jobs). Environment
      variables will be expanded within the remote job. (default: .snakemake/storage)'
    inputBinding:
      position: 102
      prefix: --remote-job-local-storage-prefix
  - id: replace_workflow_config
    type:
      - 'null'
      - boolean
    doc: Config files provided via command line do not update and extend the 
      config dictionary of the workflow but instead fully replace it. Keys that 
      are not defined in the provided config files will be undefined even if 
      specified within the workflow config.
    inputBinding:
      position: 102
      prefix: --replace-workflow-config
  - id: report
    type:
      - 'null'
      - File
    doc: Create a self-contained HTML report with default statistics, provenance
      information and user-specified results. For smaller datasets with a 
      limited report complexity, you can specify an `.html` file and all results
      will be embedded directly into this file. For customized reports on larger
      sample sizes, it makes more sense to specify a `.zip` file. The resulting 
      archive will spread the contents across a folder structure, for a quicker 
      loading of individual results. You can unpack this archive anywhere and 
      open the `report.html` file in its main folder to view the report in any 
      web browser.
    inputBinding:
      position: 102
      prefix: --report
  - id: report_after_run
    type:
      - 'null'
      - boolean
    doc: After finishing the workflow, directly create the report. It is 
      required to provide --report.
    inputBinding:
      position: 102
      prefix: --report-after-run
  - id: report_html_path
    type:
      - 'null'
      - string
    doc: Path to the report file (either .html or .zip). Use zip if your report 
      contains large results or directories with htmlindex as results.
    inputBinding:
      position: 102
      prefix: --report-html-path
  - id: report_html_stylesheet_path
    type:
      - 'null'
      - string
    doc: Path to a custom stylesheet for the report.
    inputBinding:
      position: 102
      prefix: --report-html-stylesheet-path
  - id: report_metadata
    type:
      - 'null'
      - File
    doc: Custom metadata to use for the landing page of the report. In 
      particular, this can be used to provide metadata in the report e.g. the 
      work directory, see docs.
    inputBinding:
      position: 102
      prefix: --report-metadata
  - id: report_stylesheet
    type:
      - 'null'
      - File
    doc: Custom stylesheet to use for report. In particular, this can be used 
      for branding the report with e.g. a custom logo, see docs.
    inputBinding:
      position: 102
      prefix: --report-stylesheet
  - id: reporter
    type:
      - 'null'
      - string
    doc: Specify a custom report plugin. By default, Snakemake's builtin html 
      reporter will be used. For custom reporters, check out their command line 
      options starting with `--report-`.
    inputBinding:
      position: 102
      prefix: --reporter
  - id: rerun_incomplete
    type:
      - 'null'
      - boolean
    doc: Re-run all jobs the output of which is recognized as incomplete.
    inputBinding:
      position: 102
      prefix: --rerun-incomplete
  - id: rerun_triggers
    type:
      - 'null'
      - type: array
        items: string
    doc: Define what triggers the rerunning of a job. By default, all triggers 
      are used, which guarantees that results are consistent with the workflow 
      code and configuration. If you rather prefer the traditional way of just 
      considering file modification dates, use `--rerun-trigger mtime`.
    inputBinding:
      position: 102
      prefix: --rerun-triggers
  - id: resources
    type:
      - 'null'
      - type: array
        items: string
    doc: "Define additional resources that shall constrain the scheduling analogously
      to `--cores` (see above). A resource is defined as a name and an integer value.
      E.g. `--resources mem_mb=1000`. Rules can use resources by defining the resource
      keyword, e.g. `resources: mem_mb=600`. If now two rules require 600 of the resource
      `mem_mb` they won't be run in parallel by the scheduler. In cluster/cloud mode,
      this argument will also constrain the amount of resources requested from the
      server. (See https://snakemake.readthedocs.io /en/stable/snakefiles/rules.html#resources-remote-
      execution for more info.)"
    inputBinding:
      position: 102
      prefix: --resources
  - id: retries
    type:
      - 'null'
      - int
    doc: Number of times to restart failing jobs.
    inputBinding:
      position: 102
      prefix: --retries
  - id: rulegraph
    type:
      - 'null'
      - string
    doc: 'Do not execute anything and print the dependency graph of rules in the dot
      language or in mermaid-js. This will be less crowded than above DAG of jobs,
      but also show less information. Note that each rule is displayed once, hence
      the displayed graph will be cyclic if a rule appears in several steps of the
      workflow. Use this if above option leads to a DAG that is too large. Recommended
      use on Unix systems: snakemake `--rulegraph | dot | display`. Note print statements
      in your Snakefile may interfere with visualization.'
    inputBinding:
      position: 102
      prefix: --rulegraph
  - id: runtime_profile
    type:
      - 'null'
      - File
    doc: Profile Snakemake and write the output to FILE. This requires yappi to 
      be installed.
    inputBinding:
      position: 102
      prefix: --runtime-profile
  - id: runtime_source_cache_path
    type:
      - 'null'
      - Directory
    doc: Path to the runtime source cache directory. Meant for internal use.
    inputBinding:
      position: 102
      prefix: --runtime-source-cache-path
  - id: scheduler
    type:
      - 'null'
      - string
    doc: Specifies the scheduling plugin to use. Builtin plugins are greedy 
      (fast) and ilp, while the latter scheduler aims to reduce runtime and hdd 
      usage by best possible use of resources.
    inputBinding:
      position: 102
      prefix: --scheduler
  - id: scheduler_greediness
    type:
      - 'null'
      - float
    doc: Set the greediness of scheduling. This value between 0 and 1 determines
      how careful jobs are selected for execution. The default value (1.0) 
      provides the best speed and still acceptable scheduling quality. 
      Deprecated in favor of `--scheduler-greedy- greediness`.
    inputBinding:
      position: 102
      prefix: --greediness
  - id: scheduler_greedy_greediness
    type:
      - 'null'
      - float
    doc: Set the greediness of scheduling. This value between 0 and 1 determines
      how careful jobs are selected for execution. The default value (1.0) 
      provides the best speed and still acceptable scheduling quality.
    inputBinding:
      position: 102
      prefix: --scheduler-greedy-greediness
  - id: scheduler_greedy_omit_prioritize_by_temp_and_input
    type:
      - 'null'
      - boolean
    doc: If set, jobs with larger temporary or input files are not prioritized. 
      The rationale of the prioritization is that temp files should be removed 
      as soon as possible, and larger input files may take longer to process, so
      it is better to start them earlier.
    inputBinding:
      position: 102
      prefix: --scheduler-greedy-omit-prioritize-by-temp-and-input
  - id: scheduler_ilp_solver
    type:
      - 'null'
      - string
    doc: Set MILP solver to use
    inputBinding:
      position: 102
      prefix: --scheduler-ilp-solver
  - id: scheduler_ilp_solver_path
    type:
      - 'null'
      - Directory
    doc: Set the PATH to search for scheduler solver binaries.
    inputBinding:
      position: 102
      prefix: --scheduler-ilp-solver-path
  - id: scheduler_solver_path
    type:
      - 'null'
      - Directory
    doc: 'Internal use only: Set the PATH to search for scheduler solver binaries.
      Deprecated, use --scheduler-ilp-solver-path instead.'
    inputBinding:
      position: 102
      prefix: --scheduler-solver-path
  - id: scheduler_subsample
    type:
      - 'null'
      - int
    doc: Set the number of jobs to be considered for scheduling. If number of 
      ready jobs is greater than this value, this number of jobs is randomly 
      chosen for scheduling; if number of ready jobs is lower, this option has 
      no effect. This can be useful on very large DAGs, where the scheduler can 
      take some time selecting which jobs to run.
    inputBinding:
      position: 102
      prefix: --scheduler-subsample
  - id: seconds_between_status_checks
    type:
      - 'null'
      - int
    doc: Number of seconds to wait between two rounds of status checks.
    inputBinding:
      position: 102
      prefix: --seconds-between-status-checks
  - id: set_resource_scopes
    type:
      - 'null'
      - type: array
        items: string
    doc: Overwrite resource scopes. A scope determines how a constraint is 
      reckoned in cluster execution. With RESOURCE=local, a constraint applied 
      to RESOURCE using `--resources` will be considered the limit for each 
      group submission. With RESOURCE=global, the constraint will apply across 
      all groups cumulatively. By default, only `mem_mb` and `disk_mb` are 
      considered local, all other resources are global. This may be modified in 
      the snakefile using the `resource_scopes:` directive. Note that number of 
      threads, specified via `--cores`, is always considered local.
    inputBinding:
      position: 102
      prefix: --set-resource-scopes
  - id: set_resources
    type:
      - 'null'
      - type: array
        items: string
    doc: Overwrite resource usage of rules. This allows to fine-tune workflow 
      resources. In particular, this is helpful to target certain cluster nodes 
      by e.g. defining a certain partition for a rule, or overriding a temporary
      directory. Thereby, VALUE has to be a positive integer or a string, RULE 
      has to be the name of the rule, and RESOURCE has to be the name of the 
      resource.
    inputBinding:
      position: 102
      prefix: --set-resources
  - id: set_scatter
    type:
      - 'null'
      - type: array
        items: string
    doc: Overwrite number of scatter items of scattergather processes. This 
      allows to fine-tune workflow parallelization. Thereby, SCATTERITEMS has to
      be a positive integer, and NAME has to be the name of the scattergather 
      process defined via a scattergather directive in the workflow.
    inputBinding:
      position: 102
      prefix: --set-scatter
  - id: set_threads
    type:
      - 'null'
      - type: array
        items: string
    doc: Overwrite thread usage of rules. This allows to fine- tune workflow 
      parallelization. In particular, this is helpful to target certain cluster 
      nodes by e.g. shifting a rule to use more, or less threads than defined in
      the workflow. Thereby, THREADS has to be a positive integer, and RULE has 
      to be the name of the rule.
    inputBinding:
      position: 102
      prefix: --set-threads
  - id: shadow_prefix
    type:
      - 'null'
      - Directory
    doc: Specify a directory in which the `shadow` directory is created. If not 
      supplied, the value is set to the `.snakemake` directory relative to the 
      working directory.
    inputBinding:
      position: 102
      prefix: --shadow-prefix
  - id: shared_fs_usage
    type:
      - 'null'
      - type: array
        items: string
    doc: Set assumptions on shared filesystem for non-local workflow execution. 
      To disable any sharing via the filesystem, specify `none`. Usually, the 
      executor plugin sets this to a correct default. However, sometimes it is 
      worth tuning this setting, e.g. for optimizing cluster performance. For 
      example, when using `--default-storage-provider fs` together with a 
      cluster executor like slurm, you might want to set `--shared-fs-usage 
      persistence software-deployment sources source-cache`, such that software 
      deployment and data provenance will be handled by NFS but input and output
      files will be handled exclusively by the storage provider.
      - input-output
      - persistence
      - software-deployment
      - source-cache
      - sources
      - storage-local-copies
    inputBinding:
      position: 102
      prefix: --shared-fs-usage
  - id: show_failed_logs
    type:
      - 'null'
      - boolean
    doc: Automatically display logs of failed jobs.
    inputBinding:
      position: 102
      prefix: --show-failed-logs
  - id: skip_script_cleanup
    type:
      - 'null'
      - boolean
    doc: "Don't delete wrapper scripts used for execution (default: False)"
    inputBinding:
      position: 102
      prefix: --skip-script-cleanup
  - id: snakefile
    type:
      - 'null'
      - File
    doc: The workflow definition in form of a snakefile. Usually, you should not
      need to specify this. By default, Snakemake will search for `Snakefile`, 
      `snakefile`, `workflow/Snakefile`, `workflow/snakefile` beneath the 
      current working directory, in this order. Only if you definitely want a 
      different layout, you need to use this parameter.
    inputBinding:
      position: 102
      prefix: --snakefile
  - id: software_deployment_method
    type:
      - 'null'
      - type: array
        items: string
    doc: Specify software environment deployment method.
    inputBinding:
      position: 102
      prefix: --sdm
  - id: strict_dag_evaluation
    type:
      - 'null'
      - type: array
        items: string
    doc: Strict evaluation of rules' correctness even when not required to 
      produce the output files.
    inputBinding:
      position: 102
      prefix: --strict-dag-evaluation
  - id: summary
    type:
      - 'null'
      - boolean
    doc: 'Print a summary of all files created by the workflow. The has the following
      columns: filename, modification time, rule version, status, plan. Thereby rule
      version contains the version the file was created with (see the version keyword
      of rules), and status denotes whether the file is missing, its input files are
      newer or if version or implementation of the rule changed since file creation.
      Finally the last column denotes whether the file will be updated or created
      during the next workflow execution.'
    inputBinding:
      position: 102
      prefix: --summary
  - id: target_files_omit_workdir_adjustment
    type:
      - 'null'
      - boolean
    doc: Do not adjust the paths of given target files relative to the working 
      directory.
    inputBinding:
      position: 102
      prefix: --target-files-omit-workdir-adjustment
  - id: target_jobs
    type:
      - 'null'
      - type: array
        items: string
    doc: 'Internal use only: Target particular jobs by RULE:WILDCARD1=VALUE,WILDCARD2=VALUE,...'
    inputBinding:
      position: 102
      prefix: --target-jobs
  - id: touch
    type:
      - 'null'
      - boolean
    doc: Touch output files (mark them up to date without really changing them) 
      instead of running their commands. This is used to pretend that the rules 
      were executed, in order to fool future invocations of snakemake. Fails if 
      a file does not yet exist. Note that this will only touch files that would
      otherwise be recreated by Snakemake (e.g. because their input files are 
      newer). For enforcing a touch, combine this with `--force`, `--forceall`, 
      or `--forcerun`. Note however that you lose the provenance information 
      when the files have been created in reality. Hence, this should be used 
      only as a last resort.
    inputBinding:
      position: 102
      prefix: --touch
  - id: trust_io_cache
    type:
      - 'null'
      - boolean
    doc: Tell Snakemake to assume that all input and output file existence and 
      modification time queries performed in previous dryruns are still valid 
      and therefore don't have to be repeated. This can lead to speed-ups, but 
      implies that input and output have not been modified manually in between. 
      Non dry-run execution will automatically invalidate the cache and lead to 
      redoing the queries.
    inputBinding:
      position: 102
      prefix: --trust-io-cache
  - id: unlock
    type:
      - 'null'
      - boolean
    doc: Remove a lock on the working directory.
    inputBinding:
      position: 102
      prefix: --unlock
  - id: unneeded_temp_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Given files will not be uploaded to storage and immediately deleted 
      after job or group job completion.
    inputBinding:
      position: 102
      prefix: --unneeded-temp-files
  - id: until
    type:
      - 'null'
      - type: array
        items: string
    doc: Runs the pipeline until it reaches the specified rules or files. Only 
      runs jobs that are dependencies of the specified rule or files, does not 
      run sibling DAGs.
    inputBinding:
      position: 102
      prefix: --until
  - id: use_apptainer
    type:
      - 'null'
      - boolean
    doc: If defined in the rule, run job within a apptainer/singularity 
      container. If this flag is not set, the singularity directive is ignored.
    inputBinding:
      position: 102
      prefix: --use-apptainer
  - id: use_conda
    type:
      - 'null'
      - boolean
    doc: If defined in the rule, run job in a conda environment. If this flag is
      not set, the conda directive is ignored.
    inputBinding:
      position: 102
      prefix: --use-conda
  - id: use_envmodules
    type:
      - 'null'
      - boolean
    doc: If defined in the rule, run job within the given environment modules, 
      loaded in the given order. This can be combined with `--use-conda` and 
      `--use- singularity`, which will then be only used as a fallback for rules
      which don't define environment modules.
    inputBinding:
      position: 102
      prefix: --use-envmodules
  - id: verbose
    type:
      - 'null'
      - boolean
    doc: Print debugging output.
    inputBinding:
      position: 102
      prefix: --verbose
  - id: wait_for_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Wait `--latency-wait` seconds for these files to be present before 
      executing the workflow. This option is used internally to handle 
      filesystem latency in cluster environments.
    inputBinding:
      position: 102
      prefix: --wait-for-files
  - id: wait_for_files_file
    type:
      - 'null'
      - File
    doc: Same behaviour as `--wait-for-files`, but file list is stored in file 
      instead of being passed on the commandline. This is useful when the list 
      of files is too long to be passed on the commandline. Meant for internal 
      use.
    inputBinding:
      position: 102
      prefix: --wait-for-files-file
  - id: wait_for_free_local_storage
    type:
      - 'null'
      - string
    doc: Wait for given timespan for enough free local storage when downloading 
      remote storage files. If not set, no waiting is performed.
    inputBinding:
      position: 102
      prefix: --wait-for-free-local-storage
  - id: workflow_profile
    type:
      - 'null'
      - string
    doc: 'Path (relative to current directory) to workflow specific profile folder
      to use for configuring Snakemake with parameters specific for this workflow
      (like resources). If this flag is not used, Snakemake will by default use `profiles/default`
      if present (searched both relative to current directory and relative to Snakefile,
      in this order). For skipping any workflow specific profile provide the special
      value `none`. Settings made in the workflow profile will override settings made
      in the general profile (see `--profile`). The profile folder has to contain
      a file `config.yaml`. This file can be used to set default values for command
      line options in YAML format. For example, `--executor slurm` becomes `executor:
      slurm` in the YAML file. It is advisable to use the workflow profile to set
      or overwrite e.g. workflow specific resources like the amount of threads of
      a particular rule or the amount of memory needed. Note that in such cases, the
      arguments may be given as nested YAML mappings in the profile, e.g. `set-threads:
      myrule: 4` instead of `set-threads: myrule=4`.'
    inputBinding:
      position: 102
      prefix: --workflow-profile
  - id: wrapper_prefix
    type:
      - 'null'
      - string
    doc: URL prefix for wrapper directive. Set this to use your fork or a local 
      clone of the repository, e.g., use a git URL like 
      `git+file://path/to/your/local/clone@`.
    inputBinding:
      position: 102
      prefix: --wrapper-prefix
outputs:
  - id: stdout
    type: stdout
    doc: Standard output
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/hybracter:0.12.0--pyhdfd78af_0
stdout: hybracter_install.out
