cwlVersion: v1.2
class: CommandLineTool
baseCommand:
  - rbt
  - vcf-report
label: rust-bio-tools_vcf-report
doc: "Creates report from a given VCF file including a visual plot for every variant
  with the given BAM and FASTA file. The VCF file has to be annotated with VEP, using
  the options --hgvs and --hgvsg.\n\nTool homepage: https://github.com/rust-bio/rust-bio-tools"
inputs:
  - id: fasta
    type: File
    doc: FASTA file containing the reference genome for the visual plot
    inputBinding:
      position: 1
  - id: annotation_field
    type:
      - 'null'
      - string
    doc: Set the name of the annotation field generated by VEP
    inputBinding:
      position: 102
      prefix: --annotation-field
  - id: bams
    type:
      - 'null'
      - type: array
        items: string
    doc: VCF files to include (multi-sample). Group is the name that will be 
      used in the oncoprint. There needs to be one corresponding BAM file for 
      each sample of a VCF/BCF file. Please only use VCF/BCF files annotated by 
      VEP
    inputBinding:
      position: 102
      prefix: --bams
  - id: cells
    type:
      - 'null'
      - int
    doc: Set the maximum number of cells in the oncoprint per page. Lowering 
      max-cells should improve the performance of the plots in the browser.
    inputBinding:
      position: 102
      prefix: --cells
  - id: custom_js_files
    type:
      - 'null'
      - type: array
        items: File
    doc: Add one or multiple js file (e.g. libraries) for usage in the 
      custom-js-file. The ordering of the arguments will be the same as they 
      will be imported
    inputBinding:
      position: 102
      prefix: --custom-js-files
  - id: custom_js_template
    type:
      - 'null'
      - File
    doc: Change the default javascript file for the table-report to a custom one
      to add own plots or tables to the sidebar by appending these to an empty 
      div in the HTML template
    inputBinding:
      position: 102
      prefix: --custom-js-template
  - id: formats
    type:
      - 'null'
      - type: array
        items: string
    doc: Add custom values from the format field to each variant as a data 
      attribute to access them via the custom javascript. All given format 
      values will also be inserted into the main table
    inputBinding:
      position: 102
      prefix: --formats
  - id: infos
    type:
      - 'null'
      - type: array
        items: string
    doc: Add custom values from the info field to each variant as a data 
      attribute to access them via the custom javascript. Multiple fields 
      starting with the same prefix can be added by placing '*' at the end of a 
      prefix
    inputBinding:
      position: 102
      prefix: --infos
  - id: max_read_depth
    type:
      - 'null'
      - int
    doc: Set the maximum lines of reads that will be shown in the alignment 
      plots.
    inputBinding:
      position: 102
      prefix: --max-read-depth
  - id: plot_info
    type:
      - 'null'
      - type: array
        items: string
    doc: Add multiple keys from the info field of your vcf to the plots of the 
      first and second stage of the report
    inputBinding:
      position: 102
      prefix: --plot-info
  - id: threads
    type:
      - 'null'
      - int
    doc: Sets the number of threads used to build the table reports
    inputBinding:
      position: 102
      prefix: --threads
  - id: tsv
    type:
      - 'null'
      - File
    doc: Add a TSV file that contains one or multiple custom values for each 
      sample for the oncoprint. First column has to be the sample name, followed
      by one or more columns with custom values. Make sure you include one row 
      for each given sample
    inputBinding:
      position: 102
      prefix: --tsv
  - id: vcfs
    type:
      - 'null'
      - type: array
        items: File
    doc: VCF files to include (multi-sample). Group is the name that will be 
      used in the oncoprint. There needs to be one corresponding BAM file for 
      each sample of a VCF/BCF file. Please only use VCF/BCF files annotated by 
      VEP
    inputBinding:
      position: 102
      prefix: --vcfs
outputs:
  - id: output_path
    type:
      - 'null'
      - Directory
    doc: Relative output path for the report files. Default value is the current
      directory
    outputBinding:
      glob: '*.out'
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/rust-bio-tools:0.42.2--h4458251_0
